### ISSUE TITLE
[bug] GLIB compilation recipe has an error (I think)

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#10358]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: VS 2022
  * Conan version: 1.44.0
  * Python version: 3.11

### Steps to reproduce (Include if Applicable)
Include glip/2/70.0 as a dependency then try to compile with conan install --build-missing

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
glib/2.70.0: Calling build()
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.0.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
The Meson build system
Version: 0.59.1
Source dir: C:\.conan\52e3be\1\source_subfolder
Build dir: C:\.conan\52e3be\1\build_subfolder
Build type: native build
WARNING: Unknown options: "internal_pcre"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: glib
Project version: 2.70.0
C compiler for the host machine: cl (msvc 19.30.30706 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x64")
C linker for the host machine: link link 14.30.30706.0
C++ compiler for the host machine: cl (msvc 19.30.30706 "Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x64")
C++ linker for the host machine: link link 14.30.30706.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments /utf-8: YES 
Compiler for C supports arguments -fno-strict-aliasing: NO 
cl.exe does not actually support gnu standards, and meson will instead demote to the nearest ISO C standard. This may cause compilation to fail.
Checking if "GNU C visibility attributes test" compiles: NO 
Message: Enabling various debug infrastructure
Has header "alloca.h" : NO 
Has header "crt_externs.h" : NO 
Has header "dirent.h" : NO 
Has header "float.h" : YES 
Has header "fstab.h" : NO 
Has header "grp.h" : NO 
Has header "inttypes.h" : YES 
Has header "limits.h" : YES 
Has header "linux/magic.h" : NO 
Has header "locale.h" : YES 
Has header "mach/mach_time.h" : NO 
Has header "memory.h" : YES 
Has header "mntent.h" : NO 
Has header "poll.h" : NO 
Has header "pwd.h" : NO 
Has header "sched.h" : NO 
Has header "spawn.h" : NO 
Has header "stdatomic.h" : NO 
Has header "stdint.h" : YES 
Has header "stdlib.h" : YES 
Has header "string.h" : YES 
Has header "strings.h" : NO 
Has header "sys/auxv.h" : NO 
Has header "sys/event.h" : NO 
Has header "sys/filio.h" : NO 
Has header "sys/inotify.h" : NO 
Has header "sys/mkdev.h" : NO 
Has header "sys/mntctl.h" : NO 
Has header "sys/mnttab.h" : NO 
Has header "sys/mount.h" : NO 
Has header "sys/param.h" : NO 
Has header "sys/resource.h" : NO 
Has header "sys/select.h" : NO 
Has header "sys/statfs.h" : NO 
Has header "sys/stat.h" : YES 
Has header "sys/statvfs.h" : NO 
Has header "sys/sysctl.h" : NO 
Has header "sys/time.h" : NO 
Has header "sys/times.h" : NO 
Has header "sys/types.h" : YES 
Has header "sys/uio.h" : NO 
Has header "sys/vfs.h" : NO 
Has header "sys/vfstab.h" : NO 
Has header "sys/vmount.h" : NO 
Has header "sys/wait.h" : NO 
Has header "termios.h" : NO 
Has header "unistd.h" : NO 
Has header "values.h" : NO 
Has header "wchar.h" : YES 
Has header "xlocale.h" : NO 
Checking if "malloc.h" compiles: YES 
Has header "linux/netlink.h" : NO 
Checking if "statx() test" compiles: NO 
Header <locale.h> has symbol "LC_MESSAGES" : NO 
Checking whether type "struct stat" has member "st_mtimensec" : NO 
Checking whether type "struct stat" has member "st_mtim.tv_nsec" : NO 
Checking whether type "struct stat" has member "st_atimensec" : NO 
Checking whether type "struct stat" has member "st_atim.tv_nsec" : NO 
Checking whether type "struct stat" has member "st_ctimensec" : NO 
Checking whether type "struct stat" has member "st_ctim.tv_nsec" : NO 
Checking whether type "struct stat" has member "st_birthtime" : NO 
Checking whether type "struct stat" has member "st_birthtimensec" : NO 
Checking whether type "struct stat" has member "st_birthtim" : NO 
Checking whether type "struct stat" has member "st_birthtim.tv_nsec" : NO 
Checking whether type "struct stat" has member "st_blksize" : NO 
Checking whether type "struct stat" has member "st_blocks" : NO 
Checking whether type "struct statfs" has member "f_fstypename" : NO 
Checking whether type "struct statfs" has member "f_bavail" : NO 
Checking whether type "struct dirent" has member "d_type" : NO 
Checking whether type "struct statvfs" has member "f_basetype" : NO 
Checking whether type "struct statvfs" has member "f_fstypename" : NO 
Checking whether type "struct tm" has member "tm_gmtoff" : NO 
Checking whether type "struct tm" has member "__tm_gmtoff" : NO 
Checking if "building for UWP" compiles: NO 
Library iphlpapi found: YES
Checking for function "if_nametoindex" with dependency -liphlpapi: YES 
Checking for function "if_indextoname" with dependency -liphlpapi: YES 
Checking for function "close_range" : NO 
Checking for function "endmntent" : NO 
Checking for function "endservent" : NO 
Checking for function "epoll_create" : NO 
Checking for function "fallocate" : NO 
Checking for function "fchmod" : NO 
Checking for function "fchown" : NO 
Checking for function "fdwalk" : NO 
Checking for function "fsync" : NO 
Checking for function "getauxval" : NO 
Checking for function "getc_unlocked" : NO 
Checking for function "getfsstat" : NO 
Checking for function "getgrgid_r" : NO 
Checking for function "getmntent_r" : NO 
Checking for function "getpwuid_r" : NO 
Checking for function "getresuid" : NO 
Checking for function "getvfsstat" : NO 
Checking for function "gmtime_r" : NO 
Checking for function "hasmntopt" : NO 
Checking for function "inotify_init1" : NO 
Checking for function "issetugid" : NO 
Checking for function "kevent" : NO 
Checking for function "kqueue" : NO 
Checking for function "lchmod" : NO 
Checking for function "lchown" : NO 
Checking for function "link" : NO 
Checking for function "localtime_r" : NO 
Checking for function "lstat" : NO 
Checking for function "mbrtowc" : YES 
Checking for function "memalign" : NO 
Checking for function "mmap" : NO 
Checking for function "newlocale" : NO 
Checking for function "pipe2" : NO 
Checking for function "poll" : NO 
Checking for function "prlimit" : NO 
Checking for function "readlink" : NO 
Checking for function "recvmmsg" : NO 
Checking for function "sendmmsg" : NO 
Checking for function "setenv" : NO 
Checking for function "setmntent" : NO 
Checking for function "strerror_r" : NO 
Checking for function "strnlen" : YES 
Checking for function "strsignal" : NO 
Checking for function "strtod_l" : NO 
Checking for function "strtoll_l" : NO 
Checking for function "strtoull_l" : NO 
Checking for function "symlink" : NO 
Checking for function "timegm" : NO 
Checking for function "unsetenv" : NO 
Checking for function "uselocale" : NO 
Checking for function "utimes" : NO 
Checking for function "valloc" : NO 
Checking for function "vasprintf" : NO 
Checking for function "vsnprintf" : YES 
Checking for function "wcrtomb" : YES 
Checking for function "wcslen" : YES 
Checking for function "wcsnlen" : YES 
Checking for function "sysctlbyname" : NO 
Checking for function "splice" : NO 
Checking for function "posix_spawn" : NO 
Checking for function "snprintf" : YES 
Checking for function "strcasecmp" : NO 
Checking for function "_stricmp" : YES 
Checking for function "strncasecmp" : NO 
Checking for function "_strnicmp" : YES 
Header <sys/sysmacros.h> has symbol "major" : NO 
Header <sys/mkdev.h> has symbol "major" : NO 
Header <sys/types.h> has symbol "major" : NO 
Header <dlfcn.h> has symbol "RTLD_LAZY" : NO 
Header <dlfcn.h> has symbol "RTLD_NOW" : NO 
Header <dlfcn.h> has symbol "RTLD_GLOBAL" : NO 
Header <dlfcn.h> has symbol "RTLD_NEXT" : NO 
Message: Checking whether to use statfs or statvfs .. neither
Checking if "futex(2) system call" links: NO 
Checking if "eventfd(2) system call" links: NO 
Checking if "__uint128_t available" compiles: NO 
Checking if "clock_gettime" links: NO 
Checking if "clock_gettime in librt" links: NO 
Checking if "dlopen() and dlsym() in system libraries" links: NO 
Checking if "dlopen() and dlsym() in libdl" links: NO 
Checking if "open() option O_DIRECTORY" compiles: NO 
Checking if "fcntl() option F_FULLFSYNC" compiles: NO 
Checking if "nl_langinfo and CODESET" links: NO 
Checking if "nl_langinfo (PM_STR)" links: NO 
Checking if "nl_langinfo (_NL_CTYPE_OUTDIGITn_MB)" links: NO 
Checking if "nl_langinfo (ALTMON_n)" links: NO 
Checking if "nl_langinfo (_NL_ABALTMON_n)" links: NO 
Checking if "nl_langinfo and _NL_TIME_CODESET" links: NO 
Checking if "signed" compiles: YES 
Header <stddef.h> has symbol "ptrdiff_t" : YES 
Checking if "sig_atomic_t" links: YES 
Checking if "long long" compiles: YES 
Checking if "long double" compiles: YES 
Header <stddef.h> has symbol "wchar_t" : YES 
Header <wchar.h> has symbol "wint_t" : YES 
Checking if "uintmax_t in inttypes.h" compiles: YES 
Checking if "uintmax_t in stdint.h" compiles: YES 
Checking for size of "char" : 1
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "void*" : 8
Checking for size of "long" : 4
Checking for size of "long long" : 8
Checking for size of "size_t" : 8
Checking for size of "SSIZE_T" : 8
Checking for alignment of "char" : 1
Checking for alignment of "short" : 2
Checking for alignment of "int" : 4
Checking for alignment of "void*" : 8
Checking for alignment of "long" : 4
Checking for alignment of "long long" : 8
Checking for alignment of "size_t" : 8
Checking for size of "wchar_t" : 2
Checking if "__va_copy check" compiles: NO 
Checking if "va_copy check" compiles: NO 
Checking if "va_lists can be copied as values" runs: YES
Checking if "ISO C99 varargs macros in C" compiles: YES 
Checking if "ISO C99 varargs macros in C++" compiles: YES 
Checking if "GNUC varargs macros" compiles: NO 
Has header "alloca.h" : NO (cached)
Has header "sys/poll.h" : NO 
Has header "sys/types.h" : YES (cached)
Has header "winsock2.h" : YES 
Computing int of "AF_UNIX" : 1
Computing int of "AF_INET" : 2
Computing int of "AF_INET6" : 23
Computing int of "MSG_OOB" : 1
Computing int of "MSG_PEEK" : 2
Computing int of "MSG_DONTROUTE" : 4
Checking if "stack grows check" runs: NO (1)
Found pkg-config: C:/Users/Makogan/.conan/data/pkgconf/1.7.4/_/_/package/a1a22d64beba6a0aee2215b86a5a2c34ae12d72d/bin/pkgconf.exe (1.7.4)
Run-time dependency libpcre found: YES 8.45
Checking if "Windows system PCRE is a static build" with dependency libpcre links: YES 
Library m found: NO
Run-time dependency libffi found: YES 3.4.2
Run-time dependency zlib found: YES 1.2.11
Library gnuintl found: YES
Checking for function "ngettext" with dependency -lgnuintl: YES 
Checking for function "bind_textdomain_codeset" with dependency -lgnuintl: YES 
Library ws2_32 found: YES
Checking for function "strlcpy" : NO 
Checking if "/proc/self/cmdline" runs: DID NOT COMPILE
Program python3 found: YES (C:\msys64\mingw64\bin\python3.EXE)
Program bash found: NO
Found CMake: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.21.21080301)
Run-time dependency bash-completion found: NO (tried pkgconfig and cmake)
Program sh found: NO
Program env found: NO
Configuring glibconfig.h using configuration
Dependency sysprof-capture-4 skipped: feature sysprof disabled
Checking if "where to find the exponent in a 'double'" runs: YES
Checking if "printf supports large precisions" runs: YES
Checking if "printf survives out-of-memory conditions" runs: DID NOT COMPILE
Checking if "printf supports the zero flag correctly" runs: YES
Checking if "printf supports the left-adjust flag correctly" runs: YES
Checking if "printf supports the grouping flag" runs: NO (1)
Checking if "printf supports the 'a' and 'A' directives" runs: NO (3)
Checking if "printf supports the 'F' directive" runs: YES
Checking if "printf supports the 'ls' directive" runs: YES
Checking if "printf supports 'long double' arguments" runs: YES
Checking if "printf supports infinite 'double' arguments" runs: YES
Checking if "printf supports infinite 'long double' arguments" runs: DID NOT COMPILE
Compiler for C supports arguments -Wno-format-nonliteral: NO 
Compiler for C supports arguments -Wno-duplicated-branches: NO 
Checking if "frexp works" with dependency -lm runs: YES
Checking if "frexpl works" with dependency -lm runs: YES
Checking if "frexpl prototype can be re-listed" compiles: YES 
Checking if "ldexpl works" with dependency -lm runs: YES
Checking if "ldexpl prototype can be re-listed" compiles: YES 
Configuring gnulib_math.h using configuration
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Configuring glib.rc using configuration
Windows resource compiler: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Library winmm found: YES
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Configuring gtester-report using configuration
Configuring libglib-2.0.so.0.7000.0-gdb.py using configuration
source_subfolder\glib\meson.build:459: DEPRECATION: Please use the new `install:` kwarg instead of passing `false` to `install_dir:`
Configuring gobject.rc using configuration
Configuring glib-genmarshal using configuration
Program glib-genmarshal found: YES (C:\Python311\python.exe C:\.conan\52e3be\1\build_subfolder\gobject\glib-genmarshal)
Configuring glib-mkenums using configuration
Program glib-mkenums found: YES (C:\Python311\python.exe C:\.conan\52e3be\1\build_subfolder\gobject\glib-mkenums)
Configuring libgobject-2.0.so.0.7000.0-gdb.py using configuration
source_subfolder\gobject\meson.build:157: DEPRECATION: Please use the new `install:` kwarg instead of passing `false` to `install_dir:`
Configuring gthread.rc using configuration
Configuring gmoduleconf.h using configuration
Configuring gmodule.rc using configuration
Configuring gnetworking.h using configuration
Configuring gdbus-codegen using configuration
Program gdbus-codegen found: YES (C:\Python311\python.exe C:\.conan\52e3be\1\build_subfolder\gio\gdbus-2.0/codegen\gdbus-codegen)
Configuring config.py using configuration
Library shlwapi found: YES
Library dnsapi found: YES
Configuring gio.rc using configuration
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Run-time dependency libelf found: YES 0.8.13
Program xgettext found: YES (C:\msys64\mingw64\bin\xgettext.EXE)
Configuring config.h using configuration
Build targets in project: 33

Option buildtype is: debug [default: debugoptimized]
Found ninja-1.10.2 at "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
Traceback (most recent call last):
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\mesonmain.py", line 227, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\msetup.py", line 281, in run
    app.generate()
    ^^^^^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\msetup.py", line 184, in generate
    self._generate(env)
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\msetup.py", line 263, in _generate
    mintro.generate_introspection_file(b, intr.backend)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\mintro.py", line 481, in generate_introspection_file
    intro_info += [(key, val.func())]
                         ^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\mintro.py", line 72, in <lambda>
    ('buildoptions', IntroCommand('List all build options', func=lambda: list_buildoptions(coredata), no_bd=list_buildoptions_from_source)),
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\mintro.py", line 265, in list_buildoptions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Makogan\.conan\data\meson\0.59.1\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\mesonbuild\mintro.py", line 245, in add_keys
    for key, opt in sorted(options.items()):
                    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'UserComboOption' and 'UserFeatureOption'
glib/2.70.0:
glib/2.70.0: ERROR: Package 'ee08b51ef847eeeb9484893eaee8020007a48a5f' build failed
glib/2.70.0: WARN: Build folder C:\.conan\52e3be\1
ERROR: glib/2.70.0: Error in build() method, line 165
        meson = self._configure_meson()
while calling '_configure_meson', line 109
        meson.configure(
        ConanException: Error 2 while executing meson "C:\.conan\52e3be\1\source_subfolder" "C:\.conan\52e3be\1\build_subfolder" --backend=ninja -Dprefix="C:\.conan\dd37db\1" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="shared" -Dselinux="disabled" -Dlibmount="disabled" -Dinternal_pcre="False" -Dtests="false" -Dlibelf="enabled" --wrap-mode=nofallback --buildtype=debug 
```

It seems the script is trying to sort two items with incompatible types.

**Comment by memsharded** [comment]
It is a possibility that glib itself is not ready to build with the bleeding edge VS compiler.

I am moving this to ConanCenter repo, recipes from ConanCenter are investigated there. Thanks for reporting!
