### ISSUE TITLE
[bug] can't use `tool_requires` in a profile

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan#10461]
contrary to [documentation](https://docs.conan.io/en/latest/devtools/build_requires.html#declaring-tool-requirements) using tool_requires in a profile results in
```
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/conans/client/profile_loader.py", line 132, in read_profile
    return _load_profile(text, profile_path, default_folder)
  File "/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/conans/client/profile_loader.py", line 163, in _load_profile
    doc = ConfigParser(profile_parser.profile_text,
  File "/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/conans/util/config_parser.py", line 49, in __init__
    raise ConanException("ConfigParser: Unrecognized field '%s'" % field)
conans.errors.ConanException: ConfigParser: Unrecognized field 'tool_requires'
```

### Environment Details (include every applicable attribute)
  * Conan version: 1.44.1

### Steps to reproduce (Include if Applicable)
```
conan@ac9ffffbcf86:/workspaces/conan-config$ cat ~/.conan/profiles/windows-mingw8
[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
compiler.threads=win32
build_type=RelWithDebInfo
[options]
[tool_requires]
mingw-w64/8.0.2
[env]
conan@ac9ffffbcf86:/workspaces/conan-config$ conan install -pr:h windows-mingw8 zlib/1.2.11@
ERROR: Error reading 'windows-mingw8' profile: ConfigParser: Unrecognized field 'tool_requires'
```

**Comment by dvirtz** [comment]
oops, duplicate of https://github.com/conan-io/conan/issues/10427
