### ISSUE TITLE
[bug] "too many values to unpack" when ":" in exports_sources file

### ISSUE THREAD

**Issue by Da-LiFe** [conan-io/conan#10475]
### Environment Details
  * Conan version:1.40.4
  * Python version: 3.6.12

### Steps to reproduce

- `touch "wait for: serve coffee.py"`
- create a conanfile.py with this content

```
from conans import ConanFile, CMake, tools

class Md5testConan(ConanFile):
    name = "md5test"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = ["*.py"]
```

### Logs
 `conan create conanfile.py md5test/1.0.0@testing/snapshot`

```
Exporting package recipe
Traceback (most recent call last):
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/client/command.py", line 2232, in run
    method(args[0][1:])
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/client/command.py", line 398, in create
    require_overrides=args.require_override)
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/client/conan_api.py", line 370, in create
    ignore_dirty=ignore_dirty)
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/client/cmd/export.py", line 123, in cmd_export
    previous_manifest = package_layout.recipe_manifest()
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/paths/package_layouts/package_cache_layout.py", line 187, in recipe_manifest
    return FileTreeManifest.load(self.export())
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/model/manifest.py", line 92, in load
    return FileTreeManifest.loads(text)
  File "/opt/python/osl153-x86_64/python3/stable/1.4.2/lib/python3.6/site-packages/conans/model/manifest.py", line 83, in loads
    filename, file_md5 = md5line.split(": ")
ValueError: too many values to unpack (expected 2)

ERROR: too many values to unpack (expected 2)
```

Assuming that the md5 hash in the manifest has a very limited and known charset `filename, file_md5 = md5line.rsplit(": ", 1)` could be a more robust implementation.

**Comment by memsharded** [comment]
Thanks for reporting! Proposing #10492 to fix it for 1.46
