### ISSUE TITLE
Shipping conan projects

### ISSUE THREAD

**Issue by mropert** [conan-io/conan#1061]
I've been wondering how to ship binaries that are built with Conan.
My constraints are that clients can't use Conan on their machine to install my software (for various reasons) so I need to be able to generate a self contained archive with all the required dependencies.
Basically for a conan project that means all its binaries plus all the binaries from its dependencies.
(I consider that all "external" dependencies are "system" libraries that will be available on client machines)

I've been studying two approaches for now:
1. Use CMake's ```install()``` directives. It works fine for the project itself but requires a lot of hacking to parse the various variables from the ```conanbuild.cmake``` file and extract the list of the ```.so``` of ```.dll``` files needed from the dependencies.
2. Have Conan do it for me. I was thinking about reusing the code of ```conan install``` to recursively execute the ```package``` step of each project in the dependency tree with the same target directory. That way I should be able to deploy all the files into a common directory and zip/tar it.

I'd also be interested in a way to filter out the "dev" files from the packages (like the headers and static libraries) so that I only get executables and required runtime libraries.
My best idea so far would be an optional ```dev``` tag that can be used by package maintainers when defining the ```package()``` step to conditionally include the ```.h``` and ```.a```/```.lib``` files. I've thought about scopes but there's already a ```dev``` scope that means something else.

Did you guys ever give some thought about this?

**Comment by memsharded** [comment]
Related: #102, #381, #515

Some quick question, do you want to redistribute to clients executables (exes + shared libraries), or are you distribution libraries (headers + static libs + shared libs).
For the first one, typically ``imports`` works well to extract those binaries, then zip or create the installer you want. For the second one, maybe too. Have you tried the ``imports`` feature?

**Comment by mropert** [comment]
I'll probably have two cases:
1. Binary distribution, for which I only want executables and the required dynamic libs.
2. Development distribution, for which I want all the binaries, plus the static libs and headers.

Anyway I've tried ```imports``` and it shows a lot of promise.
I ran into a weird error though:
```
PROJECT imports(): Copied 5 '.so' files
Traceback (most recent call last):
  File "/data/tooling/bin/conan", line 11, in <module>
    sys.exit(run())
  File "/data/tooling/lib/python2.7/site-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/data/tooling/lib/python2.7/site-packages/conans/client/command.py", line 1108, in main
    error = command.run(args)
  File "/data/tooling/lib/python2.7/site-packages/conans/client/command.py", line 907, in run
    raise exc
IOError: [Errno 2] No such file or directory: u'dist/dist/lib/libxxx.so'
```
Funny thing is, it only happens when I try to use the ```-d``` toggle with ```imports```, if I do not supply it the import for works fine.

**Comment by lasote** [comment]
About the error, yes, I've been able to reproduce it, it's a bug.
And yes, I think is a good idea to have a simple `conanfile.txt` requiring all your dependencies and importing the libraries/executables etc.

**Comment by lasote** [comment]
Did you manage to ship your projects using conan? Is the `imports` feature enough for you? Thanks

**Comment by memsharded** [comment]
I think the new conan 0.21 feature of ``virtualrunenv`` could be also very useful: http://conanio.readthedocs.io/en/latest/reference/generators/virtualrunenv.html

**Comment by mropert** [comment]
@lasote, the ```imports``` step will do for now as my scale is pretty limited.
I'll give you some feedback when this grow up.

**Comment by vkotovv** [comment]
@memsharded is there any documentation for creating and using `imports` feature?

**Comment by vkotovv** [comment]
I've found some docs on this feature:
http://conanio.readthedocs.io/en/latest/reference/conanfile/methods.html#imports
http://conanio.readthedocs.io/en/latest/manage_deps/conanfile_txt.html#imports
http://conanio.readthedocs.io/en/latest/reference/commands/imports.html

**Comment by lasote** [comment]
We introduced some versions ago the [deploy method](https://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=deploy#deploy). Could it help?
