### ISSUE TITLE
[bug] cmake error output not shown when using msys2/git bash

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#10709]
I've noticed that what cmake writes stderr/stdout isn't captured and proxied by conan to stdout during the configure phase (i think), and so CMake errors aren't showing.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2022 (17)
  * Conan version: 1.45.0
  * Python version: 3.9.7
  * CMake version: 3.20.3

### Steps to reproduce (Include if Applicable)
Set up a profile that looks like the following:

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```
Run 
```
conan install bzip2/1.0.8@ --build=missing -pr=vs2022
```

Because this is executed using cmake 3.20.3, the Visual Studio 17 2022 generator doesn't exist, and CMake throws the following error:

```
CMake Error: Could not create named generator Visual Studio 17 2022
```
Unfortunately, this is not displayed when attempting to build using `conan` - I only discovered this after attempting to invoke `cmake` directly

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan install bzip2/1.0.8@ --build=missing -pr=vs2022
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision b056f852bd2d5af96fc7171aadfd6c0b
Installing package:bzip2/1.0.8
Requirements
    bzip2/1.0.8 from 'conan-center' - Downloaded
Packages
    bzip2/1.0.8:53b5fd22ba061620078deefdae9a437c5f693201 - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz
bzip2/1.0.8: Configuring sources in C:\Users\user\.conan/data/bzip2\1.0.8\_\_\source

bzip2/1.0.8: Copying sources to build folder
bzip2/1.0.8: Building your package in C:\Users\user\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201
bzip2/1.0.8: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.8: Aggregating env generators
bzip2/1.0.8: Calling build()
bzip2/1.0.8:
bzip2/1.0.8: ERROR: Package '53b5fd22ba061620078deefdae9a437c5f693201' build failed
bzip2/1.0.8: WARN: Build folder C:\Users\user\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201
ERROR: bzip2/1.0.8: Error in build() method, line 67
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 61
        self._cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\user\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201 && cmake -G "Visual Studio 17 2022" -A "x64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="17" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\user\.conan\data\bzip2\1.0.8\_\_\package\53b5fd22ba061620078deefdae9a437c5f693201" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE-INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DBZ2_VERSION_STRING="1.0.8" -DBZ2_VERSION_MAJOR="1" -DBZ_BUILD_EXE="True" -Wno-dev C:\Users\user\.conan\data\bzip2\1.0.8\_\_\build\53b5fd22ba061620078deefdae9a437c5f693201
```

**Comment by memsharded** [comment]
Hi @samuel-emrys 

The bzip2 recipe is still using the 1.X build system integrations, that we are not developing anymore, unless serious bugs, this would be more a UX thing.

If you could try and report it with the new tools, like ``conan new hello/0.1 --template=cmake_lib``, that would be great, we are willing to keep improving the UX of the new integrations.

**Comment by samuel-emrys** [comment]
Hi @memsharded,

Looks like this is still an issue in new recipes:

```
user@host MINGW64 ~/projects/conanio-10709
$ conan new hello/0.1 --template=cmake_lib
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: src/hello.cpp
File saved: src/hello.h
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp

user@host MINGW64 ~/projects/conanio-10709
$ cmake --version
cmake version 3.20.0

user@host MINGW64 ~/projects/conanio-10709
$ conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (hello/0.1): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (hello/0.1): Generator txt created conanbuildinfo.txt
conanfile.py (hello/0.1): Calling generate()
conanfile.py (hello/0.1): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (hello/0.1): Aggregating env generators
conanfile.py (hello/0.1): Generated conaninfo.txt
conanfile.py (hello/0.1): Generated graphinfo

user@host MINGW64 ~/projects/conanio-10709
$ conan build .
Using lockfile: 'C:\Users\user\projects\conanio-10709/conan.lock'
Using cached profile from lockfile
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
conanfile.py (hello/0.1): Calling build()
conanfile.py (hello/0.1): CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/projects/conanio-10709" "C:\Users\user\projects\conanio-10709\."
ERROR: conanfile.py (hello/0.1): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/user/projects/conanio-10709" "C:\Users\user\projects\conanio-10709\."
```

As you can see, the appropriate error message is not propagated through to the user

**Comment by memsharded** [comment]
Not sure what is happening. I am trying to reproduce, did the following:

- conan new hello/0.1 -m=cmake_lib
- Modify CMakeLists.txt, change hello.cpp=>hello2.cpp
- conan install .
- conan build .

```
....
Using Conan toolchain: C:/Users/memshareded/conanws/kk/build/conan/conan_toolchain.cmake.
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Configuring done
CMake Error at CMakeLists.txt:4 (add_library):
  Cannot find source file:

    src/hello2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:4 (add_library):
  No SOURCES given to target: hello
CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR: conanfile.py (hello/0.1): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="C:/Users/memsharded/conanws/kk/build/conan/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/memsharded/conanws/kk" "C:\Users\memsharded\conanws\kk\."

```
Not sure what is the difference, maybe is the mingw terminal? Does it happen the same if you run it on a cmd terminal?

**Comment by samuel-emrys** [comment]
Yep this is it. Idiosyncrasy of mingw/msys2/git bash - The appropriate error message is forwarded in both test cases that we've presented.

**Comment by memsharded** [comment]
> Yep this is it. Idiosyncrasy of mingw/msys2/git bash - The appropriate error message is forwarded in both test cases that we've presented.

I have tried in an msys2 terminal:
- Installed python, pip with pacman
- Installed Conan with pip
- Did the same as above

Still able to get the error msg:
```
CMake Error at CMakeLists.txt:4 (add_library):
  Cannot find source file:

    src/hello2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:4 (add_library):
  No SOURCES given to target: hello
```

**Comment by samuel-emrys** [comment]
Interesting. I've just experimented a little bit, and I have no idea how or why this would affect things, but I'm able to get the warnings to show up when I install conan in a local virtualenv. My system wide installation was installed using `pipx`, which installs applications into a virtualenv and then makes the application available on the user path to avoid issues associated with polluting the global pip package list. I have no idea why this would affect the display of error messages though. It's worth noting that I'm able to use the system conan (as installed with pipx) without issue in cmd, but it seems to pose an issue in msys/git bash

**Comment by memsharded** [comment]
> My system wide installation was installed using pipx

You mean your msys2 installation? If I understood correctly, you are installing Conan inside the msys2 system, or are you using somehow a Windows native installation inside msys2? I could try to reproduce with pipx inside msys2

**Comment by samuel-emrys** [comment]
> If I understood correctly, you are installing Conan inside the msys2 system, or are you using somehow a Windows native installation inside msys2

My understanding is that one of the goals of msys2 is to create and use windows native binaries wherever possible (it deviates from the goals of cygwin in this way). This includes CPython, so whichever python interpreter is found on the path in either the windows native or msys2 environment is what's used first. In this case, it's the same interpreter (C:\git\usr\bin\python.exe in my set up), and its the same installation of conan that I use in both cmd and msys2, i.e. the one located in `~/.local/bin` (which is where pipx places it). Having said that, because conan is installed with pipx, i'd imagine the interpreter that it uses is the one in it's virtualenv, i.e. `~/.local/pipx/venvs/conan/Scripts/python.exe` - again, this will be the interpreter used by both msys2 and cmd in my set up.

**Comment by memsharded** [comment]
That could be related to the issue. Apparently when using msys2 specific packages and installation everything works well.

It might be worth testing the released Conan 2.0-alpha.4, some things were simplified around stdout/stderr, maybe it affects.

**Comment by samuel-emrys** [comment]
> That could be related to the issue. Apparently when using msys2 specific packages and installation everything works well.
> 
> It might be worth testing the released Conan 2.0-alpha.4, some things were simplified around stdout/stderr, maybe it affects.

conan's CLI seems to be completely broken for conan 2.0-alpha4 in msys2. For any command I try to execute, I get this:

```bash
$ conan profile list
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\cli.py", line 154, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\command.py", line 153, in run
    self._subcommands[subcommand].run(conan_api, *args)
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\command.py", line 170, in run
    info = self._method(conan_api, self._parent_parser, self._parser, *args)
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\commands\profile.py", line 89, in profile_list
    profiles_list_cli_output(result)
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\commands\profile.py", line 22, in profiles_list_cli_output
    out.writeln("Profiles found in the cache:")
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\output.py", line 77, in writeln
    self.write(data, fg, bg, newline=True)
  File "C:\Users\user\.local\pipx\venvs\conan\lib\site-packages\conans\cli\output.py", line 85, in write
    self.stream.write(data)
AttributeError: 'NoneType' object has no attribute 'write'
```
This happens regardless of how conan is installed.

**Comment by samuel-emrys** [comment]
A follow up, I think this might have something to do with how [msys2 handles streams](https://www.msys2.org/wiki/Porting/):

> mintty is primarily designed to be a good terminal emulator (in the POSIX sense of the word) and it works well with bash, ssh and other Cygwin/MSYS2 programs. Because native Windows console programs use a fundamentally different way of handling console input/output, mintty uses pipes to connect to their standard streams (stdin, stdout, stderr). Unfortunately, this has the effect that `isatty` and similar APIs (used to check whether a stream is attached to an interactive console or a pipe/file) will return incorrect values for native programs running under mintty.
>
> One way of fixing this problem is to run native programs inside a real Windows console, hide the console and use the console API to communicate with the program. This approach has obvious disadvantages, but it's good enough. Actually, this is the way most Windows console emulators work (e.g. ConsoleZ, ConEmu). There is also a wrapper program called winpty that does exactly this and translates the I/O to/from standard terminal sequences which mintty understands.
>
> Running a program under winpty (by prefixing the command line with winpty) will make the program think it is running interactively, but it will also break any special features depending on terminal sequences, possibly including colored text output and TUIs.
>
> MSYS2 includes wrappers for some affected programs, so that they will work correctly most of the time. Examples can be seen in packages containing REPLs (python3, lua, nodejs, ...).

More reading: https://github.com/mintty/mintty/issues/56

consequently, I can invoke conan with:

```
$ winpty conan profile list
```
This is less than ideal - is there an intent to support msys more natively going forward? This seems like a regression in comparison to 1.X

**Comment by samuel-emrys** [comment]
Back on topic: it looks like this issue is resolved when using winpty just generally

```
user@hostMINGW64 /c/users/user/projects/conanio-10709
$ conan --version
Conan version 2.0.0-alpha5

user@host MINGW64 /c/users/user/projects/conanio-10709
$ winpty conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (hello/0.1): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (hello/0.1): Generator txt created conanbuildinfo.txt
conanfile.py (hello/0.1): Calling generate()
conanfile.py (hello/0.1): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (hello/0.1): Aggregating env generators
conanfile.py (hello/0.1): Generated conaninfo.txt
conanfile.py (hello/0.1): Generated graphinfo
user@host MINGW64 /c/users/user/projects/conanio-10709
$ winpty conan build .
Using lockfile: 'C:\Users\user\projects\conanio-10709/conan.lock'
Using cached profile from lockfile
conanfile.py (hello/0.1): Calling build()
conanfile.py (hello/0.1): CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."
-- Using Conan toolchain: C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.31.31104.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:4 (add_library):
  Cannot find source file:

    src/hello2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:4 (add_library):
  No SOURCES given to target: hello


CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR: conanfile.py (hello/0.1): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."

```

And also with conan 1.46.0:

```
user@host MINGW64 /c/users/user/projects/conanio-10709
$ conan --version
Conan version 1.46.0

user@host MINGW64 /c/users/user/projects/conanio-10709
$ conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (hello/0.1): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (hello/0.1): Generator txt created conanbuildinfo.txt
conanfile.py (hello/0.1): Calling generate()
conanfile.py (hello/0.1): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (hello/0.1): Aggregating env generators
conanfile.py (hello/0.1): Generated conaninfo.txt
conanfile.py (hello/0.1): Generated graphinfo

user@host MINGW64 /c/users/user/projects/conanio-10709
$ conan build .
Using lockfile: 'C:\Users\user\projects\conanio-10709/conan.lock'
Using cached profile from lockfile
conanfile.py (hello/0.1): Calling build()
conanfile.py (hello/0.1): CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."
-- Using Conan toolchain: C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.31.31104.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
ERROR: conanfile.py (hello/0.1): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."

user@host MINGW64 /c/users/user/projects/conanio-10709
$ winpty conan build .
Using lockfile: 'C:\Users\user\projects\conanio-10709/conan.lock'
Using cached profile from lockfile
conanfile.py (hello/0.1): Calling build()
conanfile.py (hello/0.1): CMake command: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."
-- Using Conan toolchain: C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- Configuring done
CMake Error at CMakeLists.txt:4 (add_library):
  Cannot find source file:

    src/hello2.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:4 (add_library):
  No SOURCES given to target: hello


CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR: conanfile.py (hello/0.1): Error in build() method, line 37
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/user/projects/conanio-10709/build/conan/conan_toolchain.cmake" "C:\Users\user\projects\conanio-10709\."
```

That confuses me a bit though - I'm not sure I understand why this would manifest in 1.X _only_ when installed through `pipx` and not just generally through `pip`. I also would have thought this would have been caused by `cmake` being a windows native binary, as per the discussion about wrt mintty and pipes. I'm not sure I see what bearing conan has on that.

Regardless, there certainly seems to be some regression there in terms of how conan works with msys/mintty in 2.0 - does it make a call to work out if it's running in a tty?
