### ISSUE TITLE
[feature] [UX] Improve `conan new` command

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10964]
If you try out a simple `conan new -h`:
```
➜  tttt git:(develop2) conan new -h
usage: conan new [-h] [-d DEFINE] [-f] template

Create a new recipe (with conanfile.py and other files) from a predefined template

positional arguments:
  template              Template name, built-in predefined one or user one

optional arguments:
  -h, --help            show this help message and exit
  -d DEFINE, --define DEFINE
                        Define a template argument as key=value
  -f, --force           Overwrite file if exists
```

So, after that, you try to create  a CMake example:

```
➜  tttt git:(develop2) conan new cmake_lib
Traceback (most recent call last):
  File "/Users/franchuti/develop/conan/conans/cli/cli.py", line 163, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/Users/franchuti/develop/conan/conans/cli/command.py", line 157, in run
    info = self._method(conan_api, parser, *args)
  File "/Users/franchuti/develop/conan/conans/cli/commands/new.py", line 43, in new
    template_files = conan_api.new.render(template_files, definitions)
  File "/Users/franchuti/develop/conan/conan/api/subapi/new.py", line 87, in render
    v = Template(v, keep_trailing_newline=True).render(**definitions)
  File "/Users/franchuti/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/franchuti/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/franchuti/Library/Python/3.9/lib/python/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 5, in top-level template code
  File "/Users/franchuti/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'name' is undefined

ERROR: 'name' is undefined
```

Obviously, we're missing to specify the name and the version but `[-d DEFINE] ` appears like an optional thing so it's quite confusing:

```
➜  tttt git:(develop2) conan new cmake_lib -d name=hello -d version=0.1
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: include/hello.h
File saved: src/hello.cpp
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp
```
The UX should improve. In my opinion, if name and version are required attributes, then let's require them as parameters:
```
 conan new cmake_lib --name=hello --version=0.1
```

**Comment by memsharded** [comment]
>  conan new cmake_lib --name=hello --version=0.1

There can be templates that don't define those things, this is the reason templates are completely generic, and only ``-d`` arg is needed, so maybe better don't add those.

I agree that to capture errors in the rendering, and translate them to something more helpful is necessary to improve the UX

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/11151
