### ISSUE TITLE
[bug] Conan lockfile fails with conan-new example

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#10966]
Related to https://github.com/conan-io/conan/issues/10916 (but this is failing only if the `test_package/` folder is there)

### Steps to reproduce

```
$ conan new cmake_lib -d name=hello -d version=0.1
$ conan lock create . --profile:host default --profile:build default --lockfile-out locks/conan.lock
$ conan create . --profile:host default --profile:build default --lockfile-out locks/conan.lock
```
The output ends up with:
```
...
hello/0.1 package(): Packaged 1 '.h' file: hello.h
hello/0.1 package(): Packaged 1 '.a' file: libhello.a
hello/0.1: Package 'e360b62ce00057522e221cfe56714705a46e20e2' created
hello/0.1: Created package revision 8a5fc855aa18f358b89e93c34c816656
Package folder /Users/franchuti/.conan2/p/97df3d62d3551803/p
Saving lockfile: /Users/franchuti/develop/conan/tttt/locks/conan.lock
Traceback (most recent call last):
  File "/Users/franchuti/develop/conan/conans/cli/cli.py", line 163, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/Users/franchuti/develop/conan/conans/cli/command.py", line 157, in run
    info = self._method(conan_api, parser, *args)
  File "/Users/franchuti/develop/conan/conans/cli/commands/create.py", line 99, in create
    lockfile.save(lockfile_out)
AttributeError: 'NoneType' object has no attribute 'save'

ERROR: 'NoneType' object has no attribute 'save'
```
My profile:

```
[settings]
os=Macos
arch=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
```

Even if you get rid of the `test_package/` folder, it's failing as well.

**Comment by memsharded** [comment]
It is true that ``conan create`` expects a input ``--lockfile`` that is not being passed, in order to modify it and save it, and this is why it is failing.

 In other words, ``conan create`` was not intended to create a lockfile from scratch, but it should be created first with ``conan lock create``. But surely we can revisit that UI and change it if we think so.

**Comment by lasote** [comment]
I'm ok with the UI, I opened a PR to raise an error if `--lockfile-out` and not `--lockfile`

**Comment by franramirez688** [comment]
Closed by https://github.com/conan-io/conan/pull/10975
