### ISSUE TITLE
[bug] Error in generator 'CMakeDeps': h is not absolute

### ISSUE THREAD

**Issue by MiSo1289** [conan-io/conan#11154]
### Environment Details
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.8.10**

### Steps to reproduce
```console
$ conan profile show default
[settings]
arch=x86_64
arch_build=x86_64
os=Linux
os_build=Linux
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
build_type=Debug
[options]
*:fPIC=True
*:shared=False
[conf]
[build_requires]
[env]
$ cat conanfile.txt
[generators]
CMakeDeps
CMakeToolchain

[requires]
grpc/1.45.2
$ conan install . -if build
```

### Logs
<details><summary>Click to expand log</summary>

```
conanfile.txt: Installing package
Requirements
    abseil/20211102.0 from 'conan-center' - Cache
    c-ares/1.18.1 from 'conan-center' - Cache
    grpc/1.45.2 from 'conan-center' - Cache
    openssl/1.1.1n from 'conan-center' - Cache
    protobuf/3.20.0 from 'conan-center' - Cache
    re2/20220201 from 'conan-center' - Cache
    zlib/1.2.12 from 'conan-center' - Cache
Packages
    abseil/20211102.0:038baac88f4c7bfa972ce5adac1616bed8fe2ef4 - Cache
    c-ares/1.18.1:5a258fabd5aeaa11cbc1951f7243b664f46595f6 - Cache
    grpc/1.45.2:084fc593ec049b0f2ba0805c6ff76fe8cb900ece - Cache
    openssl/1.1.1n:23b828d52c0630e6b0b96d2945419feb7843c4f8 - Cache
    protobuf/3.20.0:0e82fcdef8d9ba4b0102d297f7412225501ac869 - Cache
    re2/20220201:038baac88f4c7bfa972ce5adac1616bed8fe2ef4 - Cache
    zlib/1.2.12:23b828d52c0630e6b0b96d2945419feb7843c4f8 - Cache

Installing (downloading, building) binaries...
abseil/20211102.0: Already installed!
c-ares/1.18.1: Already installed!
c-ares/1.18.1: Appending PATH environment variable: /home/miso/.conan/data/c-ares/1.18.1/_/_/package/5a258fabd5aeaa11cbc1951f7243b664f46595f6/bin
openssl/1.1.1n: Already installed!
re2/20220201: Already installed!
zlib/1.2.12: Already installed!
protobuf/3.20.0: Already installed!
protobuf/3.20.0: Appending PATH environment variable: /home/miso/.conan/data/protobuf/3.20.0/_/_/package/0e82fcdef8d9ba4b0102d297f7412225501ac869/bin
grpc/1.45.2: Already installed!
grpc/1.45.2: Appending PATH environment variable: /home/miso/.conan/data/grpc/1.45.2/_/_/package/084fc593ec049b0f2ba0805c6ff76fe8cb900ece/bin
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/conans/client/generators/__init__.py", line 177, in write_generators
    generator.generate()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/cmakedeps.py", line 47, in generate
    generator_files = self.content
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/cmakedeps.py", line 89, in content
    self._generate_files(require, dep, ret, find_module_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/cmakedeps.py", line 102, in _generate_files
    ret[data_target.filename] = data_target.render()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/templates/__init__.py", line 42, in render
    context = self.context
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 28, in context
    global_cpp = self._get_global_cpp_cmake()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 137, in _get_global_cpp_cmake
    return _TargetDataContext(global_cppinfo, pfolder_var_name, self.conanfile.package_folder)
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 276, in __init__
    self.build_modules_paths = join_paths(build_modules)
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps/templates/target_data.py", line 211, in join_paths
    assert os.path.isabs(p), "{} is not absolute".format(p)
AssertionError: h is not absolute

ERROR: Error in generator 'CMakeDeps': h is not absolute
```
</details>

### Other

I initially reported this as a [bug in the CCI package](https://github.com/conan-io/conan-center-index/issues/10596), but it was suggested that this is actually a bug in the client.

**Comment by memsharded** [comment]
I am afraid this is a bug in the ``abseil`` dependency, not in the Conan client.

In the abseil ``package_info()``:
```python
self.cpp_info.set_property("cmake_build_modules", cxx_std_build_module)
```

While the ``cmake_build_modules`` property must be a list. To fix it replace that with:
```python
self.cpp_info.set_property("cmake_build_modules", [cxx_std_build_module])
```

Reference: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html?highlight=cmake_build_modules

> cmake_build_modules: **List** of .cmake files (route relative to root package folder) that are automatically included when the consumer run the find_package().

Note the ``List`` part.

Transferring this to conan-center-index repo
