### ISSUE TITLE
[bug] apple-clang compatibility with compiler.version="13"

### ISSUE THREAD

**Issue by RalfBielig** [conan-io/conan#11227]
### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version: apple-clang
  * Conan version: >1.46.0
  * Python version:

https://github.com/conan-io/conan/blob/229a7c9bfea8d454770e7253bd72b1804bb43b46/conans/model/info.py#L606
```
    def apple_clang_compatible(self):
        # https://github.com/conan-io/conan/pull/10797
        # apple-clang compiler version 13 will be compatible with 13.0
        if not self.settings.compiler or \
           (self.settings.compiler != "apple-clang" and self.settings.compiler.version != "13"):
            return

        compatible = self.clone()
        compatible.settings.compiler.version = "13.0"
        return compatible
```
the if-statement must be changed to:
```
        if not self.settings.compiler or \
           (self.settings.compiler != "apple-clang" or self.settings.compiler.version != "13"):
            return
```
**and** -> **or** because we want the compatible package, if  the compiler=="apple_clang" **and** compiler.version=="13", that means, we do not want it, if compiler!="apple_clang" **or** compiler.version!="13"

**Comment by RalfBielig** [comment]
```
    def package_id(self):
        if self.settings.compiler == "apple-clang":
            version = Version(str(self.settings.compiler.version))
            for v in ("13.1", "13.0", "12.0", "11.0", "10.0", "9.1", "9.0", "8.1", "8.0", "7.3", "7.0"):
                if v!=version:
                    compatible_pkg = self.info.clone()
                    compatible_pkg.settings.compiler.version = v
                    self.compatible_packages.append(compatible_pkg)
```
causes crash with backtrace:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.1
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
Traceback (most recent call last):
  File "D:\Programs\Python39\lib\site-packages\conans\client\command.py", line 2238, in run
    method(args[0][1:])
  File "D:\Programs\Python39\lib\site-packages\conans\client\command.py", line 525, in install
    info = self._conan.install(path=args.path_or_reference,
  File "D:\Programs\Python39\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "D:\Programs\Python39\lib\site-packages\conans\client\conan_api.py", line 609, in install
    deps_install(app=self.app,
  File "D:\Programs\Python39\lib\site-packages\conans\client\manager.py", line 58, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_manager.py", line 127, in load_graph
    deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_manager.py", line 289, in _resolve_graph
    deps_graph = self._load_graph(root_node, check_updates, update,
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_manager.py", line 410, in _load_graph
    self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_manager.py", line 336, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_binaries.py", line 431, in evaluate_graph
    self._evaluate_node(node, build_mode, update, remotes)
  File "D:\Programs\Python39\lib\site-packages\conans\client\graph\graph_binaries.py", line 218, in _evaluate_node
    assert node.binary is not None
AssertionError
```

**Comment by memsharded** [comment]
Thanks for your detailed analysis, indeed seems a bug in the compatibility. I am proposing your fix, and adding a test in https://github.com/conan-io/conan/pull/11231, and maybe for a patch 1.48.1 release to be released soon.

Regarding the other stack trace, I'd say that it is not related, and it could need more information to reproduce. For a start, it seems that this is being fired in some ``build_requires`` not in a regular require, so it would be great to have more details, probably in a new dedicated issue if not connected to the other one.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/11231 closes the first item, for 1.48.1

Would you please mind opening a new issue with details for the second thing? Thanks!

**Comment by RalfBielig** [comment]
Thanks a lot for the fast fix!
Regarding the second thing: I suppose that happens if an identic compatible package is added twice.
In my case the apple-clang "13.0" package was added once implicitly by the bug you`ve fixed and once by myself in the package_id() call.
I`ll open a new issue, if I can verify the above

**Comment by NoWiseMan** [comment]
I think this answers this too: https://github.com/conan-io/conan/issues/11104

**Comment by memsharded** [comment]
Yes, thanks @NoWiseMan for pointing it out !
