### ISSUE TITLE
[develop2][bug] 'conan list packages' fails with json format

### ISSUE THREAD

**Issue by antze-k** [conan-io/conan#11339]
### Environment Details
  * Operating System+version: **Windows 11**
  * Compiler+version: **CMake 3.18.2 + Visual Studio 2015**
  * Conan version: **2.0.0-alpha7**
  * Python version: **3.10.4**

### Steps to reproduce

```from conan import ConanFile
class TestPackageConan(ConanFile):
    name = "test-package"
    version = "0.1"
    no_copy_source = True
```

`conan create test-package -pr:b=x86_64-pc-windows-msvc.v140.MD.profile -pr:h=x86_64-pc-windows-msvc.v140.MD.profile`

(I use my profiles, I suppose one can use any)

`conan list packages -f json test-package/0.1#latest`

### Logs (Executed commands with output)

```
Local Cache:
  test-package/0.1#caea832e461d511773e1a0a2b9d1db21:da39a3ee5e6b4b0d3255bfef95601890afd80709
Traceback (most recent call last):
  File "C:\Program Files\Python 3.10\lib\site-packages\conans\cli\cli.py", line 163, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "C:\Program Files\Python 3.10\lib\site-packages\conans\cli\command.py", line 163, in run
    self._subcommands[subcommand].run(conan_api, *args)
  File "C:\Program Files\Python 3.10\lib\site-packages\conans\cli\command.py", line 182, in run
    self._format(self._parent_parser, info, *args)
  File "C:\Program Files\Python 3.10\lib\site-packages\conans\cli\command.py", line 132, in _format
    result = formatter(info)
  File "C:\Program Files\Python 3.10\lib\site-packages\conans\cli\commands\__init__.py", line 33, in json_formatter
    myjson = json.dumps(data, indent=4, cls=ConanJSONEncoder)
  File "C:\Program Files\Python 3.10\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python 3.10\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Program Files\Python 3.10\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python 3.10\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python 3.10\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python 3.10\lib\json\encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not PkgReference

ERROR: keys must be str, int, float, bool or None, not PkgReference
```

**Comment by memsharded** [comment]
Hi @antze-k 

I think this bug as been addressed by https://github.com/conan-io/conan/pull/11232. It has already been merged to the ``develop2`` branch if you want to test it and it will be part of the ``2.0-beta.1``.

Thanks very much for reporting!

**Comment by memsharded** [comment]
Closing this as done.
