### ISSUE TITLE
[bug] `conan config set` broken with keys containing `.`

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#11880]
### Environment Details (include every applicable attribute)
  * Operating System+version: linux
  * Compiler+version: any
  * Conan version: 1.49.0 and 1.51.2
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
```
conan config set tools.system.package_manager:mode=install
cat /home/eric/.conan/conan.conf
conan config set tools.system.package_manager:sudo=True
cat /home/eric/.conan/conan.conf
conan -v
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
eric@DESKTOP-1HV1KQ7 ~> conan config set tools.system.package_manager:mode=install
eric@DESKTOP-1HV1KQ7 ~> cat /home/eric/.conan/conan.conf
(...)
[tools]
system.package_manager:mode = install

eric@DESKTOP-1HV1KQ7 ~> conan config set tools.system.package_manager:sudo=True
eric@DESKTOP-1HV1KQ7 ~> cat /home/eric/.conan/conan.conf
(...)
[tools]
system.package_manager = mode = install
system.package_manager:sudo = True

eric@DESKTOP-1HV1KQ7 ~>  conan -v
Traceback (most recent call last):
  File "/home/eric/.local/bin/conan", line 8, in <module>
    sys.exit(run())
  File "/home/eric/.local/lib/python3.8/site-packages/conans/conan.py", line 11, in run
    main(sys.argv[1:])
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/command.py", line 2373, in main
    conan_api, _, _ = Conan.factory()
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/conan_api.py", line 224, in factory
    return cls(), None, None
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/conan_api.py", line 238, in __init__
    check_required_conan_version(self.cache_folder, self.out)
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/conf/required_version.py", line 28, in check_required_conan_version
    cache = ClientCache(cache_folder, out)
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/cache/cache.py", line 83, in __init__
    self._store_folder = self.config.storage_path or os.path.join(self.cache_folder, "data")
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/cache/cache.py", line 156, in config
    self._config = ConanClientConfigParser(self.conan_conf_path)
  File "/home/eric/.local/lib/python3.8/site-packages/conans/client/conf/__init__.py", line 323, in __init__
    self.read(filename)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/home/eric/.conan/conan.conf' [line 25]: option 'system.package_manager' in section 'tools' already exists
```

**Comment by memsharded** [comment]
Hi @ericLemanissier 

I think you are mixing ``conan.conf`` and ``global.conf``.

The new ``conf`` items only go to ``global.conf``, so it is an error trying to add them to ``conan.conf`` (this later dissapears in 2.0). So the ``conan config ....`` command cannot be used to append them to the configuration files, instead, editing the files is the way to go. On the other hand, the new ``conf`` can also go in command line args and in profiles.

**Comment by ericLemanissier** [comment]
You are right. The proper way to go is:
```
conan profile update conf.tools.system.package_manager:mode=install default
conan profile update conf.tools.system.package_manager:sudo=True default
```
right ?
This gives the following:
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
tools.system.package_manager:mode=install
tools.system.package_manager:sudo=True
[build_requires]
[env]
```

**Comment by ericLemanissier** [comment]
it works as expected with the `conan profile update ...`

**Comment by memsharded** [comment]
Yes, conf can be in profiles, and ``conan profile update`` still works in 1.X. ``conan profile update`` has been removed in 2.0, as editing text files via commands didn't sound the best approach.
