### ISSUE TITLE
[bug] clang-cl requires only_diff=False in vcvars

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan#12014]
I'm trying to build package that depends on hiredis/1.0.2 with clang-cl conan profile. 
Build fails and only known to me way to fix it is to manyally modify all recipes from conan-center-index (that i use as dependencies) with `tools.vcvars(self.settings, only_diff=False):` . Bug related to https://github.com/conan-io/conan/issues/6577

My conan profile:

```
toolchain_arch=x86_64

[settings]
# Tested in Windows 10
os=Windows
os_target=Windows
os_build=Windows
arch_build=$toolchain_arch
arch=$toolchain_arch
compiler=clang
compiler.version=14
build_type=Debug
[options]
[tool_requires]
cmake/[>=3.23]
ninja/[>=1.11]
ccache/[>=4.6]
[buildenv]
CC=clang-cl.exe
CXX=clang-cl.exe
[build_requires]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.env.virtualenv:auto_use=True
tools.files.download:retry=3
tools.files.download:retry_wait=5
tools.system.package_manager:tool="choco"
[env]
CONAN_CMAKE_GENERATOR=Ninja
CONAN_REVISIONS_ENABLED=1
CONAN_VERBOSE_TRACEBACK=1
CONAN_PRINT_RUN_COMMANDS=1
CONAN_LOGGING_LEVEL=10
CONAN_USE_ALWAYS_SHORT_PATHS=1
CC=clang-cl.exe
CXX=clang-cl.exe
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: clang-cl.exe
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
  * Conan version: Conan version 1.51.3
  * Python version: Python 3.10.5

### Steps to reproduce (Include if Applicable)

Build anything with clang-cl profile

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
----Running------
> "C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\conanbuild.bat" && cd C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\build_subfolder && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MTd" -DCMAKE_BUILD_TYPE="Debug" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="clang" -DCONAN_COMPILER_VERSION="14" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\package\0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_MODULE_PATH="C:/Users/den00/.conan/data/hiredis/1.0.2/_/_/build/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DENABLE_SSL="False" -DDISABLE_TESTS="True" -DENABLE_EXAMPLES="False" -Wno-dev C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2
-----------------
Capturing current environment in C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\deactivate_conanbuildenv-debug-x86_64.bat
Configuring environment variables
-- The C compiler identification is Clang 12.0.0 with MSVC-like command-line
-- The CXX compiler identification is Clang 12.0.0 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Compiler Clang>=8, checking major version 14
-- Conan: Checking correct version: 12
  Detected a mismatch for the compiler version between your conan profile
  settings and CMake:

  Compiler version specified in your conan profile: 14

  Compiler version detected in CMake: 12.0

  Please check your conan profile settings (conan profile show
  [default|your_profile_name])

  P.S.  You may set CONAN_DISABLE_CHECK_COMPILER CMake variable in order to
  disable this check.
Call Stack (most recent call first):
  conanbuildinfo.cmake:501 (conan_error_compiler_version)
  conanbuildinfo.cmake:593 (check_compiler_version)
  conanbuildinfo.cmake:141 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "C:/Users/den00/.conan/data/hiredis/1.0.2/_/_/build/0974a5b97849875d7301803ccabc46a5c139aab2/build_subfolder/CMakeFiles/CMakeOutput.log".
hiredis/1.0.2:
hiredis/1.0.2: ERROR: Package '0974a5b97849875d7301803ccabc46a5c139aab2' build failed
hiredis/1.0.2: WARN: Build folder C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2
Level 5:process_lock.py[145]: Acquired file lock `b'C:\\Users\\den00\\.conan\\data\\hiredis\\1.0.2\\_\\_.count.lock'` after waiting 0.000s [1 attempts were required] [2022-09-02 14:38:12,588]
Level 5:process_lock.py[183]: Unlocked and closed file lock open on `b'C:\\Users\\den00\\.conan\\data\\hiredis\\1.0.2\\_\\_.count.lock'` [2022-09-02 14:38:12,589]
Level 5:process_lock.py[183]: Unlocked and closed file lock open on `b'C:\\Users\\den00\\.conan\\data\\hiredis\\1.0.2\\_\\_\\locks\\0974a5b97849875d7301803ccabc46a5c139aab2'` [2022-09-02 14:38:12,589]
ERROR: Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python310\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\export\conanfile.py", line 64, in build
    cmake = self._configure_cmake()
  File "C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\export\conanfile.py", line 74, in _configure_cmake
    self._cmake.configure(build_folder=self._build_subfolder)
  File "C:\Python310\lib\site-packages\conans\client\build\cmake.py", line 287, in configure
    self._run(command)
  File "C:\Python310\lib\site-packages\conans\client\build\cmake.py", line 247, in _run
    self._conanfile.run(command)
  File "C:\Python310\lib\site-packages\conans\model\conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cd C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\build_subfolder && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MTd" -DCMAKE_BUILD_TYPE="Debug" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="clang" -DCONAN_COMPILER_VERSION="14" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\package\0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_MODULE_PATH="C:/Users/den00/.conan/data/hiredis/1.0.2/_/_/build/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DENABLE_SSL="False" -DDISABLE_TESTS="True" -DENABLE_EXAMPLES="False" -Wno-dev C:\Users\den00\.conan\data\hiredis\1.0.2\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2

Elapsed time: 25 s. (time), 25.483 s. (clock)
CMake Error at C:/Users/den00/conan_github_downloader/conan_github_downloader.cmake:339 (message):
  (conan_install_target)

        Bad exit status 1
Call Stack (most recent call first):
  C:/Users/den00/conan_github_downloader/conan_github_downloader.cmake:385 (conan_install_target)
  get_conan_dependencies.cmake:14 (conan_build_target_if)
  C:/Users/den00/conan_github_downloader/conan_github_downloader.cmake:488 (include)
```

**Comment by blockspacer** [comment]
@memsharded

Is it possible to overcome that issue somehow (maybe i am doing something wrong)?

I just want to build code using clang-cl on windows and build fails due to issue above.

Note that  build of `conan new hello/0.1 -m=cmake_lib` also fails https://github.com/conan-io/conan/issues/12013#issuecomment-1236659063

**Comment by memsharded** [comment]
Hi @blockspacer 

Sorry, this is not clear. You are saying that you are using the new CMake integration, and have the configuration for it defined (for ``CMakeToolchain`` and ``CMakeDeps``). Still, I can see the logs that the ``cmake`` integration and the ``conanbuildinfo.cmake`` are being used.

We have some tests that covers building with Clang in Windows, though it is true that this needs some work, and there is an ongoing effort to improve the Windows-Clang support. These are the current tests: https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/cmake/test_cmake_toolchain_win_clang.py

So the above ``conan new hello/0.1 -m=cmake_lib`` should build with clang, at least our test suite is passing. It seems it is the other dependency ``hiredis`` that is failing (because it is still using the legacy integrations), but we need to isolate and reproduce things in the most simple way to be able to fix them. So please, try the ``conan new``, but without adding extra stuff, no additional requirements, just the simplest profile that you can define, and let us know.

**Comment by blockspacer** [comment]
@memsharded 

`conan new hello/0.1 -m=cmake_lib` fails with ninja  (message): The C++ compiler    "C:/Program Files/LLVM/bin/clang-cl.exe"
  is not able to compile a simple test program.

My conan profile:

```
[settings]
# Tested in Windows 10
os=Windows
arch=x86_64
compiler=clang
build_type=Debug
[options]
[tool_requires]
cmake/[>=3.23]
ninja/[>=1.11]
[buildenv]
CC=clang-cl.exe
CXX=clang-cl.exe
[build_requires]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
[env]
CONAN_REVISIONS_ENABLED=1
CONAN_VERBOSE_TRACEBACK=1
CONAN_PRINT_RUN_COMMANDS=1
VERBOSE=1
CONAN_LOGGING_LEVEL=10
CONAN_USE_ALWAYS_SHORT_PATHS=1
```

Note that `tools.cmake.cmaketoolchain:generator=Visual Studio 16` succeeds.

Conan version 1.51.3
SystemDirectory : C:\Windows\system32
Windows BuildNumber     : 19044
Windows  Version         : 10.0.19044

```
clang-cl -v
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

Full log:

```
conan create . conan/stable -s build_type=Debug --profile clang_cl -pr:b=clang_cl --build missing
DEBUG :conan_api.py   [176]: INIT: Using config 'C:\Users\den00\.conan\conan.conf' [2022-09-22 09:31:53,943]
DEBUG :tracer.py      [156]: CONAN_API: create(name=None,version=None,user=conan,channel=stable,profile_names=['clang_cl'],settings=['build_type=Debug'],conf=None,options=None,env=None,test_folder=None,not_export=False,build_modes=['missing'],keep_source=False,keep_build=False,verify=None,manifests=None,manifests_interactive=None,remote_name=None,update=False,test_build_folder=None,lockfile=None,lockfile_out=None,ignore_dirty=False,profile_build=ProfileData(profiles=['clang_cl'], settings=None, options=None, env=None, conf=None),is_build_require=False,require_overrides=None) [2022-09-22 09:31:53,944]
DEBUG :profile_loader.py[120]: PROFILE LOAD: C:\Users\den00\.conan\profiles\default [2022-09-22 09:31:53,946]
DEBUG :profile_loader.py[120]: PROFILE LOAD: C:\Users\den00\.conan\profiles\clang_cl [2022-09-22 09:31:53,947]
DEBUG :profile_loader.py[120]: PROFILE LOAD: C:\Users\den00\.conan\profiles\default [2022-09-22 09:31:53,980]
DEBUG :profile_loader.py[120]: PROFILE LOAD: C:\Users\den00\.conan\profiles\clang_cl [2022-09-22 09:31:53,980]
DEBUG :export.py      [114]: EXPORT: G:\files\conantest\conanfile.py [2022-09-22 09:31:54,025]
Exporting package recipe
hello/0.1@conan/stable exports_sources: Copied 1 '.txt' file: CMakeLists.txt
hello/0.1@conan/stable exports_sources: Copied 1 '.cpp' file: hello.cpp
hello/0.1@conan/stable exports_sources: Copied 1 '.h' file: hello.h
hello/0.1@conan/stable: The stored package has not changed
hello/0.1@conan/stable: Using the exported files summary hash as the recipe revision: 4fc80e430f8244be40256fab755f8c43
hello/0.1@conan/stable: Exported revision: 4fc80e430f8244be40256fab755f8c43
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.version=14
os=Windows
[options]
[build_requires]
*: cmake/[>=3.23], ninja/[>=1.11]
[env]
CONAN_LOGGING_LEVEL=10
CONAN_PRINT_RUN_COMMANDS=1
CONAN_REVISIONS_ENABLED=1
CONAN_USE_ALWAYS_SHORT_PATHS=1
CONAN_VERBOSE_TRACEBACK=1
VERBOSE=1
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
[buildenv]
CC=clang-cl.exe
CXX=clang-cl.exe

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.version=14
os=Windows
[options]
[build_requires]
*: cmake/[>=3.23], ninja/[>=1.11]
[env]
CONAN_LOGGING_LEVEL=10
CONAN_PRINT_RUN_COMMANDS=1
CONAN_REVISIONS_ENABLED=1
CONAN_USE_ALWAYS_SHORT_PATHS=1
CONAN_VERBOSE_TRACEBACK=1
VERBOSE=1
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
[buildenv]
CC=clang-cl.exe
CXX=clang-cl.exe

DEBUG :graph_builder.py[462]: GRAPH: new_node: hello/0.1@conan/stable [2022-09-22 09:31:54,074]
DEBUG :graph_builder.py[69]: GRAPH: Time to load deps 0.005983591079711914 [2022-09-22 09:31:54,077]
DEBUG :graph_builder.py[462]: GRAPH: new_node: cmake/3.24.1 [2022-09-22 09:31:54,092]
DEBUG :graph_builder.py[462]: GRAPH: new_node: ninja/1.11.0 [2022-09-22 09:31:54,098]
Version ranges solved
    Version range '>=3.23' required by 'hello/0.1@conan/stable (test package)' resolved to 'cmake/3.24.1' in local cache
    Version range '>=1.11' required by 'hello/0.1@conan/stable (test package)' resolved to 'ninja/1.11.0' in local cache

hello/0.1@conan/stable (test package): Installing package
Requirements
    hello/0.1@conan/stable from local cache - Cache
Packages
    hello/0.1@conan/stable:931d2edf6a5487d3fff35fc1858f3a207c7dd53f - Cache
Build requirements
    cmake/3.24.1 from 'conancenter' - Cache
    ninja/1.11.0 from 'conancenter' - Cache
Build requirements packages
    cmake/3.24.1:01edd76db8e16db9b38c3cca44ec466a9444c388 - Cache
    ninja/1.11.0:01edd76db8e16db9b38c3cca44ec466a9444c388 - Cache

Installing (downloading, building) binaries...
cmake/3.24.1: Already installed!
cmake/3.24.1: Appending PATH environment variable: C:\Users\den00\.conan\data\cmake\3.24.1\_\_\package\01edd76db8e16db9b38c3cca44ec466a9444c388\bin
hello/0.1@conan/stable: Already installed!
ninja/1.11.0: Already installed!
hello/0.1@conan/stable (test package): Applying build-requirement: cmake/3.24.1
hello/0.1@conan/stable (test package): Applying build-requirement: ninja/1.11.0
hello/0.1@conan/stable (test package): Generator 'VirtualRunEnv' calling 'generate()'
hello/0.1@conan/stable (test package): Generator 'VirtualBuildEnv' calling 'generate()'
hello/0.1@conan/stable (test package): Generator 'CMakeDeps' calling 'generate()'
hello/0.1@conan/stable (test package): Generator 'CMakeToolchain' calling 'generate()'
hello/0.1@conan/stable (test package): Generator txt created conanbuildinfo.txt
hello/0.1@conan/stable (test package): Aggregating env generators
hello/0.1@conan/stable (test package): Generated conaninfo.txt
hello/0.1@conan/stable (test package): Generated graphinfo
DEBUG :build.py       [19]: BUILD: folder 'G:\files\conantest\test_package' [2022-09-22 09:31:54,863]
DEBUG :build.py       [20]: BUILD: Conanfile at 'G:\files\conantest\test_package\conanfile.py' [2022-09-22 09:31:54,863]
Using lockfile: 'G:\files\conantest\test_package/conan.lock'
Using cached profile from lockfile
DEBUG :build.py       [11]: Call conanfile.build() with files in build folder: ['CMakeCache.txt', 'CMakeFiles', 'example.exe', 'example.lib', 'example.pdb'] [2022-09-22 09:31:54,942]
hello/0.1@conan/stable (test package): Calling build()
hello/0.1@conan/stable (test package): CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="G:/files/conantest/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "G:\files\conantest\test_package\."

----Running------
> "G:\files\conantest\test_package\build\generators\conanbuild.bat" && cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="G:/files/conantest/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "G:\files\conantest\test_package\."
-----------------
Capturing current environment in G:\files\conantest\test_package\build\generators\deactivate_conanbuildenv-debug-x86_64.bat
Configuring environment variables
-- Using Conan toolchain: G:/files/conantest/test_package/build/generators/conan_toolchain.cmake
-- The CXX compiler identification is Clang 14.0.6 with MSVC-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang-cl.exe - broken
CMake Error at C:/Users/den00/.conan/data/cmake/3.24.1/_/_/package/01edd76db8e16db9b38c3cca44ec466a9444c388/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "C:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: G:/files/conantest/test_package/build/Debug/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Users/den00/.conan/data/ninja/1.11.0/_/_/package/01edd76db8e16db9b38c3cca44ec466a9444c388/bin/ninja.exe cmTC_3c9ce && [1/2] Building CXX object CMakeFiles\cmTC_3c9ce.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_3c9ce.exe
    FAILED: cmTC_3c9ce.exe
    cmd.exe /C "cd . && C:\Users\den00\.conan\data\cmake\3.24.1\_\_\package\01edd76db8e16db9b38c3cca44ec466a9444c388\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_3c9ce.dir --rc=clang --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo CMakeFiles\cmTC_3c9ce.dir\testCXXCompiler.cxx.obj  /out:cmTC_3c9ce.exe /implib:cmTC_3c9ce.lib /pdb:cmTC_3c9ce.pdb /version:0.0 -m64 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "clang /fo CMakeFiles\cmTC_3c9ce.dir/manifest.res CMakeFiles\cmTC_3c9ce.dir/manifest.rc" failed (exit code 1) with the following output:
    clang: error: no such file or directory: '/fo'
    clang: error: no such file or directory: 'CMakeFiles\cmTC_3c9ce.dir/manifest.res'
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "G:/files/conantest/test_package/build/Debug/CMakeFiles/CMakeOutput.log".
See also "G:/files/conantest/test_package/build/Debug/CMakeFiles/CMakeError.log".
ERROR: Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python310\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "G:\files\conantest\test_package\conanfile.py", line 21, in build
    cmake.configure()
  File "C:\Python310\lib\site-packages\conan\tools\cmake\cmake.py", line 97, in configure
    self._conanfile.run(command)
  File "C:\Python310\lib\site-packages\conans\model\conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="G:/files/conantest/test_package/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "G:\files\conantest\test_package\."
```

**Comment by memsharded** [comment]
There is something weird in your log, the ``hello`` package seems to already exist, like it was created previously succesfully, and it is failing in the ``test_package`` step only:

> hello/0.1@conan/stable from local cache - Cache

Then, a couple of hints:
- If the environment is to be defined in profile, recipes must use the ``generators = "VirtualBuildEnv"``, to inject correctly the ``[buildenv]``, or use the ``tools.env.virtualenv:auto_use=True`` conf to enable this (2.0-compatible behavior)
- It seems that this could be a CMake issue. The ``ClangCL`` is intended to be run with the Visual Studio generators, while if using Ninja, the ``clang`` compiler frontend is the one that correctly works, but not ``clang-cl``. Have you tried that?

**Comment by memsharded** [comment]
Closing this ticket as inactive, and also outdated, because it was about Conan 1.

The integrations for Clang in Conan 2 are more mature, this is most likely not an issue nowadays, so I am closing this ticket as solved in Conan2, but please let us know otherwise, comment or open new tickets for any further question or issue. Thanks for the feedback!
