### ISSUE TITLE
[bug] KeyError: 'cmake' when having both CMake and cmake packages in the cache

### ISSUE THREAD

**Issue by Da-LiFe** [conan-io/conan#12416]
### Environment Details (include every applicable attribute)
  * Operating System+version: open suse leap 15.3
  * Compiler+version: gcc7
  * Conan version: 1.40.4
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)

We use an internal cmake package in our organisation and, unfortunatelly, called it `CMake`. For the transition to conan 2.0 we need to start using a lower-case package `cmake` and update all dependencies. I've started this process and discovered an interesting behaviour of conan.

I have `PkgA -> PkgB -> CMake`. PkgA also depends on other packages not requiring cmake. When I run `conan info PkgA` having  lower-case cmake already in the cache I get a key error. If I remove the lower-case cmake from the cache it works. Noteable, the package still depends on the upper-case variant. So even not being part of the dep-tree, lower-case cmake has an influance on the conan info command. Another observation is, that conan is not fetching `CMake` from our remote in this case.

Having `PkgD->CMake` conan info will fetch it and the command works altough lower-case cmake is in the cache.

For the transistion to conan 2.0 I think it is quite likely to have both version in the cache. So at least conan should give some meaningful error such as https://docs.conan.io/en/latest/faq/troubleshooting.html?#error-requested-a-package-but-found-case-incompatible

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
> conan search cmake
Existing package recipes:

cmake/3.24.1@3rdparty/stable

> conan info PkgA
[no fetch of CMake, because cmake is present]
...
Traceback (most recent call last):
  File ".../python3.6/site-packages/conans/client/command.py", line 2232, in run
    method(args[0][1:])
  File ".../python3.6/site-packages/conans/client/command.py", line 790, in info
    lockfile=args.lockfile)
  File ".../python3.6/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File ".../python3.6/site-packages/conans/client/conan_api.py", line 753, in info
    update, False, remotes, recorder)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 122, in load_graph
    apply_build_requires=apply_build_requires)
  File .../python3.6/site-packages/conans/client/graph/graph_manager.py", line 282, in _resolve_graph
    graph_lock=graph_lock)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 390, in _load_graph
    apply_build_requires=apply_build_requires)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 313, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File ".../python3.6/site-packages/conans/client/graph/graph_binaries.py", line 395, in evaluate_graph
    self._propagate_options(node)
  File ".../python3.6/site-packages/conans/client/graph/graph_binaries.py", line 308, in _propagate_options
    conanfile.requires[ref.name].ref = ref
KeyError: 'cmake'

> conan info PkgD
CMake/3.24.1@3rdparty/stable: Downloaded recipe revision 5bd0ad5ab85b682046a519c25293c69e
[no key error]

> conan search cmake
Existing package recipes:

CMake/3.24.1@3rdparty/stable
cmake/3.24.1@3rdparty/stable
```

**Comment by Da-LiFe** [comment]
I'm also able to reproduce this error with conan 1.54.0. Setup this time: 

conanfile.txt:
```
[requires]
CMake/[^3]@3rdparty/stable
```

```
> conan search CMake
Existing package recipes:

cmake/3.24.1@3rdparty/stable
```

```
> conan install conanfile.txt
[...]
Traceback (most recent call last):
  File ".../python3.6/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File ".../python3.6/site-packages/conans/client/command.py", line 539, in install
    require_overrides=args.require_override)
  File "../python3.6/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File ".../python3.6/site-packages/conans/client/conan_api.py", line 625, in install
    conanfile_path=os.path.dirname(conanfile_path))
  File ".../python3.6/site-packages/conans/client/manager.py", line 62, in deps_install
    require_overrides=require_overrides)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 130, in load_graph
    apply_build_requires=apply_build_requires)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 296, in _resolve_graph
    graph_lock=graph_lock)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 414, in _load_graph
    apply_build_requires=apply_build_requires)
  File ".../python3.6/site-packages/conans/client/graph/graph_manager.py", line 337, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File .../python3.6/site-packages/conans/client/graph/graph_binaries.py", line 432, in evaluate_graph
    self._propagate_options(node)
  File ".../python3.6/site-packages/conans/client/graph/graph_binaries.py", line 331, in _propagate_options
    conanfile.requires[ref.name].ref = ref
KeyError: 'CMake'
```

**Comment by memsharded** [comment]
Sorry this was not responded back then.
Now it seems this is outdated, and it shouldn't be at issue with Conan 2, I am closing as outdated, but please create new tickets if necessary. Thanks for the feedback!
