### ISSUE TITLE
[bug] Setting `conan_home` in `.conanrc` to just `.` for current directory fails

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12465]
I want to have a github repo with all of my config files in the root so it's each so show the layout.
My frame of of reference for my expectations https://github.com/conan-io/conan/pull/11675

> Set the conan home to a relative folder inside the current folder
> ```
> # accepts comments
> conan_home=./relative folder/inside current folder
> ```

I was expect to set just `.` for the current directory

### Environment Details (include every applicable attribute)
  * Operating System+version: Macos 
  * Compiler+version:
  * Conan version: 2.0.0-beta4
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)

1. With new line
```sh
echo "conan_home=.\n" > .conanrc
conan config home
```

2. no line ending
```sh
echo "conan_home=." > .conanrc
conan config home
```

```


### Logs (Executed commands with output) (Include/Attach if Applicable)

1. with new line
```sh
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/conan", line 33, in <module>
    sys.exit(load_entry_point('conan==2.0.0b4', 'console_scripts', 'conan')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/cli.py", line 211, in main
    conan_api = ConanAPIV2()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/conan_api.py", line 33, in __init__
    self.cache_folder = cache_folder or get_conan_user_home()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/paths/__init__.py", line 42, in get_conan_user_home
    user_home = _user_home_from_conanrc_file() or os.getenv("CONAN_HOME")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/paths/__init__.py", line 30, in _user_home_from_conanrc_file
    values = {k: str(v) for k, v in
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/paths/__init__.py", line 30, in <dictcomp>
    values = {k: str(v) for k, v in
ValueError: not enough values to unpack (expected 2, got 1)
```

2. no line ending
```sh
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/conan", line 33, in <module>
    sys.exit(load_entry_point('conan==2.0.0b4', 'console_scripts', 'conan')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/cli.py", line 211, in main
    conan_api = ConanAPIV2()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/conan_api.py", line 33, in __init__
    self.cache_folder = cache_folder or get_conan_user_home()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/paths/__init__.py", line 49, in get_conan_user_home
    raise Exception("Invalid CONAN_HOME value '%s', "
Exception: Invalid CONAN_HOME value '.', please specify an absolute or path starting with ~/ (relative to user home)
```

**Comment by memsharded** [comment]
But quick question, if you assign the current ``.`` folder, the project will be extremely polluted, with all the home files, subfolders, etc. Not to say the risk of collision with some project files. This is the reason why at the very least, it should be a subfolder in the current project, can you please elaborate on this?

**Comment by prince-chrismc** [comment]
So my initial reflext was most of the files need to be version controlled `settings.yml`, profiles, and I assumed extentions and plugins would follow the same logic.

Instead of having a separate repo and a `conan config install git://example.come/my-repo` my dream was I could just inline everything in on repos and have that be my home.

```diff
- conan config install ...
+ echo "" > .conanrc
```

Now that you pointed out some of the flaws and got me thinking...

I wanted to track _some_ of the files like a profile checker and ignore the rest but that seems like a very slippery slope. 

So Even if you use `.conanrc` you'll still want to `conan config install`? It's not a replacement.

***

Maybe the solution is just a nicer error message? Don't let users do this.

**Comment by memsharded** [comment]
The ``conan_home`` will contain absolutely everything, all settings, profiles, plugins, custom commands, packages cache, the version.txt, the remotes.json... that is the problem, it is a full conan home.

Yes, indeed if a stack trace happens, providing a better error message should be done.
