### ISSUE TITLE
[question] 2.0 Deployers with a graph that has skipped packages are not passed but still listed

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12522]
I found a bug :smiling_imp: no chance you'll get any sleep :sleeping: now :slightly_smiling_face: 
(it actually might not be a bug - it could be by design)

The deployers in beta 5 do not like when a dependency is marked as skipped -- you get all of them in the graph but there's no obvious way which one to ignore
The graph object contains all the references but the dependencies objects are none

```py
def deploy(graph, output_folder, **kwargs):
    conanfile = graph.root.conanfile
    files = []
    for r, d in conanfile.dependencies.items():
        if d.package_folder is None:
            print(f"{r} is None")
```

```txt
-------- Computing necessary packages --------
Requirements
    engine/1.0#073dd80b11976921b9aa641088935185:3d740000af0269cba61977e552980e5ab0eed6bf#385f2c1565f956200b7944df7e7cb543 - Cache
    game/1.0#0bf1ca0ef52e3b22d62e90d4cc8ed486:4cb01dfc6eb416f27ad67635f16a228aa3c541ad#47aa34afdc4350a79711a4f7ca561bcd - Cache
    math/1.0#02fc9388fa48ee96ef5bc9976d653729:0cbbca71fa71c42e80adb683729a9e3962abdf75#37e2e6b9bb02cd96fcb5b3b16aa9c403 - Skip

-------- Installing packages --------

-------- Installing (downloading, building) binaries... --------
engine/1.0: Already installed!
game/1.0: Already installed!

-------- Finalizing install (deploy, generators) --------
game/1.0, Traits: build=False, headers=False, libs=False, run=True, visible=True
engine/1.0, Traits: build=False, headers=False, libs=False, run=True, visible=True
math/1.0, Traits: build=False, headers=False, libs=False, run=False, visible=True # I added this print to see it 
# however it's object is None.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/cli.py", line 170, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/command.py", line 186, in run
    info = self._method(conan_api, parser, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/commands/install.py", line 182, in install
    conan_api.install.install_consumer(deps_graph=deps_graph,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/subapi/install.py", line 52, in install_consumer
    do_deploys(self.conan_api, deps_graph, deploy, base_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/subapi/install.py", line 96, in do_deploys
    deployer(graph=graph, output_folder=deploy_folder)
  File "/Users/christopherm/conan-whatsnew2/conan2_home/extensions/deploy/runtime_zip_deploy.py", line 13, in deploy
    bindir = os.path.join(d.package_folder, "bin")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I think this is by design:

- there are deployers that can be even applied to ``conan graph info`` where no package at all is retrieved, so no ``cpp_info`` at all, and ``package_folder=None`` for the whole graph.
- It is the responsibility of the writer to know that they are doing. If you want to deploy only packages that are not skipped, typically from the "host" context, you iterate ``self.dependencies.host.items()`` instead. Also ``self.dependencies.build`` can be used for the tools, and you can also check the ``package_folder`` for ``None``. 

The ``runtime_zip_deploy.py`` is most likely not complete of fully correct/robust, and need to be improved.

**Comment by prince-chrismc** [comment]
That's a good reason. I think the docs and examples with help users implement their own.
