### ISSUE TITLE
[bug] conan create with --json fails

### ISSUE THREAD

**Issue by martin-koch** [conan-io/conan#12608]
When I run conan create with --json the command fails at the very end.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.10
  * Compiler+version: clang14
  * Conan version: 1.54.0
  * Python version: 2.7.18

### Steps to reproduce (Include if Applicable)
I am able to reproduce this issue when building libsystemd from conan center.

### Logs (Executed commands with output) (Include/Attach if Applicable)
`
conan create recipes/libsystemd/all libsystemd/251.4@mychannel/stable --profile=clang14 --json=test.json --build=missing
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.10/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/home/martin/.local/lib/python3.10/site-packages/conans/client/command.py", line 402, in create
    self._outputer.json_output(info, args.json, cwd)
  File "/home/martin/.local/lib/python3.10/site-packages/conans/client/conan_command_output.py", line 82, in json_output
    save(json_output, json.dumps(info, default=date_handler))
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/martin/.local/lib/python3.10/site-packages/conans/client/conan_command_output.py", line 80, in date_handler
    raise TypeError("Unserializable object {} of type {}".format(obj, type(obj)))
TypeError: Unserializable object 251 of type <class 'conan.tools.scm._VersionItem'>

ERROR: Unserializable object 251 of type <class 'conan.tools.scm._VersionItem'>
`

**Comment by franramirez688** [comment]
Hi @martin-koch,

Thanks for reporting it! I think it's a bug in the recipe itself. These lines should be enough to solve the issue:

```python
        self.cpp_info.version = str(Version(self.version).major)
        self.cpp_info.set_property("component_version",
                                   str(Version(self.version).major))
```
Let me transfer the issue to ConanCenter and solve there the issue.
