### ISSUE TITLE
[bug] tools.files.patch not usable with development worfklow

### ISSUE THREAD

**Issue by Bearwolves** [conan-io/conan#12748]
### Environment details

* Operating System+version: Ubuntu 18.04
* Compiler+version: N.A
* Conan version: 1.55.0
* Python version: 3.6

### Steps to reproduce

Calling `tools.files.patch` with an absolute path 
```python
def source(self):
     patch(self, base_path=self.source_folder, patch_file=os.path.join(self.recipe_folder, "patches", "0001-dummy.patch"))
```
It fails
```
export CONAN_VERBOSE_TRACEBACK=1
...
conan install --profile:build "linux-settings" --profile:host "${PROFILE}" --install-folder "${BUILD_DIR}" "${SCRIPT_DIR}"
conan source --source-folder "${SOURCE_DIR}" --install-folder "${BUILD_DIR}" "${SCRIPT_DIR}"
...
conanfile.py (xxxx/3.2.3): Checkout: xxxxx-3.2.3
export_sources_folder [None]
patch_file [/home/XXX6XXX/wp/dummy/patches/0001-dummy.patch]
recipe_folder [/home/XXX6XXX/wp/dummy]
ERROR: Traceback (most recent call last):
  File "/home/XXX6XXX/.local/lib/python3.6/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/XXX6XXX/.local/lib/python3.6/site-packages/conans/client/source.py", line 157, in _run_source
    conanfile.source()
  File "/home/XXX6XXX/wp/dummy/conanfile.py", line 63, in source
    patch(self, base_path=self.source_folder, patch_file=os.path.join(self.recipe_folder, "patches", p))
  File "/home/XXX6XXX/.local/lib/python3.6/site-packages/conan/tools/files/patches.py", line 55, in patch
    patch_path = os.path.join(conanfile.export_sources_folder, patch_file)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Issue seems to be that `self.export_sources_folder` is not set, just try to print `self.export_sources_folder` in the source method() demonstrate the issue
```
print(f"self.export_sources_folder [{self.export_sources_folder}]")
...
self.export_sources_folder [None]
```
Line in the code => https://github.com/conan-io/conan/blob/develop/conan/tools/files/patches.py#L52

I didn't debug further as I don't know the conan path generation mechanic yet. Did I miss to configure something?

**Comment by memsharded** [comment]
Hi @Bearwolves 

Thanks for your report.
I am trying to reproduce, but so far I haven't been able to do it. This is the test that I have:
```python
def test_patch_error():
    # https://github.com/conan-io/conan/issues/12748
    conanfile = textwrap.dedent("""
        import os
        from conan import ConanFile
        from conan.tools.files import patch, save, load

        class Pkg(ConanFile):
            name = "mypkg"
            version = "1.0"
            exports_sources = "*"
            no_copy_source = True

            def source(self):
                self.output.info("EXPORT FOLDER: {}".format(self.export_sources_folder))
                save(self, "myfile.h", "//dummy contents")
                patch(self, base_path=self.source_folder,
                      patch_file=os.path.join(self.recipe_folder, "patches", "mypatch_h"),
                      patch_type="security")
                self.output.info("SOURCE: {}".format(load(self, "myfile.h")))
        """)

    client = TestClient()
    patch_contents = textwrap.dedent("""\
        --- myfile.{ext}
        +++ myfile.{ext}
        @@ -1 +1 @@
        -//dummy contents
        +//smart contents
        """)
    client.save({"conanfile.py": conanfile,
                 "patches/mypatch_h": patch_contents.format(ext="h")})
    # Test local source too
    client.run("install . -if=mytemp")
    client.run("source . -if=mytemp -sf=.")
    assert "conanfile.py (mypkg/1.0): Apply patch (security)" in client.out
    assert "conanfile.py (mypkg/1.0): SOURCE: //smart contents" in client.out
```
I'd say it captures your description, and if I do a print of the output of ``conan source`` I get:
```
Using cached profile from lockfile
conanfile.py (mypkg/1.0): Configuring sources in T:\tmpmr5g76ylconans\path with spaces
conanfile.py (mypkg/1.0): EXPORT FOLDER: T:\tmpmr5g76ylconans\path with spaces
conanfile.py (mypkg/1.0): Apply patch (security)
conanfile.py (mypkg/1.0): SOURCE: //smart contents
```
Not sure what could be the difference, maybe you can try the test conanfile.py locally to see what happens? Otherwise, maybe sharing your whole conanfile.py, to see if there is something else there that could be affecting.

**Comment by Bearwolves** [comment]
Hey @memsharded,

Thanks for the fast reply. By using your exactly your test, it works without problem :D. But by trying to change the source folder to anything else than "." as folder it fails. Is this a bug or a wanted behavior?

See
```bash
# works like a charm with a "." as source-folder
~/wp/conan-12748$ conan source . -if=mytemp -sf=.
Using lockfile: '/home/xxx6xxx/wp/conan-12748/mytemp/conan.lock'
Using cached profile from lockfile
conanfile.py (mypkg/1.0): Configuring sources in /home/xxx6xxx/wp/conan-12748
conanfile.py (mypkg/1.0): EXPORT FOLDER: /home/xxx6xxx/wp/conan-12748
conanfile.py (mypkg/1.0): Apply patch (security)
export_sources_folder [/home/xxx6xxx/wp/conan-12748]
patch_file [/home/xxx6xxx/wp/conan-12748/patches/mypatch_h]
recipe_folder [/home/xxx6xxx/wp/conan-12748]
conanfile.py (mypkg/1.0): /home/xxx6xxx/wp/conan-12748/patches/mypatch_h: source/target file does not exist:

# doesn't work for relative path as source-folder
~/wp/conan-12748$ conan source . -if=mytemp -sf=patches
Using lockfile: '/home/xxx6xxx/wp/conan-12748/mytemp/conan.lock'
Using cached profile from lockfile
conanfile.py (mypkg/1.0): Configuring sources in /home/xxx6xxx/wp/conan-12748/patches
conanfile.py (mypkg/1.0): Executing exports to: /home/xxx6xxx/wp/conan-12748/patches
conanfile.py (mypkg/1.0) exports_sources: Copied 1 '.py' file: conanfile.py
conanfile.py (mypkg/1.0) exports_sources: Copied 2 '.txt' files: conanbuildinfo.txt, conaninfo.txt
conanfile.py (mypkg/1.0) exports_sources: Copied 1 '.lock' file: conan.lock
conanfile.py (mypkg/1.0) exports_sources: Copied 1 '.json' file: graph_info.json
conanfile.py (mypkg/1.0): EXPORT FOLDER: None
conanfile.py (mypkg/1.0): Apply patch (security)
export_sources_folder [None]
patch_file [/home/xxx6xxx/wp/conan-12748/patches/mypatch_h]
recipe_folder [/home/xxx6xxx/wp/conan-12748]
ERROR: conanfile.py (mypkg/1.0): Error in source() method, line 17
        patch_type="security")
        TypeError: expected str, bytes or os.PathLike object, not NoneType

# neither for absolute path as source-folder
~/wp/conan-12748$ conan source . -if=mytemp -sf=$PWD/mytmp-src-abs
Using lockfile: '/home/xxx6xxx/wp/conan-12748/mytemp/conan.lock'
Using cached profile from lockfile
conanfile.py (mypkg/1.0): Configuring sources in /home/xxx6xxx/wp/conan-12748/mytmp-src-abs
conanfile.py (mypkg/1.0): Executing exports to: /home/xxx6xxx/wp/conan-12748/mytmp-src-abs
conanfile.py (mypkg/1.0) exports_sources: Copied 4 '.py' files: conanfile.py, conanfile.py, conanfile.py, conanfile.py
conanfile.py (mypkg/1.0) exports_sources: Copied 8 '.txt' files
conanfile.py (mypkg/1.0) exports_sources: Copied 4 '.lock' files: conan.lock, conan.lock, conan.lock, conan.lock
conanfile.py (mypkg/1.0) exports_sources: Copied 4 '.json' files: graph_info.json, graph_info.json, graph_info.json, graph_info.json
conanfile.py (mypkg/1.0) exports_sources: Copied 3 '.h' files: myfile.h, myfile.h, myfile.h
conanfile.py (mypkg/1.0) exports_sources: Copied 2 files: mypatch_h, mypatch_h
conanfile.py (mypkg/1.0): EXPORT FOLDER: None
conanfile.py (mypkg/1.0): Apply patch (security)
export_sources_folder [None]
patch_file [/home/xxx6xxx/wp/conan-12748/patches/mypatch_h]
recipe_folder [/home/xxx6xxx/wp/conan-12748]
ERROR: conanfile.py (mypkg/1.0): Error in source() method, line 17
        patch_type="security")
        TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Can you reproduce the issue on your side too with that?

**Comment by memsharded** [comment]
Yes, I think this is expected behavior.

The new ``patch()`` function (it is new, comes from ``from conan.tools.files`` new tools namespace), it is prepared to work with the ``layout()`` and the command line ``--source-folder, -sf`` argument has been dropped for this purpose (it has already been removed in Conan 2.0), and it will be mostly ignored, or make it fail, because things will not be where they are supposed to be.

For example, if you want the source to be in "mysrc" folder, you add to the above conanfile:
```python
def layout(self):
      self.folders.source = "mysrc"
```
And everything keeps working correctly exactly the same, but now inside a "mysrc" folder:
```
conanfile.py (mypkg/1.0): Configuring sources in T:\tmpej0ve2phconans\path with spaces\mysrc
conanfile.py (mypkg/1.0): Executing exports to: T:\tmpej0ve2phconans\path with spaces\mysrc
conanfile.py (mypkg/1.0): EXPORT FOLDER: T:\tmpej0ve2phconans\path with spaces
conanfile.py (mypkg/1.0): Apply patch (security)
conanfile.py (mypkg/1.0): SOURCE: //smart contents
```

**Comment by Bearwolves** [comment]
Oh sorry, I was not aware of that. In the conan 2.0, we can not configure our build, source folder and so on from the outside i.e. the command line or does it relates only to the source folder? Everything has to be done in the layout method?

**Comment by memsharded** [comment]
> Oh sorry, I was not aware of that. In the conan 2.0, we can not configure our build, source folder and so on from the outside i.e. the command line or does it relates only to the source folder? Everything has to be done in the layout method?

Most of it has to go to the ``layout()``, yes. Commands learnt a new ``--output-folder`` that allows to relocate the whole base folder for binaries (the build folder, including generators, etc)

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, which also dropped the `patch` method, thanks!
