### ISSUE TITLE
VirtualRunEnv generator adds win paths in environment_run.sh.env

### ISSUE THREAD

**Issue by ticollin** [conan-io/conan#12893]
I am running conan on windows in git-bash. When I run,

`conan install ... -g virtualrunenv`

then the `environment_run.sh.env` file is not usable/useful since the paths added are in windows form, e.g. the .env has a PATH adjustment like,

`PATH="E:\.conan\212321ca\1\some-lib-winx64\bin"${PATH:+:$PATH}`

but I expect that it should be like,

`PATH="/e/.conan/212321ca/1/some-lib-winx64/bin"${PATH:+:$PATH}`

**Comment by memsharded** [comment]
Hi @ticollin 

Thanks for your question.
Could you please try with the ``-g VirtualRunEnv`` generator instead? (There is also the ``-g VirtualBuildEnv``). Those are the environment management replacing the legacy one you are using. I think they should be writing the right paths given the conf is correct (check ``conan config list``, and it is necessary to activate ``tools.microsoft.bash:subsystem=msys2`` and ``tools.microsoft.bash:active=True``.)

**Comment by ticollin** [comment]
I can set `tools.microsoft.bash:subsystem=msys2`, then run those generators. Only .bat files are produced. When I also set `tools.microsoft.bash:active=True`, then `conan config list` throws:

```
$ conan config list
Traceback (most recent call last):
  File "C:\Users\ticollin\conan_venv\Scripts\conan-script.py", line 11, in <module>
    load_entry_point('conan==1.55.0', 'console_scripts', 'conan')()
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\conan.py", line 11, in run
    main(sys.argv[1:])
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\command.py", line 2373, in main
    conan_api, _, _ = Conan.factory()
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\conan_api.py", line 224, in factory
    return cls(), None, None
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\conan_api.py", line 238, in __init__
    check_required_conan_version(self.cache_folder, self.out)
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\conf\required_version.py", line 28, in check_required_conan_version
    cache = ClientCache(cache_folder, out)
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\cache\cache.py", line 83, in __init__
    self._store_folder = self.config.storage_path or os.path.join(self.cache_folder, "data")
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\cache\cache.py", line 156, in config
    self._config = ConanClientConfigParser(self.conan_conf_path)
  File "c:\users\ticollin\conan_venv\lib\site-packages\conans\client\conf\__init__.py", line 324, in __init__
    self.read(filename)
  File "E:\conan-setup\Installation\CPython\3_7\winx64\Release\python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "E:\conan-setup\Installation\CPython\3_7\winx64\Release\python\lib\configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'E:\\ANSYSDev\\downloads\\conan\\.conan\\conan.conf' [line 30]: option 'microsoft.bash' in section 'tools' already exists
(conan_venv)
```

conan is basically broken at this point. I remove the [tools] section from conan.conf to recover

**Comment by memsharded** [comment]
That configuration goes to ``global.conf``, not to ``conan.conf``. Please check: https://docs.conan.io/en/latest/reference/config_files/global_conf.html

**Comment by ticollin** [comment]
Thanks, I added both those settings to global.conf by hand. I can invoke the generator(s) and get the expected files and subsequent behaviour

**Comment by ticollin** [comment]
Hi @memsharded,
I seem to be in the same situation again.
I have a global.conf that looks like,
```
tools.microsoft.bash.subsystem=msys2
tools.microsoft.bash.active=True
```
![image](https://github.com/conan-io/conan/assets/114675093/9cdedfdc-83ed-47f5-ad99-8ad0c7710ddd)

but VirtualRunEnv and VirtualBuildEnv are giving me .bat files.
What do you suggest?
 
 
 edit:
 Oh!
 the configs should have `:` instead of the last `.`

**Comment by memsharded** [comment]
Which compiler, which generator, which build system are you using?
It is possible that some configuration like VS cl.exe compiler + Ninja will require to activate ``vcvars.bat`` and that is a batch script that needs to be activated in a regular cmd prompt, cannot be done in msys2.

Can you please provide the details? Thanks!

**Comment by ticollin** [comment]
Hi there,
sorry if I was not clear with my edit - after fixing the global conf entries (with ':') the .sh files were then generated.
