### ISSUE TITLE
[question] MSBuild Helper looking in wrong folder for buildtools

### ISSUE THREAD

**Issue by ckearney-nitro** [conan-io/conan#12964]
I am trying to create a conan package using Visual Studio Build Tools 2022. My conan file is using the MSBuild helper.

I get the following output:
```
2023-01-24T12:03:16.5246613Z The system cannot find the path specified.
2023-01-24T12:03:16.5293803Z lcms/2.14@nitro/docker: 
2023-01-24T12:03:16.5298991Z lcms/2.14@nitro/docker: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
2023-01-24T12:03:16.5300580Z lcms/2.14@nitro/docker: WARN: Build folder C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
2023-01-24T12:03:16.5311122Z ERROR: lcms/2.14@nitro/docker: Error in build() method, line 129
2023-01-24T12:03:16.5311423Z 	self._build_visual_studio()
2023-01-24T12:03:16.5311837Z while calling '_build_visual_studio', line 109
2023-01-24T12:03:16.5312213Z 	msbuild.build("lcms2.sln", targets=[target], platforms={"x86": "Win32"},
2023-01-24T12:03:16.5313283Z 	ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC/Auxiliary/Build/vcvarsall.bat" amd64 && msbuild "lcms2.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="x64" /m:16 /target:lcms2_static /p:PlatformToolset="v143" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\source_subfolder\Projects\VC2022\conan_build.props" /p:WholeProgramOptimization="false"
```
I don't think there is any x86 build tools for 2022 anymore:
https://devblogs.microsoft.com/dotnet/msbuild-and-64-bit-visual-studio-2022/

So, it seems that the MSBuild helper is looking in the wrong folder for the build tools?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ckearney-nitro 

Thanks very much for your report.
It seems you are still using the legacy MSBuild integration, instead of the new one ``from conan.tools.microsoft import MSBuild`` (that goes together with ``MSBuildDeps`` and ``MSBuildToolchain``). Please have a look to https://docs.conan.io/en/latest/reference/conanfile/tools.html.

As that legacy integration has already been removed in 2.0, which is in beta.9 already and due next month, it would be great if you could please check the new ``MSBuild`` one, and report against it if necessary. Thanks!

**Comment by ckearney-nitro** [comment]
Hello @memsharded 

That did fix the issue in the description, however it failed a later point:
`2023-01-24T14:09:44.7748231Z C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\source_subfolder\Projects\VC2022\lcms2_static\lcms2_static.vcxproj(35,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.`

Looking at the project file I am trying to build:
https://github.com/mm2/Little-CMS/blob/e71aeb6d8ad21ad5aea2240b531acf13853c8cd9/Projects/VC2022/lcms2_static/lcms2_static.vcxproj#L69

It seems that the `VCTargetsPath` isn't being set correctly by the new MSBuild I am using

**Comment by memsharded** [comment]
Do you have something that we could reproduce, like the full ``conanfile.py`` that you are using?
Are you using the new ``MSBuildToolchain`` and ``MSBuildDeps``?

Maybe the new ``conan new hello/0.1 -m=msbuild_lib`` or ``conan new hello/0.1 -m=msbuild_exe`` templates, that are fully functional working examples using all MSBuild, MSBuildDeps and MSBuildToolchain could be useful to test things and report.

**Comment by ckearney-nitro** [comment]
I didn't think I needed the MSBuildToolChain part, as the project I am trying to build already exists. 
https://github.com/mm2/Little-CMS/blob/e71aeb6d8ad21ad5aea2240b531acf13853c8cd9/Projects/VC2022/lcms2_static/lcms2_static.vcxproj

I added MSBuildToolChain:
```
def generate(self):
    tc = MSBuildToolchain(self)
    tc.generate()
```

I get a different error :
```
PS C:\repos\ext_lcms> conan install . -s compiler='Visual Studio' -s compiler.version=17 -s compiler.toolset=v143
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.toolset=v143
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.py (lcms/2.14): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (lcms/2.14): Generator txt created conanbuildinfo.txt
conanfile.py (lcms/2.14): ERROR: Traceback (most recent call last):
  File "C:\Users\ckearney\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\generators\__init__.py", line 183, in write_generators
    generator = generator_class(conanfile)
  File "C:\Users\ckearney\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\tools\microsoft\toolchain.py", line 54, in __init__
    self.runtime_library = self._runtime_library(conanfile.settings)
  File "C:\Users\ckearney\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\tools\microsoft\toolchain.py", line 119, in _runtime_library
    if compiler == "msvc" or compiler == "intel-cc":
  File "C:\Users\ckearney\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\settings.py", line 99, in __eq__
    raise ConanException(bad_value_msg(self._name, other, self.values_range))
conans.errors.ConanException: Invalid setting 'intel-cc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'intel', 'mcst-lcc', 'msvc', 'qcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```
Using conan version 1.55

**Comment by memsharded** [comment]
> I didn't think I needed the MSBuildToolChain part, as the project I am trying to build already exists.

MSBuildToolchain is the mechanism to automatically inject the variability into the build system. You can build the package for many different configuration/profiles, like different toolsets, different runtimes (MT, MD, MTd, MDd), different cppstd, etc. Conan will do ``conan create . -s compiler.runtime=dynamic -s compiler.cppstd=17``, but it needs a mechanism to pass that to the build system. That mechanism is the toolchain:

- MSBuildToolchain will create a ``conan_toolchain.props`` file
- That file should be included in the project ``vcxproj``
   - For your own projects, you can add it in the xml and done
   - For third parties, typically a patch or a replace would do it


> conans.errors.ConanException: Invalid setting 'intel-cc' is not a valid 'settings.compiler' value.

The error you are seeing could be because your cache settings is outdated. I'd suggest go to your ``<userhome>/.conan`` folder and remove the ``settings.yml`` file, it will be regenerated with an updated one next time it is necessary.

**Comment by ckearney-nitro** [comment]
Yea removing the settings.yml fixed the 'intel-cc' issue. Thanks

I trying appended the conan_toolchain.props into my target .vcxprog file. 
`<Import Project="C:\Users\ckearney\.conan\data\lcms\2.14\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\conantoolchain.props" />`

Still not able to build and the error is not very descriptive.
```

2023-01-25T14:57:41.1778776Z Configuration:
2023-01-25T14:57:41.1779009Z [settings]
2023-01-25T14:57:41.1779273Z arch=x86_64
2023-01-25T14:57:41.1779467Z arch_build=x86_64
2023-01-25T14:57:41.1779668Z build_type=Release
2023-01-25T14:57:41.1780029Z compiler=Visual Studio
2023-01-25T14:57:41.1780255Z compiler.runtime=MD
2023-01-25T14:57:41.1780478Z compiler.toolset=v143
2023-01-25T14:57:41.1780695Z compiler.version=17
2023-01-25T14:57:41.1780891Z os=Windows
2023-01-25T14:57:41.1781076Z os_build=Windows
2023-01-25T14:57:41.1781266Z [options]
2023-01-25T14:57:41.1781450Z [build_requires]
2023-01-25T14:57:41.1783962Z [env]
2023-01-25T14:57:41.1784082Z 
2023-01-25T14:57:41.1833840Z lcms/2.14@nitro/docker: Forced build from source
2023-01-25T14:57:41.1840740Z Installing package: lcms/2.14@nitro/docker
2023-01-25T14:57:41.1841022Z Requirements
2023-01-25T14:57:41.1841414Z     lcms/2.14@nitro/docker from local cache - Cache
2023-01-25T14:57:41.1841663Z Packages
2023-01-25T14:57:41.1842037Z     lcms/2.14@nitro/docker:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Build
2023-01-25T14:57:41.1842234Z 
2023-01-25T14:57:41.1842668Z Installing (downloading, building) binaries...
2023-01-25T14:57:41.1887428Z lcms/2.14@nitro/docker: Configuring sources in C:\conan\.conan\data\lcms\2.14\nitro\docker\source
2023-01-25T14:57:41.4845537Z 
2023-01-25T14:57:41.8370424Z lcms/2.14@nitro/docker: Copying sources to build folder
2023-01-25T14:57:43.2521137Z lcms/2.14@nitro/docker: Building your package in C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
2023-01-25T14:57:43.2522063Z lcms/2.14@nitro/docker: Generator 'MSBuildToolchain' calling 'generate()'
2023-01-25T14:57:43.2522745Z lcms/2.14@nitro/docker: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
2023-01-25T14:57:43.2557189Z lcms/2.14@nitro/docker: MSBuildToolchain created conantoolchain_release_x64.props
2023-01-25T14:57:43.2677800Z lcms/2.14@nitro/docker: MSBuildToolchain writing conantoolchain.props
2023-01-25T14:57:43.3548537Z lcms/2.14@nitro/docker: Calling generate()
2023-01-25T14:57:43.3549959Z lcms/2.14@nitro/docker: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
2023-01-25T14:57:43.3579177Z lcms/2.14@nitro/docker: MSBuildToolchain created conantoolchain_release_x64.props
2023-01-25T14:57:43.3622135Z lcms/2.14@nitro/docker: MSBuildToolchain writing conantoolchain.props
2023-01-25T14:57:43.4482695Z lcms/2.14@nitro/docker: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
2023-01-25T14:57:43.4485383Z lcms/2.14@nitro/docker: Aggregating env generators
2023-01-25T14:57:43.4497626Z lcms/2.14@nitro/docker: Calling build()
2023-01-25T14:57:43.4985547Z The system cannot find the path specified.
2023-01-25T14:57:43.5027140Z lcms/2.14@nitro/docker: ERROR: Package '5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b' build failed
2023-01-25T14:57:43.5027734Z lcms/2.14@nitro/docker: WARN: Build folder C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
2023-01-25T14:57:43.5028094Z Sln Exists:True
2023-01-25T14:57:43.5028407Z lcms2_static\lcms2_static.vcxproj Exists:True
2023-01-25T14:57:43.5028865Z C:\conan\.conan\data\lcms\2.14\nitro\docker\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\conantoolchain.props
2023-01-25T14:57:43.5029212Z lcms/2.14@nitro/docker: 
2023-01-25T14:57:43.5045387Z ERROR: lcms/2.14@nitro/docker: Error in build() method, line 159
2023-01-25T14:57:43.5045675Z 	self._build_visual_studio()
2023-01-25T14:57:43.5046108Z while calling '_build_visual_studio', line 130
2023-01-25T14:57:43.5046407Z 	msbuild.build("lcms2.sln", targets=[target])
2023-01-25T14:57:43.5046897Z 	ConanException: Error 1 while executing msbuild "lcms2.sln" /p:Configuration=Release /p:Platform=x64 /verbosity:Diagnostic /target:lcms2_static
2023-01-25T14:57:43.5498322Z Traceback (most recent call last):
```

**Comment by memsharded** [comment]
> 2023-01-25T14:57:43.4985547Z The system cannot find the path specified.

Something is failing while trying to locate some file. It could be the vcvars file? 

Definitely adding the ``conantoolchain.props`` with the absolute path is not ok, that will break in any other machine or configuration. The relative path from the .vcxproj to the generated ``conantoolchain.props`` should be added there.
