### ISSUE TITLE
Error using option value with an equal sign (=)

### ISSUE THREAD

**Issue by absassi** [conan-io/conan#1296]
Hi, I believe this is self-explanatory, but here follows the instructions to reproduce:

Package's conanfile.py:
```
from conans import ConanFile
class EqualerrorConan(ConanFile):
    name = "equal"
    version = "1.0.0"
    options = {"opt": "ANY"}
```

Consumer's conanfile.txt:
```
[requires]
equal/1.0.0@user/testing
[options]
equal:opt=a=b
```

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 9, in <module>
    load_entry_point('conan==0.22.3', 'console_scripts', 'conan')()
  File "/usr/local/lib/python3.5/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1047, in main
    error = command.run(args)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 862, in run
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 840, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 310, in install
    no_imports=args.no_imports)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/manager.py", line 258, in install
    conanfile = self._get_conanfile_object(loader, reference, filename, current_path)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/manager.py", line 147, in _get_conanfile_object
    conanfile = loader.load_conan_txt(conan_path, output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/loader.py", line 109, in load_conan_txt
    conanfile = self._parse_conan_txt(contents, path, output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/loader.py", line 129, in _parse_conan_txt
    options = OptionsValues.loads(parser.options)
  File "/usr/local/lib/python3.5/dist-packages/conans/model/options.py", line 242, in loads
    name, value = line.split("=")
ValueError: too many values to unpack (expected 2)
```

**Comment by memsharded** [comment]
Confirmed, thanks very much for the detailed and reproducible example. Just submitted a PR so it is included in next 0.23.
