### ISSUE TITLE
[bug] conan v2: Error message around mixing attributes and methods are very confusing

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#12961]
Instead of 

```py
def build_requirements(self):
```

I wrote 

```py
def build_requires(self): # This is the attribute
```

Lets to ... which was not fun to debug :)

```
Exporting the recipe
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/cli.py", line 170, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/command.py", line 130, in run
    info = self._method(conan_api, parser, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/cli/commands/create.py", line 52, in create
    ref, conanfile = conan_api.export.export(path=path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/subapi/__init__.py", line 21, in wrapper
    return f(subapi, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conan/api/subapi/export.py", line 19, in export
    return cmd_export(app, path, name, version, user, channel, graph_lock=lockfile,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/client/cmd/export.py", line 21, in cmd_export
    conanfile = loader.load_export(conanfile_path, name, version, user, channel, graph_lock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/client/loader.py", line 144, in load_export
    conanfile = self.load_named(conanfile_path, name, version, user, channel, graph_lock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/client/loader.py", line 98, in load_named
    conanfile, _ = self.load_basic_module(conanfile_path, graph_lock, remotes=remotes,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/client/loader.py", line 71, in load_basic_module
    result = conanfile(display)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/model/conan_file.py", line 242, in __init__
    self.requires = Requirements(getattr(self, "requires", None),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/conans/model/requires.py", line 432, in __init__
    for item in declared_build:
TypeError: 'method' object is not iterable

ERROR: 'method' object is not iterable
```

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12962
