### ISSUE TITLE
[bug] Conan fails to install package when using apple-clang 13

### ISSUE THREAD

**Issue by zouhairm** [conan-io/conan#12978]
### Environment details

* Operating System+version:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/430175/214677504-b001f116-0939-45e5-89db-dceb0c6db4cd.png">* 
* Compiler+version:
```
$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
* Conan version:
```
$ conan --version
Conan version 1.57.0
```
* Python version:
```
$ python3 --version
Python 3.10.8
```

### Steps to reproduce

1. have a mypkg with a recipe with `def compatibility(): ` defined as follows:
```
    def compatibility(self):
        """
        Determine which packages are compatible.

        We assume all compilers with the same or older version as compatible,
        with more recent versions being prefered
        """
        ver_consumer = Version(str(self.settings.compiler.version))

        # Get the versions declared in the settings.yml for this compiler type
        # Note reversed order when sorting so that more recent versions are preferred

        default_settings = Settings.loads(get_default_settings_yml())
        default_settings.compiler = self.settings.compiler
        known_compiler_versions = sorted(
            default_settings.compiler.version.values_range,
            key=lambda x: Version(x),
            reverse=True)

        return [
            {"settings": [("compiler.version", v)]}
            for v in known_compiler_versions if v <= ver_consumer]
```

2. run `conan install mypkg -s compiler.version=13` produces error

Running with `conan install mypkg -s compiler.version=13.0` does not produce the error.
Running with  `-s compiler.version=14` also do not have issues

Seems to be related to https://github.com/conan-io/conan/issues/11227 ?

### Logs

`conan install mypkg -s compiler.version=13`
Error log:
```
Traceback (most recent call last):
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/command.py", line 547, in install
    info = self._conan.install_reference(ref,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/conan_api.py", line 558, in install_reference
    deps_install(self.app, ref_or_path=reference, install_folder=install_folder,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/manager.py", line 58, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_manager.py", line 128, in load_graph
    deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_manager.py", line 290, in _resolve_graph
    deps_graph = self._load_graph(root_node, check_updates, update,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_manager.py", line 411, in _load_graph
    self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_manager.py", line 337, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_binaries.py", line 459, in evaluate_graph
    self._evaluate_node(node, build_mode, update, remotes)
  File "/private/tmp/.test_env/lib/python3.10/site-packages/conans/client/graph/graph_binaries.py", line 227, in _evaluate_node
    assert node.binary is not None
AssertionError
```

**Comment by memsharded** [comment]
Hi @zouhairm 

Thanks for your report.
I'd say this could be due to an internal compatibility built-in fallback between ``13`` and ``13.0``:
```python
    def apple_clang_compatible(self):
        # https://github.com/conan-io/conan/pull/10797
        # apple-clang compiler version 13 will be compatible with 13.0
        if not self.settings.compiler or \
           (self.settings.compiler != "apple-clang" or self.settings.compiler.version != "13"):
            return

        compatible = self.clone()
        compatible.settings.compiler.version = "13.0"
        return compatible
```
I'd try to skip the fallback in the ``compatibility()`` method if the version is ``13``, if you intend to use minor versions.

**Comment by zouhairm** [comment]
Thanks for the quick reply.
Can you please elaborate by what you mean by "skip the fallback in the compatibility() method if the version is 13" ?

Would we just do that by somehow over-ridding `def apple_clang_compatible(self)` in our package recipe?

**Comment by memsharded** [comment]
We have that internal built-in compatibility to workaround a model change in the apple-clang version setting. At the moment, if the ``compiler.version=13`` then, it will try to use a binary compiled with ``13.0`` too.

So if you check in your ``compatibility()`` method that ``compiler.version`` didn't specify a ``.minor`` version to not fallback to any other version (unless you want to fallback to 12, 11, etc), that would solve the issue. Are you trying to fallback minors like 13.2 to 13.1 and 13.0, or are you trying to fallback majors too, like falling back to 12, 11, 10, etc? (I think the later might be too much)

**Comment by zouhairm** [comment]
I think we're doing the latter (that was the idea at least), but in practice I don't think we run into that case as we don't have binaries.
I think I understand what you're suggesting, we'll try to implement a workaround in our recipes.

Thanks again

**Comment by memsharded** [comment]
> I think we're doing the latter (that was the idea at least), but in practice I don't think we run into that case as we don't have binaries.

Even if you don't have binaries, the fallback will try to look for them, and I think it is the repeated/overlapping compatibility that is causing the issue.

Also, it would be great if you can keep an eye or even better, testing the Conan 2.0 beta, because it contains a ``compatibility.py`` plugin, that you can put in your cache, install it with ``conan config install`` and it will apply to all recipes, no need to have the ``compatibility()`` method in recipes.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, the new compatibility method does not face this issue
