### ISSUE TITLE
[bug] fix_apple_shared_install_name fails for universal dylib binaries

### ISSUE THREAD

**Issue by hedtke** [conan-io/conan#13014]
### Environment details

* Operating System+version: 13.1
* Compiler+version: apple-clang 14
* Conan version: 1.58
* Python version: 3.7.12

### Steps to reproduce

1. clone https://github.com/dbschenker/conan-gurobi
2. run `conan create conan-gurobi/gurobi/all/conanfile.py 10.0.0@`

### Logs

```
$ conan create conan-gurobi/gurobi/all/conanfile.py 10.0.0@

ERROR: gurobi/10.0.0: Error in package_info() method, line 79
    fix_apple_shared_install_name(self)  # pre-built C lib contains an absolute path
    ConanException: Error 2 while executing install_name_tool /Users/lwienkam/.conan/data/gurobi/10.0.0/_/_/package/daebbf7064402b094badcd78dbe07eac9f97be77/lib/libgurobi100.dylib -id @rpath/libgurobi100.dylib (architecture arm64)
```

it looks like the stuff in brackets `(architecture arm64)` is added to the command but it should not, and thus `install_name_tool` fails

**Comment by uilianries** [comment]
I can reproduce the very error when running from Mac M1 machine, with Apple Clang 14 and Conan 1.58.0:

```
% conan create gurobi/all/conanfile.py 10.0.0@
Exporting package recipe
gurobi/10.0.0 exports: File 'conandata.yml' found. Exporting it...
gurobi/10.0.0 exports: Copied 1 '.yml' file: conandata.yml
gurobi/10.0.0: Calling export_sources()
gurobi/10.0.0 export_sources() method: Copied 1 '.txt' file: CMakeLists.txt
gurobi/10.0.0: A new conanfile.py version was exported
gurobi/10.0.0: Folder: /Users/uilian/.conan/data/gurobi/10.0.0/_/_/export
gurobi/10.0.0: Using the exported files summary hash as the recipe revision: 3411e4d92a91222a9291a13788f03bb6 
gurobi/10.0.0: Source folder is corrupted, forcing removal
gurobi/10.0.0: Exported revision: 3411e4d92a91222a9291a13788f03bb6
Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=14
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tools.system.package_manager:mode=install

gurobi/10.0.0: Forced build from source
gurobi/10.0.0 (test package): Installing package
Requirements
    gurobi/10.0.0 from local cache - Cache
Packages
    gurobi/10.0.0:53814b1c975d3e5fe52565e7c19f8897ffdde452 - Build

Installing (downloading, building) binaries...
gurobi/10.0.0: WARN: Build folder is dirty, removing it: /Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
gurobi/10.0.0: Configuring sources in /Users/uilian/.conan/data/gurobi/10.0.0/_/_/source
Downloading grb completed [92572.26k]                                                    gurobi/10.0.0: 10.0.0: 
gurobi/10.0.0: 

----Running------
> pkgutil --expand-full grb buildfolder
-----------------
gurobi/10.0.0: Copied 19 '.h' files
gurobi/10.0.0: Copied 15 '.cpp' files
gurobi/10.0.0: Copied 1 '.dylib' file: libgurobi100.dylib
gurobi/10.0.0: Copied 2 '.h' files: gurobi_c.h, gurobi_c++.h
gurobi/10.0.0: Copying sources to build folder
gurobi/10.0.0: Building your package in /Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452
gurobi/10.0.0: Generator txt created conanbuildinfo.txt
gurobi/10.0.0: Calling generate()
gurobi/10.0.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
gurobi/10.0.0: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
gurobi/10.0.0: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
gurobi/10.0.0: Aggregating env generators
gurobi/10.0.0: Calling build()
gurobi/10.0.0: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452"

----Running------
> cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452"
-----------------
-- Using Conan toolchain: /Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = ON
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: /Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452
gurobi/10.0.0: CMake command: cmake --build "/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452" '--' '-j10'

----Running------
> cmake --build "/Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452" '--' '-j10'
-----------------
[  6%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Batch.cpp.o
[ 12%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Env.cpp.o
[ 18%] Building CXX object CMakeFiles/gurobi_c++.dir/src/GenConstr.cpp.o
[ 25%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Constr.cpp.o
[ 31%] Building CXX object CMakeFiles/gurobi_c++.dir/src/LinExpr.cpp.o
[ 37%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Column.cpp.o
[ 43%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Model.cpp.o
[ 50%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Exception.cpp.o
[ 56%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Callback.cpp.o
[ 62%] Building CXX object CMakeFiles/gurobi_c++.dir/src/QConstr.cpp.o
[ 68%] Building CXX object CMakeFiles/gurobi_c++.dir/src/QuadExpr.cpp.o
[ 75%] Building CXX object CMakeFiles/gurobi_c++.dir/src/SOS.cpp.o
[ 81%] Building CXX object CMakeFiles/gurobi_c++.dir/src/TempConstr.cpp.o
[ 87%] Building CXX object CMakeFiles/gurobi_c++.dir/src/Var.cpp.o
[ 93%] Building CXX object CMakeFiles/gurobi_c++.dir/src/attrprivate.cpp.o
[100%] Linking CXX static library libgurobi_c++.a
[100%] Built target gurobi_c++
gurobi/10.0.0: Package '53814b1c975d3e5fe52565e7c19f8897ffdde452' built
gurobi/10.0.0: Build folder /Users/uilian/.conan/data/gurobi/10.0.0/_/_/build/53814b1c975d3e5fe52565e7c19f8897ffdde452
gurobi/10.0.0: Generated conaninfo.txt
gurobi/10.0.0: Generated conanbuildinfo.txt
gurobi/10.0.0: Generating the package
gurobi/10.0.0: Package folder /Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452
gurobi/10.0.0: Calling package()

gurobi/10.0.0 package(): Packaged 2 '.h' files: gurobi_c.h, gurobi_c++.h
gurobi/10.0.0 package(): Packaged 1 '.a' file: libgurobi_c++.a
gurobi/10.0.0 package(): Packaged 1 '.dylib' file: libgurobi100.dylib
gurobi/10.0.0: Package '53814b1c975d3e5fe52565e7c19f8897ffdde452' created
gurobi/10.0.0: Created package revision 2df5aade1131969d05cf844cc0740eac

----Running------
> install_name_tool /Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib -id @rpath/libgurobi100.dylib (architecture arm64)
-----------------
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `install_name_tool /Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib -id @rpath/libgurobi100.dylib (architecture arm64)'
ERROR: Traceback (most recent call last):
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/client/installer.py", line 703, in _call_package_info
    conanfile.package_info()
  File "/Users/uilian/.conan/data/gurobi/10.0.0/_/_/export/conanfile.py", line 79, in package_info
    fix_apple_shared_install_name(self)  # pre-built C lib contains an absolute path
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conan/tools/apple/apple.py", line 262, in fix_apple_shared_install_name
    substitutions = _fix_dylib_files(conanfile)
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conan/tools/apple/apple.py", line 219, in _fix_dylib_files
    _fix_install_name(shared_lib, rpath_name)
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conan/tools/apple/apple.py", line 181, in _fix_install_name
    conanfile.run(command)
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/model/conan_file.py", line 464, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 2 while executing install_name_tool /Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib -id @rpath/libgurobi100.dylib (architecture arm64)
```

Some important information, those pre-built libraries installed and linked, they have mac universal2 support, which is not a regular case using that feature:

```
% otool -D /Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib 
/Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib (architecture x86_64):
/Library/gurobi1000/macos_universal2/lib/libgurobi100.dylib
/Users/uilian/.conan/data/gurobi/10.0.0/_/_/package/53814b1c975d3e5fe52565e7c19f8897ffdde452/lib/libgurobi100.dylib (architecture arm64):
```

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/13034, for next 1.59 release.

However, please be aware that the recommendation for Conan packages is that every package binary (for every profile/configuration) contains its own binaries. Having universal binaries inside Conan packages for multiple architectures is not the general recommendation. 

It is likely that for custom use cases of users using Conan for some multi-arch/fat binaries inside Conan packages, that ``fix_apple_shared_install_name()`` is not the right approach, and the recipe should handle the special case itself.

Thanks!
