### ISSUE TITLE
[bug] download_cache requires checksum for "conanmanifest.txt"

### ISSUE THREAD

**Issue by chulup** [conan-io/conan#13078]
### Environment details

* Operating System+version: macOS 12.6
* Compiler+version: apple-clang 12
* Conan version: 1.58.0
* Python version: 3.10.6

### Steps to reproduce

1. Run `conan install .. --install-folder . --profile=macos-clang12-debug --build='WebRTC'` without download_cache enabled, it runs and builds the source correctly.
2. Set storage.download_cache=/Users/me/workspace/conan-cache
3. Run the same command again, it fails with `ERROR: if download_cache is set, we need the file checksums.`
4. I looked that line in my conan instance and changed it to log filename too and got the following error: `AssertionError: if download_cache is set, we need the file checksums: conanmanifest.txt`

I thought download_cache applies to files with checksums only? Also, isn't conanmanifest some internal file that should not concern me as the package developer?

### Logs

Stacktrace:
```
ERROR :remote_manager.py[301]: Traceback (most recent call last):
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/remote_manager.py", line 290, in _call_remote
                                   return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/auth_manager.py", line 40, in call_rest_api_method
                                   ret = getattr(rest_client, method_name)(*args, **kwargs)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client.py", line 86, in get_recipe
                                   return self._get_api().get_recipe(ref, dest_folder)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client_v1.py", line 215, in get_recipe
                                   zipped_files = self._download_files_to_folder(urls, dest_folder, md5s)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client_v1.py", line 202, in _download_files_to_folder
                                   assert not download_cache or snapshot_md5, \
                               AssertionError: if download_cache is set, we need the file checksums: conanmanifest.txt
                                [2023-02-08 17:20:11,673]
```

**Comment by memsharded** [comment]
Hi @chulup 

Quick question, just to make sure: do you have revisions enabled? Enabling revisions is strongly recommended at this moment, they have been there for years, and Conan 2.0 always use revisions.

**Comment by chulup** [comment]
I have the following conan.conf file:

```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = warning            # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
revisions_enabled = 1
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 10                  # environment CONAN_REQUEST_TIMEOUT (seconds)
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE

[storage]
path = ./data
download_cache=/Users/me/workspace/conan-cache

[proxies]

[hooks]
attribute_checker
```

**Comment by memsharded** [comment]
Please try activating the revisions: ``conan config set general.revisions_enabled=True``. 
Better clean before it:
- Remove everything in the cache and in the download cache
- Activate revisions
- Retry

**Comment by chulup** [comment]
I did all that (line in conan.conf changed to `revisions_enabled = True`) and now it breaks with the same message on the very first package it tries to download:

```
conan install .. --install-folder . --profile:build=default --profile:host=macos-10.13-clang13-debug --build='WebRTC'
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os.version=10.13
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
[options]
[build_requires]
[env]

function2/4.2.0: Not found in local cache, looking in remotes...
function2/4.2.0: Trying with 'nexus-hosted-custom'...
function2/4.2.0: Trying with 'nexus-hosted'...
function2/4.2.0: Trying with 'nexus-conancenter'...
ERROR :remote_manager.py[301]: Traceback (most recent call last):
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/remote_manager.py", line 290, in _call_remote
                                   return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/auth_manager.py", line 40, in call_rest_api_method
                                   ret = getattr(rest_client, method_name)(*args, **kwargs)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client.py", line 86, in get_recipe
                                   return self._get_api().get_recipe(ref, dest_folder)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client_v1.py", line 215, in get_recipe
                                   zipped_files = self._download_files_to_folder(urls, dest_folder, md5s)
                                 File "/usr/local/lib/python3.10/site-packages/conans/client/rest/rest_client_v1.py", line 202, in _download_files_to_folder
                                   assert not download_cache or snapshot_md5, \
                               AssertionError: if download_cache is set, we need the file checksums: conanmanifest.txt
                                [2023-02-08 18:15:12,813]
ERROR: Failed requirement 'function2/4.2.0' from 'conanfile.py (my_branch)'
ERROR: if download_cache is set, we need the file checksums: conanmanifest.txt. [Remote: nexus-conancenter]
```

**Comment by memsharded** [comment]
Oh, I see, it seems you are using ``nexus`` server. Up to my knowledge, this server didn't implement revisions yet properly, so it might have issue. You might want to file an issue to their tracker.

Please try with a conan_server or an ArtifactoryCE (it is free, you can get it from https://conan.io/downloads.html), and let us know.

**Comment by chulup** [comment]
We are already planning to move to Artifactory, but who knows how long it would take?

Does that mean download_cache will not work without revisions? You may want to note that in documentation, if so.

**Comment by memsharded** [comment]
No, I think it works in both with and without revisions, just that every client should be using revisions as soon as possible, to be ready for 2.0, as it will take time, and revisions is a feature that has been there for years. It seems that the nexus API is not returning properly the file checksums in the response, so the caching fails, that was the probably reason for the failure in either case (with or without revisions)

**Comment by chulup** [comment]
Thank you so much!
It is unfortunate, of course. I will try pushing the use of Artifactory instead of Nexus.
