### ISSUE TITLE
[bug] Failed assert, when building qt package for 2.0

### ISSUE THREAD

**Issue by rainman110** [conan-io/conan#13256]
### Environment details

* Operating System+version: windows
* Compiler+version: msvc 2019
* Conan version: 2.0.0
* Python version: 3.9

### Steps to reproduce

1. Download the qt recipe from: https://github.com/rainman110/conan-qt5
    This is a minimally modified copy from conan-center-index.
2. Build the recipe via 
      conan create 5.x.x --version 5.15.8

It fails by the assertion
```
  File "c:\local\miniforge3\lib\site-packages\conans\model\options.py", line 341, in copy_conaninfo_options
    assert not self._deps_package_options
AssertionError
```

### Logs

```
(base) C:\src\qt-conan>conan create 5.x.x --version 5.15.8

======== Exporting recipe to the cache ========
qt/5.15.8: Exporting package recipe: C:\src\qt-conan\5.x.x\conanfile.py
qt/5.15.8: exports: File 'conandata.yml' found. Exporting it...
qt/5.15.8: Calling export()
qt/5.15.8: Calling export_sources()
qt/5.15.8: Copied 1 '.yml' file: conandata.yml
qt/5.15.8: Copied 1 '.py' file: conanfile.py
qt/5.15.8: Copied 1 '.conf' file: qtmodules5.15.8.conf
qt/5.15.8: Copied 4 '.patch' files: 0001-Find-fontconfig-using-pkg-config.patch, 337f28c9ab-5.15.8.patch, chromium-skia-missing-iterator-include.patch, chromium-v8-missing-constexpr.patch
qt/5.15.8: Copied 4 '.diff' files: aa2a39dea5.diff, c72097e.diff, fix-macdeployqt.diff, skia-cd397f3.diff
qt/5.15.8: Exported to cache folder: C:\Users\sigg_ma\.conan2\p\qtc9b5b710367d1\e
qt/5.15.8: Exported: qt/5.15.8#bdf4ee6c022d1d9e182a8a547c27675e (2023-02-27 12:05:34 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    brotli/1.0.9#ffbecf553112bc3e25a08c91c28b8b68 - Cache
    bzip2/1.0.8#23cc41191fd58460207c5db046033507 - Cache
    double-conversion/3.2.1#0e6c00f6a48471b4b13163f01bd6bbb2 - Cache
    freetype/2.12.1#98d8601ae19d2aa9d640ea0ba358534f - Cache
    libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187 - Cache
    libpng/1.6.39#deca555b0890e584fc895ba756e83c06 - Cache
    libpq/14.5#76d5e0452fcfa19f8f7ed250bcd7a525 - Cache
    md4c/0.4.8#6724c3bee6da8d4d9a17d16d35756e9a - Cache
    opengl/system#7c9316636990f3f64a7a6f6b24e0718f - Cache
    openssl/1.1.1t#1e58dd56a2a930f23160558c572a62fd - Cache
    pcre2/10.40#58467e19b38a61f5c3f065006fb684f6 - Cache
    qt/5.15.8#bdf4ee6c022d1d9e182a8a547c27675e - Cache
    sqlite3/3.39.4#d69fe4efe5e21fb8a1ce472e5d09cf5e - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
    zstd/1.5.4#8000dcd4e4cbcbdb8114fb684a6801a9 - Cache
Build requirements
    cmake/3.25.2#1e43a83edba41c63a6d14e02baf20134 - Cache
    jom/1.1.3#e50a5f5e4115f259eb6d1f87d10af85f - Cache
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache

======== Computing necessary packages ========
cmake/3.25.2: Compatible package ID 581183ca2ec1945c2d8e6bd2fb4795f24f993e62 equal to the default package ID
double-conversion/3.2.1: Checking 2 compatible configurations:
double-conversion/3.2.1: 'dfa8c31b225ffb8dfcf6a48ffd071f448777ae71': compiler.cppstd=17
double-conversion/3.2.1: '88783055ab9f2e8198b56fdcaf04496aaa3d4a9b': compiler.cppstd=20
jom/1.1.3: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
strawberryperl/5.32.1.1: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
strawberryperl/5.32.1.1: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
strawberryperl/5.32.1.1: Compatible package ID 522dcea5982a3f8a5b624c16477e47195da2f84f equal to the default package ID
Traceback (most recent call last):
  File "c:\local\miniforge3\lib\site-packages\conan\cli\cli.py", line 264, in main
    cli.run(args)
  File "c:\local\miniforge3\lib\site-packages\conan\cli\cli.py", line 167, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "c:\local\miniforge3\lib\site-packages\conan\cli\command.py", line 130, in run
    info = self._method(conan_api, parser, *args)
  File "c:\local\miniforge3\lib\site-packages\conan\cli\commands\create.py", line 77, in create
    conan_api.graph.analyze_binaries(deps_graph, build_modes, remotes=remotes,
  File "c:\local\miniforge3\lib\site-packages\conan\api\subapi\graph.py", line 190, in analyze_binaries
    binaries_analyzer.evaluate_graph(graph, build_mode, lockfile, remotes, update)
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\graph_binaries.py", line 324, in evaluate_graph
    self._evaluate_package_id(node)
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\graph_binaries.py", line 292, in _evaluate_package_id
    compute_package_id(node, self._cache.new_config)  # TODO: revise compute_package_id()
  File "c:\local\miniforge3\lib\site-packages\conans\client\graph\compute_pid.py", line 44, in compute_package_id
    options=conanfile.options.copy_conaninfo_options(),
  File "c:\local\miniforge3\lib\site-packages\conans\model\options.py", line 341, in copy_conaninfo_options
    assert not self._deps_package_options
AssertionError

ERROR:
```

**Comment by memsharded** [comment]
Hi @rainman110 

Thanks very much for your report and repro case.
I think this might be addressed by https://github.com/conan-io/conan/pull/13207, for next 2.0.1. It is only a clear error message, but it should point to the root case more clearly: the original ``qt`` recipe has an invalid assignment of ``options`` inside the ``requirements()`` method, which is causing the traceback, but it was always invalid, probably it doesn't even have any effect in 1.X. The solution would be to move that to the ``configure()`` method instead, please try it. (also keep tuned to the conan-center-index, because the recipe might get updates soon too)

**Comment by ericLemanissier** [comment]
@rainman110 it should be fixed by https://github.com/rainman110/conan-qt5/pull/1

**Comment by rainman110** [comment]
Hi @memsharded . Thanks for the insights. @ericLemanissier already provided a patched recipe, so I can continue working on the 2.0 port. Shall we keep this issue opened or do you think it will be closed by #13207 ?

**Comment by ericLemanissier** [comment]
@rainman110 I think you can close the issue, now that conan 2.0.1 is released (and also because it's actually a bug in the recipe)

**Comment by rainman110** [comment]
Okay, closing it then...
