### ISSUE TITLE
[bug] conan cache clean --temp fails if temp folder does not exist

### ISSUE THREAD

**Issue by felix2010** [conan-io/conan#13645]
### Environment details

* Operating System+version: ubuntu jammy
* Compiler+version: gcc 11
* Conan version: 2.0.3
* Python version: 8.10

Running the command `conan cache clean -v --temp` on my system gives the following error
```Traceback (most recent call last):
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/cli/cli.py", line 171, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/cli/command.py", line 164, in run
    self._subcommands[subcommand].run(conan_api, *args)
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/cli/command.py", line 181, in run
    info = self._method(conan_api, self._parent_parser, self._parser, *args)
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/cli/commands/cache.py", line 78, in cache_clean
    conan_api.cache.clean(package_list, source=args.source, build=args.build,
  File "/home/fesc/.venv/conan2/lib/python3.10/site-packages/conan/api/subapi/cache.py", line 66, in clean
    shutil.rmtree(app.cache.temp_folder)
  File "/usr/lib/python3.10/shutil.py", line 714, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 712, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/fesc/.conan2/p/t'

ERROR: [Errno 2] No such file or directory: '/home/fesc/.conan2/p/t'
```

**Comment by AbrilRBS** [comment]
Hi! Thanks for your report :)

We identified this issue a bit ago and have already implemented a fix for it #13601, to be released in 2.0.4. Will leave this open to notify you when this goes live!
