### ISSUE TITLE
[bug] Insufficient information with full verbosity on encountering an error in `requirements` when evaluating the graph

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#13666]
### Environment details

* Operating System+version: Arch btw
* Conan version: 2.0.3
* Python version: 3.10.10

### Steps to reproduce

```bash
(conan2-env) hipony:Dev/axt (feature/conan2)✗ % conan export . --version=test
(conan2-env) hipony:Dev/axt (feature/conan2)✗ % conan graph build-order -vvv --requires=axt/test  
```

/cc @prince-chrismc 

### Logs

```
(conan2-env) hipony:Dev/axt (feature/conan2)✗ % conan graph build-order -vvv --requires=axt/test             [1] 21:42:38

======== Computing dependency graph ========

======== Computing necessary packages ========

catch2/3.3.2: Checking 7 compatible configurations:
catch2/3.3.2: 'f1c37f8d7cf2f9fe9e52fa705e55476e752d6475': compiler.cppstd=14
catch2/3.3.2: '9cd2c97d38685c80592a7269eaff6bc4911ef37e': compiler.cppstd=gnu14
catch2/3.3.2: '6d7b10a1613a8cae0255e0abef2a33cb7b06bd31': compiler.cppstd=17
catch2/3.3.2: 'eeea1a613881c0ae1f99f6926ea7cefd5e151103': compiler.cppstd=20
catch2/3.3.2: '804a123b25f416a2f166593c97deb91a5eadd880': compiler.cppstd=gnu20
catch2/3.3.2: 'f38001e8cb3fed29006609bb90bc71aa96fa2c30': compiler.cppstd=23
catch2/3.3.2: '544bcb27ed9dc05259f85799e6ff9dbdbea1d549': compiler.cppstd=gnu23
catch2/3.3.2: Checking 7 compatible configurations:
catch2/3.3.2: 'f1c37f8d7cf2f9fe9e52fa705e55476e752d6475': compiler.cppstd=14
catch2/3.3.2: '9cd2c97d38685c80592a7269eaff6bc4911ef37e': compiler.cppstd=gnu14
catch2/3.3.2: '6d7b10a1613a8cae0255e0abef2a33cb7b06bd31': compiler.cppstd=17
catch2/3.3.2: 'eeea1a613881c0ae1f99f6926ea7cefd5e151103': compiler.cppstd=20
catch2/3.3.2: '804a123b25f416a2f166593c97deb91a5eadd880': compiler.cppstd=gnu20
catch2/3.3.2: 'f38001e8cb3fed29006609bb90bc71aa96fa2c30': compiler.cppstd=23
catch2/3.3.2: '544bcb27ed9dc05259f85799e6ff9dbdbea1d549': compiler.cppstd=gnu23
double-conversion/3.2.1: Checking 11 compatible configurations:
... omitted private projects ...
harfbuzz/5.3.1: Checking 11 compatible configurations:
harfbuzz/5.3.1: 'aece4ffeaf91ed1524eda4984103091bfbd4f836': compiler.cppstd=98
harfbuzz/5.3.1: 'ac3c347e4522f99a313d161bd2e604fb79162ff3': compiler.cppstd=gnu98
harfbuzz/5.3.1: '8ad51964fff56b675fb5b244fef01113ee5d0773': compiler.cppstd=11
harfbuzz/5.3.1: '40830451ac70b014458fc3c443a1e2b8b3f27bfa': compiler.cppstd=gnu11
harfbuzz/5.3.1: '69ba51a3a76c7fe7e6749bae0b2218df03e96930': compiler.cppstd=14
harfbuzz/5.3.1: 'dd3feaba7df8832aa1d7c2aa8de1f45172e61000': compiler.cppstd=gnu14
harfbuzz/5.3.1: '35deaf954183066b04300ff10f83f21a3189b3a2': compiler.cppstd=17
harfbuzz/5.3.1: '394e3e79759c40fd53ec68448f4f2cfdc34016a6': compiler.cppstd=20
harfbuzz/5.3.1: '74d616559f6d40b4677a74edc893e10cc4826439': compiler.cppstd=gnu20
harfbuzz/5.3.1: 'ec0543ad3e5bfd9a33cd29686d46062e7aa1de4e': compiler.cppstd=23
harfbuzz/5.3.1: '8e3dd3758efc0772cf16e9861f9af80dfbbb50ad': compiler.cppstd=gnu23
Traceback (most recent call last):
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conan/cli/cli.py", line 171, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conan/cli/command.py", line 164, in run
    self._subcommands[subcommand].run(conan_api, *args)
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conan/cli/command.py", line 181, in run
    info = self._method(conan_api, self._parent_parser, self._parser, *args)
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conan/cli/commands/graph.py", line 69, in graph_build_order
    conan_api.graph.analyze_binaries(deps_graph, args.build, remotes=remotes, update=args.update,
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conan/api/subapi/graph.py", line 190, in analyze_binaries
    binaries_analyzer.evaluate_graph(graph, build_mode, lockfile, remotes, update)
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conans/client/graph/graph_binaries.py", line 324, in evaluate_graph
    self._evaluate_package_id(node)
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conans/client/graph/graph_binaries.py", line 292, in _evaluate_package_id
    compute_package_id(node, self._cache.new_config)  # TODO: revise compute_package_id()
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conans/client/graph/compute_pid.py", line 44, in compute_package_id
    options=conanfile.options.copy_conaninfo_options(),
  File "/home/hipony/Dev/conan2-env/lib/python3.10/site-packages/conans/model/options.py", line 330, in copy_conaninfo_options
    raise ConanException("Dependencies options were defined incorrectly. Maybe you"
conans.errors.ConanException: Dependencies options were defined incorrectly. Maybe you tried to define options values in 'requirements()' or other invalid place

ERROR: Dependencies options were defined incorrectly. Maybe you tried to define options values in 'requirements()' or other invalid place
```

**Comment by memsharded** [comment]
Hi @Minimonium 

Thanks for your report.
I guess that you meant that the error message is not including the reference of the recipe causing the error? 
If that is the case, I am adding it in https://github.com/conan-io/conan/pull/13668.

**Comment by prince-chrismc** [comment]
Yes that's exactly what we were looking for :)
