### ISSUE TITLE
[bug] openssl/3.1.0 failed to build on msys2/mingw64 gcc 9.2

### ISSUE THREAD

**Issue by bennyhuo** [conan-io/conan#13752]
### Environment details

* Operating System+version: Windows 11 + msys2
* Compiler+version: Gcc 9.2
* Conan version: 2.0.2
* Python version: 3.9

### Steps to reproduce

conanfile.txt: 
```
[requires]
libcurl/8.0.1
sqlite3/3.41.1
tinycthreadpool/1.0

[generators]
CMakeDeps
CMakeToolchain
```

conan2 profile named 'mingw64':

```
{% set MSYS2_ROOT = "C:/msys64" %}
{% set MINGW64_ROOT = "C:/msys64/mingw64" %}

[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=9.2
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release

[buildenv]
MSYS_ROOT={{ MSYS2_ROOT }}/bin
MSYS_BIN={{ MSYS2_ROOT }}/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX={{ MINGW64_ROOT }}/bin/g++.exe
CC={{ MINGW64_ROOT }}/bin/gcc.exe
PATH+={{ MSYS2_ROOT }}/usr/bin;{{ MINGW64_ROOT }}/bin

[conf]
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path={{ MSYS2_ROOT }}/usr/bin/bash
```

run command in the project folder:

```
conan install . --output-folder=cmake-build-debug -pr:b=mingw64 -pr:h=mingw64 --build=missing -vvv
```

### Logs

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++.exe
CC=C:/msys64/mingw64/bin/gcc.exe
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++.exe
CC=C:/msys64/mingw64/bin/gcc.exe
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin


======== Computing dependency graph ========
libcurl/8.0.1: Not found in local cache, looking in remotes...
libcurl/8.0.1: Checking remote: conancenter
Decompressing conan_export.tgz
libcurl/8.0.1: Downloaded recipe revision 671cb47ae525a8bdb369af8599634fc0
Graph root
    conanfile.txt: D:\WorkSpace\iMooc\C\ProgramInC\Chapter16\conanfile.txt
Requirements
    libcurl/8.0.1#671cb47ae525a8bdb369af8599634fc0 - Downloaded (conancenter)
    openssl/3.1.0#25925a18588e030e406a15da96c4d32b - Cache
    sqlite3/3.41.1#a367521f65fc33539addbebededbf873 - Cache
    tinycthreadpool/1.0#20400830304a395b72ccdc376b9a7401 - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    autoconf/2.71#f4e2bd681d49b4b80761aa587bde94d5 - Cache
    automake/1.16.5#891f585a736bce951cc0e7109aa5ffee - Cache
    gnu-config/cci.20210814#eb941b98dbf40f3eb1753f6b1f05861f - Cache
    libtool/2.4.7#d55a3c2435c19e830fa77aa5c6c19350 - Cache
    m4/1.4.19#7689d2cae05587d0efb12261ddc4124d - Cache
    meson/1.0.0#15586c0ac6f682805875ef903dbe7ee2 - Cache
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1 - Cache
    ninja/1.11.1#a2f0b832705907016f336839f96963f8 - Cache
    pkgconf/1.9.3#a920b5c7f8d04f22b9fe03db91a864dd - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache

======== Computing necessary packages ========
Requirements
    libcurl/8.0.1#671cb47ae525a8bdb369af8599634fc0:028d50716e338270a240c3ab9f5f83b9af8347dc - Build
    openssl/3.1.0#25925a18588e030e406a15da96c4d32b:f8a03f2d3f8906ecb0e0e0ecc028a6ee3e146399 - Build
    sqlite3/3.41.1#a367521f65fc33539addbebededbf873:4dd7051320472fb88b58d4b4980c9d24c975aa8d#99dac688c6abc236caba7ed09b9a4823 - Cache
    tinycthreadpool/1.0#20400830304a395b72ccdc376b9a7401:0e27a7b23643fdc6d081b5a840eab2e71f0a31a6#0b2bb9807549b7ff4e957f93099bcf6b - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:0e27a7b23643fdc6d081b5a840eab2e71f0a31a6#31805eb6b1da69cac457631c10b709c7 - Cache
Build requirements
    autoconf/2.71#f4e2bd681d49b4b80761aa587bde94d5:da39a3ee5e6b4b0d3255bfef95601890afd80709#5c53a519d70fdb79d3cd4145e9f0355f - Skip
    automake/1.16.5#891f585a736bce951cc0e7109aa5ffee:ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715#07094da42a0b39fd4b34760c5f1f3e7d - Cache
    gnu-config/cci.20210814#eb941b98dbf40f3eb1753f6b1f05861f:da39a3ee5e6b4b0d3255bfef95601890afd80709#0d678e64f84cc730eaf93b400db0864f - Cache
    libtool/2.4.7#d55a3c2435c19e830fa77aa5c6c19350:0e27a7b23643fdc6d081b5a840eab2e71f0a31a6 - Build
    m4/1.4.19#7689d2cae05587d0efb12261ddc4124d:723257509aee8a72faf021920c2874abc738e029#7cfc2a45eeed64b49a5ac80482f427a5 - Skip
    meson/1.0.0#15586c0ac6f682805875ef903dbe7ee2:da39a3ee5e6b4b0d3255bfef95601890afd80709#5c8fd51fc33f12e26519674d99afd0e5 - Skip
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1:723257509aee8a72faf021920c2874abc738e029#35f6a3ef14b15246b30071d024e4f18d - Cache
    ninja/1.11.1#a2f0b832705907016f336839f96963f8:723257509aee8a72faf021920c2874abc738e029#2af209f6b38a9f7b2c777c6bff456ffb - Skip
    pkgconf/1.9.3#a920b5c7f8d04f22b9fe03db91a864dd:43771b8671ac44479c188dd72670e2eb2d7918a6#ce4d1d61f0b05d4229631aa740250685 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47:522dcea5982a3f8a5b624c16477e47195da2f84f#a365b3810f698e2f0a00fbeece022903 - Skip

======== Installing packages ========
gnu-config/cci.20210814: Already installed! (1 of 12)
m4/1.4.19: Already installed! (2 of 12)
m4/1.4.19: Appending PATH environment variable: C:\Users\benny\.conan2\p\m4fd4297abfc654\p\bin
m4/1.4.19: Appending PATH environment variable: C:\Users\benny\.conan2\p\m4fd4297abfc654\p\bin
sqlite3/3.41.1: Already installed! (3 of 12)
tinycthreadpool/1.0: Already installed! (4 of 12)
zlib/1.2.13: Already installed! (5 of 12)
nasm/2.15.05: Already installed! (6 of 12)
pkgconf/1.9.3: Already installed! (7 of 12)
pkgconf/1.9.3: Appending PATH env var: C:\Users\benny\.conan2\p\pkgco3e0c2be422576\p\bin
pkgconf/1.9.3: Setting PKG_CONFIG env var: C:/Users/benny/.conan2/p/pkgco3e0c2be422576/p/bin/pkgconf.exe
pkgconf/1.9.3: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
pkgconf/1.9.3: Appending AUTOMAKE_CONAN_INCLUDES env var: C:/Users/benny/.conan2/p/pkgco3e0c2be422576/p/bin/aclocal
autoconf/2.71: Already installed! (8 of 12)
autoconf/2.71: Defining AC_MACRODIR environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\res\autoconf
autoconf/2.71: Defining autom4te_perllibdir environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\res\autoconf
autoconf/2.71: Defining AUTOCONF environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoconf
autoconf/2.71: Defining AUTORECONF environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoreconf
autoconf/2.71: Defining AUTOHEADER environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoheader
autoconf/2.71: Defining AUTOM4TE environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autom4te
autoconf/2.71: Defining AC_MACRODIR environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\res\autoconf
autoconf/2.71: Defining autom4te_perllibdir environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\res\autoconf
autoconf/2.71: Defining AUTOCONF environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoconf
autoconf/2.71: Defining AUTORECONF environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoreconf
autoconf/2.71: Defining AUTOHEADER environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autoheader
autoconf/2.71: Defining AUTOM4TE environment variable: C:\Users\benny\.conan2\p\autoc84ad36d1c05b9\p\bin\autom4te

-------- Installing package openssl/3.1.0 (9 of 12) --------
openssl/3.1.0: Building from source
openssl/3.1.0: Package openssl/3.1.0:f8a03f2d3f8906ecb0e0e0ecc028a6ee3e146399
openssl/3.1.0: Copying sources to build folder
openssl/3.1.0: Building your package in C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b
openssl/3.1.0: Calling generate()
openssl/3.1.0: Generators folder: C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release\conan
openssl/3.1.0: using target: mingw-conan-Release-Windows-x86_64-gcc-9.2 -> mingw64
openssl/3.1.0: my %targets = (
    "mingw-conan-Release-Windows-x86_64-gcc-9.2" => {
        inherit_from => [ "mingw64" ],
        cflags => add("-m64 -O3"),
        cxxflags => add("-m64 -O3"),
        defines => add("NDEBUG"),
        lflags => add("-m64"),




    },
);

openssl/3.1.0: Generating aggregated env files
openssl/3.1.0: Generated aggregated env files: ['conanbuild.sh', 'conanrun.bat']
openssl/3.1.0: Calling build()
wrapped: "C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release\conan\msys2_mode.bat" && C:/msys64/usr/bin/bash --login -c ^". \^"C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release\conan\conanbuild.sh\^" ^&^& perl 
./Configure \^"mingw-conan-Release-Windows-x86_64-gcc-9.2\^" no-shared --prefix=/ --libdir=lib --openssldir=\^"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\^" no-unit-test threads PERL=perl no-tests --release enable-fips no-md2 zlib --with-zlib-include=\^"C:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include\^" --with-zlib-lib=\^"C:/Users/benny/.conan2/p/zlib1902ddd954da9/p/lib/z.lib\^"^"
openssl/3.1.0: RUN: perl ./Configure "mingw-conan-Release-Windows-x86_64-gcc-9.2" no-shared --prefix=/ --libdir=lib --openssldir="/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res" no-unit-test threads PERL=perl no-tests --release enable-fips no-md2 zlib --with-zlib-include="C:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include" --with-zlib-lib="C:/Users/benny/.conan2/p/zlib1902ddd954da9/p/lib/z.lib"
Configuring OpenSSL version 3.1.0 for target mingw-conan-Release-Windows-x86_64-gcc-9.2
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************

wrapped: "C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release\conan\msys2_mode.bat" && C:/msys64/usr/bin/bash --login -c ^". \^"C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release\conan\conanbuild.sh\^" ^&^& make -j16^"
openssl/3.1.0: RUN: make -j16
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/asn1.h.in > include/openssl/asn1.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/asn1t.h.in > include/openssl/asn1t.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/bio.h.in > include/openssl/bio.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/cmp.h.in > include/openssl/cmp.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/cms.h.in > include/openssl/cms.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/conf.h.in > include/openssl/conf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/crmf.h.in > include/openssl/crmf.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/crypto.h.in > include/openssl/crypto.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/ct.h.in > include/openssl/ct.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/err.h.in > include/openssl/err.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/ess.h.in > include/openssl/ess.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/fipskey.h.in > include/openssl/fipskey.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/lhash.h.in > include/openssl/lhash.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/ocsp.h.in > include/openssl/ocsp.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/opensslv.h.in > include/openssl/opensslv.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/pkcs12.h.in > include/openssl/pkcs12.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/pkcs7.h.in > include/openssl/pkcs7.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/safestack.h.in > include/openssl/safestack.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/srp.h.in > include/openssl/srp.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/ssl.h.in > include/openssl/ssl.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/ui.h.in > include/openssl/ui.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/x509.h.in > include/openssl/x509.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/x509_vfy.h.in > include/openssl/x509_vfy.h
perl "-I." -Mconfigdata "util/dofile.pl" "-oMakefile" include/openssl/x509v3.h.in > include/openssl/x509v3.h
make depend && make _build_sw
make[1]: Entering directory '/c/Users/benny/.conan2/p/t/opensc31bebc8b705f/b/src'
make[1]: Leaving directory '/c/Users/benny/.conan2/p/t/opensc31bebc8b705f/b/src'
make[1]: Entering directory '/c/Users/benny/.conan2/p/t/opensc31bebc8b705f/b/src'
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-app_libctx.obj apps/lib/app_libctx.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-app_params.obj apps/lib/app_params.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-app_provider.obj apps/lib/app_provider.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-app_rand.obj apps/lib/app_rand.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-app_x509.obj apps/lib/app_x509.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-apps.obj apps/lib/apps.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-apps_ui.obj apps/lib/apps_ui.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-columns.obj apps/lib/columns.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-engine.obj apps/lib/engine.c
C:/msys64/mingw64/bin/gcc.exe  -I. -Iinclude -Iapps/include  -m64 -m64 -O3 -m64 -O3 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/c/users/benny/.conan2/p/t/opensc31bebc8b705f/p/res\"" -DENGINESDIR="\"//lib/engines-3\"" -DMODULESDIR="\"//
lib/ossl-modules\"" -DUNICODE -D_UNICODE -DWIN32_LEAN_AND_MEAN -D_MT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -DNDEBUG -IC:/Users/benny/.conan2/p/zlib1902ddd954da9/p/include -DNDEBUG  -c -o apps/lib/libapps-lib-engine_loader.obj apps/lib/engine_loader.c
make[1]: *** [Makefile:2431: apps/lib/libapps-lib-app_libctx.obj] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:2433: apps/lib/libapps-lib-app_params.obj] Error 1
make[1]: *** [Makefile:2435: apps/lib/libapps-lib-app_provider.obj] Error 1
make[1]: *** [Makefile:2437: apps/lib/libapps-lib-app_rand.obj] Error 1
make[1]: *** [Makefile:2439: apps/lib/libapps-lib-app_x509.obj] Error 1
make[1]: *** [Makefile:2441: apps/lib/libapps-lib-apps.obj] Error 1
make[1]: *** [Makefile:2443: apps/lib/libapps-lib-apps_ui.obj] Error 1
make[1]: *** [Makefile:2445: apps/lib/libapps-lib-columns.obj] Error 1
make[1]: *** [Makefile:2447: apps/lib/libapps-lib-engine.obj] Error 1
make[1]: *** [Makefile:2449: apps/lib/libapps-lib-engine_loader.obj] Error 1
make[1]: Leaving directory '/c/Users/benny/.conan2/p/t/opensc31bebc8b705f/b/src'
make: *** [Makefile:1412: build_sw] Error 2

openssl/3.1.0: ERROR:
Package 'f8a03f2d3f8906ecb0e0e0ecc028a6ee3e146399' build failed
openssl/3.1.0: WARN: Build folder C:\Users\benny\.conan2\p\t\opensc31bebc8b705f\b\build-release
Traceback (most recent call last):
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\errors.py", line 51, in conanfile_exception_formatter
    yield
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\conanfile\build.py", line 13, in run_build_method
    conanfile.build()
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 519, in build
    self._make()
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 512, in _make
    self._run_make()
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 489, in _run_make
    self.run(" ".join(command), env="conanbuild")
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\conan_file.py", line 319, in run
    raise ConanException("Error %d while executing" % retcode)
conans.errors.ConanException: Error 2 while executing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\cli.py", line 171, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\command.py", line 157, in run
    info = self._method(conan_api, parser, *args)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\commands\install.py", line 82, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\api\subapi\install.py", line 22, in install_binaries
    installer.install(deps_graph, remotes)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 252, in install
    self._handle_package(package, install_reference, None, handled_count, package_count)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 315, in _handle_package
    self._handle_node_build(package, package_layout)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 385, in _handle_node_build
    pref = builder.build_package(node, pkg_layout)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 159, in build_package
    raise exc
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 152, in build_package
    self._build(conanfile, pref)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 101, in _build
    raise exc
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 94, in _build
    run_build_method(conanfile, self._hook_manager)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    raise
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\errors.py", line 66, in conanfile_exception_formatter
    _raise_conanfile_exc(exc)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\errors.py", line 46, in _raise_conanfile_exc
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 519, in build
    self._make()
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 512, in _make
    self._run_make()
  File "C:\Users\benny\.conan2\p\opens4d8b8eb2b5350\e\conanfile.py", line 489, in _run_make
    self.run(" ".join(command), env="conanbuild")
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\conan_file.py", line 319, in run
    raise ConanException("Error %d while executing" % retcode)
conans.errors.ConanException: Error 2 while executing
```

**Comment by bennyhuo** [comment]
The msys2 pack I used can be downloaded here: https://drive.bennyhuo.com/api/raw/?path=/imooc/C/msys64.rar

**Comment by memsharded** [comment]
Hi @bennyhuo 

Thanks for your report.
This might not be a Conan bug, but could be an issue with the ConanCenter recipe, not prepared to build for msys2. If it is a recipe issue, better move it to the ``conan-center-index``.

Lets try to isolate something that is minimal to reproduce:

- First, lets try to work with the Conan ``msys2/cci.latest`` package, you can add it to your profile ``tool_requires``, and forget about all the other configurations. I would try the setup first with some very simple recipe, like ``conan new cmake_lib -d name=pkg -d version=0.1`` + ``conan create . -pr=myprofile``. Also, some information if your existing profile already works for other packages would be relevant.
- Lets isolate the openssl building, like the command to reproduce could be ``conan install --requires=openssl/3.1.0 --build=openssl* -pr=myprofile``, no need for conanfile.txt or the like

Then, most likely we should move it to the ConanCenter repo.

**Comment by bennyhuo** [comment]
OK, Thank you.
