### ISSUE TITLE
[bug] unknown compilers with Autotools reliably raise TypeError 

### ISSUE THREAD

**Issue by datalogics-robb** [conan-io/conan#13813]
### Environment details

* Operating System: AIX 7.2 Power64 (native build)
* Compiler+version: BM xlc 17.1.1
* Conan version: 1.59
* Python version: 3.9.16

### Steps to reproduce

1. Use the cci ICU recipe (or any autotools recipe) and a compiler that is not one of: "Visual Studio", "msvc", "clang", "gcc", "apple-clang", "qcc", "mcst-lcc", or "sun-cc"
2. Run `conan create` to attempt to build the ICU Conan package

This method https://github.com/conan-io/conan/blob/1.59.0/conan/tools/_compilers.py#L120 returns a list in every case except the final return on 168.  It should be changed from `return ""` to `return []`

### Logs

```
 CONAN_VERBOSE_TRACEBACK=1 conan create . icu/73.1@_/_ -s:h build_type=Debug -pr:h aix-xlc17-ppc64 -pr:b aix-xlc17-ppc64  --settings:build build_type=Release --build missing
Exporting package recipe
icu/73.1 exports: File 'conandata.yml' found. Exporting it...
icu/73.1 exports: Copied 1 '.yml' file: conandata.yml
icu/73.1: Calling export_sources()
icu/73.1: The stored package has not changed
icu/73.1: Using the exported files summary hash as the recipe revision: 0e0abdeeaef39f3ea3558f69a76f4b5e 
icu/73.1: Exported revision: 0e0abdeeaef39f3ea3558f69a76f4b5e
Configuration (profile_host):
[settings]
arch=ppc64
build_type=Debug
compiler=xlc
compiler.version=17.1
os=AIX
os.version=7.2
[options]
boost:debug_level=1
[build_requires]
[env]
CC=/opt/IBM/openxlC/17.1.1/bin/ibm-clang_r
CFLAGS=-mcpu=power8 -m64 -maltivec
CXX=/opt/IBM/openxlC/17.1.1/bin/ibm-clang++_r
CXXFLAGS=-mcpu=power8 -m64 -maltivec -fsized-deallocation
OBJECT_MODE=64
PATH=[/opt/IBM/openxlC/17.1.1/bin]
Configuration (profile_build):
[settings]
arch=ppc64
build_type=Release
compiler=xlc
compiler.version=17.1
os=AIX
os.version=7.2
[options]
boost:debug_level=1
[build_requires]
[env]
CC=/opt/IBM/openxlC/17.1.1/bin/ibm-clang_r
CFLAGS=-mcpu=power8 -m64 -maltivec
CXX=/opt/IBM/openxlC/17.1.1/bin/ibm-clang++_r
CXXFLAGS=-mcpu=power8 -m64 -maltivec -fsized-deallocation
OBJECT_MODE=64
PATH=[/opt/IBM/openxlC/17.1.1/bin]
icu/73.1: WARN: Package binary is corrupted, removing: 54ad05321292dc314bfe8cb6f6f8f2ef695a6617
icu/73.1 (test package): Installing package
Requirements
    icu/73.1 from local cache - Cache
Packages
    icu/73.1:54ad05321292dc314bfe8cb6f6f8f2ef695a6617 - Build

Installing (downloading, building) binaries...
icu/73.1: WARN: Build folder is dirty, removing it: /home/robb/.conan/data/icu/73.1/_/_/build/54ad05321292dc314bfe8cb6f6f8f2ef695a6617
icu/73.1: Copying sources to build folder
icu/73.1: Building your package in /home/robb/.conan/data/icu/73.1/_/_/build/54ad05321292dc314bfe8cb6f6f8f2ef695a6617
icu/73.1: Generator txt created conanbuildinfo.txt
icu/73.1: Calling generate()
ERROR: Traceback (most recent call last):
  File "/devlocal/robb/pdfl18_all/python-env-kantipur/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/devlocal/robb/pdfl18_all/python-env-kantipur/lib/python3.9/site-packages/conans/client/generators/__init__.py", line 259, in write_toolchain
    conanfile.generate()
  File "/home/robb/.conan/data/icu/73.1/_/_/export/conanfile.py", line 151, in generate
    tc.generate()
  File "/devlocal/robb/pdfl18_all/python-env-kantipur/lib/python3.9/site-packages/conan/tools/gnu/autotoolstoolchain.py", line 149, in generate
    env = env or self.environment()
  File "/devlocal/robb/pdfl18_all/python-env-kantipur/lib/python3.9/site-packages/conan/tools/gnu/autotoolstoolchain.py", line 139, in environment
    env.append("CXXFLAGS", self.cxxflags)
  File "/devlocal/robb/pdfl18_all/python-env-kantipur/lib/python3.9/site-packages/conan/tools/gnu/autotoolstoolchain.py", line 99, in cxxflags
    ret = ret + self.build_type_flags + apple_flags + conf_flags + self.extra_cxxflags
TypeError: can only concatenate list (not "str") to list


```

**Comment by memsharded** [comment]
Thanks for reporting @datalogics-robb !

I am submitting the fix you suggested in https://github.com/conan-io/conan/pull/13815 for next 1.60, indeed seems the correct fix.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13815 for 1.60
