### ISSUE TITLE
[bug] Missing sqlite3 python package after pip install

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#13947]
### Environment details

* Operating System+version:
On both FreeBSD and NetBSD, installing conan-2.0.5 via pip
* Compiler+version:
* Conan version: 2.0.5
* Python version: 3.11

### Logs

On NetBSD I get the following, which is fixed by `pkgin install py311-sqlite3`

```
arm64$ conan --version                                                                                                                               [912/912]
Traceback (most recent call last):
  File "/home/gicc/.local/bin/conan", line 33, in <module>
    sys.exit(load_entry_point('conan==2.0.5', 'console_scripts', 'conan')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gicc/.local/bin/conan", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/pkg/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/pkg/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gicc/.local/lib/python3.11/site-packages/conans/conan.py", line 3, in <module>
    from conan.cli.cli import main
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/cli/cli.py", line 13, in <module>
    from conan.api.conan_api import ConanAPI
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/api/conan_api.py", line 3, in <module>
    from conan.api.subapi.cache import CacheAPI
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/api/subapi/cache.py", line 3, in <module>
    from conan.internal.conan_app import ConanApp
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/internal/conan_app.py", line 4, in <module>
    from conans.client.cache.cache import ClientCache
  File "/home/gicc/.local/lib/python3.11/site-packages/conans/client/cache/cache.py", line 11, in <module>
    from conan.internal.cache.cache import DataCache, RecipeLayout, PackageLayout
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 9, in <module>
    from conan.internal.cache.db.cache_database import CacheDatabase
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/internal/cache/db/cache_database.py", line 1, in <module>
    from conan.internal.cache.db.packages_table import PackagesDBTable
  File "/home/gicc/.local/lib/python3.11/site-packages/conan/internal/cache/db/packages_table.py", line 1, in <module>
    import sqlite3
  File "/usr/pkg/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/pkg/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
arm64$ conan --version
```

**Comment by memsharded** [comment]
Hi @jputcu 

Thanks for your report.

The problem with this issue is that ``pkgin install py311-sqlite3`` is outside of our control. We cannot do anything in the Conan app to install this, but those particular OSs need such package installed at the system level. But Conan installs as a Python app, and sqlite3 is built-in Python, not a Conan explicit dependency.

If you are more aware of those OSs, any suggestion?

**Comment by jputcu** [comment]
This is because sqlite3 python packages needs compiled libraries. If we can't ask pip to install the sqlite package I don't know, the cleanest would be to have an official `conan` package on those platforms.

**Comment by memsharded** [comment]
Maintaining a Conan package on those platforms at this moment seems a bit challenging. We are quite overwhelmed, and we don't have any expertise on those platforms. If there is interest by the users, I'd suggest this being under the umbrella of the community, users or distro maintainers, as it already happens for:
- Arch Linux
- Chocolatey (Windows)
- Brew
- Conda

**Comment by jputcu** [comment]
For FreeBSD, I also had to install `py39-distro`. Could it be possible to document this for now or perhaps have `pip` output some notes when on FreeBSD or NetBSD?

**Comment by jputcu** [comment]
About `sqlite3`, it is being used in the `conan` code (e.g. `conan/internal/cache/db/packages_table.py`) but no mention in the `requirements*.txt`, shouldn't it be added?

**Comment by memsharded** [comment]
sqlite3 is not a requirement. It is part of the Python standard library: https://docs.python.org/3/library/sqlite3.html

This is why it cannot be added to ``requirements.txt``, it is supposed to be part of Python itself, not an external pip package, and it should come with the Python distro. The fact that in BSD OSs it is not part of the Python distro is completely outside of our control, there is nothing we can do to install it while installing Conan app.

**Comment by jputcu** [comment]
When installing python on FreeBSD, there is the following message:
~~~~
Note that some standard Python modules are provided as separate ports
as they require additional dependencies. They are available as:

py39-gdbm       databases/py-gdbm@py39
py39-sqlite3    databases/py-sqlite3@py39
py39-tkinter    x11-toolkits/py-tkinter@py39
~~~~

Maybe in the future, the FreeBSD `conan-1.53` package will be updated, which installs the `sqlite3` package.
So I don't think we can do much to improve this.

**Comment by memsharded** [comment]
Thanks @jputcu for the feedback and following up!

**Comment by esotericpig** [comment]
I just ran into this today. Stupidly, I should have read the `pyenv` docs better. Just make sure to have these installed for your platform:

https://github.com/pyenv/pyenv/wiki#suggested-build-environment

On Debian/Ubuntu, just do this:

```
$ sudo apt install build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev curl git \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
```

Then reinstall your Python versions:

```
$ pyenv install 3
$ pyenv install 2
```

Now `conan --version` works.

**Comment by memsharded** [comment]
Thanks for the feedback @esotericpig 

I am a bit surprised this is happening in a regular Ubuntu distro, this is what I usually use, and things work by default, I don't recall having to install those packages. But those hints can be useful to solve issues if that is not the case for other users, so many thanks!
