### ISSUE TITLE
[question] How to package an application with its dependencies libraries?

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14119]
### What is your question?

Hello,

This is to get more clarification regarding #14067

I ran your code @RubenRBS:
```python
from conan.tools.files import copy

def deploy(graph, output_folder, **kwargs):
    for node in graph.nodes:
        libdirs = node.conanfile.cpp_info.libdirs
        if libdirs:
            for libdir in libdirs: 
                copy(node.conanfile, "*.so*", src=libdir, dst="your/final/path")
```

Two things were to be fixed. The first one was the import (```files``` instead of ```file```). The second one was to change the copy from ```*.so``` to ```*.so*``` to prevent some links to be broken, like for ```boost``` libraries.

I have a few questions:
- Is it possible to run a ```cmake install``` at the beginning of the ```deploy()``` method? I already do so inside my ```package()```method:
```python
def package(self):
	cmake = CMake(self)
	cmake.install()
```
but I do not know if I can call that one directly.

- Is it possible to remove some of the unrequired libs? In fact, taking the example of boost once again, one does not necessarily needs all the libs, since it only makes the deployment folder bigger.

- Is it possible to add system libs? I need to add python to my folder, but since the recipe of cpython is not Conan 2.X ready just yet on conancenter, I am forced to link with the system Python in my CMakeLists.txt.

All of these questions serve one purpose : I want to run a single conan command to package (build done beforehand) and create a zip file of my project and all its dependencies. I then want to distribute it to clients (they will have the proper environment to run it, but won't have conan installed). Do you think you could give me a hint?

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question:

> Is it possible to run a cmake install at the beginning of the deploy() method? I already do so inside my package()method:

You can do whatever you like in a ``deploy()`` method, but that sounds unexpected, probably not great. ``deployers`` are intended to copy and extract files from package binaries, how these binaries are built is hidden. In fact, many times, when the package binaries are installed from the server and not built locally, there will not be built at all, CMake will not be called, there will be no Cmake project to install.


> Is it possible to remove some of the unrequired libs? In fact, taking the example of boost once again, one does not necessarily needs all the libs, since it only makes the deployment folder bigger.

yes, you can define your own filters, copy the patterns that you want. Note that the target folder is your own folder, under user space, you can do there whatever you like, like zipping all files and then removing those files and keep only the .zip file


> Is it possible to add system libs? I need to add python to my folder, but since the recipe of cpython is not Conan 2.X ready just yet on conancenter, I am forced to link with the system Python in my CMakeLists.txt.

**Comment by Todiq** [comment]
Hey @memsharded 

Thank you for your quick response, as usual.

I installed the deployer with ```conan config install https://github.com/conan-io/conan-extensions.git``` and ran the install by adding ```--deploy=runtime_zip_deploy```. However, I encountered the following issue:

<details>
  <summary>Log</summary>

```bash
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
castcore/1.0:shared=True
[conf]
tools.build:skip_test=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[conf]
tools.build:skip_test=True


======== Computing dependency graph ========
castcore/1.0: Not found in local cache, looking in remotes...
castcore/1.0: Checking remote: conancenter
castcore/1.0: Checking remote: castconan
castcore/1.0: Downloaded recipe revision 0097efb349c71833d5c28ba2741925fc
boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

Graph root
    cli
Requirements
    boost/1.81.0#9bd7ae86a881631b6cc76590621e470b - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    castcore/1.0#0097efb349c71833d5c28ba2741925fc - Downloaded (castconan)
    icu/72.1#8fa9fd1c317244e914cbd6f3fe403230 - Cache
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335 - Cache
    libxml2/2.10.3#da52bac51b6cd7463fc08413541b0e8c - Cache
    pugixml/1.13#adee6d41b5ec42da7d4a39e0377dae34 - Cache
    xerces-c/3.2.4#4671e88f6dfce5089e314d2be26b1eb3 - Cache
Test requirements
    gtest/1.13.0#8a0bc5b3e159ed45de97260c2bff65b5 - Cache
Build requirements
    b2/4.9.6#2e02945ad41739b8051247d14fe8297d - Cache

======== Computing necessary packages ========
Requirements
    boost/1.81.0#9bd7ae86a881631b6cc76590621e470b:fe958fe55c7c08d3fd1a4c9e8b7ede53eb583486#d261cd39fa329eaa9303d8be5118e49d - Cache
    castcore/1.0#0097efb349c71833d5c28ba2741925fc:87d2ccc5c54e7d3fa631c0e30871577e36cbe5c3#3c0c9fa96467165de605d2431cdff440 - Download (castconan)
    icu/72.1#8fa9fd1c317244e914cbd6f3fe403230:9a31ec3b2e0130e364172600173500c19b6120de#e98e3f60900ab90166dfc3fa6c0469fc - Cache
    libxml2/2.10.3#da52bac51b6cd7463fc08413541b0e8c:20c3ad8b00f8bb5ab8149e5f62fe7341469ea46e#ba73b135326f06ed7240dfac6a657241 - Cache
    xerces-c/3.2.4#4671e88f6dfce5089e314d2be26b1eb3:a7d6915b081955a117fc42b5f27fbab1518170fb#e4cd6581b26539a4523ab1f6dc65dfe1 - Cache
Test requirements
Build requirements
Skipped binaries
    bzip2/1.0.8, libbacktrace/cci.20210118, libiconv/1.17, pugixml/1.13, gtest/1.13.0, b2/4.9.6

======== Installing packages ========

-------- Downloading 1 package --------
castcore/1.0: Retrieving package 87d2ccc5c54e7d3fa631c0e30871577e36cbe5c3 from remote 'castconan'
castcore/1.0: Downloading 1.0MB conan_package.tgz
castcore/1.0: Decompressing 1.0MB conan_package.tgz
castcore/1.0: Package installed 87d2ccc5c54e7d3fa631c0e30871577e36cbe5c3
castcore/1.0: Downloaded package revision 3c0c9fa96467165de605d2431cdff440
icu/72.1: Already installed! (1 of 5)
xerces-c/3.2.4: Already installed! (2 of 5)
boost/1.81.0: Already installed! (3 of 5)
boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

libxml2/2.10.3: Already installed! (4 of 5)
libxml2/2.10.3: Appending PATH environment variable: /home/carl/.conan2/p/b/libxm086d903dc6140/p/bin
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: libxml2/2.10.3, icu/72.1, boost/1.81.0
WARN: deprecated:     'env_info' used in: libxml2/2.10.3, icu/72.1, boost/1.81.0
WARN: deprecated:     'cpp_info.filenames' used in: libxml2/2.10.3, boost/1.81.0
WARN: deprecated:     'user_info' used in: boost/1.81.0
WARN: deprecated:     'cpp_info.build_modules' used in: libxml2/2.10.3

======== Finalizing install (deploy, generators) ========
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conan/cli/command.py", line 134, in run
    info = self._method(conan_api, parser, *args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/commands/install.py", line 82, in install
    conan_api.install.install_consumer(deps_graph=deps_graph,
  File "/usr/local/lib/python3.9/site-packages/conan/api/subapi/install.py", line 68, in install_consumer
    do_deploys(self.conan_api, deps_graph, deploy, base_folder)
  File "/usr/local/lib/python3.9/site-packages/conan/internal/deploy.py", line 44, in do_deploys
    deployer(graph=graph, output_folder=deploy_folder)
  File "/home/carl//.conan2/extensions/deployers/runtime_zip_deploy.py", line 22, in deploy
    shutil.copy2(src, dst)
  File "/usr/lib64/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/home/carl/.conan2/p/b/libxm086d903dc6140/p/lib/cmake'
```
</details>

I then decided to apply a fix withing ```runtime_zip_deploy.py``` by replacing
```python
if f.endswith(".dll") or f.endswith(".exe") or f.endswith(".dylib") or os.access(src, os.X_OK)
```
with
```python
if (os.path.isdir(src) is False) and (f.endswith(".dll") or f.endswith(".exe") or f.endswith(".dylib") or os.access(src, os.X_OK))
```
but that led to:
<details>
  <summary>Log</summary>

```bash
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[conf]
tools.build:skip_test=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[conf]
tools.build:skip_test=True


======== Computing dependency graph ========
boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

Graph root
    conanfile.py (carl/1.0): /home/carl/Carl/conanfile.py
Requirements
    boost/1.81.0#9bd7ae86a881631b6cc76590621e470b - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    castcore/1.0#0097efb349c71833d5c28ba2741925fc - Cache
    castdbconnectivity/1.0#aa4c3a1a39f8f7037efe8d4f2aaa2987 - Cache
    castframework/1.0#3efa52e128cab3a4a48dcd9d084885e7 - Cache
    castparsing/1.0#9a66a4b0a838030c12da3ceda57ff10d - Cache
    cppunit/1.15.1#ab7aa369cbf20014946964574a427088 - Cache
    gtest/1.13.0#8a0bc5b3e159ed45de97260c2bff65b5 - Cache
    icu/72.1#8fa9fd1c317244e914cbd6f3fe403230 - Cache
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335 - Cache
    libpq/14.5#c42ba3a37dc1d8b18c61c91feddfd4c6 - Cache
    libxml2/2.10.3#da52bac51b6cd7463fc08413541b0e8c - Cache
    pugixml/1.13#adee6d41b5ec42da7d4a39e0377dae34 - Cache
    rapidjson/1.1.0#219bf1ea2756b263575da26288753262 - Cache
    xerces-c/3.2.4#4671e88f6dfce5089e314d2be26b1eb3 - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache
Test requirements
    gtest/1.13.0#8a0bc5b3e159ed45de97260c2bff65b5 - Cache
Build requirements
    b2/4.9.6#2e02945ad41739b8051247d14fe8297d - Cache

======== Computing necessary packages ========
Requirements
    boost/1.81.0#9bd7ae86a881631b6cc76590621e470b:fe958fe55c7c08d3fd1a4c9e8b7ede53eb583486#d261cd39fa329eaa9303d8be5118e49d - Cache
    castcore/1.0#0097efb349c71833d5c28ba2741925fc:87d2ccc5c54e7d3fa631c0e30871577e36cbe5c3#3c0c9fa96467165de605d2431cdff440 - Cache
    castdbconnectivity/1.0#aa4c3a1a39f8f7037efe8d4f2aaa2987:be04f7809b2091c3e9717d86f027a73ed78bc805#27acce261e29e124a8a6831dd8d30e18 - Cache
    castframework/1.0#3efa52e128cab3a4a48dcd9d084885e7:0e05dc89c75a32555a72542b69686f7c76451706#8edbb6918b8d62704a09d55d17201147 - Cache
    castparsing/1.0#9a66a4b0a838030c12da3ceda57ff10d:bbd16ac26c8544437c7a461b23107bba85f687e9#f23bb71c70f3fbdf8a5eff31a9f9dff4 - Cache
    cppunit/1.15.1#ab7aa369cbf20014946964574a427088:25d664844ba0add5c56b4ecd6338933ac571b8ed#bf49015cd509e2b00720a4277e051106 - Cache
    gtest/1.13.0#8a0bc5b3e159ed45de97260c2bff65b5:7d21ff1fb3121220f7077e5275f8cd543628bc03#c646a7ba8ad49eaa6d2610e1fa747a55 - Cache
    icu/72.1#8fa9fd1c317244e914cbd6f3fe403230:9a31ec3b2e0130e364172600173500c19b6120de#e98e3f60900ab90166dfc3fa6c0469fc - Cache
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c:897e6fde718e72637d92b0b8ed929893a1976238#6ece239f6629e3930a1dd8357a7b9ab1 - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335:897e6fde718e72637d92b0b8ed929893a1976238#e6448d31bae5b2231df4440864d720db - Cache
    libpq/14.5#c42ba3a37dc1d8b18c61c91feddfd4c6:a300700127e386d922d80e4806686a2e9cea2eda#457513303ec0dd67b10f64fa169903be - Cache
    libxml2/2.10.3#da52bac51b6cd7463fc08413541b0e8c:20c3ad8b00f8bb5ab8149e5f62fe7341469ea46e#ba73b135326f06ed7240dfac6a657241 - Cache
    pugixml/1.13#adee6d41b5ec42da7d4a39e0377dae34:da39a3ee5e6b4b0d3255bfef95601890afd80709#ae530054ed7ac99330514c13a5bfde3a - Cache
    rapidjson/1.1.0#219bf1ea2756b263575da26288753262:da39a3ee5e6b4b0d3255bfef95601890afd80709#c8d3999780598e0fbaed67c22f961d87 - Cache
    xerces-c/3.2.4#4671e88f6dfce5089e314d2be26b1eb3:a7d6915b081955a117fc42b5f27fbab1518170fb#e4cd6581b26539a4523ab1f6dc65dfe1 - Cache
    zlib/1.2.13#e377bee636333ae348d51ca90874e353:f940c1f7889f9018080dbeebdede5a67d6c3b30e#f6c432466a22a8650ef0e6b459b4722e - Cache
Test requirements
Build requirements
Skipped binaries
    bzip2/1.0.8, gtest/1.13.0, b2/4.9.6

======== Installing packages ========
cppunit/1.15.1: Already installed! (1 of 16)
gtest/1.13.0: Already installed! (2 of 16)
icu/72.1: Already installed! (3 of 16)
libbacktrace/cci.20210118: Already installed! (4 of 16)
libiconv/1.17: Already installed! (5 of 16)
libpq/14.5: Already installed! (6 of 16)
pugixml/1.13: Already installed! (7 of 16)
rapidjson/1.1.0: Already installed! (8 of 16)
xerces-c/3.2.4: Already installed! (9 of 16)
zlib/1.2.13: Already installed! (10 of 16)
boost/1.81.0: Already installed! (11 of 16)
boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

boost/1.81.0: running "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.81.0: RUN: "/usr/bin/python3" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"

libxml2/2.10.3: Already installed! (12 of 16)
libxml2/2.10.3: Appending PATH environment variable: /home/carl/.conan2/p/b/libxm086d903dc6140/p/bin
castcore/1.0: Already installed! (13 of 16)
castdbconnectivity/1.0: Already installed! (14 of 16)
castparsing/1.0: Already installed! (15 of 16)
castframework/1.0: Already installed! (16 of 16)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: libxml2/2.10.3, icu/72.1, libiconv/1.17, libpq/14.5, boost/1.81.0, gtest/1.13.0, zlib/1.2.13, rapidjson/1.1.0
WARN: deprecated:     'env_info' used in: libxml2/2.10.3, icu/72.1, libiconv/1.17, libpq/14.5, boost/1.81.0
WARN: deprecated:     'cpp_info.filenames' used in: boost/1.81.0, libxml2/2.10.3
WARN: deprecated:     'user_info' used in: boost/1.81.0
WARN: deprecated:     'cpp_info.build_modules' used in: libxml2/2.10.3

======== Finalizing install (deploy, generators) ========
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conan/cli/command.py", line 134, in run
    info = self._method(conan_api, parser, *args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/commands/install.py", line 82, in install
    conan_api.install.install_consumer(deps_graph=deps_graph,
  File "/usr/local/lib/python3.9/site-packages/conan/api/subapi/install.py", line 68, in install_consumer
    do_deploys(self.conan_api, deps_graph, deploy, base_folder)
  File "/usr/local/lib/python3.9/site-packages/conan/internal/deploy.py", line 44, in do_deploys
    deployer(graph=graph, output_folder=deploy_folder)
  File "/home/carl//.conan2/extensions/deployers/runtime_zip_deploy.py", line 12, in deploy
    for dir in [d.cpp_info.bindir, d.cpp_info.libdir]:
  File "/usr/local/lib/python3.9/site-packages/conans/model/build_info.py", line 408, in __getattr__
    return getattr(self._package, attr)
  File "/usr/local/lib/python3.9/site-packages/conans/model/build_info.py", line 188, in bindir
    assert bindirs
AssertionError

ERROR:
```bash

Any ideas?

**Comment by memsharded** [comment]
Yeah, the deployer there might not be very mature yet. You might need to check for existing or something:

```python
for dirs in [d.cpp_info.bindirs, d.cpp_info.libdirs]:
     if not dirs:
           continue
     for dir in dirs:
           ....
```

Please use that deployer only as a "hint", it is not ready for production. Maybe we want to move this issue to that repo and collaborate there to make a more robust one that will work for more users?

**Comment by Todiq** [comment]
Sure, I'll close that one. Thanks for your help! Have a good day.

**Comment by memsharded** [comment]
But lets re-open and transfer to the other repo, and we can try to improve the deployer there.
