### ISSUE TITLE
[bug] conan_sources.tgz not downloaded when using artifactory cache

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan#14458]
### Environment details

* Operating System+version: RHEL 8.8
* Compiler+version: gcc 8.5.0
* Conan version: 1.60.2
* Python version: 3.11

### Steps to reproduce

1. Empty directory with a `conanfile.txt` that lists `zlib/1.2.13` as the only requirement
2. `conan install . --build missing`

When using an artifactory cache, `conan_sources.tgz` is never downloaded and the build fails due to the missing files.

I've confirmed that `https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files` and `https://center.conan.io/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files` both return the same content of:

```
{
  "files" : {
    "conan_export.tgz" : { },
    "conan_sources.tgz" : { },
    "conanmanifest.txt" : { },
    "conanfile.py" : { }
  }
```

### Logs

```
DEBUG :conan_api.py   [176]: INIT: Using config '/home/rshade/.conan/conan.conf' [2023-08-09 12:27:27,099]
DEBUG :tracer.py      [156]: CONAN_API: install(path=.,name=None,version=None,user=None,channel=None,settings=None,options=None,env=None,profile_names=None,conf=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None, conf=None),remote_name=ng-conan,verify=None,manifests=None,manifests_interactive=None,build=['missing'],update=False,generators=None,no_imports=False,install_folder=None,output_folder=None,lockfile=None,lockfile_out=None,require_overrides=None) [2023-08-09 12:27:27,100]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/default [2023-08-09 12:27:27,102]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/centos8 [2023-08-09 12:27:27,102]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/release_dev_tools [2023-08-09 12:27:27,102]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/el8 [2023-08-09 12:27:27,102]                                                                                                                                                                                         DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/release_dev_tools [2023-08-09 12:27:27,102]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/default [2023-08-09 12:27:27,251]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/centos8 [2023-08-09 12:27:27,251]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/release_dev_tools [2023-08-09 12:27:27,252]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/el8 [2023-08-09 12:27:27,252]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/rshade/.conan/profiles/release_dev_tools [2023-08-09 12:27:27,252]
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
cmake:build_type=Release
ninja:build_type=Release
*:compiler.version=8
[options]
qt:qtwayland=True
[build_requires]
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++
zlib/1.2.13: Retrieving from server 'ng-conan'
zlib/1.2.13: Trying with 'ng-conan'...
DEBUG :rest_client_common.py[160]: REST: ping: https://artifactory.redacted.com/api/conan/ng-conan/v1/ping [2023-08-09 12:27:27,256]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions', 'matrix_params', 'only_v2'] [2023-08-09 12:27:27,665]
DEBUG :rest_client_common.py[188]: REST: get: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/latest [2023-08-09 12:27:27,665]
DEBUG :rest_client_common.py[188]: REST: get: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files [2023-08-09 12:27:27,772]
Downloading conanmanifest.txt
DEBUG :file_downloader.py[130]: DOWNLOAD: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files/conanmanifest.txt [2023-08-09 12:27:27,999]
Downloading conanfile.py
DEBUG :file_downloader.py[130]: DOWNLOAD: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files/conanfile.py [2023-08-09 12:27:28,106]
Downloading conan_export.tgz
DEBUG :file_downloader.py[130]: DOWNLOAD: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files/conan_export.tgz [2023-08-09 12:27:28,209]
zlib/1.2.13: Downloaded recipe revision e377bee636333ae348d51ca90874e353
DEBUG :graph_builder.py[478]: GRAPH: new_node: zlib/1.2.13 [2023-08-09 12:27:28,217]
DEBUG :graph_builder.py[69]: GRAPH: Time to load deps 0.9644403457641602 [2023-08-09 12:27:28,218]
DEBUG :rest_client_common.py[188]: REST: get: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/packages/761432f3453a17c960259b5b2605153e3bcffd7d/latest [2023-08-09 12:27:28,220]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.NotFoundException'> [2023-08-09 12:27:28,467]
conanfile.txt: Installing package
Requirements
    zlib/1.2.13 from 'ng-conan' - Downloaded
Packages
    zlib/1.2.13:761432f3453a17c960259b5b2605153e3bcffd7d - Build

Installing (downloading, building) binaries...
DEBUG :rest_client_common.py[188]: REST: get: https://artifactory.redacted.com/api/conan/ng-conan/v2/conans/zlib/1.2.13/_/_/revisions/e377bee636333ae348d51ca90874e353/files [2023-08-09 12:27:28,473]
zlib/1.2.13: Configuring sources in /home/rshade/.conan/data/zlib/1.2.13/_/_/source/src
DEBUG :file_downloader.py[130]: DOWNLOAD: https://zlib.net/fossils/zlib-1.2.13.tar.gz [2023-08-09 12:27:28,769]
zlib/1.2.13:
zlib/1.2.13: Copying sources to build folder
DEBUG :installer.py   [128]: BUILD: Copied to /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d [2023-08-09 12:27:29,240]
DEBUG :installer.py   [129]: BUILD: Files copied src [2023-08-09 12:27:29,240]
zlib/1.2.13: Building your package in /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d
INFO  :installer.py   [133]: GENERATORS: Writing generators [2023-08-09 12:27:29,241]
zlib/1.2.13: Generator txt created conanbuildinfo.txt
INFO  :installer.py   [137]: TOOLCHAIN: Writing toolchain [2023-08-09 12:27:29,241]
zlib/1.2.13: Calling generate()
zlib/1.2.13: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
zlib/1.2.13: Preset 'debug' added to CMakePresets.json. Invoke it manually using 'cmake --preset debug'
zlib/1.2.13: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/build/Debug/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug'
zlib/1.2.13: Aggregating env generators
DEBUG :build.py       [11]: Call conanfile.build() with files in build folder: ['conanbuildinfo.txt', 'generators'] [2023-08-09 12:27:29,270]
zlib/1.2.13: Calling build()
zlib/1.2.13:
zlib/1.2.13: ERROR: Package '761432f3453a17c960259b5b2605153e3bcffd7d' build failed
zlib/1.2.13: WARN: Build folder /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/build/Debug
ERROR: Traceback (most recent call last):
  File "/home/rshade/.local/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/rshade/.local/lib/python3.9/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/home/rshade/.conan/data/zlib/1.2.13/_/_/export/conanfile.py", line 82, in build
    self._patch_sources()
  File "/home/rshade/.conan/data/zlib/1.2.13/_/_/export/conanfile.py", line 66, in _patch_sources
    apply_conandata_patches(self)
  File "/home/rshade/.local/lib/python3.9/site-packages/conan/tools/files/patches.py", line 117, in apply_conandata_patches
    patch(conanfile, patch_file=patch_file, **entry)
  File "/home/rshade/.local/lib/python3.9/site-packages/conan/tools/files/patches.py", line 53, in patch
    patchset = patch_ng.fromfile(patch_path)
  File "/home/rshade/.local/lib/python3.9/site-packages/patch_ng.py", line 197, in fromfile
    fp = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/patches/1.2.13/0001-Fix-cmake.patch'
```

**Comment by robert-shade** [comment]
[conan_trace_cci.log](https://github.com/conan-io/conan/files/12304955/conan_trace_cci.log)
[conan_trace_artifactory.log](https://github.com/conan-io/conan/files/12304956/conan_trace_artifactory.log)

**Comment by robert-shade** [comment]
This was due to a corrupt package being in another repository included in a virtual repository.  sorry for the noise.

**Comment by memsharded** [comment]
No prob  🙂 thanks for the feedback!
