### ISSUE TITLE
[bug] PremakeDeps fails in Conan v1

### ISSUE THREAD

**Issue by valgur** [conan-io/conan#14482]
### Environment details

* Operating System+version: Windows
* Conan version: 1.60.2 (worked without issues in 2.0.9)
* Python version: 3.11

### Steps to reproduce

1. Add `PremakeDeps(self).generate()` to some recipe.
I was trying to use it with https://github.com/conan-io/conan-center-index/pull/18853
2. Run `conan create` on the recipe.

### Logs

```
yojimbo/1.2.1: Calling generate()
Traceback (most recent call last):
  File "C:\Users\martin\.conan\data\yojimbo\1.2.1\_\_\export\conanfile.py", line 73, in generate
    tc.generate()
  File "C:\Users\martin\miniconda3\envs\conan1\Lib\site-packages\conan\tools\premake\premakedeps.py", line 45, in generate
    generator_files = self.content
                      ^^^^^^^^^^^^
  File "C:\Users\martin\miniconda3\envs\conan1\Lib\site-packages\conan\tools\premake\premakedeps.py", line 80, in content
    deps = _PremakeTemplate(self._get_cpp_info())
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martin\miniconda3\envs\conan1\Lib\site-packages\conan\tools\premake\premakedeps.py", line 52, in _get_cpp_info
    dep_cppinfo = dep.cpp_info.copy()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\martin\miniconda3\envs\conan1\Lib\site-packages\conans\model\new_build_info.py", line 106, in __getattr__
    return getattr(self.components[None], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_NewComponent' object has no attribute 'copy'
```

Fails here: https://github.com/conan-io/conan/blob/8695925f3ab0f3968665c17aadc50159e5a8d303/conan/tools/premake/premakedeps.py#L49-L57

**Comment by memsharded** [comment]
Yes, I am afraid that PremakeDeps is not even documented in Conan 1 (https://docs.conan.io/1/reference/conanfile/tools.html), so this is not expected to work, even if it is there.

It is also not documented in Conan 2, I think this generator might still not be ready to be released, it might need more work and stabilization, but unfortunately we never had the time to invest in it (neither the expertise).

If you are interested in this generator, the recommendation would be to push it in Conan 2.0, contribute and give feedback there, until it is matured and documented.

**Comment by memsharded** [comment]
Closing as not planned, Conan 1 not getting these fixes anymore.
