### ISSUE TITLE
[bug]   Spaces in version range can lead to:  IndexError: string index out of range

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#14612]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: N/A
* Conan version: 2.0.10
* Python version: 3.10.8

The following version range works:
```
[>=0.0.1 <1.0]
```
The following does NOT work:
```
[>=0.0.1 < 1.0]
```

If a version range has a space after ```<```, we get the following error:
```
ERROR: Traceback (most recent call last):
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conan/cli/commands/create.py", line 46, in create
    ref, conanfile = conan_api.export.export(path=path,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conan/api/subapi/export.py", line 16, in export
    return cmd_export(app, path, name, version, user, channel, graph_lock=lockfile,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/cmd/export.py", line 20, in cmd_export
    conanfile = loader.load_export(conanfile_path, name, version, user, channel, graph_lock,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/loader.py", line 144, in load_export
    conanfile = self.load_named(conanfile_path, name, version, user, channel, graph_lock,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/loader.py", line 98, in load_named
    conanfile, _ = self.load_basic_module(conanfile_path, graph_lock, remotes=remotes,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/loader.py", line 60, in load_basic_module
    self._pyreq_loader.load_py_requires(conanfile, self, graph_lock, remotes,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/graph/python_requires.py", line 75, in load_py_requires
    py_requires = self._resolve_py_requires(py_requires_refs, graph_lock, loader, remotes,
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/graph/python_requires.py", line 93, in _resolve_py_requires
    resolved_ref = self._resolve_ref(requirement, graph_lock, remotes, update)
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/graph/python_requires.py", line 112, in _resolve_ref
    self._range_resolver.resolve(requirement, "python_requires", remotes, update)
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/client/graph/range_resolver.py", line 18, in resolve
    version_range = require.version_range
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/model/requires.py", line 171, in version_range
    return VersionRange(version[1:-1])
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/model/version_range.py", line 107, in __init__
    self.condition_sets.append(_ConditionSet(alternative, prereleases))
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/model/version_range.py", line 22, in __init__
    self.conditions.extend(self._parse_expression(e))
  File "/home/antoine/anaconda3/envs/py310/lib/python3.10/site-packages/conans/model/version_range.py", line 36, in _parse_expression
    if expression[1] == "=":
IndexError: string index out of range

ERROR: string index out of range

```

**Comment by AbrilRBS** [comment]
Hi @antoinebardoz thanks a lot for your report! You're right that having traces shown to the user is never a good thing. I've submitted #14616 to properly fail in cases like this :)
