### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'distro'

### ISSUE THREAD

**Issue by s-ker-s** [conan-io/conan#14753]
### Environment details

* Operating System+version: Alpine Linux 3.18, Debian "bookworm" 12.1 
* Compiler+version: N/A
* Conan version: 2.0.10
* Python version: 3.10.13, 3.9.17

### Steps to reproduce

1. Use the following `Pipfile`:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
conan = "~=2.0"
```
2. `pipenv install`
3. `pipenv run conan --version`

This results in an error `ModuleNotFoundError: No module named 'distro'`. The culprit is line 167 in `conans/client/cache/cache.py`:

```
                if platform.system() in ["Linux", "FreeBSD"]:
                    import distro
```

I'd expect distro to be declared as a dependency of conan (if needed) when installing via pip or pipenv. Our current workaround is installing distro manually.

### Logs

```
Traceback (most recent call last):
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/bin/conan", line 8, in <module>
    sys.exit(run())
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conan/cli/cli.py", line 244, in main
    conan_api = ConanAPI()
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conan/api/conan_api.py", line 41, in __init__
    check_required_conan_version(self.cache_folder)
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conans/client/conf/required_version.py", line 29, in check_required_conan_version
    cache = ClientCache(cache_folder)
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conans/client/cache/cache.py", line 47, in __init__
    self._store_folder = self.new_config.get("core.cache:storage_path") or \
  File "/tmp/builds/0/conan-recipe/KsHsZjTr/0/conan_recipe/.venv/lib/python3.9/site-packages/conans/client/cache/cache.py", line 167, in new_config
    import distro
ModuleNotFoundError: No module named 'distro'
```

**Comment by memsharded** [comment]
Hi @s-ker-s 

Thanks for your report.
This is our current ``requirements.txt``:
```
requests>=2.25, <3.0.0
urllib3>=1.26.6, <1.27
colorama>=0.4.3, <0.5.0
PyYAML>=6.0, <7.0
patch-ng>=1.17.4, <1.18
fasteners>=0.15
distro>=1.4.0, <=1.8.0; sys_platform == 'linux' or sys_platform == 'linux2'
Jinja2>=3.0, <4.0.0
python-dateutil>=2.8.0, <3
```
It seems that for most distros it has been enough to pull ``distro`` package and install it. I am wondering why for Alpine this is not the case. What is the result if you do a ``pip install -r requirements.txt`` over the above file?

**Comment by s-ker-s** [comment]
```
Requirement already satisfied: requests<3.0.0,>=2.25 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: urllib3<1.27,>=1.26.6 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.26.16)
Requirement already satisfied: colorama<0.5.0,>=0.4.3 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: PyYAML<7.0,>=6.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (6.0.1)
Requirement already satisfied: patch-ng<1.18,>=1.17.4 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.17.4)
Requirement already satisfied: fasteners>=0.15 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.18)
Collecting distro<=1.8.0,>=1.4.0 (from -r requirements.txt (line 7))
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: Jinja2<4.0.0,>=3.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (3.1.2)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.25->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.25->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.25->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.10/site-packages (from Jinja2<4.0.0,>=3.0->-r requirements.txt (line 8)) (2.1.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil<3,>=2.8.0->-r requirements.txt (line 9)) (1.16.0)
Installing collected packages: distro
Successfully installed distro-1.8.0
```
This is after installing conan via pipenv. Note that we saw the same issue on Debian 12.1, not just Alpine.

**Comment by memsharded** [comment]
Good, it seems that in that case ``distro`` is being installed correctly. I wonder why it isn't when installing the Conan package from ``pip``, this ``requirements.txt`` is the "ground truth" for dependencies definition.

**Comment by jputcu** [comment]
Just had the same issue when installing `conan-2.5.0` using `pip` on `FreeBSD-13.3`.
I had to manually `pip install distro` to get it working.

**Comment by memsharded** [comment]
This is the current definition in requirements.txt:
```
distro>=1.4.0, <=1.8.0; sys_platform == 'linux' or sys_platform == 'linux2'
```
What condition should be used to add FreeBSD too? Would you like to submit a PR yourself if this is possible?

**Comment by jputcu** [comment]
Should be as simple as?
~~~~
distro>=1.4.0, <=1.8.0; sys_platform == 'linux' or sys_platform == 'linux2' or sys_platform == 'freebsd'
~~~~
I'm currently not able to easily test this on my single FreeBSD CI/CD instance.

**Comment by memsharded** [comment]
It seems the above will not be enough, because ``sys.platform`` can return different strings. I have changed it to ``platform_system`` instead in https://github.com/conan-io/conan/pull/16700, which seems more robust.
