### ISSUE TITLE
[feature] Prettier output for conan install & conan build

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14785]
### What is your suggestion?

Hello,

I simply would like to know if it is possible to print the same output (or a slimmed down version) as `conan build --help` when running `conan build` (without any arguments).
On conan 2.0.11, I get this error (both Windows & Linux):
```bash
➜  ~ conan build
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/commands/build.py", line 35, in build
    path = conan_api.local.get_conanfile_path(args.path, cwd, py=True)
  File "/usr/local/lib/python3.9/site-packages/conan/api/subapi/local.py", line 26, in get_conanfile_path
    if os.path.isdir(path):  # Can be a folder
  File "/usr/lib64/python3.9/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

ERROR: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

The output for `conan install` is a bit better, but not as clean as for the other commands (e.g. `conan source` is a slimmer output of the one given by `conan source --help`):
```bash
➜  ~ conan install
ERROR: Please specify a path to a conanfile or a '--requires=<ref>'
```

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for reporting @Todiq !

yes, this was an overlook of a copy/paste, with the ``nargs`` argparse argument, not mandating having a path. Fixing it for next release.
