### ISSUE TITLE
[bug] Error copying sources to build folder

### ISSUE THREAD

**Issue by maichmueller** [conan-io/conan#14820]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: GCC-11
* Conan version: 1.60.2
* Python version:  Python 3.11.4  (also Python 3.9.18)

When installing packages conan is unable to unpack sources into a build folder, crashing in the process. However, Conan succeeds installing when it can download pre-binaries. I unfortunately cannot use pre-built binaries with every compiler I am using (e.g. for clang it needs to build some packages)
This problem does not occur on my private desktop machine, so I am rather certain it has to do with the fact that the home directory (where conan is meant to install into) is a mounted network drive at work (the drive has more than 20GB of storage left, so it's not a storage limit issue). Any tips on what might trigger this?

### Steps to reproduce

1. Install conan in a conda env
2. Use the conanfile.txt:
```
 [requires]
gtest/1.13.0
pybind11/2.10.4
range-v3/0.12.0
fmt/10.1.1
xtensor/0.24.3
openblas/0.3.20
spdlog/1.12.0
frozen/1.1.1

[generators]
cmake
cmake_find_package
cmake_paths

[layout]
cmake_layout
```
3. Run `conan install conanfile.txt -pr=default -pr:b=default -s build_type=Release -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -g=cmake --build`
4. Watch it fail :(
5. Run instead `conan install conanfile.txt -pr=default -pr:b=default -s build_type=Release -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing`
6. Conan succeeds

### Logs

```
/work/rleap1/michael.aichmueller/miniconda/bin/conan install /u/michael.aichmueller/GitProjects/reinforce/deps/conanfile.txt -pr=default -pr:b=default -s build_type=Release -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -g=cmake --build

Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

fmt/10.1.1: Forced build from source
frozen/1.1.1: Forced build from source
gtest/1.13.0: Forced build from source
nlohmann_json/3.11.2: Forced build from source
openblas/0.3.20: Forced build from source
pybind11/2.10.4: Forced build from source
range-v3/0.12.0: Forced build from source
xsimd/11.1.0: Forced build from source
xtl/0.7.5: Forced build from source
spdlog/1.12.0: Forced build from source
xtensor/0.24.3: Forced build from source
conanfile.txt: Installing package
Requirements
    fmt/10.1.1 from 'conancenter' - Cache
    frozen/1.1.1 from 'conancenter' - Cache
    gtest/1.13.0 from 'conancenter' - Cache
    nlohmann_json/3.11.2 from 'conancenter' - Cache
    openblas/0.3.20 from 'conancenter' - Cache
    pybind11/2.10.4 from 'conancenter' - Cache
    range-v3/0.12.0 from 'conancenter' - Cache
    spdlog/1.12.0 from 'conancenter' - Cache
    xsimd/11.1.0 from 'conancenter' - Cache
    xtensor/0.24.3 from 'conancenter' - Cache
    xtl/0.7.5 from 'conancenter' - Cache
Packages
    fmt/10.1.1:2c09c8f84c016041549fcee94e4caae5d89424b6 - Build
    frozen/1.1.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    gtest/1.13.0:4fefe176018d6564b5e2144163a209c027be31c5 - Build
    nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    openblas/0.3.20:1611de3a5677d1d94d77e7279247aa09f53735bb - Build
    pybind11/2.10.4:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    range-v3/0.12.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    spdlog/1.12.0:44fdd9f52bc6b25f679e19e16c208cd5449ebaf9 - Build
    xsimd/11.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    xtensor/0.24.3:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
    xtl/0.7.5:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
fmt/10.1.1: Copying sources to build folder
ERROR: [('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/std.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/std.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/std.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/core.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/core.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/core.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/ostream.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/ostream.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/ostream.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/format.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/format.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/format.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/format-inl.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/format-inl.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/format-inl.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/os.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/os.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/os.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/chrono.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/chrono.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/chrono.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/ranges.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/ranges.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/ranges.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/args.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/args.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/args.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/printf.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/printf.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/printf.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/color.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/color.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/color.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/compile.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/compile.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/compile.h'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/include/fmt/xchar.h', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/xchar.h', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt/xchar.h'"), (<DirEntry 'fmt'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/include/fmt', (LOADS OF THE SAME, COMMENT LIMIT REACHED.........) "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/conf.py'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/rtd/theme/layout.html', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme/layout.html', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme/layout.html'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/rtd/theme/theme.conf', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme/theme.conf', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme/theme.conf'"), (<DirEntry 'theme'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/theme'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/rtd/index.rst', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/index.rst', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd/index.rst'"), (<DirEntry 'rtd'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/rtd'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/manage.py', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/manage.py', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/manage.py'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/Android.mk', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/Android.mk', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/Android.mk'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/Vagrantfile', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/Vagrantfile', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/Vagrantfile'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/support/printable.py', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/printable.py', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support/printable.py'"), (<DirEntry 'support'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/support'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/LICENSE.rst', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/LICENSE.rst', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/LICENSE.rst'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/src/format.cc', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/format.cc', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/format.cc'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/src/fmt.cc', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/fmt.cc', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/fmt.cc'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/src/os.cc', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/os.cc', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src/os.cc'"), (<DirEntry 'src'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/src'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/ChangeLog.rst', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/ChangeLog.rst', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src/ChangeLog.rst'"), (<DirEntry 'src'>, '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6/src'"), ('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6', "[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/2c09c8f84c016041549fcee94e4caae5d89424b6'")]
Error copying sources to build folder
```

**Comment by memsharded** [comment]
Hi @maichmueller 

Thanks for your report.
If ``fmt`` is the one failing, the above error can be reproduced with just ``fmt`` in the ``conanfile``? It would be to reduce the case as much as possible.

It would also be great to try to reproduce in the same machine, but instead of using a mounted drive, using a local folder (setting CONAN_USER_HOME). That way, we can reduce a bit the scope, trying to decide if it is related to the mounted drive or not.



A side (but important) note. The ``cmake_layout`` might not work correctly with the legacy generators ``cmake``, ``cmake_find_package`` and ``cmake_paths``, but only with ``CMakeDeps`` and ``CMakeToolchain``, please upgrade to these as soon as possible, specially if using ConanCenter recipes, as they might eventually stop supporting the legacy generators

**Comment by maichmueller** [comment]
Hi @memsharded 

thanks for your answer! I just tried this conanfile:
```
[requires]
fmt/10.1.1

[generators]
cmake
cmake_find_package
cmake_paths
```
and can confirm that this is enough to trigger the problem (in fact, one simply needs any dependency that one can build, i.e. any non header-only lib) on the network drive. The copying of the sources does not work on the network drive.

I also just tested a local installation by setting CONAN_USER_HOME=/local/michael.aichmueller/ and then the copying is **not** a problem at all. So we can safely say that the problem is actually copying on the network drive. 

Is there any more debug information I can get on how the copying of sources fails exactly, e.g., what command is being executed to copy maybe.

Thanks for the side-note on the deprecation of the `cmake_layout`. (I have held out changing to the new generators so far, since they arent as simple as just loading conanbuildinfo and conan_paths and I could not immediately figure out how the switch to 2.0 works without losing the cmake-does-it-all convenience)

**Comment by memsharded** [comment]
You might try to define the ``[CONAN_VERBOSE_TRACEBACK](https://docs.conan.io/1/reference/env_vars.html#conan-verbose-traceback)`` env-var to see if the traceback gives a bit more information (though I am not sure we will see much more, this sounds like the typical challenging to debug issue, because it is very specific to that setup).

The code that is failing seems to be:
```python
@staticmethod
    def _copy_sources(conanfile, source_folder, build_folder):
        # Copies the sources to the build-folder, unless no_copy_source is defined
        _remove_folder_raising(build_folder)
        if not getattr(conanfile, 'no_copy_source', False):
            conanfile.output.info('Copying sources to build folder')
            try:
                shutil.copytree(source_folder, build_folder, symlinks=True)
            except Exception as e:
                msg = str(e)
                if "206" in msg:  # System error shutil.Error 206: Filename or extension too long
                    msg += "\nUse short_paths=True if paths too long"
                raise ConanException("%s\nError copying sources to build folder" % msg)
            logger.debug("BUILD: Copied to %s", build_folder)
            logger.debug("BUILD: Files copied %s", ",".join(os.listdir(build_folder)))
```
Which means that it seems the very basic ``shutil.copytree(source_folder, build_folder, symlinks=True)`` function call that is failing, so something internal to python, it will be difficult to fix.

It is possible that it is related to permissions/user in that drive. Trying to reproduce with pure python ``shutil.copytree()`` calls targeting the folder of the shared drive will further help to reduce the scope.

**Comment by memsharded** [comment]
> Thanks for the side-note on the deprecation of the cmake_layout. (I have held out changing to the new generators so far, since they arent as simple as just loading conanbuildinfo and conan_paths and I could not immediately figure out how the switch to 2.0 works without losing the cmake-does-it-all convenience)

If relying on ``cmake_paths`` for using packaged config.cmake files, then the ``CMakeToolchain`` should be a good replacement (but ``cmake_find_package`` is not necessary if that is the case). In any case, please do not hesitate to open tickets for questions or support in this migration, we will try to help as much as possible.

**Comment by maichmueller** [comment]
Hi @memsharded 

thanks for your help in debuggin this. It appears that relying on shutils.copytree is indeed a problem in combination with NFS mounted drives:

```
>>> import shutil
>>> print(os.getcwd())
/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_
>>> shutil.copytree(os.path.join(os.getcwd(), "source"), os.path.join(os.getcwd(), "build", "mybuildfoldertest"), symlinks=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/rleap1/michael.aichmueller/miniconda/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/rleap1/michael.aichmueller/miniconda/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/source/src/CMakeLists.txt', '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/mybuildfoldertest/src/CMakeLists.txt', ...LOOOONG LIST OF FILES THAT TRIGGER ERRORS HERE..."[Errno 5] Input/output error: '/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/mybuildfoldertest'")]
>>> 
```

I have found this issue discussing this same problem (different error code though) on mounted drives: https://github.com/python/cpython/issues/68752

In there a hotfix on stackoverflow is linked: https://stackoverflow.com/a/51635427/3736286


When trying this hotfix I am able to execute the copying it seems:
```
>>> from unittest import mock
>>> with mock.patch('os.listxattr', return_value=[]):
...    shutil.copytree(os.path.join(os.getcwd(), "source"), os.path.join(os.getcwd(), "build", "mybuildfoldertest"), symlinks=True)
... 
'/u/michael.aichmueller/.conan/data/fmt/10.1.1/_/_/build/mybuildfoldertest'

```

Although I haven't looked into what mock.patch exactly does and whether it would be a meaningful workaround for conan in general as well.

> > Thanks for the side-note on the deprecation of the cmake_layout. (I have held out changing to the new generators so far, since they arent as simple as just loading conanbuildinfo and conan_paths and I could not immediately figure out how the switch to 2.0 works without losing the cmake-does-it-all convenience)
> 
> If relying on `cmake_paths` for using packaged config.cmake files, then the `CMakeToolchain` should be a good replacement (but `cmake_find_package` is not necessary if that is the case). In any case, please do not hesitate to open tickets for questions or support in this migration, we will try to help as much as possible.

Thanks! I will hopefully get to trying the transition to conan 2.0 soon again. Will do if questions come up :+1:

**Comment by memsharded** [comment]
Thanks very much for the great investigation, indeed this is unfortunate, I am a bit surprised that this basic thing keeps failing in Python 3.11. Maybe it is worth considering if there are other alternatives than having the Conan cache in an NFS folder? Is it necessary for the cloud CI (Azure I guess)? Can't it be a local (even if temporary) folder? I am having a look to the patch, and I cannot fully understand the patch either, or what risks could it have for other platforms, but doesn't look great in general.

**Comment by maichmueller** [comment]
I was also quite surprised to find the problem in a pythonlib. I can mitigate the problem for my own setup by moving the files to a local path. Still, general compatibility with NFS would be desirable (CIs are definitely a reason, but our workspace doesn't grant local storage rights to normal users either). Although I believe that a fix should happen in the domain of python's internals rather than conan's, perhaps the workaround can be put to use in the interim. Thanks for your swift help with this problem anyhow!

**Comment by memsharded** [comment]
> Although I believe that a fix should happen in the domain of python's internals rather than conan's, perhaps the workaround can be put to use in the interim. Thanks for your swift help with this problem anyhow!

I am checking the ``mock.patch`` approach, and looks a bit concerning to be used for Conan:
- It needs to be applied in multiple places
- It can be breaking, as applying it unconditionally is effectively removing all extended attributes in the copy
- It is not easy to check if copies are being done from NFS to NFS, so doesn't seem possible to condition the patch just for those cases.

I am a bit confused by the fact that I have been searching on the internet, and I wasn't able to find new, updated information about this issue, only https://github.com/python/cpython/issues/61278, that is already many (10) years old, and it was closed as fixed. If this was failing at scale for NFS, I guess there should be more reports and users complaining in Python about this, but nothing out there.

So it might still be possible that there is something else. The patch might be working in your case because it might be effectively bypassing the permissions that doesn't allow the copy. But if that is the case, maybe the right approach would be to fix the permissions in the NFS share, not patching Python. Would it be possible to have a docker image or something that we could reproduce?

**Comment by maichmueller** [comment]
> It is not easy to check if copies are being done from NFS to NFS, so doesn't seem possible to condition the patch just for those cases.

From some quick google search it seems to be possible but probably not worth the effort.

> I am a bit confused by the fact that I have been searching on the internet, and I wasn't able to find new, updated information about this issue, only https://github.com/python/cpython/issues/61278, that is already many (10) years old, and it was closed as fixed. If this was failing at scale for NFS, I guess there should be more reports and users complaining in Python about this, but nothing out there.

I agree, this seemed off to me as well, however the python issue and workaround directly applied to my case, so I figured the fix may not cover all versions. Otherwise, the use case of NFS -> NFS copying may just come up rarely (but I'm skeptical).

These are my permission settings according to `ls`:
```
 ~ ls -al .conan                      
total 482
drwxr-xr-x  5 michael.aichmueller assi     12 Jul 19 11:34 .
drwxr-xr-x 36 michael.aichmueller assi     96 Okt  4 13:09 ..
-rw-r--r--  1 michael.aichmueller assi  12288 Jul 19 11:34 .conan.db
-rw-r--r--  1 michael.aichmueller assi      0 Jul 19 11:34 artifacts.properties
-rw-r--r--  1 michael.aichmueller assi 351649 Jul 19 11:34 cacert.pem
-rw-r--r--  1 michael.aichmueller assi   4586 Jul 19 10:51 conan.conf
drwxr-xr-x 15 michael.aichmueller assi     15 Sep 28 16:49 data
drwxr-xr-x  2 michael.aichmueller assi      3 Jul 19 11:34 hooks
drwxr-xr-x  2 michael.aichmueller assi      3 Jul 19 11:34 profiles
-rw-r--r--  1 michael.aichmueller assi    113 Jul 19 11:34 remotes.json
-rw-r--r--  1 michael.aichmueller assi   8056 Jul 19 11:34 settings.yml
-rw-r--r--  1 michael.aichmueller assi      6 Aug 30 10:19 version.txt

```
So I should be fine from a user's perspective. Perhaps within a python shell this permission does not carry over, but it doesn't appear to be so:
```
>>> import subprocess
>>> print(subprocess.check_output(["ls", "-al"]).decode())
total 482
drwxr-xr-x  5 michael.aichmueller assi     12 Jul 19 11:34 .
drwxr-xr-x 36 michael.aichmueller assi     96 Okt  4 14:24 ..
-rw-r--r--  1 michael.aichmueller assi      0 Jul 19 11:34 artifacts.properties
-rw-r--r--  1 michael.aichmueller assi 351649 Jul 19 11:34 cacert.pem
-rw-r--r--  1 michael.aichmueller assi   4586 Jul 19 10:51 conan.conf
-rw-r--r--  1 michael.aichmueller assi  12288 Jul 19 11:34 .conan.db
drwxr-xr-x 15 michael.aichmueller assi     15 Sep 28 16:49 data
drwxr-xr-x  2 michael.aichmueller assi      3 Jul 19 11:34 hooks
drwxr-xr-x  2 michael.aichmueller assi      3 Jul 19 11:34 profiles
-rw-r--r--  1 michael.aichmueller assi    113 Jul 19 11:34 remotes.json
-rw-r--r--  1 michael.aichmueller assi   8056 Jul 19 11:34 settings.yml
-rw-r--r--  1 michael.aichmueller assi      6 Aug 30 10:19 version.txt
```
If I understand this correctly then there should not be a permissions problem here. Or am I not seeing something?

**Comment by memsharded** [comment]
Based on the patch code I'd say that it would be worth to do a ``os.listxattr()`` over the files in the cache too, and see if there could be something there that could give us some hint.

**Comment by maichmueller** [comment]
```
>>> os.getcwd()
'/u/michael.aichmueller/.conan'
>>> os.listxattr()
['system.nfs4_acl']
```
seems like no more than an attribute to state we are dealing with an nfs drive.

**Comment by memsharded** [comment]
That is an AccessControlList (ACL), maybe you can gets its value?
This is the one attr mentioned in https://bugs.python.org/issue24564, so I would expect by now to no longer be an issue...

**Comment by maichmueller** [comment]
It seems standard to me:
```
 ~ getfacl .conan
# file: .conan
# owner: michael.aichmueller
# group: assi
user::rwx
group::r-x
other::r-x
```

**Comment by memsharded** [comment]
I am running out of ideas...
Maybe the next step could be to have something that we could reproduce. Some docker-compose with an nfs volume would be great to experiment a bit with it, I'll ping @uilianries to see if he can help with this.
