### ISSUE TITLE
[bug] Example2 consuming_packages broken on Windows

### ISSUE THREAD

**Issue by pierricgimmig** [conan-io/conan#14853]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: MSVC 2019
* Conan version: conan 2.0.13
* Python version: 3.11.4

### Steps to reproduce

Run `conan install` with this conanfile.py from [example2](https://github.com/conan-io/examples2/blob/main/tutorial/consuming_packages/conanfile_py/conanfile.py):

```
from conan import ConanFile

class CompressorRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("zlib/1.2.11")

    def build_requirements(self):
        self.tool_requires("cmake/3.22.6")
```

### Logs

```
PS C:\git\conan_playground\build ()
> conan install ..

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
cmake/3.22.6: Not found in local cache, looking in remotes...
cmake/3.22.6: Checking remote: conancenter
cmake/3.22.6: Downloaded recipe revision 32cced101c6df0fab43e8d00bd2483eb
Graph root
    conanfile.py: C:\git\conan_playground\conanfile.py
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e - Cache
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb - Downloaded (conancenter)

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e:7bfde258ff4f62f75668d0896dbddedaa7480a0f - Invalid
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb:522dcea5982a3f8a5b624c16477e47195da2f84f - Invalid

======== Installing packages ========
ERROR: There are invalid packages:
cmake/3.22.6: Invalid: 'settings.os.subsystem' value not defined
zlib/1.2.11: Invalid: 'settings.os.subsystem' value not defined
```

**Comment by memsharded** [comment]
Hi @pierricgimmig 

Thanks for your report.
I have just tried the above steps, and I was not able to reproduce. Not sure what could it be. Some quick checks:

- Are you using the recipes from ConanCenter as-is, or did you do some modifications to the recipes?
- Have you installed some hook or maybe some custom ``profile.py`` plugin?
- Are you sure you are using a clean Conan installation? Have you patched it or modified Conan source files in some way?
- Are you using subsystems like msys2 somewhere?
- Maybe trying ``-vvv`` to try to have a bit more verbose output

**Comment by pierricgimmig** [comment]
Hi @memsharded , thanks for the suggestions. Here's a little bit more info:

- The conan recipe is the one pasted above, taken as-is from `example2`.
- Nothing particularly special on the install, no customization, installed through `pip install conan`
- no msys2
- `conan install -vvv` gives:

```
> conan install . -vvv

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.py: C:\git\conan_playground\conanfile.py
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e - Cache
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e:7bfde258ff4f62f75668d0896dbddedaa7480a0f - Invalid
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb:522dcea5982a3f8a5b624c16477e47195da2f84f - Invalid

======== Installing packages ========
Traceback (most recent call last):
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\commands\install.py", line 70, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\api\subapi\install.py", line 21, in install_binaries
    installer.install(deps_graph, remotes)
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\installer.py", line 241, in install
    install_graph.raise_errors()
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\graph\install_graph.py", line 295, in raise_errors
    raise ConanInvalidConfiguration("\n".join(msg))
conans.errors.ConanInvalidConfiguration: There are invalid packages:
cmake/3.22.6: Invalid: 'settings.os.subsystem' value not defined
zlib/1.2.11: Invalid: 'settings.os.subsystem' value not defined

ERROR: There are invalid packages:
cmake/3.22.6: Invalid: 'settings.os.subsystem' value not defined
zlib/1.2.11: Invalid: 'settings.os.subsystem' value not defined
```

**Comment by memsharded** [comment]
I am still baffled about this error.

I don't have many ideas what to check, maybe let's try the following just in case:
- Lets try to run the above but setting a new temporary CONAN_HOME=C:/some/path, just to rule out some cache corruption
- If you have been updating the Conan version from previous versions, try to completely wipe it, or use a new fresh installation in a new virtualenv or something, also to rule out some Conan app corruption.

**Comment by pierricgimmig** [comment]
Hi @memsharded , I did update from conan 1.60 to 2.0.1. 

I ran `pip uninstall conan`, deleted my `.conan2` directory, and ran `pip install conan`, it now works!

Thanks for your help.

**Comment by pierricgimmig** [comment]
Here's the successful log:

```
> conan install .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Checking remote: conancenter
zlib/1.2.11: Downloaded recipe revision dc0e384f0551386cd76dc29cc964c95e
cmake/3.22.6: Not found in local cache, looking in remotes...
cmake/3.22.6: Checking remote: conancenter
cmake/3.22.6: Downloaded recipe revision 32cced101c6df0fab43e8d00bd2483eb
Graph root
    conanfile.py: C:\git\conan_playground\conanfile.py
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e - Downloaded (conancenter)
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb - Downloaded (conancenter)

======== Computing necessary packages ========
Requirements
    zlib/1.2.11#dc0e384f0551386cd76dc29cc964c95e:7bfde258ff4f62f75668d0896dbddedaa7480a0f#77962e8149c888d6de891f98c70c69d4 - Download (conancenter)
Build requirements
    cmake/3.22.6#32cced101c6df0fab43e8d00bd2483eb:522dcea5982a3f8a5b624c16477e47195da2f84f#a9d024f459972755e5a815b775408fff - Download (conancenter)

======== Installing packages ========

-------- Downloading 2 packages --------
cmake/3.22.6: Retrieving package 522dcea5982a3f8a5b624c16477e47195da2f84f from remote 'conancenter'
cmake/3.22.6: Downloading 25.7MB conan_package.tgz
cmake/3.22.6: Decompressing 25.7MB conan_package.tgz
cmake/3.22.6: Package installed 522dcea5982a3f8a5b624c16477e47195da2f84f
cmake/3.22.6: Downloaded package revision a9d024f459972755e5a815b775408fff
zlib/1.2.11: Retrieving package 7bfde258ff4f62f75668d0896dbddedaa7480a0f from remote 'conancenter'
zlib/1.2.11: Package installed 7bfde258ff4f62f75668d0896dbddedaa7480a0f
zlib/1.2.11: Downloaded package revision 77962e8149c888d6de891f98c70c69d4
cmake/3.22.6: Appending PATH environment variable: C:\Users\pierr\.conan2\p\cmake1927748c2604b\p\bin
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: cmake/3.22.6
WARN: deprecated:     'cpp_info.names' used in: zlib/1.2.11

======== Finalizing install (deploy, generators) ========
conanfile.py: Writing generators to C:\git\conan_playground
conanfile.py: Generator 'CMakeDeps' calling 'generate()'
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: CMakeToolchain generated: conan_toolchain.cmake
conanfile.py: Preset 'conan-default' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-default' if using CMake>=3.23
conanfile.py: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\git\conan_playground\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.py: CMakeToolchain generated: CMakePresets.json
conanfile.py: Generating aggregated env files
conanfile.py: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
Install finished successfully
```

**Comment by memsharded** [comment]
Excellent!

I guess then it was some glitch in ``pip`` update, that didnt manage to update everything cleanly. 
I think we can close this issue now? Sounds more like a glitch challenging to reproduce than a Conan app bug.

**Comment by pierricgimmig** [comment]
> I think we can close this issue now?

Yes, unblocked now, thank you!

**Comment by svenbarnett** [comment]
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows
settings.os.subsystem=msys2

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=191
os=Windows
settings.os.subsystem=msys2


======== Computing dependency graph ========
Graph root
    cli
Requirements
    zlib/3.1.12#77191091173744d3568a36ebbc7a882b - Cache

======== Computing necessary packages ========
Requirements
    zlib/3.1.12#77191091173744d3568a36ebbc7a882b:57f2b99d76417b45f23b61187dd8c5b9d78a38f2 - Invalid
Traceback (most recent call last):
  File "D:\PythonProject\ConanTest\venv\lib\site-packages\conan\cli\cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "D:\PythonProject\ConanTest\venv\lib\site-packages\conan\cli\command.py", line 164, in run
    info = self._method(conan_api, parser, *args)
  File "D:\PythonProject\ConanTest\venv\lib\site-packages\conan\cli\commands\create.py", line 115, in create
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "D:\PythonProject\ConanTest\venv\lib\site-packages\conan\api\subapi\install.py", line 23, in install_binaries
    install_graph.raise_errors()
  File "D:\PythonProject\ConanTest\venv\lib\site-packages\conans\client\graph\install_graph.py", line 475, in raise_errors
    raise ConanInvalidConfiguration("\n".join(msg))
conans.errors.ConanInvalidConfiguration: There are invalid packages:
zlib/3.1.12: Invalid: 'settings.os.subsystem' value not defined

ERROR: There are invalid packages:
zlib/3.1.12: Invalid: 'settings.os.subsystem' value not defined

```

i have same error，but reinstall， not works
