### ISSUE TITLE
[bug] Incorrect behavior with CMakeToolchain when package doesn't contain compiler setting

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14893]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: Visual Studio 2022
* Conan version: 2.0.13
* Python version: 3.11.5

### Steps to reproduce

Run `python repro.py` in the attached file.

The recipe doesn't include `compiler` in the settings, because in this case it was building a tool, and I didn't care what compiler was used...only the os. `CMakeToolchain` can't find a compiler and also ends up selecting the "MinGW MakeFiles" generator. It seems like the [code](https://github.com/conan-io/conan/blob/4650e1260c7ae2b681dcef1107716d2520871585/conan/tools/cmake/toolchain/toolchain.py#L212) should be handling this situation but it doesn't. At the least it would have been helpful for the `CMakeToolchain` generator to report an error indicating the issue here, but I think potentially `CMakeToolchain` should work without a compiler setting - but either way is ok.

### Logs

```
======== Exporting recipe to the cache ========
test/1.0: Exporting package recipe: D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\recipe\conanfile.py
test/1.0: Copied 1 '.py' file: conanfile.py
test/1.0: Copied 1 '.txt' file: CMakeLists.txt
test/1.0: Copied 1 '.cpp' file: main.cpp
test/1.0: Exported to cache folder: D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\conan_home\p\test4ee0011e56607\e
test/1.0: Exported: test/1.0#73e719f5d98fb94f0d56ecad1bc77a24 (2023-10-08 17:40:15 UTC)

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    cli
Requirements
    test/1.0#73e719f5d98fb94f0d56ecad1bc77a24 - Cache

======== Computing necessary packages ========
test/1.0: Forced build from source
Requirements
    test/1.0#73e719f5d98fb94f0d56ecad1bc77a24:ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715 - Build

======== Installing packages ========

-------- Installing package test/1.0 (1 of 1) --------
test/1.0: Building from source
test/1.0: Package test/1.0:ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715
test/1.0: Copying sources to build folder
test/1.0: Building your package in D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\conan_home\p\b\testc973b6df452c0\b
test/1.0: Calling generate()
test/1.0: Generators folder: D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\conan_home\p\b\testc973b6df452c0\b
test/1.0: CMakeToolchain generated: conan_toolchain.cmake
test/1.0: CMakeToolchain generated: CMakePresets.json
test/1.0: Generating aggregated env files
test/1.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
test/1.0: Calling build()
test/1.0: Running CMake.configure()
test/1.0: RUN: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="D:/dev/third_party_bug_reports/conan/cmaketoolchain_vcvars/conan_home/p/b/testc973b6df452c0/b/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/dev/third_party_bug_reports/conan/cmaketoolchain_vcvars/conan_home/p/b/testc973b6df452c0/p" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\conan_home\p\b\testc973b6df452c0\b"
-- Using Conan toolchain: D:/dev/third_party_bug_reports/conan/cmaketoolchain_vcvars/conan_home/p/b/testc973b6df452c0/b/conan_toolchain.cmake
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/dev/third_party_bug_reports/conan/cmaketoolchain_vcvars/conan_home/p/b/testc973b6df452c0/b/CMakeFiles/CMakeOutput.log".

test/1.0: ERROR:
Package 'ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715' build failed
test/1.0: WARN: Build folder D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\conan_home\p\b\testc973b6df452c0\b
*********************************************************
Recipe 'test/1.0' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: test/1.0: Error in build() method, line 18
        cmake.configure()
        ConanException: Error 1 while executing
Traceback (most recent call last):
  File "D:\dev\third_party_bug_reports\conan\cmaketoolchain_vcvars\repro.py", line 16, in <module>
    subprocess.check_call("conan create ./recipe -pr:b win_release_profile -pr:h win_release_profile ")
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conan create ./recipe -pr:b win_release_profile -pr:h win_release_profile ' returned non-zero exit status 1.
```

**Comment by rconde01** [comment]
[repro.zip](https://github.com/conan-io/conan/files/12841330/repro.zip)
