### ISSUE TITLE
[feature] Add option to pylint recipe on export

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14908]
### What is your suggestion?

It would be useful to optionally lint on export to catch errors early. I tried:
```
python -m pylint --errors-only --load-plugins=conans.pylint_plugin conanfile.py
```
and got:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\pylint\__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\pylint\__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\pylint\lint\run.py", line 155, in __init__
    linter.load_plugin_modules(self._plugins)
  File "C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\pylint\lint\pylinter.py", line 380, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\astroid\modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python311\Lib\site-packages\conans\pylint_plugin.py", line 7, in <module>
    from pylint.interfaces import IRawChecker
ImportError: cannot import name 'IRawChecker' from 'pylint.interfaces' (C:\Users\rob.conde\AppData\Roaming\Python\Python311\site-packages\pylint\interfaces.py)
Traceback (most recent call last):
  File "D:\dev\ff1\Conan\scripts\export_recipes.py", line 246, in <module>
    cmds = get_cmds()
           ^^^^^^^^^^
  File "D:\dev\ff1\Conan\scripts\export_recipes.py", line 75, in get_cmds
    subprocess.check_call(cmd, shell=True)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -m pylint --errors-only --load-plugins=conans.pylint_plugin D:\dev\ff1\Conan\recipes/actipro/conanfile.py' returned non-zero exit status 1.
```
and I also tried without the plugin, which worked for some cases but broke on recipes using:
```
get(self, **self.conan_data["sources"][self.version], strip_root=True)
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Closing as wont-do. This is something we have little chance to add to Conan 2 directly, but would consider community PRs in https://github.com/conan-io/conan-extensions to add the hook for just this, thanks!
