### ISSUE TITLE
[bug] [critical] conan 2 suddenly broken with python 3.12

### ISSUE THREAD

**Issue by wAuner** [conan-io/conan#14957]
### Environment details

* Operating System+version: macOS 14.0 + 13
* Compiler+version: n/a
* Conan version: 2.0.13
* Python version: 3.12
* Installed via `homebrew`

I just updated conan via brew and it stopped working. Also all of our CI pipelines stopped working. It's always some kind of `ModuleNotFoundError` like the one below.

Intel + arm are affected with at least macOS 13 + 14.

### Steps to reproduce

1. brew install conan
2. conan --version

### Logs

```
conan --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/conan", line 5, in <module>
    from conans.conan import run
  File "/opt/homebrew/Cellar/conan/2.0.13_2/libexec/lib/python3.12/site-packages/conans/conan.py", line 3, in <module>
    from conan.cli.cli import main
  File "/opt/homebrew/Cellar/conan/2.0.13_2/libexec/lib/python3.12/site-packages/conan/__init__.py", line 1, in <module>
    from conans.model.conan_file import ConanFile
  File "/opt/homebrew/Cellar/conan/2.0.13_2/libexec/lib/python3.12/site-packages/conans/model/conan_file.py", line 14, in <module>
    from conans.model.settings import Settings
  File "/opt/homebrew/Cellar/conan/2.0.13_2/libexec/lib/python3.12/site-packages/conans/model/settings.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by memsharded** [comment]
Hi @wAuner 

Thanks for your report.
Can you do a quick test if it works from ``pip`` in in your system? I suspect this could be a ``brew`` issue (but we don't have control over it)

**Comment by wAuner** [comment]
Hey James, thanks for the quick response. It could indeed to be related to the brew distribution. Locally I was able to get it to work via pip. I'll update our CI and let you know if it fixes the problem there as well.

**Comment by wAuner** [comment]
would you recommend to use a fixed python version in the CI or just always use the latest one? Our CI agents currently need to install conan on every run. For that we use brew currently, but I'd change that to installing python via brew and then use conan from pip in an venv.

**Comment by memsharded** [comment]
We try to test conan with a range of python versions, and we try to keep as compatible as possible with all of them, it shouldn't be a big problem per-se to run with different Python versions. 
If you ask for my personal opinion, I'd try to be a bit more stable in the Python version I use, waiting a bit until using the very latest one.

There are some other people from the team trying to have a look to the brew install

**Comment by franramirez688** [comment]
Hi @wAuner 

Facing the same problem. In my case, it fails with the `six` package is not found.
It seems the problem comes from Brew which requires the Python 3.12 version, but the installation could be wrong because using pip is not happening as I show below:

```
~ brew install conan -n
==> Would install 1 formula:
conan
==> Downloading https://ghcr.io/v2/homebrew/core/conan/manifests/2.0.13_2
Already downloaded: /Users/franchuti/Library/Caches/Homebrew/downloads/e1818f91c833d1959ea846ba09fc133bc1186b68f54e01d2d973e341c16aad31--conan-2.0.13_2.bottle_manifest.json
==> Would install 1 dependency for conan:
python@3.12
```
I have macOS Sonoma too. Another weird thing is that another team member has the same OS, but brew is using python 3.11 instead and it's running OK.

Now, using pip it's working with Python 3.12:
```
➜  ~ mkvirtualenv testi -p /usr/local/bin/python3.12
created virtual environment CPython3.12.0.final.0-64 in 747ms
  creator CPython3macOsBrew(dest=/Users/franchuti/.virtualenvs/testi, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/franchuti/Library/Application Support/virtualenv)
    added seed packages: pip==23.2.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /Users/franchuti/.virtualenvs/testi/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/franchuti/.virtualenvs/testi/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/franchuti/.virtualenvs/testi/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/franchuti/.virtualenvs/testi/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/franchuti/.virtualenvs/testi/bin/get_env_details
(testi) ➜  ~ pip install conan
Collecting conan
  Downloading conan-2.0.13.tar.gz (375 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.9/375.9 kB 1.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests<3.0.0,>=2.25 (from conan)
  Obtaining dependency information for requests<3.0.0,>=2.25 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting urllib3<1.27,>=1.26.6 (from conan)
  Obtaining dependency information for urllib3<1.27,>=1.26.6 from https://files.pythonhosted.org/packages/b0/53/aa91e163dcfd1e5b82d8a890ecf13314e3e149c05270cc644581f77f17fd/urllib3-1.26.18-py2.py3-none-any.whl.metadata
  Downloading urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 1.6 MB/s eta 0:00:00
Collecting colorama<0.5.0,>=0.4.3 (from conan)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting PyYAML<7.0,>=6.0 (from conan)
  Obtaining dependency information for PyYAML<7.0,>=6.0 from https://files.pythonhosted.org/packages/bc/06/1b305bf6aa704343be85444c9d011f626c763abb40c0edc1cad13bfd7f86/PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata
  Downloading PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting patch-ng<1.18,>=1.17.4 (from conan)
  Using cached patch-ng-1.17.4.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fasteners>=0.15 (from conan)
  Obtaining dependency information for fasteners>=0.15 from https://files.pythonhosted.org/packages/61/bf/fd60001b3abc5222d8eaa4a204cd8c0ae78e75adc688f33ce4bf25b7fafa/fasteners-0.19-py3-none-any.whl.metadata
  Downloading fasteners-0.19-py3-none-any.whl.metadata (4.9 kB)
Collecting Jinja2<4.0.0,>=3.0 (from conan)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting python-dateutil<3,>=2.8.0 (from conan)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting MarkupSafe>=2.0 (from Jinja2<4.0.0,>=3.0->conan)
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/3a/72/9f683a059bde096776e8acf9aa34cbbba21ddc399861fe3953790d4f2cde/MarkupSafe-2.1.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata
  Downloading MarkupSafe-2.1.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.9 kB)
Collecting six>=1.5 (from python-dateutil<3,>=2.8.0->conan)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.25->conan)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/25/27/fdd2027b4f3bba7e92ec3a3a5450bfecdfe92ed1066ecf9cc1f64d871e8e/charset_normalizer-3.3.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata
  Downloading charset_normalizer-3.3.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (32 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.25->conan)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.25->conan)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Downloading fasteners-0.19-py3-none-any.whl (18 kB)
Downloading PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl (178 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 1.4 MB/s eta 0:00:00
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 1.8 MB/s eta 0:00:00
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Downloading charset_normalizer-3.3.0-cp312-cp312-macosx_10_9_x86_64.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.6/119.6 kB 1.4 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.3-cp312-cp312-macosx_10_9_x86_64.whl (13 kB)
Building wheels for collected packages: conan, patch-ng
  Building wheel for conan (pyproject.toml) ... done
  Created wheel for conan: filename=conan-2.0.13-py3-none-any.whl size=482166 sha256=9b0986ee7748e99a9fb53187fcacf8c106fdb042e2ff88dd64de882f7e432e65
  Stored in directory: /Users/franchuti/Library/Caches/pip/wheels/a3/d4/42/2cd19b4ccef08637988ff2f6208d5c2e6bb72728f20261554b
  Building wheel for patch-ng (pyproject.toml) ... done
  Created wheel for patch-ng: filename=patch_ng-1.17.4-py3-none-any.whl size=16076 sha256=54f0f1592d0d3fd1b4797ae775ce609e4e8e5898704db0416b38f413c87d3cdd
  Stored in directory: /Users/franchuti/Library/Caches/pip/wheels/c0/ca/79/d6c49e498d31e473f26449c5aaa3ffdeb4d9d74b48407f8067
Successfully built conan patch-ng
Installing collected packages: patch-ng, urllib3, six, PyYAML, MarkupSafe, idna, fasteners, colorama, charset-normalizer, certifi, requests, python-dateutil, Jinja2, conan
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 PyYAML-6.0.1 certifi-2023.7.22 charset-normalizer-3.3.0 colorama-0.4.6 conan-2.0.13 fasteners-0.19 idna-3.4 patch-ng-1.17.4 python-dateutil-2.8.2 requests-2.31.0 six-1.16.0 urllib3-1.26.18

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: pip install --upgrade pip
(testi) ➜  ~ conan

Consumer commands
cache      Perform file operations in the local cache (of recipes and/or packages).
config     Manage the Conan configuration in the Conan home.
graph      Compute a dependency graph, without installing or building the binaries.
inspect    Inspect a conanfile.py to return its public fields.
install    Install the requirements specified in a recipe (conanfile.py or conanfile.txt).
list       List existing recipes, revisions, or packages in the cache (by default) or the
             remotes.
lock       Create or manage lockfiles.
profile    Manage profiles.
remote     Manage the remote list and the users authenticated on them.
remove     Remove recipes or packages from local cache or a remote.
search     Search for package recipes in all the remotes (by default), or a remote.
version    Give information about the Conan client version.

Creator commands
build      Install dependencies and call the build() method.
create     Create a package.
download   Download (without installing) a single conan package from a remote server.
editable   Allow working with a package that resides in user folder.
export     Export a recipe to the Conan package cache.
export-pkg Create a package directly from pre-compiled binaries.
new        Create a new example recipe and source files from a template.
source     Call the source() method.
test       Test a package from a test_package folder.
upload     Upload packages to a remote.

Type "conan <command> -h" for help
```

**Comment by jcar87** [comment]
I've just done a quick test on a clean install (installed hombrew and then conan from homebrew) and it works fine with Python 3.12 and conan 2.0.13 - no issues whatsoever.

Unfortunately I think some of these can be side effects of "living" installations where a version of something is installed and then updated in the future. Homebrew's Conan package is maintained here https://github.com/Homebrew/homebrew-core/blob/3a9452be03755fceabbc66ea08f667282eb54605/Formula/c/conan.rb and not by us, so it's hard to tell what could be wrong.

When Conan is installed via homebrew, all its dependencies should be visible with `brew list`:

```
==> Formulae
autoconf		docutils		isl			lz4			pycparser		rbenv
awscli			gcc			jq			m4			pygments		readline
brotli			gettext			libidn2			mpdecimal		python-certifi		ruby-build
c-ares			gh			libmpc			mpfr			python-markupsafe	six
ca-certificates		git-lfs			libnghttp2		node			python-setuptools	sqlite
cffi			gitlab-runner		libunistring		oniguruma		python@3.11		wget
cmake			gmp			libuv			openssl@3		python@3.12		xz
conan			icu4c			libyaml			pkg-config		pyyaml			zstd
```

If the missing dependency in your case is `pyyaml`, please make sure that it is installed (via `brew list`).

Second, I would try and verify which python interpreter is being used for Conan, you can get it by running:

`head -n1 $(which conan)`
which should say something like:

```
/opt/homebrew/Cellar/conan/2.0.13_2/libexec/bin/python
```

I would then try running:
```
 /opt/homebrew/Cellar/conan/2.0.13_2/libexec/bin/python --version
```

to verify the version of python (3.12)
and also:

```
/opt/homebrew/Cellar/conan/2.0.13_2/libexec/bin/python  -c "import yaml; print(yaml.__file__)"
```
to see if this can successfully locate the yaml module and import it 

I get:
```
/opt/homebrew/opt/pyyaml/lib/python3.12/site-packages/yaml/__init__.py
```

if running these commands yields a different result on your end, there may be a broken installation somewhere :/

**Comment by booltox** [comment]
Reinstalling pyyaml seems to fix this for me. 
`brew reinstall pyyaml`

**Comment by AbrilRBS** [comment]
Closing as solved, feel free to reopen/create a new issue should you find similar issues in the future :)
