### ISSUE TITLE
[bug] ConanReferenceDoesNotExistInDB is very rarely thrown in conan install

### ISSUE THREAD

**Issue by vient** [conan-io/conan#14977]
### Environment details

* Operating System+version: Ubuntu 20.04
* Conan version: 2.0.13
* Python version: 3.11.4

### Steps to reproduce

It's very hard to make a reproducer, I observed this error once in about 150 runs, so I'm hoping that maybe you will get some ideas from description.

Error occured in Jenkins under heavy load. I'm using `core.download:download_cache` pointing to mapped directory from host, and `core.download:parallel = 4`.

Full `global.conf`
```
core:required_conan_version = >=2.0.13
core.download:download_cache = {{ os.getenv("CONAN_DOWNLOAD_CACHE") }}
core.download:parallel = 4
core.download:retry = 10
core.download:retry_wait = 1
```

Other arguments passed to `conan install` seem irrelevant but please say if you need anything. I get a feeling that there may be some small race condition in code, triggered by parallel>1? Maybe only if combined with download cache, if that makes sense?

### Logs

```
...
aws-sdk-cpp/1.9.234: Copying 13.0MB conan_package.tgz from download cache, instead of downloading it
aws-sdk-cpp/1.9.234: Decompressing 13.0MB conan_package.tgz
aws-sdk-cpp/1.9.234: Package installed 20f5b8fb6c3edc2f567e2a236e4d9372abdfca34
aws-sdk-cpp/1.9.234: Downloaded package revision 3a67fbf575a0e116e209794ee6934b77
ERROR: Traceback (most recent call last):
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 132, in get_or_create_pkg_layout
    return self.get_package_layout(pref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 112, in get_package_layout
    pref_data = self._db.try_get_package(pref)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/db/cache_database.py", line 66, in try_get_package
    ref_data = self._packages.get(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/db/packages_table.py", line 66, in get
    raise ConanReferenceDoesNotExistInDB(f"No entry for package '{repr(pref)}'")
conans.errors.ConanReferenceDoesNotExistInDB: No entry for package 'aws-c-s3/0.1.37#d9922e5a296d5685900d275766754941%1696414613.251:421e2dc12c90b3fc8f7fd3a1c4dc3f988b4a4716#f98dfea306e1ffd356736bf50510fcd8%1696843414.044'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/cli/commands/install.py", line 70, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/api/subapi/install.py", line 21, in install_binaries
    installer.install(deps_graph, remotes)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conans/client/installer.py", line 249, in install
    self._download_bulk(install_order)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conans/client/installer.py", line 279, in _download_bulk
    thread_pool.map(self._download_pkg, downloads)
  File "/usr/lib/python3.11/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conans/client/installer.py", line 290, in _download_pkg
    self._remote_manager.get_package(node.pref, node.binary_remote)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conans/client/remote_manager.py", line 117, in get_package
    pkg_layout = self._cache.get_or_create_pkg_layout(pref)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conans/client/cache/cache.py", line 102, in get_or_create_pkg_layout
    return self._data_cache.get_or_create_pkg_layout(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 138, in get_or_create_pkg_layout
    self._db.create_package(package_path, pref, None)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/db/cache_database.py", line 73, in create_package
    self._packages.create(path, ref, build_id=build_id)
  File "/usr/lib/python3.11/lib/python3.11/site-packages/conan/internal/cache/db/packages_table.py", line 78, in create
    conn.execute(f'INSERT INTO {self.table_name} '
sqlite3.OperationalError: database is locked

ERROR: database is locked
```

**Comment by memsharded** [comment]
Hi @vient 

I think this is the same issue as reported in https://github.com/conan-io/conan/issues/13924, and recently reopened. It is not really a race condition, but a timeout in the DB (sqlite) that might happen under very heavy load of the system.

The current PR https://github.com/conan-io/conan/pull/14968 is doubling the timeout to 20 seconds, which already sounds very large, I hope it helps mitigating the issue. It seems that when the system is so overloaded, then things can start to degenerate, and no timeout large enough will really solve it, but lets see how 20 seconds work...

**Comment by vient** [comment]
Ok, closing as duplicate. I did not try to search for `database is locked` 🙂

**Comment by vient** [comment]
Reopening since `database is locked` was thrown during handling of exception, which is ConanReferenceDoesNotExistInDB. Seems to be a separate issue.

**Comment by vient** [comment]
Damn, and now I finally understand that it is indeed caused by that bug - it failed because of db issues exactly in ConanReferenceDoesNotExistInDB exception handler. Sorry for the spam, I'll just leave this issue for you to close 🙂

**Comment by memsharded** [comment]
Not a problem, yes it happens inside an ``except`` clause, but this was totally valid flow, Python uses exception flows more frequently than C++ and with more business logic, not only associated to hard errors.

Closing again, I think we can follow up in the other issue and PR, thanks again! 🙂

**Comment by vient** [comment]
Saw this bug two times again with latest version :(

Over a month I think, looks like it triggers less then before but the bug is still there.
