### ISSUE TITLE
[bug] ERROR: database is locked with `core.download:parallel` when pre-built packages are downloaded

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#15022]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: Visual Studio 2022
* Conan version: 2.0.13
* Python version: 3.11.1

### Steps to reproduce

1. set `core.download:parallel` to number of core of your CPU
2. put many recipes in your conanfile
3. call conan install such that you know that all packages will be downloaded from remote

It may or may not fail, it's not reproducible. More chance to happen with many packages.

### Logs

```
-------- Downloading 20 packages --------
Downloading binary packages in 8 parallel threads
clhep/2.4.1.3: Retrieving package 9bdee485ef71c14ac5f8a657202632bdb8b4482b from remote 'conancenter'
easylzma/0.0.7: Retrieving package f7dcd1cec4586c154a242a765a1de011300db8e2 from remote 'conancenter'
stb/cci.20230920: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter'
stringzilla/2.0.1: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter'
libmikmod/3.3.11.1: Retrieving package 14ab68c7be93df93d9bf07e9453293b8740ee13a from remote 'conancenter'
perfetto/38.0: Retrieving package 76d5cb5ba5268994580cd844541b6d03bf36f753 from remote 'conancenter'
octomap/1.9.8: Retrieving package 0087131052ed7f8b32329ef9e6e03279f48d1220 from remote 'conancenter'
tre/cci.20230717: Retrieving package f7dcd1cec4586c154a242a765a1de011300db8e2 from remote 'conancenter'
easylzma/0.0.7: Package installed f7dcd1cec4586c154a242a765a1de011300db8e2
easylzma/0.0.7: Downloaded package revision 3cf545445f4a20d83c4a32f9ea275795
xerces-c/3.2.4: Retrieving package 529b8de666f3bc1d3318cfd88a7258686ce2f7e2 from remote 'conancenter'
stringzilla/2.0.1: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
stringzilla/2.0.1: Downloaded package revision 640d390034990be1847c0b40fdfd1ba9
zstd/1.5.5: Retrieving package 8a6fcd7475ee0c70dffa0d381a7ff89fce5e3cf0 from remote 'conancenter'
clhep/2.4.1.3: Package installed 9bdee485ef71c14ac5f8a657202632bdb8b4482b
clhep/2.4.1.3: Downloaded package revision 3e287db22fedd3a00904e2c34f1b43ca
gmp/6.3.0: Retrieving package deeb86d617ccfdc956de72096fc3225aebe5b266 from remote 'conancenter'
perfetto/38.0: Package installed 76d5cb5ba5268994580cd844541b6d03bf36f753
perfetto/38.0: Downloaded package revision e7da4515f956b861b3d4db1708e0cc12
cfitsio/4.3.0: Retrieving package cb3f7ee173d812f3e5fbe8ce551e05c17e05d073 from remote 'conancenter'
octomap/1.9.8: Package installed 0087131052ed7f8b32329ef9e6e03279f48d1220
octomap/1.9.8: Downloaded package revision fd9b9320e3b6ae787bb0c712568b3141
frugally-deep/0.15.25-p0: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter'
onetbb/2021.10.0: Retrieving package 59da3f6b4490e510d683914a597e1abb82e0386f from remote 'conancenter'
tre/cci.20230717: Package installed f7dcd1cec4586c154a242a765a1de011300db8e2
tre/cci.20230717: Downloaded package revision b797db6232efb9c1e9949f5c8e786559
log4cxx/1.1.0: Retrieving package fbbf8c37d617e4990310d203308a27c7b14bd71c from remote 'conancenter'
libmikmod/3.3.11.1: Package installed 14ab68c7be93df93d9bf07e9453293b8740ee13a
libmikmod/3.3.11.1: Downloaded package revision 3656cd622fd5ae236ac1dc178e40c8e4
sdl_image/2.6.3: Retrieving package 8fc55889302327e1adff2ec78aaa5eefc0388622 from remote 'conancenter'
frugally-deep/0.15.25-p0: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
frugally-deep/0.15.25-p0: Downloaded package revision 90ab5fb98e968e2523c91459e6cabed3
vulkan-validationlayers/1.3.239.0: Retrieving package 8742a58a61cb59448ee9510d411212e229c4c59f from remote 'conancenter'
xerces-c/3.2.4: Package installed 529b8de666f3bc1d3318cfd88a7258686ce2f7e2
xerces-c/3.2.4: Downloaded package revision 539d86cf18e0d85a93d4fc985ba27323
qt/5.15.11: Retrieving package a2ff417d513f4e6b30bad272188a84593492f2e8 from remote 'conancenter'
zstd/1.5.5: Package installed 8a6fcd7475ee0c70dffa0d381a7ff89fce5e3cf0
zstd/1.5.5: Downloaded package revision 404d922913d3ffcc9136f6de5bde5dc6
libmediainfo/22.03: Retrieving package 00f436f22087e0ca7635cca3bea07131c7357c49 from remote 'conancenter'
gmp/6.3.0: Package installed deeb86d617ccfdc956de72096fc3225aebe5b266
gmp/6.3.0: Downloaded package revision c5d497c392ea453fb070f1e9319e68cf
netcdf/4.8.1: Retrieving package b578a6281bb1b3890dca8c90938e727c7cf9da55 from remote 'conancenter'
onetbb/2021.10.0: Package installed 59da3f6b4490e510d683914a597e1abb82e0386f
onetbb/2021.10.0: Downloaded package revision db25e7695a21647b3a9b86e61d45ca54
cfitsio/4.3.0: Package installed cb3f7ee173d812f3e5fbe8ce551e05c17e05d073
cfitsio/4.3.0: Downloaded package revision 8aeb1d0592e972a62a8d8aab417eb91f
vulkan-validationlayers/1.3.239.0: Downloading 12.0MB conan_package.tgz
sdl_image/2.6.3: Package installed 8fc55889302327e1adff2ec78aaa5eefc0388622
sdl_image/2.6.3: Downloaded package revision 230f8be63610c54d4fcb6baaa5560b7d
qt/5.15.11: Downloading 20.0MB conan_package.tgz
log4cxx/1.1.0: Package installed fbbf8c37d617e4990310d203308a27c7b14bd71c
log4cxx/1.1.0: Downloaded package revision 73796a28751c4cae948a476d16d824ff
netcdf/4.8.1: Package installed b578a6281bb1b3890dca8c90938e727c7cf9da55
netcdf/4.8.1: Downloaded package revision 86dadb9824c8d6a90d3ea9bbf4d4bb52
vulkan-validationlayers/1.3.239.0: Decompressing 12.0MB conan_package.tgz
libmediainfo/22.03: Package installed 00f436f22087e0ca7635cca3bea07131c7357c49
libmediainfo/22.03: Downloaded package revision ff7a2d09fcc4193939f0d45b2bf5a368
vulkan-validationlayers/1.3.239.0: Package installed 8742a58a61cb59448ee9510d411212e229c4c59f
vulkan-validationlayers/1.3.239.0: Downloaded package revision 598dde58f6356eb9417cac3abb5ef7c4
qt/5.15.11: Decompressing 20.0MB conan_package.tgz
qt/5.15.11: Package installed a2ff417d513f4e6b30bad272188a84593492f2e8
qt/5.15.11: Downloaded package revision 970fad73764f8dd37c726c9985faafe4
ERROR: Traceback (most recent call last):
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\cache.py", line 132, in get_or_create_pkg_layout
    return self.get_package_layout(pref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\cache.py", line 112, in get_package_layout
    pref_data = self._db.try_get_package(pref)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\db\cache_database.py", line 66, in try_get_package
    ref_data = self._packages.get(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\db\packages_table.py", line 66, in get
    raise ConanReferenceDoesNotExistInDB(f"No entry for package '{repr(pref)}'")
conans.errors.ConanReferenceDoesNotExistInDB: No entry for package 'stb/cci.20230920#efb9bf194ca7ce230d6dd59d434e6581%1696489933.565:da39a3ee5e6b4b0d3255bfef95601890afd80709#38d484ea5243a545747108b2f684b07c%1696490326.701'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\cli.py", line 272, in main
    cli.run(args)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\cli\commands\install.py", line 70, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\api\subapi\install.py", line 21, in install_binaries
    installer.install(deps_graph, remotes)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\installer.py", line 249, in install
    self._download_bulk(install_order)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\installer.py", line 279, in _download_bulk
    thread_pool.map(self._download_pkg, downloads)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\installer.py", line 290, in _download_pkg
    self._remote_manager.get_package(node.pref, node.binary_remote)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\remote_manager.py", line 117, in get_package
    pkg_layout = self._cache.get_or_create_pkg_layout(pref)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\cache\cache.py", line 102, in get_or_create_pkg_layout
    return self._data_cache.get_or_create_pkg_layout(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\cache.py", line 138, in get_or_create_pkg_layout
    self._db.create_package(package_path, pref, None)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\db\cache_database.py", line 73, in create_package
    self._packages.create(path, ref, build_id=build_id)
  File "C:\Users\spaceim\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\internal\cache\db\packages_table.py", line 78, in create
    conn.execute(f'INSERT INTO {self.table_name} '
sqlite3.OperationalError: database is locked

ERROR: database is locked
```

**Comment by memsharded** [comment]
Thanks for the report @SpaceIm 
Duplicated to https://github.com/conan-io/conan/issues/13924
