### ISSUE TITLE
[bug] CONAN_TRACE_FILE fails if points to the root directory (Windows, Conan 1.x)

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15049]
### Environment details

* Operating System+version: Windows 10
* Conan version: 1.61.0
* Python version: 3.8.10

### Steps to reproduce

The following log demonstrates the problem: 
```
D:\>set CONAN_TRACE_FILE=D:\conan_trace.log

D:\>conan --version
1.61.0

D:\>conan install zlib/1.2.13@ --build zlib
Traceback (most recent call last):
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\client\command.py", line 2216, in run
    method(args[0][1:])
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\client\command.py", line 547, in install
    info = self._conan.install_reference(ref,
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\client\conan_api.py", line 91, in wrapper
    log_command(f.__name__, kwargs)
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\util\tracer.py", line 155, in log_command
    _append_action("COMMAND", {"name": name, "parameters": parameters})
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\util\tracer.py", line 66, in _append_action
    _append_to_log(props)
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\conans\util\tracer.py", line 56, in _append_to_log
    with fasteners.InterProcessLock(filepath + ".lock", logger=logger):
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\fasteners\process_lock.py", line 157, in __enter__
    gotten = self.acquire()
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\fasteners\process_lock.py", line 135, in acquire
    self._do_open()
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\fasteners\process_lock.py", line 99, in _do_open
    made_basedir = _ensure_tree(basedir)
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\fasteners\process_lock.py", line 37, in _ensure_tree
    os.makedirs(path)
  File "c:\users\dbely\.pyenv\pyenv-win\versions\3.8.10\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: b'D:\\'

ERROR: [WinError 5] Access is denied: b'D:\\'
```
Of course, `D:\` is writable. Just discovered that non-root paths work:
```
D:\>set CONAN_TRACE_FILE=D:\subdir\conan_trace.log

D:\>conan install zlib/1.2.13@ --build zlib
(no error)
```

**Comment by memsharded** [comment]
Thanks for your report.

Yes, it makes sense that it is failing, Conan is trying to create the folder to contain the logs, otherwise the log file fails to be created. This can work for any folder, except the ``D:`` root one, that will fail to be created (even if it is marked with ``exists_ok``.

The problem is that this is failing inside the ``fasteners`` library, not Conan code, so this seems challenging to be fixed in Conan.
I'd suggest avoiding using D:/ as a folder for trace files, that would be problematic anyway if that location is being used by different Conan projects. Also, because Conan 2.0 no longer has this file, so this shouldn't be an issue.

**Comment by db4** [comment]
@memsharded 
As a simple workaround exists, it really isn't worth fixing.
