### ISSUE TITLE
[bug] Conan2: 'bool' object has no attribute 'dumps'

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#15059]
### Environment details

* Operating System+version: Windows 10
* Compiler+version:  Visual Studio 2019
* Conan version: 2.013
* Python version: 3.6.4

>conan profile show
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[conf]

>conan version
version: 2.0.13
python
  version: 3.6.4
  sys_version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]

### Steps to reproduce

I am trying to create my package on Windows:
conan create . --version 0.0.0
and get the following error:

ERROR: Traceback (most recent call last):
  File "g:\conan\venv_conan2\lib\site-packages\conan\cli\cli.py", line 272, in main
    cli.run(args)
  File "g:\conan\venv_conan2\lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "g:\conan\venv_conan2\lib\site-packages\conan\cli\command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
  File "g:\conan\venv_conan2\lib\site-packages\conan\cli\commands\create.py", line 93, in create
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "g:\conan\venv_conan2\lib\site-packages\conan\api\subapi\install.py", line 20, in install_binaries
    installer.install_system_requires(deps_graph)  # TODO: Optimize InstallGraph computation
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\installer.py", line 198, in install_system_requires
    install_graph = InstallGraph(graph)
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\graph\install_graph.py", line 205, in __init__
    self._initialize_deps_graph(deps_graph)
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\graph\install_graph.py", line 243, in _initialize_deps_graph
    self._nodes[node.ref] = _InstallRecipeReference.create(node)
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\graph\install_graph.py", line 123, in create
    result.add(node)
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\graph\install_graph.py", line 146, in add
    install_pkg_ref = _InstallPackageReference.create(node)
  File "g:\conan\venv_conan2\lib\site-packages\conans\client\graph\install_graph.py", line 53, in create
    result.options = node.conanfile.self_options.dumps().splitlines()
  File "g:\conan\venv_conan2\lib\site-packages\conans\model\options.py", line 258, in dumps
    dep_pkg_option = pkg_option.dumps(scope=pkg_pattern)
  File "g:\conan\venv_conan2\lib\site-packages\conans\model\options.py", line 111, in dumps
    dump = package_option.dumps(scope)
AttributeError: 'bool' object has no attribute 'dumps'

ERROR: 'bool' object has no attribute 'dumps'

It is all inside conan and I have no idea what could be wrong
I hope somebody could help.
Is it a problem with my recipe?

Thanks

**Comment by gouriano** [comment]
Ah, I see. I touch with my dirty hands private parts of Conan2. That is why...
