### ISSUE TITLE
[bug] conan 2.0.14 'no such column: lru' error running 'conan install'

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#15104]
### Environment details

For some reason, I'm not seeing this in a local macOS environment, even when I deleted the Conan cache, but it's very repeatable in macOS, Linux, and Windows GitHub Actions runner environments on Conan 2.0.14. It works fine with 2.0.13.

Linux
* Operating System+version: Ubuntu 20.04.6 LTS
* Compiler+version: gcc 9
* Conan version: 2.0.14
* Python version: 3.8.10

macOS
* Operating System+version: macOS 13.6
* Compiler+version: AppleClang 14
* Conan version: 2.0.14
* Python version: 3.11.6

Windows
* Operating System+version: Microsoft Windows Server 2022 10.0.20348
* Compiler+version: MSVC 193
* Conan version: 2.0.14
* Python version: 3.9.13

### Steps to reproduce

I think these are the key steps causing this:
1. `conan profile detect`
2. `conan install --require zlib/1.3 --build=missing`

In case it's not, here's all the code including the GitHub Actions CI you could fork, if needed:
https://github.com/ssrobins/sdl2-example/tree/troubleshoot_conan_error

### Logs

Linux
```
Run conan install --require zlib/1.3 --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
ERROR: Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/conan/cli/cli.py", line 2[7](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593034#step:17:8)2, in main
    cli.run(args)
  File "/home/runner/.local/lib/python3.[8](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593034#step:17:9)/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/runner/.local/lib/python3.8/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
  File "/home/runner/.local/lib/python3.8/site-packages/conan/cli/commands/install.py", line 62, in install
    deps_graph = gapi.load_graph_requires(args.requires, args.tool_requires, profile_host,
  File "/home/runner/.local/lib/python3.8/site-packages/conan/api/subapi/graph.py", line 131, in load_graph_requires
    deps_graph = self.load_graph(root_node, profile_host=profile_host,
  File "/home/runner/.local/lib/python3.8/site-packages/conan/api/subapi/graph.py", line 180, in load_graph
    deps_graph = builder.load_graph(root_node, profile_host, profile_build, lockfile)
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/graph_builder.py", line 51, in load_graph
    new_node = self._expand_require(require, node, dep_graph, profile_host,
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/graph_builder.py", line [9](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593034#step:17:10)0, in _expand_require
    new_node = self._create_new_node(node, require, graph, profile_host, profile_build,
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/graph_builder.py", line 262, in _create_new_node
    resolved = self._resolve_recipe(require.ref, graph_lock)
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/graph_builder.py", line 2[10](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593034#step:17:11), in _resolve_recipe
    result = self._proxy.get_recipe(ref, self._remotes, self._update, self._check_update)
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/proxy.py", line 23, in get_recipe
    resolved = self._get_recipe(ref, remotes, update, check_update)
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/graph/proxy.py", line 37, in _get_recipe
    recipe_layout = self._cache.recipe_layout(reference)
  File "/home/runner/.local/lib/python3.8/site-packages/conans/client/cache/cache.py", line 60, in recipe_layout
    return self._data_cache.get_recipe_layout(ref)
  File "/home/runner/.local/lib/python3.8/site-packages/conan/internal/cache/cache.py", line 97, in get_recipe_layout
    ref_data = self._db.get_latest_recipe(ref)
  File "/home/runner/.local/lib/python3.8/site-packages/conan/internal/cache/db/cache_database.py", line 77, in get_latest_recipe
    return self._recipes.get_latest_recipe(ref)
  File "/home/runner/.local/lib/python3.8/site-packages/conan/internal/cache/db/recipes_table.py", line [11](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593034#step:17:12)9, in get_latest_recipe
    r = conn.execute(query)
sqlite3.OperationalError: no such column: lru

ERROR: no such column: lru
Error: Process completed with exit code 7.
```

macOS
```
Run conan install --require zlib/1.3 --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu1[7](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593252#step:17:8)
compiler.libcxx=libc++
compiler.version=14
os=Macos

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos


======== Computing dependency graph ========
ERROR: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/cli/command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/cli/commands/install.py", line 62, in install
    deps_graph = gapi.load_graph_requires(args.requires, args.tool_requires, profile_host,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/api/subapi/graph.py", line 131, in load_graph_requires
    deps_graph = self.load_graph(root_node, profile_host=profile_host,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/api/subapi/graph.py", line 180, in load_graph
    deps_graph = builder.load_graph(root_node, profile_host, profile_build, lockfile)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/graph/graph_builder.py", line 51, in load_graph
    new_node = self._expand_require(require, node, dep_graph, profile_host,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/graph/graph_builder.py", line [9](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593252#step:17:10)0, in _expand_require
    new_node = self._create_new_node(node, require, graph, profile_host, profile_build,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/graph/graph_builder.py", line 262, in _create_new_node
    resolved = self._resolve_recipe(require.ref, graph_lock)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/graph/graph_builder.py", line 2[10](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593252#step:17:11), in _resolve_recipe
    result = self._proxy.get_recipe(ref, self._remotes, self._update, self._check_update)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.[11](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593252#step:17:12)/lib/python3.11/site-packages/conans/client/graph/proxy.py", line 23, in get_recipe
    resolved = self._get_recipe(ref, remotes, update, check_update)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/graph/proxy.py", line 37, in _get_recipe
    recipe_layout = self._cache.recipe_layout(reference)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conans/client/cache/cache.py", line 60, in recipe_layout
    return self._data_cache.get_recipe_layout(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/internal/cache/cache.py", line 97, in get_recipe_layout
    ref_data = self._db.get_latest_recipe(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/internal/cache/db/cache_database.py", line 77, in get_latest_recipe
    return self._recipes.get_latest_recipe(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/conan/internal/cache/db/recipes_table.py", line 1[19](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593252#step:17:20), in get_latest_recipe
    r = conn.execute(query)
        ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: lru

ERROR: no such column: lru
Error: Process completed with exit code 7.
```

Windows
```
Run conan install --require zlib/1.3 --build=missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
ERROR: Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\cli\cli.py", line 2[7](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593510#step:17:8)2, in main
    cli.run(args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\cli\command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\cli\commands\install.py", line 62, in install
    deps_graph = gapi.load_graph_requires(args.requires, args.tool_requires, profile_host,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\api\subapi\graph.py", line 131, in load_graph_requires
    deps_graph = self.load_graph(root_node, profile_host=profile_host,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\api\subapi\graph.py", line 1[8](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593510#step:17:9)0, in load_graph
    deps_graph = builder.load_graph(root_node, profile_host, profile_build, lockfile)
  File "C:\hostedtoolcache\windows\Python\3.[9](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593510#step:17:10).13\x64\lib\site-packages\conans\client\graph\graph_builder.py", line 51, in load_graph
    new_node = self._expand_require(require, node, dep_graph, profile_host,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\graph\graph_builder.py", line 90, in _expand_require
    new_node = self._create_new_node(node, require, graph, profile_host, profile_build,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\graph\graph_builder.py", line 262, in _create_new_node
    resolved = self._resolve_recipe(require.ref, graph_lock)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\graph\graph_builder.py", line 2[10](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593510#step:17:11), in _resolve_recipe
    result = self._proxy.get_recipe(ref, self._remotes, self._update, self._check_update)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\graph\proxy.py", line 23, in get_recipe
    resolved = self._get_recipe(ref, remotes, update, check_update)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\graph\proxy.py", line 37, in _get_recipe
    recipe_layout = self._cache.recipe_layout(reference)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\cache\cache.py", line 60, in recipe_layout
    return self._data_cache.get_recipe_layout(ref)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\internal\cache\cache.py", line 97, in get_recipe_layout
    ref_data = self._db.get_latest_recipe(ref)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\internal\cache\db\cache_database.py", line 77, in get_latest_recipe
    return self._recipes.get_latest_recipe(ref)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\internal\cache\db\recipes_table.py", line [11](https://github.com/ssrobins/sdl2-example/actions/runs/6874606896/job/18696593510#step:17:12)9, in get_latest_recipe
    r = conn.execute(query)
sqlite3.OperationalError: no such column: lru

ERROR: no such column: lru
Error: Process completed with exit code 1.
```

**Comment by memsharded** [comment]
Hi @ssrobins 

Thanks for your report.
This seems an unexpected side effect of reusing the cache storage but not the home in the Github actions.
The Conan client migration system uses a ``version.txt`` that is in the Conan home, not inside the package storage. Migrations happen when this version doesn't match the current client version. Conan 2.0.13 also introduced back-migrations to be able to go back to 2.0.13 after a successful migration to 2.0.14

So the problem could be in your Github-caching of the Conan-package storage in your Github actions:
```
 path: ~/.conan2/p
```

I think this could be easily solved by caching the ``path: ~/.conan2`` Conan home instead, that will contain the right ``version.txt``. 

Otherwise, if you only cache the package storage, the migration will only move forward, and will expect to only use 2.0.14 from that moment, not possible to mix different Conan versions using the same cached package storage.

Please let us know if that helps.

**Comment by ssrobins** [comment]
Yeah, thanks for looking into this, I confirmed it's cache-related. Sorry for not checking that before posting. Closing....

**Comment by memsharded** [comment]
> Yeah, thanks for looking into this, I confirmed it's cache-related. Sorry for not checking that before posting. Closing..

No prob, it is also something that was not considered in the migrations design, as it is mostly assumed a 1:1 relation between the home and the package storage, it was difficult to foresee this issue. We might consider it in the future now for possible migrations, thanks very much for the feedback anyway, it is always useful, don't stop sending it! 🙂
