### ISSUE TITLE
[bug] `conan profile show` crashes when requesting json output if profile contains a reference.

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#15183]
### Environment details

* Operating System+version: macOS 12.6
* Conan version: 2.0.14
* Python version: 3.11.4

### Steps to reproduce

Issuing `conan profile show -pr:h ourprofile`, we get:

```
[settings]
arch=x86_64
...
os.version=10.13
[tool_requires]
*: cmake/3.27.7
[conf]
tools.apple:enable_visibility=False
```

Yet, if we request the output as Json format (in order to be able to parse to output with `jq`, [as advised here](https://github.com/conan-io/conan/issues/13654#issuecomment-1517973377)), conan crashes with:

    ERROR: Object of type RecipeReference is not JSON serializable

If we remove the `tool_requires` section of our profile, the json output works as expected.

### Logs

ERROR: Traceback (most recent call last):
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/command.py", line 141, in run
    sub.run(conan_api, parser, *args)
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/command.py", line 157, in run
    self._format(parent_parser, info, *args)
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/command.py", line 94, in _format
    formatter(info)
  File "/Users/someguy/MigrationConan2/env/lib/python3.11/site-packages/conan/cli/commands/profile.py", line 30, in json_profiles
    cli_out_write(json.dumps(result))
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RecipeReference is not JSON serializable

**Comment by AbrilRBS** [comment]
Hi @Adnn thanks a lot for taking the time to report the issue.

I've proposed https://github.com/conan-io/conan/pull/15185 to fix it for the next 2.0.15 release, I still need to check with the team about the serialization of the reference itself or whether just outputting the string representation would be enough :)
