### ISSUE TITLE
[bug] conan cache save fails to save to a directory that doesn't exist

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#15362]
### Environment details

* Operating System+version: Arch Linux
* Compiler+version: clang 16
* Conan version: 2.0.16
* Python version: 3.11.1

### Steps to reproduce

1. `conan install --requires zlib/1.2.13`
2. `conan cache save "zlib/1.2.13" --file package/zlib.tgz`

Observe that provided the `package` directory doesn't already exist, conan fails to create the directory and place the `tgz` file there.

### Logs

```
$ conan install --requires "zlib/1.2.13"

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=16
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/clang', 'cpp': '/usr/bin/clang++'}

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=16
os=Linux
[conf]
tools.build:compiler_executables={'c': '/usr/bin/clang', 'cpp': '/usr/bin/clang++'}


======== Computing dependency graph ========
Graph root
    cli
Requirements
    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.2.13#e377bee636333ae348d51ca90874e353:0d992ed9f90f1c38fd1c3eac3fccc60c755490e2#a36fa1dae2f25f076d6ff135a01dad5b - Cache

======== Installing packages ========
zlib/1.2.13: Already installed! (1 of 1)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: zlib/1.2.13

======== Finalizing install (deploy, generators) ========
cli: Generating aggregated env files
cli: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully

$ conan cache save "zlib/1.2.13" --file package/zlib.tgz
ERROR: Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/command.py", line 141, in run
    sub.run(conan_api, parser, *args)
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/command.py", line 155, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/commands/cache.py", line 133, in cache_save
    conan_api.cache.save(package_list, tgz_path)
  File "/home/user/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/api/subapi/cache.py", line 117, in save
    with open(tgz_path, "wb") as tgz_handle:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/conan-cache-test/package/zlib.tgz'

ERROR: [Errno 2] No such file or directory: '/tmp/conan-cache-test/package/zlib.tgz'
```

**Comment by memsharded** [comment]
Thanks for the report @samuel-emrys 

Indeed, it seems the command assumes the folder exists, but this could be easily change by doing a ``mkdir(os.path.dirname(path))`` before the ``save()``, would you like to submit a PR yourself to the ``release/2.0`` branch? If not don't worry, we will fix it ourselves. Thanks!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15409 for next 2.0.17
