### ISSUE TITLE
[bug] conan upload raises error if no metadata is present for recipe

### ISSUE THREAD

**Issue by lhocmf** [conan-io/conan#15540]
### Environment details

* Operating System+version: Windows 10, Windows Server 2019
* Compiler+version: MSVC 19.38.33133
* Conan version: 2.0.17
* Python version: 3.12.1

### Steps to reproduce

1. Have a recipe (e.g. for `pkg/version`)
2. `conan export` it (`conan export .`)
3. `conan upload` it to a remote (`conan upload --remote <our_remote> --recipe-only --confirm pkg/version@#rrev`)

Expected behavior: Upload completes, `conan upload` returns 0 as exit code
Observed behavior: Upload of the recipe completes, but conan raises a `FileNotFoundError` afterwards, thus returning a non-zero exit code.

Note: `core.sources:download_cache` is set to `C:\conan_cache\sources` for the snippet below

### Logs

```
-------- Checking server existing packages --------
pkg/version: Checking which revisions exist in the remote server
Please log in to "staging" to perform this action. Execute "conan remote login" command.
Got username **** from environment
Got password '******' from environment

-------- Preparing artifacts for upload --------
pkg/version: Compressing conan_export.tgz

-------- Uploading artifacts --------
Uploading recipe 'pkg/version#aae6e4753df992755ac63ebb23dc0d0b'
Upload complete

ERROR: Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\conan\cli\cli.py", line 280, in main
    cli.run(args)
  File "C:\Python312\Lib\site-packages\conan\cli\cli.py", line 190, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\Python312\Lib\site-packages\conan\cli\command.py", line 126, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\conan\cli\commands\upload.py", line 109, in upload
    backup_files = conan_api.upload.get_backup_sources(package_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\conan\api\subapi\upload.py", line 69, in get_backup_sources
    return download_cache.get_backup_sources_files_to_upload(excluded_urls, package_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\conans\client\downloaders\download_cache.py", line 81, in get_backup_sources_files_to_upload
    metadata = json.loads(load(metadata_path))
                          ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\conans\util\files.py", line 130, in load
    with open(path, 'r', encoding=encoding, newline="") as handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\conan_cache\\sources\\s\\ab5174b9b5c6236588e15a1aa1aaecb6658cdbe09501c7981ac8db276a24d9ab.dirty.json'

ERROR: [Errno 2] No such file or directory: 'C:\\conan_cache\\sources\\s\\ab5174b9b5c6236588e15a1aa1aaecb6658cdbe09501c7981ac8db276a24d9ab.dirty.json'
```

**Comment by AbrilRBS** [comment]
Hi! Thanks a lot for taking the time to report this issue :)

This has already been fixed in https://github.com/conan-io/conan/pull/15501 for the next 2.1 release, to be published in the next few weeks :)

**Comment by lhocmf** [comment]
Ah, thanks. Somehow I must have missed that during my prior search for similar issues.
