### ISSUE TITLE
[bug] Conan fails to install some packages that are available in the cache when the network is disabled

### ISSUE THREAD

**Issue by realbogart** [conan-io/conan#15739]
### Environment details

* Operating System+version: Tested on Windows 11 and Linux
* Conan version: Tested on  2.1 and 2.0.16
* Python version: Tested on 3.11.7, 3.10.2 and 3.10.12

Trying to install certain packages that are available in the cache fails when the network is disabled.

### Steps to reproduce

1. Run the following command with the network enabled:
```conan install --requires libcurl/7.87.0@#3fa5ead82de3d84eb3bf43078a69c69b -pr:a <some_profile> -c tools.graph:skip_binaries=False -vvv```

Replace <some_profile> with a real profile. Running this should install `libcurl` in your cache.

2. Disable your network and run the same command again.

Expected result: The install succeeds.
Actual result: The install fails. (See log output)

### Logs

```

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.runtime=static
compiler.runtime_type=Debug
compiler.version=14
os=Linux
os_build=Linux
os_target=Linux
llvm/10*:compiler.cppstd=14
dxc*:build_type=Release
llvm*:build_type=Release
llvm*:compiler.runtime=static
llvm*:compiler.runtime_type=Release
[options]
*:BuildConfiguration=Debug
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.graph:skip_binaries=False
[buildenv]
CC=/usr/bin/clang
CXX=/usr/bin/clang++

Profile build:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.runtime=static
compiler.runtime_type=Debug
compiler.version=14
os=Linux
os_build=Linux
os_target=Linux
llvm/10*:compiler.cppstd=14
dxc*:build_type=Release
llvm*:build_type=Release
llvm*:compiler.runtime=static
llvm*:compiler.runtime_type=Release
[options]
*:BuildConfiguration=Debug
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
[buildenv]
CC=/usr/bin/clang
CXX=/usr/bin/clang++


======== Computing dependency graph ========
Graph root
    cli
Requirements
    libcurl/7.87.0#3fa5ead82de3d84eb3bf43078a69c69b - Cache
    openssl/3.1.0#25925a18588e030e406a15da96c4d32b - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    autoconf/2.71#f4e2bd681d49b4b80761aa587bde94d5 - Cache
    automake/1.16.5#891f585a736bce951cc0e7109aa5ffee - Cache
    gnu-config/cci.20210814#dc430d754f465e8c74463019672fb97b - Cache
    libtool/2.4.7#d55a3c2435c19e830fa77aa5c6c19350 - Cache
    m4/1.4.19#b38ced39a01e31fef5435bc634461fd2 - Cache
    meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
    pkgconf/1.9.3#3e658ebc066dc868a1f8a472c1065368 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.1.0

======== Computing necessary packages ========
ERROR: Failed checking for binary 'gnu-config/cci.20210814:da39a3ee5e6b4b0d3255bfef95601890afd80709' in remote 'artifactory-local': remote not available
Traceback (most recent call last):
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ffff54a2090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='artifactory.build.paradox-interactive.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffff54a2090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/remote_manager.py", line 238, in _call_remote
    return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/auth_manager.py", line 41, in call_rest_api_method
    ret = getattr(rest_client, method_name)(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/rest_client.py", line 130, in get_latest_package_reference
    return self._get_api().get_latest_package_reference(pref, headers=headers)
           ^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/rest_client.py", line 51, in _get_api
    revisions = self._capable(REVISIONS)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/rest_client.py", line 46, in _capable
    capabilities = tmp.server_capabilities(user, password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/rest_client_common.py", line 143, in server_capabilities
    ret = self.requester.get(url, auth=auth, headers=self.custom_headers, verify=self.verify_ssl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/conan_requester.py", line 152, in get
    return self._call_method("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/rest/conan_requester.py", line 176, in _call_method
    tmp = getattr(self._http_requester, method)(url, **all_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='artifactory.build.paradox-interactive.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffff54a2090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conan/cli/cli.py", line 191, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conan/cli/command.py", line 142, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conan/cli/commands/install.py", line 68, in install
    gapi.analyze_binaries(deps_graph, args.build, remotes, update=args.update, lockfile=lockfile)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conan/api/subapi/graph.py", line 201, in analyze_binaries
    binaries_analyzer.evaluate_graph(graph, build_mode, lockfile, remotes, update,
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/graph/graph_binaries.py", line 371, in evaluate_graph
    self._evaluate_node(node, build_mode, remotes, update)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/graph/graph_binaries.py", line 163, in _evaluate_node
    self._process_node(node, build_mode, remotes, update)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/graph/graph_binaries.py", line 222, in _process_node
    self._evaluate_download(node, remotes, update)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/graph/graph_binaries.py", line 288, in _evaluate_download
    self._get_package_from_remotes(node, remotes, update)
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/graph/graph_binaries.py", line 62, in _get_package_from_remotes
    latest_pref = self._remote_manager.get_latest_package_reference(pref, r, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/remote_manager.py", line 222, in get_latest_package_reference
    return self._call_remote(remote, "get_latest_package_reference", pref, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johan/.local/share/virtualenvs/conan-bug-b2_v7R5D/lib/python3.11/site-packages/conans/client/remote_manager.py", line 240, in _call_remote
    raise ConanConnectionError(("%s\n\nUnable to connect to remote %s=%s\n"
conans.errors.ConanConnectionError: HTTPSConnectionPool(host='artifactory.build.paradox-interactive.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffff54a2090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Unable to connect to remote artifactory-local=https://artifactory.build.paradox-interactive.com/artifactory/api/conan/conan-local
1. Make sure the remote is reachable or,
2. Disable it with 'conan remote disable <remote>' or,
3. Use the '-nr/--no-remote' argument
Then try again.

ERROR: HTTPSConnectionPool(host='artifactory.build.paradox-interactive.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffff54a2090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Unable to connect to remote artifactory-local=https://artifactory.build.paradox-interactive.com/artifactory/api/conan/conan-local
1. Make sure the remote is reachable or,
2. Disable it with 'conan remote disable <remote>' or,
3. Use the '-nr/--no-remote' argument
Then try again.

```

**Comment by memsharded** [comment]
Thanks for your detailed report @realbogart 

```
conan install --requires libcurl/7.87.0@#3fa5ead82de3d84eb3bf43078a69c69b -pr:a <some_profile> -c tools.graph:skip_binaries=False -vvv
```

This is failing for me, there are no precompiled binaries, need to add ``--build=missing``?

Then it is confusing, because the report says ``Tested on Windows 11``, but then the profiles are Linux profiles, not Windows. So if I am testing in Windows with a windows compatible profile, I don't even get the same dependencies. Maybe you could clarify? Thanks!

**Comment by realbogart** [comment]
@memsharded  We have an Artifactory instance and have built and uploaded binaries for these profiles. So in our case it works the same for Linux and Windows because it first just downloads the binary from our Artifactory.

Edit: So to clarify further: I am able to run the command with the Linux profile on Windows and it works when the network is enabled.

**Comment by memsharded** [comment]
Ok, got it.

It seems you are missing ``-c:a tools.graph:skip_binaries=False``, to make sure that both host and build requirements are not skipped and downloaded. With ``-c tools....`` only the "host" requirements are forced to be downloaded.

Please try that and let us know.

**Comment by realbogart** [comment]
That solved it! Changing from `-c tools.graph:skip_binaries=False` to `-c:a tools.graph:skip_binaries=False` downloaded the extra dependencies and it succeded with the network disabled.

I'm curious. What are these binaries that were skipped and why did they need the network?

Thank you!

Edit: What I mean with my question: If the binaries are skipped when the network is on, then why is the network needed at all when running the command?

**Comment by memsharded** [comment]
> I'm curious. What are these binaries that were skipped and why did they need the network?
> Edit: What I mean with my question: If the binaries are skipped when the network is on, then why is the network needed at all when running the command?

This is a great question.

There is a difference in knowing that you can skip the binaries and don't need to download them and not even knowing if that binary exist in the server. 
The logic goes like this:

- First, Conan builds the full "recipes" graph, with conanfiles and its versions. Still it doesn't know the ``package_id`` of each node in the graph.
- Then, the computation of ``package_id`` happens. As binaries are affected by their dependencies, it is necessary to compute first from the top of the graph (those packages without any dependencies), and move down the graph. Only when a package knows all of its dependencies ``package_ids`` can compute its own ``package_id``.
- Even build-requires can affect the ``package_id`` of consumers, even if it is not the default, it can be done. Packages in the "build" context that are required with regular ``requires = "openssl/..."`` will definitely affect their consumers ``package_id``.
- Conan checks first if a binary is in the cache, if not it will look in the servers. If found in the server, it knows its ``package_id``, and uses that to compute its dependants ``package_ids``.
- At the end of the computation of ``package_id``, every node in the graph has its own ``package_id``, and a label saying ``Cache``, ``Download``, ``Build``, ``Update``, ``Missing``(and an associated remote in case of download/update), depending the location of that package.
- Now Conan can "optimize". If there are some nodes in the graph that are not needed, because their dependencies already have existing binaries, no need to build them, and the transitive dep is not needed, Conan can deduce it can be ``Skip`` and avoid downloading it

This is the basic flow. It could be argued that we could always use the computed ``package_id`` of one dependency whether it is found or not in the remote, even if it is ``Missing``. But then the compatibility kicks in, via both ``compatibility()`` recipe method and ``compatibility.py`` plugin. If at some point Conan is looking for a binary, and it is not found anywhere, it can fallback to use a compatible binary (with a different ``package_id``). This is great to avoid building excessive number of binaries when we know it is not necessary because ABI compatibility is good. But using a different binary with a different ``package_id`` will also change the dependants ``package_ids``, and that will result in a different evaluation of what needs to be built, downloaded or used as-is from the cache.

A full solution to this problem would involve a full backtracking algorithm, that is able to compute things with certain hypothesis, evaluate the ``Skip``, and then backtrack and re-evaluate as necessary if the hypothesis are not satisfied. This can be both very complex in implementation (compounded over time with maintenance, bugfixes, etc) and also quite slow in execution time in practice.

**Comment by realbogart** [comment]
@memsharded , thank you for that very detailed answer! I will close this issue with this comment. Thank you again for your help!

**Comment by memsharded** [comment]
Thanks for the feedback @realbogart, very appreciated!
