### ISSUE TITLE
Migration: remove conan.conf manually but generated one is STILL too old

### ISSUE THREAD

**Issue by arnemertz** [conan-io/conan#1578]
I upgraded my Conan installation on a VM after several months, and now I get the following error message every time I try to use it:

    ERROR: Migration: Your Conan version was too old, please, remove the conan.conf file manually, Conan will generate a new one.

Seems easy to fix, but removing it results in a newly generated conan.conf that is **still** too old, at least the message reappears every time. 

Content of conan.conf (the generated one):

```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
# trace_file =              # environment CONAN_TRACE_FILE
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
# bash_path = ""                      # environment CONAN_BASH_PATH (only windows)
# recipe_linter = False               # environment CONAN_RECIPE_LINTER

# cmake_generator                     # environment CONAN_CMAKE_GENERATOR
# http://www.vtk.org/Wiki/CMake_Cross_Compiling
# cmake_toolchain_file                # environment CONAN_CMAKE_TOOLCHAIN_FILE
# cmake_system_name                   # environment CONAN_CMAKE_SYSTEM_NAME
# cmake_system_version                # environment CONAN_CMAKE_SYSTEM_VERSION
# cmake_system_processor              # environment CONAN_CMAKE_SYSTEM_PROCESSOR
# cmake_find_root_path                # environment CONAN_CMAKE_FIND_ROOT_PATH
# cmake_find_root_path_mode_program   # environment CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM
# cmake_find_root_path_mode_library   # environment CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY
# cmake_find_root_path_mode_include   # environment CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE

# cpu_count = 1             # environment CONAN_CPU_COUNT


[storage]
# This is the default path, but you can write your own
path = ~/.conan/data

[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
# http = http://user:pass@10.10.1.10:3128/
# http = http://10.10.1.10:3128
# https = http://10.10.1.10:1080


# Default settings now declared in the default profile 
```

Stack trace: 
```
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 922, in main
    conan_api = Conan.factory()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 114, in factory
    client_cache = migrate_and_get_client_cache(user_folder, out)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 700, in migrate_and_get_client_cache
    migrator.migrate()
  File "/usr/local/lib/python2.7/dist-packages/conans/migrations.py", line 23, in migrate
    self._make_migrations(old_version)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/migrations.py", line 85, in _make_migrations
    "a new one." % CONAN_CONF)
conans.errors.ConanException: Migration: Your Conan version was too old, please, remove the conan.conf file manually, Conan will generate a new one.
```

**Comment by arnemertz** [comment]
It seems that the migrator only checks the old version and then assumes that conan.conf is outdated if it exists. The problem is that this happens after conan.conf gets created:
When I delete conan.conf and restrict write permissions, I get the following stack trace:

```
ERROR: [Errno 13] Permission denied: '/home/vagrant/.conan/conan.conf'
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 922, in main
    conan_api = Conan.factory()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 114, in factory
    client_cache = migrate_and_get_client_cache(user_folder, out)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 696, in migrate_and_get_client_cache
    client_cache = ClientCache(base_folder, storage_folder, out)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/client_cache.py", line 35, in __init__
    self._store_folder = store_folder or self.conan_config.storage_path or self.conan_folder
  File "/usr/local/lib/python2.7/dist-packages/conans/client/client_cache.py", line 73, in conan_config
    generate_default_config_file()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/client_cache.py", line 69, in generate_default_config_file
    save(self.conan_conf_path, normalize(default_client_conf))
  File "/usr/local/lib/python2.7/dist-packages/conans/util/files.py", line 86, in save
    with open(path, mode) as handle:
IOError: [Errno 13] Permission denied: '/home/vagrant/.conan/conan.conf'
```
conan_api.py", line 696 where the client cache is created happens before the migrator in line 700 (version 0.25.1)

**Comment by lasote** [comment]
Wow, such a mess. Try to remove the **~/.conan/conan.conf**, **~/.conan/version.txt**, and the **settings.yml**. It should generate a fresh configuration.

**Comment by arnemertz** [comment]
I managed for now by replacing the exception with a warning for one `conan --version` call ;-)
