### ISSUE TITLE
[bug] Double call of `conan lock create` may leads to generating bad lock file

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#15986]
### Describe the bug

Conan version: 2.0.17

Hi!

I tried to discover how to work with lock files and found some bug. If try to generate lock file twice with `--lockfile-packages` option and some specific settings, then you can get bad lock file.

```python
from conan import ConanFile


class RtcryptConanfile(ConanFile):
    settings = "os", "compiler", "arch", "build_type"

    def build_requirements(self):
            self.requires("zlib/1.3.1")
```

```console
$ conan remove -c '*'
$ rm -rf conan.lock
$ conan lock create -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ --lockfile-packages .
======== Computing dependency graph ========
zlib/1.3.1: Not found in local cache, looking in remotes...
zlib/1.3.1: Checking remote: rutoken
zlib/1.3.1: Checking remote: conancenter
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/test/conanfile.py
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)

======== Computing necessary packages ========
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - Download (conancenter)
Generated lockfile: /Users/lo1ol/Documents/work/test/conan.lock

$ cat conan.lock
{
    "version": "0.5",
    "requires": [
        [
            "zlib/1.3.1#f52e03ae3d251dec704634230cd806a2%1708593606.497",
            {
                "b647c43bfefae3f830561ca202b6cfd935b56205": "6b307bbcbae23635c4006543ffdbf3ef"
            }
        ]
    ],
    "build_requires": [],
    "python_requires": []
}

$ conan lock create -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ --lockfile-packages .
Using lockfile: '/Users/lo1ol/Documents/work/test/conan.lock'

======== Computing dependency graph ========
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/test/conanfile.py
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - None
Generated lockfile: /Users/lo1ol/Documents/work/test/conan.lock

$ cat conan.lock
{
    "version": "0.5",
    "requires": [
        "zlib/1.3.1#f52e03ae3d251dec704634230cd806a2%1708593606.497"
    ],
    "build_requires": [],
    "python_requires": []
}
```

Originally I faced with this problem, when try to use this lock file inside `install` command:

```console
$ conan remove -c "*" && \
> rm -rf conan.lock && \
> conan lock create . -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ --lockfile-packages && \
> conan install -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ . -l conan.lock
Remove summary:
Local Cache
  zlib/1.3.1#f52e03ae3d251dec704634230cd806a2: Removed recipe and all binaries

======== Computing dependency graph ========
zlib/1.3.1: Not found in local cache, looking in remotes...
zlib/1.3.1: Checking remote: rutoken
zlib/1.3.1: Checking remote: conancenter
zlib/1.3.1: Downloaded recipe revision f52e03ae3d251dec704634230cd806a2
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/test/conanfile.py
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (conancenter)

======== Computing necessary packages ========
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - Download (conancenter)
Generated lockfile: /Users/lo1ol/Documents/work/test/conan.lock
Using lockfile: '/Users/lo1ol/Documents/work/test/conan.lock'

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]



======== Computing dependency graph ========
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/test/conanfile.py
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Cache

======== Computing necessary packages ========
Requirements
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#6b307bbcbae23635c4006543ffdbf3ef - None

======== Installing packages ========
ERROR: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/conan/cli/cli.py", line 280, in main
    cli.run(args)
  File "/opt/homebrew/lib/python3.12/site-packages/conan/cli/cli.py", line 190, in run
    command.run(self._conan_api, args[0][1:])
  File "/opt/homebrew/lib/python3.12/site-packages/conan/cli/command.py", line 126, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/conan/cli/commands/install.py", line 73, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "/opt/homebrew/lib/python3.12/site-packages/conan/api/subapi/install.py", line 21, in install_binaries
    installer.install(deps_graph, remotes)
  File "/opt/homebrew/lib/python3.12/site-packages/conans/client/installer.py", line 258, in install
    self._handle_package(package, install_reference, handled_count, package_count)
  File "/opt/homebrew/lib/python3.12/site-packages/conans/client/installer.py", line 304, in _handle_package
    assert package.binary in (BINARY_CACHE, BINARY_BUILD, BINARY_DOWNLOAD, BINARY_UPDATE)
AssertionError

ERROR:
```

### How to reproduce it

```bash
cat <<EOF > conanfile.py
from conan import ConanFile

class RtcryptConanfile(ConanFile):
    settings = "os", "compiler", "arch", "build_type"

    def build_requirements(self):
            self.requires("zlib/1.3.1")
EOF

cat <<EOF > script.sh
pip3 install conan==2.0.17

conan profile detect
conan lock create . -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ --lockfile-packages
conan install -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++ . -l conan.lock
EOF

docker run --rm --workdir=/workdir --volume "$PWD:/workdir" python bash script.sh
```

**Comment by lo1ol** [comment]
On conan 2.2.2 behaviour is the same

**Comment by memsharded** [comment]
Hi @lo1ol 

Thanks for your report.

If you use ``--lockfile-packages`` in any command you should see:
```
$  conan install ... --lockfile-packages
ERROR: The --lockfile-packages arg is private and shouldn't be used
```

The argument is also not in the documentation. Please do not use this argument, it is expected to fail, it will be eventually removed completely too.

**Comment by lo1ol** [comment]
Thank you for answer and sorry for late question (I went to vocation). If option `--lockfile-packages` is deprecated, so how to lock binary packages?

**Comment by memsharded** [comment]
> Thank you for answer and sorry for late question (I went to vocation). If option --lockfile-packages is deprecated, so how to lock binary packages?

It is not necessary. All the information to lock something is already encoded in the recipe revisions and the configuration, and that  results in obtaining the same ``package_id``, as it is a pure function of those inputs.

If you are talking about package-revisions, please check: https://docs.conan.io/2/tutorial/versioning/revisions.html#package-revisions. More than 1 package revisions shouldn't happen for the same recipe_revision+package_id, and lockfiles do not support locking a specific package revision if there exist more than one, as that is considered a model or process error, not something that Conan should handle.

**Comment by lo1ol** [comment]
I'm not sure that conan saves info about binary packages without `--lockfile-packages`: For example, I get the same output for different profiles:

```console
conan lock create -pr glibc-x86_64-gcc13 -s build_type=Debug --lockfile-out  conan13.lock . -u
rutokenconanfile/0.35@rutoken/stable: Checking remote: rutoken

======== Computing dependency graph ========
zlib/v1.3-3d1449b@rutoken/stable: Checking remote: rutoken
rutokenconanfile/0.35@rutoken/stable: Checking remote: rutoken
libcbor/v0.10.2-17ce8b9@rutoken/stable: Checking remote: rutoken
openssl/3.0.8-65b5a78@rutoken/stable: Checking remote: rutoken
libudev/1.5.0@rutoken/stable: Checking remote: rutoken
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/libfido2/conanfile.py
Requirements
    libcbor/v0.10.2-17ce8b9@rutoken/stable#f148d89eb98d0ad48c4f08aa7beedd8a - Cache (rutoken)
    libudev/1.5.0@rutoken/stable#d55ee708c9eea62934b77663172d2c56 - Cache (rutoken)
    openssl/3.0.8-65b5a78@rutoken/stable#3700470fc765c9a25afb8a792ec45b82 - Cache (rutoken)
    zlib/v1.3-3d1449b@rutoken/stable#7d00412ea2fe7086b799148ac77418ad - Cache (rutoken)
Python requires
    rutokenconanfile/0.35@rutoken/stable#e3c87d2e6fd0ee6fdb44ce344f036ba9 - Cache (rutoken)

======== Computing necessary packages ========
libcbor/v0.10.2-17ce8b9@rutoken/stable: Checking 31 compatible configurations
libcbor/v0.10.2-17ce8b9@rutoken/stable: '54fac0cfb8a344573d37fd4b895cb6ad6d623561': build_type=Release
libcbor/v0.10.2-17ce8b9@rutoken/stable: Main binary package 'e706d592022f7ab1d5acc493e2afff2f9fffe977' missing. Using compatible package '54fac0cfb8a344573d37fd4b895cb6ad6d623561': build_type=Release
libudev/1.5.0@rutoken/stable: Current package revision is newer than the remote one
openssl/3.0.8-65b5a78@rutoken/stable: Checking 31 compatible configurations
openssl/3.0.8-65b5a78@rutoken/stable: '1028ef5306e87e9740dc8d9a52c6285783614e6a': build_type=Release
openssl/3.0.8-65b5a78@rutoken/stable: Main binary package '8f9231c19a3d35ff07d372ec8e6ece109e1d0468' missing. Using compatible package '1028ef5306e87e9740dc8d9a52c6285783614e6a': build_type=Release
zlib/v1.3-3d1449b@rutoken/stable: Checking 31 compatible configurations
zlib/v1.3-3d1449b@rutoken/stable: '54fac0cfb8a344573d37fd4b895cb6ad6d623561': build_type=Release
zlib/v1.3-3d1449b@rutoken/stable: Main binary package 'e706d592022f7ab1d5acc493e2afff2f9fffe977' missing. Using compatible package '54fac0cfb8a344573d37fd4b895cb6ad6d623561': build_type=Release
Requirements
    libcbor/v0.10.2-17ce8b9@rutoken/stable#f148d89eb98d0ad48c4f08aa7beedd8a:54fac0cfb8a344573d37fd4b895cb6ad6d623561#55cac7deebb270f831051a2f29deded2 - Download (rutoken)
    libudev/1.5.0@rutoken/stable#d55ee708c9eea62934b77663172d2c56:ff47581be5225eed65b4a015a6e62713b00ae46a#4d429f525aa94f91cf025e504cf1d066 - Cache
    openssl/3.0.8-65b5a78@rutoken/stable#3700470fc765c9a25afb8a792ec45b82:1028ef5306e87e9740dc8d9a52c6285783614e6a#f0b343b117c467fe33e3cb34c68820b8 - Download (rutoken)
    zlib/v1.3-3d1449b@rutoken/stable#7d00412ea2fe7086b799148ac77418ad:54fac0cfb8a344573d37fd4b895cb6ad6d623561#1db904fb2c1c25859f487f6f0f7049e6 - Download (rutoken)
Generated lockfile: /Users/lo1ol/Documents/work/libfido2/conan13.lock
lo1ol@Petrs-MacBook-Air ~/D/w/libfido2 (fix-using-bad-compats)> conan lock create -pr glibc-x86_64-gcc11 -s build_type=Debug --lockfile-out  conan11.lock . -u
rutokenconanfile/0.35@rutoken/stable: Checking remote: rutoken

======== Computing dependency graph ========
zlib/v1.3-3d1449b@rutoken/stable: Checking remote: rutoken
rutokenconanfile/0.35@rutoken/stable: Checking remote: rutoken
libcbor/v0.10.2-17ce8b9@rutoken/stable: Checking remote: rutoken
openssl/3.0.8-65b5a78@rutoken/stable: Checking remote: rutoken
libudev/1.5.0@rutoken/stable: Checking remote: rutoken
Graph root
    conanfile.py: /Users/lo1ol/Documents/work/libfido2/conanfile.py
Requirements
    libcbor/v0.10.2-17ce8b9@rutoken/stable#f148d89eb98d0ad48c4f08aa7beedd8a - Cache (rutoken)
    libudev/1.5.0@rutoken/stable#d55ee708c9eea62934b77663172d2c56 - Cache (rutoken)
    openssl/3.0.8-65b5a78@rutoken/stable#3700470fc765c9a25afb8a792ec45b82 - Cache (rutoken)
    zlib/v1.3-3d1449b@rutoken/stable#7d00412ea2fe7086b799148ac77418ad - Cache (rutoken)
Python requires
    rutokenconanfile/0.35@rutoken/stable#e3c87d2e6fd0ee6fdb44ce344f036ba9 - Cache (rutoken)

======== Computing necessary packages ========
libcbor/v0.10.2-17ce8b9@rutoken/stable: Checking 15 compatible configurations
libcbor/v0.10.2-17ce8b9@rutoken/stable: '26909014f768338c6cb542c68c56186b86a4b2ab': build_type=Release
libcbor/v0.10.2-17ce8b9@rutoken/stable: Current package revision is newer than the remote one
libcbor/v0.10.2-17ce8b9@rutoken/stable: Main binary package 'a4a79b25dfaaac6ea181e4a9b165285702702508' missing. Using compatible package '26909014f768338c6cb542c68c56186b86a4b2ab': build_type=Release
libudev/1.5.0@rutoken/stable: Current package revision is newer than the remote one
openssl/3.0.8-65b5a78@rutoken/stable: Checking 15 compatible configurations
openssl/3.0.8-65b5a78@rutoken/stable: '449ee076a0030331be32d825903a819d90d536c1': build_type=Release
openssl/3.0.8-65b5a78@rutoken/stable: Current package revision is newer than the remote one
openssl/3.0.8-65b5a78@rutoken/stable: Main binary package '0d598902967b209d4696f5f898d2da672bef522d' missing. Using compatible package '449ee076a0030331be32d825903a819d90d536c1': build_type=Release
zlib/v1.3-3d1449b@rutoken/stable: Checking 15 compatible configurations
zlib/v1.3-3d1449b@rutoken/stable: '26909014f768338c6cb542c68c56186b86a4b2ab': build_type=Release
zlib/v1.3-3d1449b@rutoken/stable: Current package revision is newer than the remote one
zlib/v1.3-3d1449b@rutoken/stable: Main binary package 'a4a79b25dfaaac6ea181e4a9b165285702702508' missing. Using compatible package '26909014f768338c6cb542c68c56186b86a4b2ab': build_type=Release
Requirements
    libcbor/v0.10.2-17ce8b9@rutoken/stable#f148d89eb98d0ad48c4f08aa7beedd8a:26909014f768338c6cb542c68c56186b86a4b2ab#64ee9137d1e82ea809a3e896f527a139 - Cache
    libudev/1.5.0@rutoken/stable#d55ee708c9eea62934b77663172d2c56:ff47581be5225eed65b4a015a6e62713b00ae46a#4d429f525aa94f91cf025e504cf1d066 - Cache
    openssl/3.0.8-65b5a78@rutoken/stable#3700470fc765c9a25afb8a792ec45b82:449ee076a0030331be32d825903a819d90d536c1#5d3b6b709ecf555bd76a5f609da2809d - Cache
    zlib/v1.3-3d1449b@rutoken/stable#7d00412ea2fe7086b799148ac77418ad:26909014f768338c6cb542c68c56186b86a4b2ab#2b5dbcb8e717c73531a9d48a17c47e9b - Cache
Generated lockfile: /Users/lo1ol/Documents/work/libfido2/conan11.lock
lo1ol@Petrs-MacBook-Air ~/D/w/libfido2 (fix-using-bad-compats)> diff conan1{1,3}.lock
```

Btw, I want to try to use lock files to resolve this [problem](https://github.com/conan-io/conan/issues/15792). I wanted to check what conan prefer to use: less compatible downloaded package in cache (specified as one of the possible package in lock file) or try to download most compatible package also specified in conan lock file

**Comment by memsharded** [comment]
> I'm not sure that conan saves info about binary packages without --lockfile-packages: For example, I get the same output for different profiles:

Yes, two different profiles can have exactly the same lockfile (for the same initial input recipes and same state of the server). If the dependencies don't change, and there are no conditional dependencies that depend on the configuration, the lockfile is the same. This is a feature, it is designed to be able to manage 1 lockfile for multiple configurations/profiles. Conan 1 managed 1 lockfile per configuration and it was very complex and unintuitive.

When a dependency graph is to be reproduced, it has to provide:
- the lockfile
- the same initial ``conanfile`` or ``--requires``
- the same profiles/configuration

> Btw, I want to try to use lock files to resolve this https://github.com/conan-io/conan/issues/15792. I wanted to check what conan prefer to use: less compatible downloaded package in cache (specified as one of the possible package in lock file) or try to download most compatible package also specified in conan lock file

I am not sure if I understand this. Lockfiles are not connected to binary compatibility, lockfiles are a source version/revision control mechanism, not related to the binaries. Binaries are a function of the dependency graph, once the dependency graph of versions/revisions can be reproduced down to the revision level, the same profiles will produce same binaries, so binary compatibility is not involved at all in the lockfile resolution.

**Comment by lo1ol** [comment]
Thank you for answer)

**Comment by memsharded** [comment]
Thanks for your feedback!
