### ISSUE TITLE
Failing tests on OS X

### ISSUE THREAD

**Issue by springmeyer** [conan-io/conan#16]
Seeing some failing tests that look like https://gist.github.com/springmeyer/e51c32b1cf32f25a3aee. Wondering if you have any suggestions for what I might be doing wrong. My install method was https://gist.github.com/springmeyer/4f4a4d20e4918c6cd2e1

**Comment by lasote** [comment]
Do you have cmake > 2.8? Sorry, I don't know if it's on the README.Some tests use CMake for build.

**Comment by springmeyer** [comment]
Great, thank you, that fixes many of the failures (I did not have `cmake` on my PATH).

Now the remaining failures I'm seeing are:

```
~/projects/conan[develop]$ nosetests
...............................................EE.................................................................................................
======================================================================
ERROR: reuse_test (conan.conans.test.integration.go_complete_test.GoCompleteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dane/projects/conan/conans/test/integration/go_complete_test.py", line 141, in reuse_test
    reuse_conan.runner(command, os.path.join(reuse_conan.current_folder, 'bin'))
  File "/Users/dane/projects/conan/conans/test/utils/runner.py", line 9, in __call__
    proc = Popen(command, shell=True, bufsize=1, stdout=PIPE, stderr=STDOUT, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/var/folders/jv/bhkldrpj41jbkpzxgc9ggr_r0000gn/T/tmpmHHKiGconans/path with spaces/bin'

======================================================================
ERROR: reuse_test (conan.conans.test.integration.go_diamond_test.GoDiamondTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dane/projects/conan/conans/test/integration/go_diamond_test.py", line 48, in reuse_test
    client.runner(command, os.path.join(client.current_folder, 'bin'))
  File "/Users/dane/projects/conan/conans/test/utils/runner.py", line 9, in __call__
    proc = Popen(command, shell=True, bufsize=1, stdout=PIPE, stderr=STDOUT, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/var/folders/jv/bhkldrpj41jbkpzxgc9ggr_r0000gn/T/tmp0nH8KQconans/path with spaces/bin'

----------------------------------------------------------------------
Ran 146 tests in 69.757s

FAILED (errors=2)
```

```
$ cmake --version
cmake version 3.2.3
```

```
$ clang++ --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by memsharded** [comment]
It seems that for those 2 tests you need golang also installed on your machine, and available in the path. Could you try to install it too, please?

**Comment by springmeyer** [comment]
@memsharded - excellent, thanks! Installing `go` (brew install go) did it!:

```
nosetests .
..................................................................................................................................................
----------------------------------------------------------------------
Ran 146 tests in 71.667s

OK
```

**Comment by memsharded** [comment]
:) Thanks you for testing
