### ISSUE TITLE
[bug] binutils package fails to build

### ISSUE THREAD

**Issue by sigidagi** [conan-io/conan#16018]
### Describe the bug

`conan install --requires binutils/2.41 --build missing --format=json `

Stack trace:
```
Install finished successfully
ERROR: Traceback (most recent call last):
  File "/home/sigis/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/cli.py", line 283, in main
    cli.run(args)
  File "/home/sigis/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/sigis/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/command.py", line 167, in run
    self._format(parser, info, *args)
  File "/home/sigis/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/command.py", line 98, in _format
    formatter(info)
  File "/home/sigis/.local/pipx/venvs/conan/lib/python3.11/site-packages/conan/cli/formatters/graph/graph.py", line 148, in format_graph_json
    json_result = json.dumps({"graph": serial}, indent=4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _PackageOption is not JSON serializable

ERROR: Object of type _PackageOption is not JSON serializable

```

### How to reproduce it

Conan version 2.2.2
Python version 3.11

`conan install --requires binutils/2.41 --build missing --format=json `

**Comment by memsharded** [comment]
Hi @sigidagi 

Thanks for reporting.

This looks mostly a bug in the ``binutils`` recipe, not in the Conan client, and most likely will not fail for other packages.

The culprit is:
```
self.conf_info.define("user.binutils:gnu_triplet", self.options.target_triplet)
self.conf_info.define("user.binutils:prefix", self.options.prefix)
```
The ``conf`` definition admits Python primitives, but not user objects.
Also those specific confs are not used in ConanCenter, so I am not sure why they are defined.
They were introduced by https://github.com/conan-io/conan-center-index/pull/15352 by @StellaSmith, maybe they can help with this, maybe these can be removed (or converted to strings)

**Comment by memsharded** [comment]
As a hint, the package was correctly created, it is the ``--format=json`` final output that is failing only, but the package should be there, and most likely you can use it.

**Comment by sigidagi** [comment]
Thanks @memsharded ,
Yes, by removing these two lines, I've got nice json output.

**Comment by memsharded** [comment]
> Yes, by removing these two lines, I've got nice json output.

Thanks for the feedback. Lets wait a bit for @StellaSmith feedback about those confs, to take a decision to remove them or convert them to strings in ``conan-center-index``

**Comment by memsharded** [comment]
I am proposing to remove those entries in https://github.com/conan-io/conan-center-index/pull/23427

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan-center-index/pull/23427

Don't hesitate tp create new tickets for any further question or issue, thanks!
