### ISSUE TITLE
[question] Failure on corrupted (empty) remotes.json

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#16089]
### What is your question?

Hi,

I'm not sure whether this is a bug or a feature. Conan throws errors if remotes.json has zero size. And it can't reset it to clean state. Maybe some better error message would help in this case if it's intended behavior?

```
C:\Users\Nekto\.conan2>conan remote remove "*"
ERROR: Traceback (most recent call last):
  File "C:\Soft\Python39\lib\site-packages\conan\cli\cli.py", line 283, in main
    cli.run(args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\Soft\Python39\lib\site-packages\conan\cli\command.py", line 180, in run
    sub.run(conan_api, parser, *args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\command.py", line 197, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\commands\remote.py", line 103, in remote_remove
    remotes = conan_api.remotes.remove(args.remote)
  File "C:\Soft\Python39\lib\site-packages\conan\api\subapi\remotes.py", line 140, in remove
    remotes = _load(self._remotes_file)
  File "C:\Soft\Python39\lib\site-packages\conan\api\subapi\remotes.py", line 260, in _load
    data = json.loads(load(remotes_file))
  File "C:\Soft\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Soft\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Soft\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Expecting value: line 1 column 1 (char 0)

C:\Users\Nekto\.conan2>conan remote add conancenter "https://center.conan.io"
ERROR: Traceback (most recent call last):
  File "C:\Soft\Python39\lib\site-packages\conan\cli\cli.py", line 283, in main
    cli.run(args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\Soft\Python39\lib\site-packages\conan\cli\command.py", line 180, in run
    sub.run(conan_api, parser, *args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\command.py", line 197, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
  File "C:\Soft\Python39\lib\site-packages\conan\cli\commands\remote.py", line 92, in remote_add
    conan_api.remotes.add(r, force=args.force, index=args.index)
  File "C:\Soft\Python39\lib\site-packages\conan\api\subapi\remotes.py", line 110, in add
    remotes = _load(self._remotes_file)
  File "C:\Soft\Python39\lib\site-packages\conan\api\subapi\remotes.py", line 260, in _load
    data = json.loads(load(remotes_file))
  File "C:\Soft\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Soft\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Soft\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Expecting value: line 1 column 1 (char 0)
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks @Nekto89 for reporting this.

Yes, at the very least a better error message would be desired, not the full stacktrace, lets improve it.
