### ISSUE TITLE
[bug] Conan cache restore on non-existing file

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16112]
### Describe the bug

OS : Windows 11 23H2 & Python 3.9.13. Same behaviour on docker image python:3.9.19-slim
Conan version : 2.2.3

Trying to restore a non-existing file with `conan cache restore file` results in a traceback.

### How to reproduce it

```bash
I have no name!@docker-desktop:/workspace$ conan cache restore hello
ERROR: Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/conan/cli/cli.py", line 283, in main
    cli.run(args)
  File "/opt/venv/lib/python3.9/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/opt/venv/lib/python3.9/site-packages/conan/cli/command.py", line 180, in run
    sub.run(conan_api, parser, *args)
  File "/opt/venv/lib/python3.9/site-packages/conan/cli/command.py", line 197, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
  File "/opt/venv/lib/python3.9/site-packages/conan/cli/commands/cache.py", line 156, in cache_restore
    package_list = conan_api.cache.restore(path)
  File "/opt/venv/lib/python3.9/site-packages/conan/api/subapi/cache.py", line 158, in restore
    with open(path, mode='rb') as file_handler:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/hello'

ERROR: [Errno 2] No such file or directory: '/workspace/hello'
```

**Comment by memsharded** [comment]
Thanks for reporting @Todiq 
It was fixed in https://github.com/conan-io/conan/pull/16113 for next Conan 2.3
