### ISSUE TITLE
[bug] simultaneous execute

### ISSUE THREAD

**Issue by Dimitrius-dev** [conan-io/conan#16880]
## My settings:
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux
[conf]
tools.build:skip_test=True
[buildenv]
CC=/usr/bin/gcc-13
CXX=/usr/bin/g++-13

## Description
I use conan with CLion (IDE). By default i generate cmake for both: debug, release at the same time. Cmake script calls conan with this cmake code:
```
execute_process(
        COMMAND ${CMAKE_COMMAND} -E echo "--- execute conan install ---"
        COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_SOURCE_DIR}/conanfile.py ${CMAKE_BINARY_DIR}/conanfile.py
        COMMAND ${conan} install ${CMAKE_BINARY_DIR}
        -s build_type=${CMAKE_BUILD_TYPE}
        --output-folder=${CMAKE_BINARY_DIR}/conan_files --build=missing
        -pr:h=${conan_profile}
        -c tools.build:skip_test=${conan_skip_test}
        RESULT_VARIABLE OUTPUT
)
```
At cmake project reloading one version (debug/release) gets the valid output, and another produces with error:
```
======== Computing dependency graph ========
ERROR: Traceback (most recent call last):
  File "/home/belov/.local/lib/python3.10/site-packages/conan/cli/cli.py", line 294, in main
    cli.run(args)
  File "/home/belov/.local/lib/python3.10/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/belov/.local/lib/python3.10/site-packages/conan/cli/command.py", line 171, in run
    info = self._method(conan_api, parser, *args)
  File "/home/belov/.local/lib/python3.10/site-packages/conan/cli/commands/install.py", line 61, in install
    deps_graph = gapi.load_graph_consumer(path, args.name, args.version, args.user, args.channel,
  File "/home/belov/.local/lib/python3.10/site-packages/conan/api/subapi/graph.py", line 148, in load_graph_consumer
    deps_graph = self.load_graph(root_node, profile_host=profile_host,
  File "/home/belov/.local/lib/python3.10/site-packages/conan/api/subapi/graph.py", line 180, in load_graph
    deps_graph = builder.load_graph(root_node, profile_host, profile_build, lockfile)
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/graph_builder.py", line 53, in load_graph
    new_node = self._expand_require(require, node, dep_graph, profile_host,
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/graph_builder.py", line 100, in _expand_require
    new_node = self._create_new_node(node, require, graph, profile_host, profile_build,
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/graph_builder.py", line 348, in _create_new_node
    resolved = self._resolve_recipe(require.ref, graph_lock)
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/graph_builder.py", line 246, in _resolve_recipe
    result = self._proxy.get_recipe(ref, self._remotes, self._update, self._check_update)
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/proxy.py", line 25, in get_recipe
    resolved = self._get_recipe(ref, remotes, update, check_update)
  File "/home/belov/.local/lib/python3.10/site-packages/conans/client/graph/proxy.py", line 48, in _get_recipe
    self._cache.update_recipe_lru(ref)
  File "/home/belov/.local/lib/python3.10/site-packages/conan/internal/cache/cache.py", line 277, in update_recipe_lru
    self._db.update_recipe_lru(ref)
  File "/home/belov/.local/lib/python3.10/site-packages/conan/internal/cache/db/cache_database.py", line 46, in update_recipe_lru
    self._recipes.update_lru(ref)
  File "/home/belov/.local/lib/python3.10/site-packages/conan/internal/cache/db/recipes_table.py", line 72, in update_lru
    conn.execute(query)
sqlite3.OperationalError: disk I/O error

ERROR: disk I/O error
```

### How to reproduce it

Get some conan project and try to call `conan install` at the same time for both `debug` and `release` versions.

**Comment by memsharded** [comment]
Hi @Dimitrius-dev 

Thanks for your report.

This is known behavior, the Conan cache is not concurrent, and trying to install the same thing can cause race conditions as the one you are seeing. This is documented in https://docs.conan.io/2/knowledge/guidelines.html. 
This would be the ticket to track for future support: https://github.com/conan-io/conan/issues/15840

If you are using CLion the recommendations would be:
- Use the CLion plugin, I think it will not have this issue: https://www.jetbrains.com/help/clion/conan-plugin.html, https://github.com/conan-io/conan-clion-plugin
- Use the ``cmake-conan`` integration (https://github.com/conan-io/cmake-conan) that calls Conan automatically (the CLion plugin uses this ``cmake-conan`` by default)
- The canonical ``conan install`` + using CMake presets works pretty well too.

**Comment by Dimitrius-dev** [comment]
Thank you!

**Comment by memsharded** [comment]
Happy to help! Don't hesitate to create new tickets for any further question or issue you might have
