### ISSUE TITLE
[bug] Problem bootstrapping self-referencing recipe with Conan 2.8.0

### ISSUE THREAD

**Issue by jwatson0** [conan-io/conan#17096]
### Describe the bug

Maybe this is a bug, or maybe just a question.
Ubuntu 22.04
Conan 2.8.0

I'm compiling a build tool that uses a previous version of itself to build.  I'd like to be able to use `tool_requires` to reference a version range that is `>=` some past version of the tool, but that of course includes the current version being built.  In past versions of conan, this gives an error indicating a dependency loop.

I was hoping that [#16870](https://github.com/conan-io/conan/pull/16870) would allow this, but I'm getting a different error when I try with conan 2.8.0.

Here is a simplified pseudocode of the recipe:
```
  def set_name(self):
    self.name = "slm"

  def set_version(self):
    self.version = `"0.6.19"`

  def build_requirements(self):
    self.tool_requires("slm/[>=0.6.18 <0.7.0]")
```

If I use `self.tool_requires("slm/0.6.18")` referencing a specific previous version, it works fine.

If I use the version range including the currently building version, I get this error:
```
Graph root
    cli
Requirements
    http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235 - Downloaded (artifactory)
    libarchive/3.7.3#2456d159710a717790bfec6e38fa6e10 - Downloaded (artifactory)
    libcurl/8.6.0#357425be60d85553bfe65154194b71be - Downloaded (artifactory)
    libgit2/1.7.2#80911288a6688637de4ae1d969ae522c - Downloaded (artifactory)
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd - Downloaded (artifactory)
    libssh2/1.11.0#398cc57c58bbe9d41fd672c3a4e19782 - Downloaded (artifactory)
    openssl/3.2.2#899583c694f9deccec74dbe0bbc65a15 - Downloaded (artifactory)
    slm/0.6.19#ef53694e98a718cf2f314e0e91334ebb - Cache
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2 - Downloaded (artifactory)
Build requirements
    autoconf/2.71#53be95d228b2dcb30dc199cb84262d8f - Downloaded (artifactory)
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Downloaded (artifactory)
    cmake/3.27.7#6e11610a238b9292dffda14c34bb53e6 - Downloaded (artifactory)
    gnu-config/cci.20210814#15c3bf7dfdb743977b84d0321534ad90 - Downloaded (artifactory)
    lbstanza/0.18.94#a06918c214bf2c64177ce89cf427e1e0 - Downloaded (artifactory)
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b - Downloaded (artifactory)
    m4/1.4.19#adbdd7fb7db33e609425c797196baccb - Downloaded (artifactory)
    meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d - Downloaded (artifactory)
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Downloaded (artifactory)
    pkgconf/2.1.0#27f44583701117b571307cf5b5fe5605 - Downloaded (artifactory)
    slm/0.6.19#ef53694e98a718cf2f314e0e91334ebb - Cache
Python requires
    lbstanzagenerator_pyreq/0.6.17#a9447a4e1905ca2e327c74b0028cfdd6 - Cache
Resolved version ranges
    cmake/[>=3.20 <4.0]: cmake/3.27.7
    lbstanza/[>=0.18.78 <1.0]: lbstanza/0.18.94
    ninja/[>=1.11 <2.0]: ninja/1.11.1
    slm/[>=0.6.18 <0.7.0]: slm/0.6.19

======== Computing necessary packages ========
slm/0.6.19: Forced build from source
Requirements
    http_parser/2.9.4#38bd28da476afbba5e4adcdd726ea235:b647c43bfefae3f830561ca202b6cfd935b56205#9f89697f2023418cd89bc371219ede33 - Skip
    libarchive/3.7.3#2456d159710a717790bfec6e38fa6e10:5518335b7fd841a90ef004d6d7659a015b225973#9a846411d74fbf09a2c3f95f393d31b1 - Skip
    libcurl/8.6.0#357425be60d85553bfe65154194b71be:30324594e680f1c0c0a881247c2a0c20bd8733c0#c3f2fcfaabbd3c2200d4c2a42d9ea669 - Skip
    libgit2/1.7.2#80911288a6688637de4ae1d969ae522c:91ad714687bf169c18ee6a225c75e18c0f411e93#de23a024a74da786bc9bf9dd9db7587c - Skip
    libiconv/1.17#73fefc1b696e069df90fd1d18aa63edd:b647c43bfefae3f830561ca202b6cfd935b56205#dc3d5e49b81df7c37e57e1875ee4a2e8 - Skip
    libssh2/1.11.0#398cc57c58bbe9d41fd672c3a4e19782:032a393b8a0cb19ddc72a043eb4eeaafb9909edb#edda57493d41acb73fc25bc1244e9e3e - Skip
    openssl/3.2.2#899583c694f9deccec74dbe0bbc65a15:ba0c965640dfc9185194d683d05bfbe6419b47a3#281cd6a9a1066f4a26d97c01a32cc7b5 - Skip
    slm/0.6.19#ef53694e98a718cf2f314e0e91334ebb:a4b54cca2e36f0953babee402f42eb85e7a65aa7 - Invalid
    zlib/1.3.1#f52e03ae3d251dec704634230cd806a2:b647c43bfefae3f830561ca202b6cfd935b56205#fd85b1346d5377ae2465645768e62bf2 - Skip
Build requirements
    autoconf/2.71#53be95d228b2dcb30dc199cb84262d8f:da39a3ee5e6b4b0d3255bfef95601890afd80709#ecdedaa05db7f162580f145df740c73b - Skip
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50:9a4eb3c8701508aa9458b1a73d0633783ecc2270#9719e51a6a62041af6a63e00eef35434 - Skip
    cmake/3.27.7#6e11610a238b9292dffda14c34bb53e6:63fead0844576fc02943e16909f08fcdddd6f44b#9583e30af903650c949bb4ebeaa67180 - Skip
    gnu-config/cci.20210814#15c3bf7dfdb743977b84d0321534ad90:da39a3ee5e6b4b0d3255bfef95601890afd80709#22618e30bd9e326eb95e824dc90cc860 - Skip
    lbstanza/0.18.94#a06918c214bf2c64177ce89cf427e1e0:63fead0844576fc02943e16909f08fcdddd6f44b#0df788cba68bdc954cc4b6967431d4bf - Skip
    libtool/2.4.7#08316dad5c72c541ed21e039e4cf217b:b647c43bfefae3f830561ca202b6cfd935b56205#f4c8da5bffcf49cdf1b4ce011cab7737 - Skip
    m4/1.4.19#adbdd7fb7db33e609425c797196baccb:3593751651824fb813502c69c971267624ced41a#eb16145946d9c9fa95b777969da769ab - Skip
    meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d:da39a3ee5e6b4b0d3255bfef95601890afd80709#2bfd29b9a8744e08daf4c11bdb43a4ce - Skip
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21:3593751651824fb813502c69c971267624ced41a#60e6fc0f973babfbed66a66af22a4f02 - Skip
    pkgconf/2.1.0#27f44583701117b571307cf5b5fe5605:c0b621fd4b3199fe05075171573398833dba85f4#74a82dec52448dda20253a19d65965c7 - Skip
    slm/0.6.19#ef53694e98a718cf2f314e0e91334ebb:a4b54cca2e36f0953babee402f42eb85e7a65aa7 - Skip
Traceback (most recent call last):
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conan/cli/command.py", line 171, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conan/cli/commands/create.py", line 118, in create
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conan/api/subapi/install.py", line 26, in install_binaries
    install_graph.raise_errors()
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conans/client/graph/install_graph.py", line 476, in raise_errors
    self._raise_invalid(invalid)
  File "/home/jwatson/git/slm/venv/lib/python3.12/site-packages/conans/client/graph/install_graph.py", line 506, in _raise_invalid
    raise ConanInvalidConfiguration("\n".join(msg))
conans.errors.ConanInvalidConfiguration: There are invalid packages:
slm/0.6.19: Invalid: None

ERROR: There are invalid packages:
slm/0.6.19: Invalid: None
ERROR: 'slm/0.6.19#ef53694e98a718cf2f314e0e91334ebb:null' not found in cache
```

Is this the case that #16870 was supposed to address?

Edit - note: there are previous versions of slm such as `slm/0.6.18` available on the configured remote

Thanks!

### How to reproduce it

```
> git clone git@github.com:StanzaOrg/slm.git
> cd slm
# adjust tool_requires version range
> make
```

**Comment by memsharded** [comment]
Hi @jwatson0 

Thanks for your report.

Is this a regression, it worked in Conan 2.7, or is it the first time you are trying this.

In theory ``self.tool_requires("slm/[>=0.6.18 <0.7.0]")`` including the current or even larger version is incorrect for bootstrapping, you really cannot depend on yourself, that creates an infinite dependency loop. 
The correct approach is to depend strictly on versions older than the current one, something like:

```python
self.tool_requires(f"slm/[>=0.6.18 <{self.version}]")
```
Can you please try that and let us know? thanks!

**Comment by jwatson0** [comment]
No, not a regression.  The `<{self.version}` works perfectly, and is just the trick I needed.  Thanks!

**Comment by memsharded** [comment]
Great to hear that, thanks for the feedback!
