### ISSUE TITLE
[question] `ConanAPI.install.install_binaries` fails with `Node Not in remote`

### ISSUE THREAD

**Issue by i-ilak** [conan-io/conan#17107]
### What is your question?

Hi! Im trying to write a custom command for `conan`, but Im doing something wrong when setting either up the dependency graph, or calling `conan_api.install.install_binaries`.

The custom command looks something like this:
```python
import json
from os import listdir, getcwd
from platform import system

from conan.api.conan_api import ConanAPI
from conan.api.output import ConanOutput
from conan.cli.command import conan_command
from conan.cli import make_abs_path


def output_json(msg):
    return json.dumps({"greet": msg})


@conan_command(group="mll", formatters={"json": output_json})
def install(conan_api: ConanAPI, parser, *args):
    """Documentation string otherwise it crashes"""
    out = ConanOutput()
    if system() == "Linux":
        profile_folder = make_abs_path("conan_profiles/linux")
    elif system() == "Darwin":
        profile_folder = make_abs_path("conan_profiles/macOS")
    else:
        out.error("Unsupported OS")
        return

    args = parser.parse_args(*args)

    cwd = getcwd()
    path = conan_api.local.get_conanfile_path("./", cwd, py=None)
    remotes = [conan_api.remotes.get("our_hosted_conan_remote")]

    profiles_to_load = [
        profile_folder + "/" + profile for profile in listdir(profile_folder)
    ]
    profiles = [
        conan_api.profiles.get_profile([profile_path], cwd=cwd)
        for profile_path in profiles_to_load
    ]

    for profile in profiles:
        for build_type in ["Debug", "Release"]:
            profile.settings["build_type"] = build_type
            dependency_graph = conan_api.graph.load_graph_consumer(
                path,
                name=None,
                version=None,
                user=None,
                channel=None,
                profile_host=profile,
                profile_build=profile,
                lockfile=None,
                remotes=remotes,
                update=False,
                check_updates=True,
                is_build_require=False,
            )
            conan_api.install.install_binaries(deps_graph=dependency_graph, remotes=remotes)
            conan_api.install.install_consumer(dependency_graph)

    return
```
When I make the call `conan mll:install` I get the following output:
```
❯ conan mll:install

======== Computing dependency graph ========
breakpad/0.91: Checking remote: our_hosted_conan_remote
dart-sass/1.57.1: Checking remote: our_hosted_conan_remote
MORE_PACKAGES ARE HERE
ERROR: Traceback (most recent call last):
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conan/cli/cli.py", line 294, in main
    cli.run(args)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conan/cli/command.py", line 171, in run
    info = self._method(conan_api, parser, *args)
  File "/local0/home/i-ilak/conan2/extensions/commands/mll/cmd_install.py", line 58, in install
    conan_api.install.install_binaries(deps_graph=dependency_graph, remotes=remotes)
  File "/home/iilak/.pyenv/versions/default/lib/python3.10/site-packages/conan/api/subapi/install.py", line 25, in install_binaries
    install_graph = InstallGraph(deps_graph)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/install_graph.py", line 336, in __init__
    self._initialize_deps_graph(deps_graph)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/install_graph.py", line 386, in _initialize_deps_graph
    self._nodes[key] = self._node_cls.create(node)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/install_graph.py", line 133, in create
    result.add(node)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/install_graph.py", line 156, in add
    install_pkg_ref = _InstallPackageReference.create(node)
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/install_graph.py", line 48, in create
    result.package_id = node.pref.package_id
  File "/home/i-ilak/.pyenv/versions/default/lib/python3.10/site-packages/conans/client/graph/graph.py", line 206, in pref
    assert self.ref is not None and self.package_id is not None, "Node %s" % self.recipe
AssertionError: Node Not in remote

ERROR: Node Not in remote
```
The goal is to have a single call, e.g. `conan mll:install` that installs the dependencies with all the profiles available in both `Debug` and `Release` and adds them to a `CMakeUserPresets.json`. 

Any hints on what Im doing wrong in `conan_api.install.install_binaries` are appreciated!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @i-ilak 

Thanks for your question.

It doesn't seem it is an error in the ``install_binaries``, but earlier.
Make sure to add the lines before calling ``install_binaries()``:
```python
print_graph_basic(dependency_graph )
dependency_graph.report_graph_error()
```
(you can omit the print, but the ``report_graph_error()`` must be there.
This will most likely raise an error about a dependency that was not found, and as such, the graph couldn't be fully resolved.

Then, you are missing another important call, before installing binaries, you need to:
```python
conan_api.graph.analyze_binaries(dependency_graph, build_mode=[ref.name], lockfile=lockfile,
                                     remotes=remotes)
```

because this is what computes what needs to be installed

I'll suggest to have a detailed look to the source code of the built-in ``install()`` command.

Please let me know if this helps

**Comment by i-ilak** [comment]
Hi @memsharded 
Thanks so much. The `analyze_binaries` command was what was missing... Also, thank you for pointing me to [this](https://github.com/conan-io/conan/blob/ee9cf01f46c11fb318e70bcbb435154b602cbbd8/conan/cli/commands/install.py), that turned out to be very useful!

I have one more question regarding this. How exactly do the `conanfile.py` and the `custom command` interact with each other? What I mean by this is that one can in the `conanfile.py` write something like this:

```python
# the relevant imports

class MyAwesomeSWConan(ConanFile):
    name = "MyAwesomeSW"
    version = "XX.Y"
    settings = "os", "compiler", "build_type", "arch"
  
    def requirements(self):
        # implementation

    def configure(self):
        # implementation

    def layout(self):
        self.folders.build_folder_vars = [
            "settings.compiler",
            "settings.compiler.version",
            "settings.build_type",
        ]
        cmake_layout(self)
    
     def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()
    
     def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
Assuming I do a classical `conan install -pr:a=default ...` this will generate build-folder with the structure `compiler-version-build_type` and consequently also name the `cmake` presets accordingly. 

If I now have a custom command that looks like this:
```python
    cwd = # path to conanfile.py
    for profile in profiles:
        for build_type in ["Debug", "Release"]:
            profile.settings["build_type"] = build_type
            dependency_graph = conan_api.graph.load_graph_consumer(
                # relevant arguments
            )
            conan_api.graph.analyze_binaries(
                dependency_graph, build_mode=["missing"], lockfile=None, remotes=remotes
            )

            conan_api.install.install_binaries(
                deps_graph=dependency_graph, remotes=remotes
            )

            conan_api.install.install_consumer(
                deps_graph=dependency_graph,
                generators=None,
                source_folder=cwd,
                output_folder=cwd + "/build/conan",
            )

```
And run it I end up with something that looks like this
```
$ tree -L 3 build/conan
build/conan
└── build
    ├── clang-14-release
    │   └── generators
    └── gcc-11-release
        └── generators
```
even though I would expect
```
$ tree -L 3 build/conan
build/conan
└── build
    ├── clang-14-release
    │   └── generators
    └── gcc-11-release
        └── generators
    └── clang-14-debug
        └── generators
    └── gcc-11-debug
        └── generators
```
since I'm setting `profile.settings["build_type"] = build_type` (which is correctly picked up for compiling the dependencies)...

**Comment by memsharded** [comment]
Quick note: It is likely that you don't want to use the same ``profile`` for the "build" context always. For the build context, it is typical to use ``build_type=Release`` (to run things like ``cmake`` if it is a tool-requires as release executable).
 

The reason it is not working is because:
```python
profile_host.settings["build_type"] = s
```
Is not enough. That ``settings`` is not intended to be modified after the profile has be loaded, you can try something like putting the load of the profile inside the for-loop:

```python
    for s in ("Debug", "Release"):
        profile_host = conan_api.profiles.get_profile(["default"], settings=[f"build_type={s}"])
```

It is also true that there is a lot of work pending to better document the APIs, but things take time, we were focused lately on CI-Tutorial docs.

**Comment by i-ilak** [comment]
Hi @memsharded 

Thank you so much for the support and the work on conan. Everything works as expected!

**Comment by memsharded** [comment]
Excellent, thanks for your feedback!
