### ISSUE TITLE
[bug] transitive-libs=false shared library do not link on sysroot profiles

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#17256]
### Describe the bug

If A depends on a shared library B and A says that B is not a transitive libs, the GCC linker command fails when using shared libraries and using sysroot.

If I then set B as being a transitive-libs the whole things works.

What I see is that the target_data.cmake file has a diff:

```
32c32
< set(B_LIBS_RELWITHDEBINFO B)
---
> set(B_LIBS_RELWITHDEBINFO )
64c64
< set(B_B_B_LIBS_RELWITHDEBINFO B)
---
> set(B_B_B_LIBS_RELWITHDEBINFO )
```

at the link.txt generated by cmake we see this convert in the lib being added to the command or not.

When we do not specify the lib, the behavior of the linker is then to search for the library using rpath and others, except that gcc will "prepend" the sysroot to any specified rpaths.   Since conan install will install the deps in the .conan2/p folder, the rpath cannot work with GCC (GCC always prepend the sysroot to any rpath).

When we set transitive-libs we see the lib B added to the linker command and things works.

I believe the code in conan that cause the diff is:

```
        # traits logic
        if require and not require.headers:
            self.include_paths = ""
        if require and not require.libs:
            # self.lib_paths = ""  IMPORTANT! LINKERS IN LINUX FOR SHARED MIGHT NEED IT EVEN IF
            #                      NOT REALLY LINKING LIB
            self.libs = ""
            if cpp_info.frameworkdirs:  # Only invalidate for in-package frameworks
                # FIXME: The mix of in-package frameworks + system ones is broken
                self.frameworks = ""
```

inside conan/tools/cmake/cmakedeps/template/target_data.py

I need to understand why the transitive_libs set to false require that the linker use the search path instead of having the lib explicitly pass as it is done with transitive_libs set to true.

It also seems that when using GCC, conan/cmake should be using -Wl,-rpath-link instead of -Wl,-rpath, since conan will never copy the package file in the sysroot.

### How to reproduce it

Create a shared lib as B
Create a shared lib as A
Have A depends on B
  target_link_libraries(A PRIVATE B)
  
 If B is transitive-libs = true, it works, it B is transitive_libs = false it fails

Only in cross-compilation with gcc.

**Comment by memsharded** [comment]
Thanks for your report @hpe-ykoehler 

Could you please try with the new CMakeDeps generator in Conan 2.9, enabled with ``-c tools.cmake.cmakedeps:new=will_break_next``?

**Comment by hpe-ykoehler** [comment]
will do.

**Comment by hpe-ykoehler** [comment]
I was using conan 2.6.0

I upgraded to 2.9.1

The issue was still present.

I enabled the -c option you have specified 

and got an error:

```
A/0.1.0: WARN: Using the new CMakeDeps generator, behind the 'tools.cmake.cmakedeps:new' gate conf. This conf will changenext release, breaking, so use it only for testing and dev
ERROR: A/0.1.0: Error in generate() method, line 103
        deps.generate()
        ValueError: None is not a valid PackageType
```

my package conanfile.py 

  class AConan(ConanFile):
      package_type = "library"
      
      
 I added package_type to test_package/conanfile.py and set it to package_type="application", yet no success.

**Comment by memsharded** [comment]
Thanks for the feedback. If you can repeat the above, with the ``tools.cmake.cmakedeps:new`` conf and also ``-vvv`` to get the full stacktrace, I'll have a look to try to fix this.

Quick question, the ``package_type = "library"`` also defines a ``shared`` option?

**Comment by hpe-ykoehler** [comment]
yes, it is imposed, note that I created my issue using "conan new"...

It seems that if I use C++ it passes, if I convert this to C, ,I can repro my problem.

Then I used your -c option on that package and it passed

The thing which are particular to my profile are 

CMAKE_SYSROOT
C

and importantly the optioN

*:shared=True

**Comment by hpe-ykoehler** [comment]
[conantest.zip](https://github.com/user-attachments/files/17577719/conantest.zip)

here is the package a / b

cd a/
conan create .  -pr:h myccprofile --build=missing 

it fails, but when I did

conan create .  -pr:h myccprofile --build=missing  -c  tools.cmake.cmakedeps:new=will_break_next

it passed.

**Comment by hpe-ykoehler** [comment]
myccprofile looks like:

```
[settings]
arch=armv7hf
build_type=RelWithDebInfo
compiler=gcc
compiler.libcxx=libstdc++
compiler.libc=glibc
compiler.libc.version=2.31
compiler.version=9.3
os=Linux
os.version=4.19

[buildenv]
CONAN_CMAKE_FIND_ROOT_PATH=/usr/mycc-toolchain
CONAN_CMAKE_SYSROOT=/usr/mycc-sysroot
...

[conf]
tools.build:sysroot=/usr/mycc-sysroot
tools.build:skip_test=True
tools.build.cross_building:can_run=False

[options]
*:shared=True
*:fPIC=True
```

**Comment by hpe-ykoehler** [comment]
even with -vvv I do not understand why it claims package type is set to none in my recipe.  I am comparing my recipe to the "a" recipe and ... I don't see a diff that could explain this.

```
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/conan/internal/errors.py", line 35, in conanfile_exception_formatter
    yield
  File "/usr/local/lib/python3.8/dist-packages/conan/internal/api/install/generators.py", line 126, in write_generators
    conanfile.generate()
  File "/home/aos-dev/.conan2/p/dala3e3d39d00048/e/conanfile.py", line 83, in generate
    deps.generate()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps2/cmakedeps.py", line 41, in generate
    generator_files = self._content()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps2/cmakedeps.py", line 68, in _content
    ret[target_configuration.filename] = target_configuration.content()
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps2/target_configuration.py", line 24, in content
    return t.render(self._context)
  File "/usr/local/lib/python3.8/dist-packages/conan/tools/cmake/cmakedeps2/target_configuration.py", line 74, in _context
    cpp_info = self._conanfile.cpp_info.deduce_full_cpp_info(self._conanfile)
  File "/usr/local/lib/python3.8/dist-packages/conans/model/build_info.py", line 747, in deduce_full_cpp_info
    result._package.deduce_locations(pkg_type)
  File "/usr/local/lib/python3.8/dist-packages/conans/model/build_info.py", line 546, in deduce_locations
    if self._type != pkg_type:
  File "/usr/local/lib/python3.8/dist-packages/conans/model/pkg_type.py", line 22, in __eq__
    return super().__eq__(PackageType(other))
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: None is not a valid PackageType
```

If you can reach me on the slack channel on private on the conan workspace, I could share more if you are kind enough to help me on this.

**Comment by memsharded** [comment]
The possible root cause of the new ``CMakeDeps`` crash is:
- It uses a ``deduce_location()`` python method to find the full ``location`` property for a given lib, based only on the ``cpp_info.libs = ["libname"]`` and the ``cpp_info.libdirs``
- If this location is not found, then ``package_type`` is not deduced either and it becomes ``None``
- The warning trying to warn against possible package types mismatches was not prepared for this case.

I am doing in  #17257 a PR so the new CMakeDeps raises a full error. We plan to iterate the ``deduce_locations()`` to make it more robust and complete. There is always the possibility of defining it explicitly in the recipe with ``cpp_info.location = "full/path/to/fulllibname.a"``, but the intention is that this is not necessary for the vast majority of cases.

I think it is worth to try to make the new CMakeDeps generator for this case, as the current one has the problem that most frequently IMPORTED targets are unknown, not specified as SHARED/STATIC, and that makes more challenging for CMake to correctly define linkage.

**Comment by hpe-ykoehler** [comment]
The problem seems to be that the code is invoked during "generate" which occurs before the library is built, as such, there is no way it can find its location...

**Comment by hpe-ykoehler** [comment]
Is the new cmakedeps official in 2.10? or do we still need the -c flags?

Also, is there a workaround in past release?

**Comment by memsharded** [comment]
Partly available in Conan 2.9, documented in 2.10 as dev-testing: https://docs.conan.io/2/incubating.html, still the ``-c`` is necessary (and it will change in next release)

**Comment by hpe-ykoehler** [comment]
I tried to use the new cmake deps in a case where grpc is involved and got this error (2.10.1)

conanfile.py (fluentbit-krypton/None): WARN: Using the new CMakeDeps generator, behind the 'tools.cmake.cmakedeps:new' gate conf. This conf will changenext release, breaking, so use it only for testing and dev
grpc/1.50.1: WARN: There were several matches for Lib grpc: ['/home/aos-dev/.conan2/p/grpcff93700e1e527/p/lib/libgrpc.so.28.0.0', '/home/aos-dev/.conan2/p/grpcff93700e1e527/p/lib/libgrpc_plugin_support.so.1.50.1', '/home/aos-dev/.conan2/p/grpcff93700e1e527/p/lib/libgrpc_unsecure.so.28.0.0']

**Comment by hpe-ykoehler** [comment]
ok I think I pass that using a different cmake target such as gRPC::grpc_unsecure instead of grpc

**Comment by memsharded** [comment]
But that is not an error, just a warning. It is the auto-detection of the location of the artifact. We might try to improve the code, but it is also already possible to define the ``cpp_info.location`` information in the ``grpc`` library to dissambiguate.

It would be good to have this reported as its own ticket, with details on how to reproduce, @franramirez688 developed the auto-detection, he might try to add this case too.

**Comment by hpe-ykoehler** [comment]
It was not indicated as an error, but it then stopped the process from proceeding further. So, even if that is not the error, there was still an error triggered.

**Comment by jcar87** [comment]
> It also seems that when using GCC, conan/cmake should be using -Wl,-rpath-link instead of -Wl,-rpath,

This is the underlying issue - which I'm currently looking at - I would've expected the information we have in the generated targets to result in CMake passing `-rpath-link` but that does not seem to be the case.

It's not exactly an issue with GCC, more narrowly, this is due to the behaviour of the GNU bfd linker (the good old linker). This behaviour has not been preserved in neither gold, lld, mold, and from what I can see, is also not the case on Windows or macOS.



From https://github.com/conan-io/conan-center-index/pull/25195 and the ld manpages:


> The default behaviour is to report errors for any undefined symbols referenced in shared libraries if the linker is being used to create an executable, but to allow them if the linker is being used to create a shared library.

You may be be able to work around this by adding the following to your profile:

```
tools.build:exelinkflags=['-fuse-ld=bfd', '-Wl,--allow-shlib-undefined']
```

or by using the gold linker:

```
tools.build:exelinkflags=['-fuse-ld=gold']
tools.build:sharedlinkflags=['-fuse-ld=gold']
```

On the other hand, we will continue looking into why `-rpath-link` flags are not being passed correctly as they should.

**Comment by memsharded** [comment]
The -rpath-link correct flags should be passed now by the new incubating ``CMakeDeps``, so this might be solved by this.

The other issue would be a different one, if the ``grcp`` recipe cannot fully detect the ``.location`` of the artifacts, it might need some fix in the detection routine, or maybe a explicit definition of ``.location`` in the recipe, but that would need a different ticket.

**Comment by hpe-ykoehler** [comment]
@memsharded is the new cmake deps part of an official conan release yet?

I was trying to cross-compile conan-center-index tensorflow-lite on arm64 and I am having similar problem, when I tried with cmakedeps2, I hit issue under libtool's test package... using v2.11, will update conan to latest and igve it another shot

**Comment by memsharded** [comment]
It has been renamed to ``CMakeConfigDeps`` generator, included in latest Conan releases: https://docs.conan.io/2/incubating.html

It is still under "incubating", and need ``-c tools.cmake.cmakedeps:new=will_break_next`` to automatically opt-in from ``CMakeDeps`` usages.

**Comment by memsharded** [comment]
This ticket should now be fixed with the new CMakeConfigDeps generator: https://docs.conan.io/2/incubating.html, available in Conan 2.12. Please open a new ticket for any further issue with the CMakeConfigDeps generator if necessary.

To get the new CMakeConfigDeps out of "incubating", please test it and report your positive feedback in https://github.com/conan-io/conan/issues/18211 (for issues/questions, better open new tickets)

Many thanks!
