### ISSUE TITLE
Is it possible to run multiple conan_server processes pointing to the same data folder?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1961]
I am experiencing around 5% failure in fetching conan packages when the number of concurrent requests is relatively high. The errors in the client side are very different:

    '('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected 
    party did not properly respond after a period of time, or established connection failed because 
    connected host has failed to respond', None, 10060, None))' 

or 

    HTTPConnectionPool(host='conan.server.com', port=9300): Max retries exceeded with url: 
    /v1/conans/package/version/user/stable/download_urls (Caused by 
    NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04618030>: Failed to establish 
    a new connection: [WinError 10060] A connection attempt failed because the connected party did not 
    properly respond after a period of time, or established connection failed because connected host has 
    failed to respond',))

or even

    502 Bad Gateway 

from nginx.

On the server side this exception is raised:

    Exception happened during processing of request from ('172.30.78.56', 61253)
    Traceback (most recent call last):
    File "/usr/lib64/python3.4/socketserver.py", line 305, in _handle_request_noblock
      self.process_request(request, client_address)
    File "/usr/lib64/python3.4/socketserver.py", line 331, in process_request
      self.finish_request(request, client_address)
    File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
      self.RequestHandlerClass(request, client_address, self)
    File "/usr/lib64/python3.4/socketserver.py", line 673, in __init__
      self.handle()
    File "/usr/lib64/python3.4/wsgiref/simple_server.py", line 118, in handle
      self.raw_requestline = self.rfile.readline(65537)
    File "/usr/lib64/python3.4/socket.py", line 378, in readinto
      return self._sock.recv_into(b)
    ConnectionResetError: [Errno 104] Connection reset by peer

These errors are usually raised when there is a burst of requests, around 10 req/s for about 15 minutes. These numbers will just keep increasing and I am thinking of using nginx as a load balancer. I want to run `conan_server` on different machines but share the data folder over a network share (NFS) between different instances of conan_server. I am just not sure how conan_server serves the requests. If the requests are all reads, there shouldn't be a problem, however if there are multiple concurrent write requests going to different instances of the conan_server, what would happen? 

I am running version `0.25.1`.

Do you have any suggestions?

**Comment by memsharded** [comment]
Yes, as long as requests are reads, it should be mostly OK. But as you guess writes are a different story, I would say that can indeed be problematic if there are concurrent writes of the same package. However, if following some thought process, (like, why two processes would be uploading the same binary? Was it built twice?) the collisions should be minimized. Parallel write of different binaries  for the same package, or different packages shouldn't be a problem.

Biggest problem could be the continous reads while some process is writing. ``conan_server`` is not prepared for this concurrency at that scale. Recently some concurrency has been added to the client, with a basic implementation of the readers-writers problem, but I don't think it can support that massive concurrency without undesired locking (like readers locking for a long time and writers timing-out). 

I think to achieve scale with conan_server, you might want to implement your own, concurrent storage backend. If you have a look to the conan_server, "store" folder, it is prepared for this. There are a couple of adapters that you could replace for your own (database for big payloads, or FS with concurrent access), mainly the ``ServerDiskAdapter``.

**Comment by AliAskari** [comment]
I see. Thank you very much for the insight. The concurrent write issues I was thinking about is when we upload the same package with different configurations, Debug/Release/x86/etc. Yes, you are right we should never have concurrent write requests to a package with exactly the same configurations.

Do you know if this issue is present in JFrog artifactory?

**Comment by memsharded** [comment]
No, JFrog Artifactory will scale much better and handle much larger loads without issues.

**Comment by memsharded** [comment]
Hi @AliAskari 

Are you still having the same issue? Now that free Artifactory CE is available, it is the recommended way for large loads, concurrency, etc., as said above, it will scale much better than conan_server.

Could this issue be closed? Thanks!
