### ISSUE TITLE
ValueError causes an exception cascade

### ISSUE THREAD

**Issue by giraldeau** [conan-io/conan#1979]
Installing the dependencies as usual, but a strange behavior happened, but it does not reproduce. I upgraded my system and reinstalled the latest conan from pip, maybe there was some stalled data. Anyway, I just wanted to share that in case someone else has the same problem. Thanks!

```
icu/59rc@pbtrung/stable: Looking for package f5a6882590d137de693642227ed35e8e26da3dac in remote 'conan-transit' 
Downloading conanmanifest.txt
[==================================================] 13.6KB/13.6KB    
Downloading conaninfo.txt
[==================================================] 435B/435B        
Downloading conan_package.tgz
[==================================================] 12.9MB/12.9MB    
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/model/ref.py", line 70, in loads
    name, version, user, channel = tokens
ValueError: not enough values to unpack (expected 4, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 299, in install
    reference = ConanFileReference.loads(args.path)
  File "/usr/local/lib/python3.5/dist-packages/conans/model/ref.py", line 73, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference ..
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1125, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 310, in install
    install_folder=args.install_folder)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 66, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 496, in install
    no_imports=no_imports)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/manager.py", line 404, in install
    installer.install(deps_graph)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 290, in install
    self._build(nodes_by_level, skip_private_nodes, deps_graph)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 401, in _build
    self._get_remote_package(conan_file, package_ref, output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/installer.py", line 426, in _get_remote_package
    short_paths=conan_file.short_paths):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/proxy.py", line 102, in get_package
    output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/proxy.py", line 395, in _retrieve_remote_package
    self._remote_manager.get_package(package_ref, package_folder, remote)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/remote_manager.py", line 219, in get_package
    touch(os.path.join(dirname, fname))
  File "/usr/local/lib/python3.5/dist-packages/conans/util/files.py", line 53, in touch
    os.utime(fname, times)
FileNotFoundError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
```

**Comment by giraldeau** [comment]
Closing this issue since I cannot reproduce it at the moment.

**Comment by memsharded** [comment]
No problem, let us know if it happens again and you are able to reproduce

**Comment by memsharded** [comment]
Hi @HawkHow 

Could you please share the conanfile.txt that is firing this trace? Thanks!
