### ISSUE TITLE
Trouble exporting on macOS

### ISSUE THREAD

**Issue by reidhoch** [conan-io/conan#2146]
I'm currently running into an issue on our macOS (10.12) CI machines. `conan create` is failing when it attempts to export, I'm unable to reproduce this locally but it is consistent across all our macOS CI machines. The machines in question are running macOS 10.11, 10.12, and 10.13.

```
Successfully installed PyJWT-1.5.3 PyYAML-3.12 astroid-1.4.9 backport-ipaddress-0.1 backports.functools-lru-cache-1.4 bottle-0.12.13 cffi-1.11.2 colorama-0.3.9 conan-0.26.1 conan-package-tools-0.5.5 configparser-3.5.0 cryptography-1.4 distro-1.0.4 enum34-1.1.6 fasteners-0.14.1 future-0.16.0 idna-2.6 ipaddress-1.0.18 isort-4.2.15 lazy-object-proxy-1.3.1 mccabe-0.6.1 monotonic-1.4 ndg-httpsclient-0.4.3 node-semver-0.1.1 oauthlib-2.0.6 patch-1.16 pluginbase-0.5 pyOpenSSL-16.0.0 pyasn-1.5.0b7 pyasn1-0.4.2 pycparser-2.18 pygments-2.2.0 pylint-1.6.5 requests-2.8.1 requests-oauthlib-0.7.0 setuptools-38.2.4 six-1.11.0 wrapt-1.10.11
WARN: Remotes registry file missing, creating default one in /Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA@tmp/.conan/registry.txt
Current 'conan-center' user: None (anonymous)
Current 'conan-transit' user: None (anonymous)

############## CONAN PACKAGE TOOLS ######################

INFO: Not additional remotes declared... 

#########################################################


############## CONAN PACKAGE TOOLS ######################

INFO: ******** RUNNING BUILD ********** 
conan create jenkins/feature_xcode9 --profile /var/folders/x9/8qyp07493js2qbnc0mgg3mlm0000gn/T/tmpjmTB0kconan_package_tools_profiles/profile  

[build_requires]
[settings]
arch=x86_64
build_type=Debug
compiler=apple-clang
compiler.version=8.1
[options]
[scopes]
[env]
 

#########################################################

liblicensing/1.3.0.7@jenkins/feature_xcode9: Exporting package recipe
WARN: Conanfile doesn't have 'license'.
It is recommended to add it as attribute
Traceback (most recent call last):
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/command.py", line 884, in run
    method(args[0][1:])
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/command.py", line 184, in create
    channel=channel)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/conan_api.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/conan_api.py", line 286, in create
    version=version)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/manager.py", line 118, in export
    filename)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/export.py", line 61, in export_conanfile
    output, filename)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/export.py", line 144, in _execute_export
    copier(pattern, links=True, excludes=excluded_sources)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/file_copier.py", line 78, in __call__
    self._link_folders(src, dst, link_folders)
  File "/Users/localadmin/workspace/libLicensing_feature_xcode9-V54G2TU4NIXCYQZHQUB6G3YTKPABMRW4KCU2CVVACKNMIJI7UOPA/venv_x86_64_8.1_7/lib/python2.7/site-packages/conans/client/file_copier.py", line 147, in _link_folders
    os.symlink(link, linked_folder)
OSError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-transit: https://conan-transit.bintray.com [Verify SSL: True]
barbarian: http://barbarian[Verify SSL: True]
('Page       : ', 1)
Builds list:
[('settings', {'compiler.version': '8.1', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'apple-clang'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '8.1', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'apple-clang'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
Error while executing:
	 conan create jenkins/feature_xcode9 --profile /var/folders/x9/8qyp07493js2qbnc0mgg3mlm0000gn/T/tmpjmTB0kconan_package_tools_profiles/profile ```

**Comment by memsharded** [comment]
That is very weird, it looks like it is thinking there is some symlink subfolder in the folder it is being exported, but I don't know why it doesn't happen locally. Are you aware of some config in your CI machines that can cause it?, can you configure the CI script to do a listing ``ls -al`` of the folder before executing the ``conan create``

Also, not sure what conan version are you running. Thanks!

**Comment by reidhoch** [comment]
Our CI servers are typically set up via puppet IIRC, nothing out of the ordinary that I'm aware of.

```
drwxr-xr-x  18 localadmin  staff     612 Dec 12 16:32 .
drwxr-xr-x   4 localadmin  staff     136 Dec 12 16:31 ..
drwxr-xr-x  14 localadmin  staff     476 Dec 12 16:32 .git
-rw-r--r--   1 localadmin  staff      94 Dec 12 16:32 .gitignore
-rw-r--r--   1 localadmin  staff     105 Dec 12 16:32 .gitmodules
-rw-r--r--   1 localadmin  staff    1639 Dec 12 16:32 CMakeLists.txt
-rw-r--r--   1 localadmin  staff     414 Dec 12 16:32 ChangeLog
-rw-r--r--   1 localadmin  staff  109151 Dec 12 16:32 Doxyfile
-rw-r--r--   1 localadmin  staff    2562 Dec 12 16:32 EnableWarnings.cmake
-rw-r--r--   1 localadmin  staff     256 Dec 12 16:32 Jenkinsfile
-rw-r--r--   1 localadmin  staff    1657 Dec 12 16:32 build.py
-rw-r--r--   1 localadmin  staff    1586 Dec 12 16:32 conanfile.py
drwxr-xr-x   4 localadmin  staff     136 Dec 12 16:32 demos
drwxr-xr-x   3 localadmin  staff     102 Dec 12 16:32 docs
drwxr-xr-x  11 localadmin  staff     374 Dec 12 16:32 source
drwxr-xr-x   5 localadmin  staff     170 Dec 12 16:32 test_package
drwxr-xr-x   5 localadmin  staff     170 Dec 12 16:32 testing
drwxr-xr-x   3 localadmin  staff     102 Dec 12 16:32 workspace
```

**Comment by memsharded** [comment]
No idea of what the problem is, reviewed the code, and is like python is given a false positive for a folder, thinking it is a symlink. If you can run conan from one of my branches, I could prepare one with a few prints to try to debug it. We are also available to chat, if you want to try to pair-debug, please tell us.

**Comment by reidhoch** [comment]
Sure, please point me to your branch and I'll use it during my builds tomorrow

**Comment by memsharded** [comment]
Good, here it goes: https://github.com/memsharded/conan/tree/feature/debug_linked_folders
It is a branch in my fork, it adds a couple of prints, please tell me what happens. Many thanks!

**Comment by reidhoch** [comment]
Thanks for taking a look at this issue, I greatly appreciate it.
```(venv) localadminsmac2:modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA localadmin$ python build.py --arch x86_64 --apple-clang-version 9.0
('Page       : ', 1)
Builds list:
[('settings', {'compiler.version': '9.0', 'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'apple-clang'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
[('settings', {'compiler.version': '9.0', 'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'apple-clang'}), ('options', {}), ('env_vars', {}), ('build_requires', {})]
tidy-html5/0.1@jenkins/testing: Exporting package recipe
WARN: Conanfile doesn't have 'license'.
It is recommended to add it as attribute
WARN: Conanfile doesn't have 'description'.
It is recommended to add it as attribute
Root is symlink: /Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/include/python2.7
Root is symlink: /Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/config
Root is symlink: /Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/encodings
Root is symlink: /Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/lib-dynload
Linked folders: ['venv/include/python2.7', 'venv/lib/python2.7/config', 'venv/lib/python2.7/encodings', 'venv/lib/python2.7/lib-dynload']
Traceback (most recent call last):
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/command.py", line 884, in run
    method(args[0][1:])
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/command.py", line 184, in create
    channel=channel)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/conan_api.py", line 57, in wrapper
    return f(*args, **kwargs)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/conan_api.py", line 286, in create
    version=version)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/manager.py", line 118, in export
    filename)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/export.py", line 61, in export_conanfile
    output, filename)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/export.py", line 144, in _execute_export
    copier(pattern, links=True, excludes=excluded_sources)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/file_copier.py", line 79, in __call__
    self._link_folders(src, dst, link_folders)
  File "/Users/localadmin/workspace/modules_tidy-html5_testing-TGWP25SHBGF35QLPC2I4YFR4ADPBNYQ7WUT5ZFCWXEWQR4ZM3DPA/venv/lib/python2.7/site-packages/conans/client/file_copier.py", line 149, in _link_folders
    os.symlink(link, linked_folder)
OSError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
Error while executing:
	 conan create jenkins/testing --profile /var/folders/x9/8qyp07493js2qbnc0mgg3mlm0000gn/T/tmpmW6vKCconan_package_tools_profiles/profile```

**Comment by memsharded** [comment]
That seems the issue: there are some special things inside workspace, the full python installation, that cannot be copied. Is it your intent to copy the whole "workspace" (with a copy of conan itself and all its dependencies) into the package?

We can try to improve conan, so this error is not that ugly, or convert it to a warning, but I think you might want to selectively ``exports_sources`` only the things you want to put into the package. Please tell if this make sense, and what is your current ``exports_sources``. Thanks!

**Comment by reidhoch** [comment]
Thank you for looking into this, I was creating the virtualenv within the same directory as the source. I've updated our build scripts to create it in another directory and everything seems to work as expected. Thanks for clarifying the issue.

**Comment by memsharded** [comment]
You are very welcome, glad that it is working now :)

Even though, it is weird that it was producing that ugly stack trace, which was not very helpful. Unexpected stacktraces like that might be considered as bugs, so I am trying to improve this for next release, to avoid future problems. Thanks very much for your great help!
