### ISSUE TITLE
Comments are parsed in [imports] section of conanfile.txt

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#224]
I have the following in my `conanfile.txt` (with the comments as they are in the [docs](http://docs.conan.io/en/latest/manage_deps/conanfile_txt.html#imports)):

```
[imports]
bin, *.dll -> ./build/bin # Copies all dll files from the package "bin" folder to my project "bin" folder
lib, *.dylib* -> ./build/bin # Copies all dylib files from the package "lib" folder to my project "bin" folder
```
And what I get after a `conan install` is:

```
PROJECT: Generated conaninfo.txt
PROJECT: Generated cmake created conanbuildinfo.cmake
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<string>", line 6, in run
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.command", line 615, in main
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.command", line 529, in run
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.command", line 218, in install
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.manager", line 205, in install
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.importer", line 72, in execute
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\conans.client.file_copier", line 81, in __call__
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\shutil", line 130, in copy2
  File "C:\Users\lasot\workspace\dev-tools\installer\pyinstaller\conan\build\conan\out00-PYZ.pyz\shutil", line 83, in copyfile
IOError: [Errno 22] invalid mode ('wb') or filename: 'D:\\Development\\_VirtualEnvs\\neutron\\neutron\\processing\\compute_informer_order\\build\\bin # Copies all dll files from the package "bin" folder to my project "bin" folder\\zlibd.dll'
```
The last line has the comment inside it, building an invalid path:

 'D:\\Development\\_VirtualEnvs\\neutron\\neutron\\processing\\compute_informer_order\\build\\bin **# Copies all dll files from the package "bin" folder to my project "bin" folder**\\zlibd.dll'

Of course, after removing the comments in `conanfile.txt`, everything works as expected :dancer:

```
PROJECT: Generated conaninfo.txt
PROJECT: Generated cmake created conanbuildinfo.cmake
PROJECT imports(): Copied 32 '.dll' files
```

-----
conan version 0.8.5
win7 64bits
python 3.4.3

**Comment by memsharded** [comment]
Yes, this is a bug, please avoid the comments till we fix it, shouldn't be difficult (maybe you want to try? :) :) 
Thanks for reporting

**Comment by memsharded** [comment]
Should be fixed by PR https://github.com/conan-io/conan/pull/225. It is quite simple, but please have a look and ask any question about the implementation if you want. Cheers!

**Comment by jgsogo** [comment]
Sure it fixes it ;D I agree with you that it was easy for a first contribution, but at home I'm working with python 3 and I was lazy to install an environment for py2. Do you or @lasote need help with #205?

**Comment by memsharded** [comment]
Sure! Thanks very much. Yes, it would be great if you could have a look to #205 PR and review it, try to identify possible problems... any help is very, very appreciated. Upgrades and compatibility are always problematic, so the more eyes reviewing it, the better, thanks!
