### ISSUE TITLE
deploy and imports fail with read-only cache

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#2441]
When using deploy() in a package or imports as a package user, the copied files are read-only when the Conan cache is set to read-only (`general.read_only_cache=True`).

This causes every invocation of `conan install` after the first to fail because the deployed or imported files can't be overwritten. I expected Conan to take care of this. From my point of view, the fact the cache is read-only does not mean the deployed or imported files have to be read-only as well.

I've tested this with Conan 1.0.4 on both Windows 7 and Ubuntu 16.04.

Example logging of imports as a package user:
```
conan install -u --build=outdated --set build_type=Release --set compiler=Visual Studio --set compiler.runtime=MT D:\dev\ruggedsw\base\dds\test


PROJECT: Installing D:\dev\ruggedsw\base\dds\test\conanfile.txt
Requirements
    Boost/1.66.0-0@rugged/stable from shuttle
    google.test/1.8.0-0@rugged/stable from shuttle
    rugged.base/develop@demo/testing from local
    rugged.cmake/0.2.0@rugged/stable from shuttle
    rugged.dds/develop@demo/testing from local
    rugged.idl.coredx.cpp/develop@demo/testing from local
    twinoaks.coredx/4.0.16-0@rugged/stable from shuttle
    twinoaks.coredx.license/latest@rugged/stable from shuttle
Packages
    Boost/1.66.0-0@rugged/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    google.test/1.8.0-0@rugged/stable:7ce94352b9d6c95dd4f54be06f40814de83033cc
    rugged.base/develop@demo/testing:0360a5f1de3610acad6fc54319fae7f93d69080f
    rugged.cmake/0.2.0@rugged/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    rugged.dds/develop@demo/testing:be478f16b38bce7c5b9b377d28de2be18dd0f742
    rugged.idl.coredx.cpp/develop@demo/testing:cf3c4eea01e24ccdb48737197cec263338b785dc
    twinoaks.coredx/4.0.16-0@rugged/stable:7bd6f2c3d5c4e48a75805376b58cde753392f711
    twinoaks.coredx.license/latest@rugged/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Boost/1.66.0-0@rugged/stable: Package is up to date
google.test/1.8.0-0@rugged/stable: Package is up to date
rugged.cmake/0.2.0@rugged/stable: Package is up to date
twinoaks.coredx/4.0.16-0@rugged/stable: Package is up to date
twinoaks.coredx.license/latest@rugged/stable: Package is up to date
rugged.base/develop@demo/testing: Package is up to date
rugged.idl.coredx.cpp/develop@demo/testing: Package is up to date
rugged.dds/develop@demo/testing: Package is up to date
Boost/1.66.0-0@rugged/stable: Already installed!
google.test/1.8.0-0@rugged/stable: Already installed!
rugged.cmake/0.2.0@rugged/stable: Already installed!
twinoaks.coredx/4.0.16-0@rugged/stable: Already installed!
twinoaks.coredx.license/latest@rugged/stable: Already installed!
rugged.base/develop@demo/testing: Already installed!
rugged.idl.coredx.cpp/develop@demo/testing: Already installed!
rugged.dds/develop@demo/testing: Already installed!
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\conans\model\ref.py", line 70, in loads
    name, version, user, channel = tokens
ValueError: not enough values to unpack (expected 4, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\conans\client\command.py", line 243, in install
    reference = ConanFileReference.loads(args.path)
  File "c:\program files\python35\lib\site-packages\conans\model\ref.py", line 73, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference D:\dev\ruggedsw\base\dds\test
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\conans\client\command.py", line 1099, in run
    method(args[0][1:])
  File "c:\program files\python35\lib\site-packages\conans\client\command.py", line 254, in install
    install_folder=args.install_folder)
  File "c:\program files\python35\lib\site-packages\conans\client\conan_api.py", line 63, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python35\lib\site-packages\conans\client\conan_api.py", line 402, in install
    no_imports=no_imports)
  File "c:\program files\python35\lib\site-packages\conans\client\manager.py", line 385, in install
    run_imports(conanfile, install_folder, output)
  File "c:\program files\python35\lib\site-packages\conans\client\importer.py", line 72, in run_imports
    conanfile.imports()
  File "c:\program files\python35\lib\site-packages\conans\client\loader_parse.py", line 175, in imports
    conan_file.copy(*import_params)
  File "c:\program files\python35\lib\site-packages\conans\client\importer.py", line 139, in __call__
    excludes=excludes)
  File "c:\program files\python35\lib\site-packages\conans\client\file_copier.py", line 77, in __call__
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, links)
  File "c:\program files\python35\lib\site-packages\conans\client\file_copier.py", line 171, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "c:\program files\python35\lib\shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\program files\python35\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'D:\\dev\\ruggedsw\\base\\dds\\test\\build.vs.Release.Static\\CoreDXeval.lic'

ERROR: [Errno 13] Permission denied: 'D:\\dev\\ruggedsw\\base\\dds\\test\\build.vs.Release.Static\\CoreDXeval.lic'
```

Example logging of package with deploy() on Linux:

```
conan install -u --build=outdated rugged.python.build/0.2.0@rugged/stable
rugged.python.build/0.2.0@rugged/stable: Installing package
Requirements
    rugged.python.build/0.2.0@rugged/stable from shuttle
Packages
    rugged.python.build/0.2.0@rugged/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

rugged.python.build/0.2.0@rugged/stable: Package is up to date
rugged.python.build/0.2.0@rugged/stable: Already installed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1099, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 265, in install
    install_folder=args.install_folder)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 63, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 374, in install_reference
    install_reference=True)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/manager.py", line 392, in install
    run_deploy(deploy_conanfile, install_folder, output)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/importer.py", line 96, in run_deploy
    conanfile.deploy()
  File "/home/lewie/.conan/data/rugged.python.build/0.2.0/rugged/stable/export/conanfile.py", line 19, in deploy
    self.copy("rugged_build.py")
  File "/usr/local/lib/python3.5/dist-packages/conans/client/importer.py", line 88, in file_copier
    copied = file_copy(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/file_copier.py", line 77, in __call__
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, links)
  File "/usr/local/lib/python3.5/dist-packages/conans/client/file_copier.py", line 171, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "/usr/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/lewie/dev/ruggedsw/base/rugged_build.py'

ERROR: [Errno 13] Permission denied: '/home/lewie/dev/ruggedsw/base/rugged_build.py'
```

**Comment by memsharded** [comment]
We were thinking about this issue when that feature was implemented. There is a problem with changing permissions/modes of the deployed/imported artifacts, is that you don't respect possible permissions that were really set on purpose. It is possible, and in fact I have seen it, that users are setting custom permissions in the ``imports()`` or ``deploy()`` methods. Automatic addition of the ``write`` mode will overwrite their configuration.

So it doesn't have an easy solution, lets try to think something. 
Thanks very much for reporting this.

**Comment by lasote** [comment]
Fix approved:
 
When `general.read_only_cache=True` if any file is copied to a user space folder (imports / deploy) we set write permissions, always, to all artifacts, no matter if the original file had write permissions.
