### ISSUE TITLE
install through pip fails

### ISSUE THREAD

**Issue by KrayZeee** [conan-io/conan#2521]
hey im currenttly trying to get conan to run, but i am already stuck at the installation through pip (win10 fcu/python 3.6.4/pip 9.0.1)

it throws following exception:
```
Exception:
Traceback (most recent call last):
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 97: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\toni\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 97: invalid start byte
```

**Comment by memsharded** [comment]
Hi!

I think we have seen this error before. I am trying to locate the history, but meanwhile:

- are you running python 32 or 64 bits?. Even if notes in: http://docs.conan.io/en/latest/installation.html, could you please try also 64 bits?
- what is the locale/language of your Windows
- Are you using python for something else? Have you tried using a virtualenv for python?

Thanks!

**Comment by SSE4** [comment]
seems to be a python (pip) issue https://github.com/pypa/pip/issues/4110

**Comment by memsharded** [comment]
Actually, I recall that there was one of the conan python dependencies from PyPI that would fire the issue. We reported on it and had some workarounds, but can't find it. Could you please @KrayZeee copy the full installation output?

Also, trying the Python 2.7 conan package version could add additional information. Thanks
