### ISSUE TITLE
conan search gives AttributeError: 'UserIO' object has no attribute 'warn'

### ISSUE THREAD

**Issue by mattgodbolt** [conan-io/conan#2589]
Version: 1.1.1
OS: Linux Ubuntu 14.04 
conda: v4.2.7

Repro steps:
* `conda create -n conan python=2.7`
* `source activate conan`
* `pip install conan`
* `conan search zlib/1.2.11@conan/stable -r=conan-center`

Gives the following python stack:

```
(conan) ~ $ conan search zlib/1.2.11@conan/stable -r=conan-center
Traceback (most recent call last):
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/command.py", line 1131, in run
    method(args[0][1:])
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/command.py", line 814, in search
    outdated=args.outdated)
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/conan_api.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/conan_api.py", line 595, in search_packages
    outdated=outdated)
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/cmd/search.py", line 44, in search_packages
    remote = RemoteRegistry(self._client_cache.registry, self._user_io).remote(remote)
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/remote_registry.py", line 95, in remote
    remotes, _ = self._load()
  File "/home/mgodbolt/apps/miniconda/envs/conan/lib/python2.7/site-packages/conans/client/remote_registry.py", line 65, in _load
    self._output.warn("Remotes registry file missing, creating default one in %s"
AttributeError: 'UserIO' object has no attribute 'warn'

ERROR: 'UserIO' object has no attribute 'warn'
```

**Comment by mattgodbolt** [comment]
I just tried using `virtualenv` (v1.11.4) too, same issue.

```
$ conan search zlib/1.2.11@conan/stable -r=conan-center
Traceback (most recent call last):
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/command.py", line 1131, in run
    method(args[0][1:])
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/command.py", line 814, in search
    outdated=args.outdated)
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/conan_api.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/conan_api.py", line 595, in search_packages
    outdated=outdated)
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/cmd/search.py", line 44, in search_packages
    remote = RemoteRegistry(self._client_cache.registry, self._user_io).remote(remote)
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/remote_registry.py", line 95, in remote
    remotes, _ = self._load()
  File "/tmp/conan-ve/local/lib/python2.7/site-packages/conans/client/remote_registry.py", line 65, in _load
    self._output.warn("Remotes registry file missing, creating default one in %s"
AttributeError: 'UserIO' object has no attribute 'warn'
```

**Comment by memsharded** [comment]
This is very weird. The normal pip install works well, so I guess it might be something related to the conda install. Which is the conan version installed by conda? Can you please post the output of the install procedure? Are you able to install conan in the same machine with normal python (just ``pip install conan``)?

Do you have a link to the conda package for conan? Who created this package? I recall some conan user, but we didn't try it.

Thanks very much for your feedback Matt!

**Comment by memsharded** [comment]
Oh, you are totally right. I just reproduced it.

This is a very stupid bug. Just do a:

```bash
$ conan remote list
```
first, as a workaround, or a ``conan search zlib* -r=conan-center``, first, before the failing search command. 

We will release a fix as soon as possible.

**Comment by memsharded** [comment]
I have just submitted a fix for it in: https://github.com/conan-io/conan/pull/2592, and assigned for 1.2 release.

In second thought, I think a patch release is not really necessary, 1.2 will be out in a couple of weeks, the bug has a very simple workaround, the severity is small, and the likelihood of hitting it is very low. But please tell otherwise. Thanks!

**Comment by mattgodbolt** [comment]
Thanks all!
