### ISSUE TITLE
conan create is not working on the sample given in creating packages section of conan documentation

### ISSUE THREAD

**Issue by penugondac** [conan-io/conan#2678]
To help us debug your issue please explain:

- [Yes ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [yes ] I've specified the Conan version, operating system version and any tool that can be relevant.
1.1.1 conan verstion ,Linux Ubuntu, Python 2.7
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.
I tried to 
- conan new Hello/0.1 -t
- conan create . demo/testing
I got the below error when i performed the above steps.

pcreddy@vgitlab:~/conan-try/mypkg$ conan create . demo/testing
Hello/0.1@demo/testing: Exporting package recipe
Traceback (most recent call last):
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/command.py", line 1131, in run
    method(args[0][1:])
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/command.py", line 217, in create
    test_build_folder=args.test_build_folder)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 64, in wrapper
    return f(*args, **kwargs)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/conan_api.py", line 261, in create
    self._manager.export(conanfile_path, name, version, user, channel, keep_source)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/manager.py", line 155, in export
    self._user_io.out, self._client_cache)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/cmd/export.py", line 32, in cmd_export
    conan_linter(conanfile_path, output)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/cmd/export_linter.py", line 21, in conan_linter
    py3_msgs = _lint_py3(conanfile_path)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/cmd/export_linter.py", line 68, in _lint_py3
    output_json = _runner(args)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/conans/client/cmd/export_linter.py", line 51, in _runner
    Run(args, reporter=JSONReporter(output), exit=False)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/lint.py", line 1266, in __init__
    linter.load_default_plugins()
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/lint.py", line 479, in load_default_plugins
    checkers.initialize(self)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/checkers/__init__.py", line 119, in initialize
    register_plugins(linter, __path__[0])
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/utils.py", line 1033, in register_plugins
    module = modutils.load_module_from_file(join(directory, filename))
  File "/home/pcreddy/.local/lib/python2.7/site-packages/astroid/modutils.py", line 272, in load_module_from_file
    return load_module_from_modpath(modpath, path, use_sys)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/checkers/python3.py", line 124, in <module>
    class Python3Checker(checkers.BaseChecker):
  File "/home/pcreddy/.local/lib/python2.7/site-packages/pylint/checkers/python3.py", line 566, in Python3Checker
    'sys.version_info < (3, 0)',
  File "/home/pcreddy/.local/lib/python2.7/site-packages/astroid/node_classes.py", line 837, in repr_tree
    _repr_tree(self, result, set())
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/astroid/node_classes.py", line 826, in _repr_node
    depth)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/astroid/node_classes.py", line 826, in _repr_node
    depth)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 191, in dispatch
    impl = _find_impl(cls, registry)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 142, in _find_impl
    mro = _compose_mro(cls, registry.keys())
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 130, in _compose_mro
    return _c3_mro(cls, abcs=mro)
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 84, in _c3_mro
    other_c3_mros = [_c3_mro(base, abcs=abcs) for base in other_bases]
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 88, in _c3_mro
    [explicit_bases] + [abstract_bases] + [other_bases]
  File "/home/pcreddy/.local/lib/python2.7/site-packages/singledispatch.py", line 39, in _c3_merge
    raise RuntimeError("Inconsistent hierarchy")
RuntimeError: Inconsistent hierarchy

Could you pl. let me know how can I come out of this issue.

Regards

**Comment by memsharded** [comment]
It seem something is corrupted in your installation:
- Have you installed conan with pip?
- Did you have other python tools, previous to conan?
- Have you tried with a virtualenv (I recommend virtualenvwrapper)?

**Comment by memsharded** [comment]
Hi @penugondac 

Still same issue? Could you provide further details? It looked like you had a corrupted python installation.
I am closing this issue now, as didn't get a response, but please re-open or ask new questions if necessary. Thanks!
