### ISSUE TITLE
Jenkins Artifactory Plugin throws NoSuchFileException for artifacts.properties

### ISSUE THREAD

**Issue by tobysmith** [conan-io/conan#2757]
Conan Version: `1.2.3`
Jenkins Version: `2.107.1`
Artifactory Plugin Version: `2.15.1`

I'm trying to run the following Jenkins pipeline but it fails at the `def buildInfo = conanClient.run command: "install . --build missing"` step.

Possibly related: #2690 

Jenkinsfile:
```
pipeline {
    agent {
        dockerfile true
    }
    stages {
        stage('Build') {
            steps {
                script {
                    def server = Artifactory.server 'artifactory'
                    def conanClient = Artifactory.newConanClient()

                    String remoteName = conanClient.remote.add server: server, repo: "conan-local"

                    def buildInfo = conanClient.run command: "install . --build missing"

                    String command = "upload * --all -r ${remoteName} --confirm"
                    conanClient.run command: command, buildInfo: buildInfo

                    server.publishBuildInfo buildInfo
                }
            }
        }
    }
}
```

Stacktrace:
```
java.nio.file.NoSuchFileException: /tmp/conan396545227137368255/.conan/artifacts.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at hudson.FilePath$21.invoke(FilePath.java:1508)
	at hudson.FilePath$21.invoke(FilePath.java:1503)
	at hudson.FilePath.act(FilePath.java:1009)
	at hudson.FilePath.act(FilePath.java:987)
	at hudson.FilePath.touch(FilePath.java:1503)
	at org.jfrog.hudson.pipeline.steps.conan.RunCommandStep$Execution.persistBuildProperties(RunCommandStep.java:121)
	at org.jfrog.hudson.pipeline.steps.conan.RunCommandStep$Execution.run(RunCommandStep.java:84)
	at org.jfrog.hudson.pipeline.steps.conan.RunCommandStep$Execution.run(RunCommandStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tobysmith** [comment]
As a workaround I tried something similar as suggested in #2690 with

```
def userHome = conanClient.getUserPath()
sh "touch ${userHome}/.conan/artifacts.properties"
sh "ls -la ${userHome}/.conan/"
```

before the install step but encountered the same error.

**Comment by tobysmith** [comment]
I think I have solved this by using a userHome directory for conan and not relying on the tmp dir.

**Comment by memsharded** [comment]
Thanks for reporting @tobysmith and following up.

Glad you made it work. In any case the approach for tmp-dirs has to be revisited, thanks for your feedback!
