### ISSUE TITLE
del self.info.options.<option> in package_id() fails

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2826]
In [conan.io docs](http://docs.conan.io/en/latest/reference/conanfile/methods.html?highlight=deploy#self-info) I saw an example:
```python
def package_id(self):
    del self.info.settings.compiler
    del self.info.options.shared
```
So I expected the following should work:
```
from conans import ConanFile

class TestConan(ConanFile):
    name = "Test"
    version = "0.0.1"
    options = {"opt": [True, False]}
    default_options = "opt=False"

    def package(self):
        pass

    def package_info(self):
        del self.info.options.opt
```
But it does not:
```
conan create . dbely/testing
...
Test/0.0.1@dbely/testing: Calling package()
Test/0.0.1@dbely/testing: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
ERROR: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\conans\errors.py", line 24, in conanfile_exception_formatter
    yield
  File "c:\python36\lib\site-packages\conans\client\installer.py", line 473, in _call_package_info
    conanfile.package_info()
  File "C:\Users\dbely\.conan\data\Test\0.0.1\dbely\testing\export\conanfile.py", line 13, in package_info
    del self.info.options.opt
AttributeError: opt
```

**Comment by memsharded** [comment]
Yes, this is intended ``package_id()`` and ``package_info()`` are very different methods for different things. The ``self.info`` field is used exclusively for the computation of the binary package ID, and it should only be modified in the ``package_id()`` method.

May I ask why are you trying to delete the option in the ``package_info()`` method? What would be the use case for that? Thanks!

**Comment by db4** [comment]
Thanks, but `package_id()` fails too:
```python
from conans import ConanFile

class TestConan(ConanFile):
    name = "Test"
    version = "0.0.1"
    options = {"opt": [True, False]}
    default_options = "opt=False"

    def package(self):
        pass

    def package_id(self):
        del self.info.options.opt
```
```
ERROR: Test/0.0.1@dbely/testing: Error in package_id() method, line 13
        del self.info.options.opt
        AttributeError: opt
```
Am I still missing something?

> May I ask why are you trying to delete the option in the `package_info()` method? What would be the use case for that? Thanks!

There is an option that just sets an environment variable:
```python
    def package_info(self):
        ...
        if self.options.cygwin:
            self.output.info("Creating CYGWIN env var : %s" % self.options.cygwin)
            self.env_info.CYGWIN = str(self.options.cygwin)
```
I thought it could be safe to exclude it from `package_id()`

**Comment by memsharded** [comment]
Yes, @db4 you were totally right!
For some reason the "del" methods were not there for the options. Thanks very much for raising this bug.

I have just submitted a fix in PR #2844, I will try to have it in next minor release asap.
