### ISSUE TITLE
conan export: IOError: [Errno 6] No such device or address: '/tmp/.ICE-unix/2377'

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/conan#289]
Just installed conan from pip on Ubuntu 16.04 x64, followed [the docs](http://docs.conan.io/en/latest/packaging/creating_in.html), but when I came to:
```
$ conan export demo/testing
```
I got:
```
WARN: Conanfile doesn't have 'url'.
It is recommended to add your repo URL as attribute
WARN: Conanfile doesn't have a 'license'.
It is recommended to add the package license as attribute
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 680, in main
    error = command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 593, in run
    method(args[0][1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 385, in export
    self._manager.export(args.user, current_path, keep_source)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 112, in export
    conan_file.exports, conan_file_path, conan_ref, keep_source)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/export.py", line 20, in export_conanfile
    _export(file_patterns, origin_folder, destination_folder, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/export.py", line 60, in _export
    copier(pattern)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/file_copier.py", line 81, in __call__
    shutil.copy2(abs_src_name, abs_dst_name)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 6] No such device or address: '/tmp/.ICE-unix/2377'
```

**Comment by memsharded** [comment]
Very strange. Are you using some kind of temporary installation, sandbox, VM, virtualenv?

**Comment by SamuelMarks** [comment]
Nope, it was all installed globally with the regular `sudo -H pip install conan`

**Comment by memsharded** [comment]
And are you running it in a regular folder in your home? Not in temporary directory?

**Comment by SamuelMarks** [comment]
Oh, I cloned `hello` to `/tmp`

**Comment by memsharded** [comment]
``/tmp`` is not a good place to work. Weird things can happen :)

**Comment by memsharded** [comment]
Please tell me if everything works fine, close the issue in that case. Also if you need anything else, questions, support, I am also available at twitter (DM), hangouts.... Current timezone: Sydney ;)

**Comment by SamuelMarks** [comment]
Great thanks.

Confirmed

PS: I'll drop a task in https://github.com/conan-io/wishlist
