### ISSUE TITLE
ICU Build broken in Conan v1.4.0, worked in v1.3.0

### ISSUE THREAD

**Issue by hebaishi** [conan-io/conan#2973]
The upgrade to conan v1.4.0 has broken the ICU build, which is based on [this recipe](https://github.com/bincrafters/conan-icu). This build worked fine on conan v1.3.0. I'm attaching my conan recipe along with the test folder.
[icu.zip](https://github.com/conan-io/conan/files/2058153/icu.zip)

Building the ICU recipe now fails with the following message:
```
icu/60.2@demo/demo: Package 'b04c48a1d8327d9fb403b61492950b31c7b2c890' created
DEBUG :installer.py   [269]: Install-build 52.0773050785 [2018-05-31 13:13:55,772]
icu/60.2@demo/demo (test package): Generator cmake created conanbuildinfo.cmake
icu/60.2@demo/demo (test package): Generator txt created conanbuildinfo.txt
icu/60.2@demo/demo (test package): Generated conaninfo.txt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1182, in run
    method(args[0][1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 246, in create
    test_build_folder=args.test_build_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 77, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 325, in create
    test_build_folder, test_folder, conanfile_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/create.py", line 40, in create
    test_build_folder=test_build_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/test.py", line 39, in install_build_and_test
    keep_build=keep_build)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 344, in install
    run_imports(conanfile, install_folder, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/importer.py", line 82, in run_imports
    conanfile.imports()
  File "/home/hebaishi/git/conan-recipes/recipes/icu/test_package/conanfile.py", line 15, in imports
    self.copy("*.dll", dst="bin", src=lib_dir_src)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/importer.py", line 160, in __call__
    excludes=excludes, keep_path=keep_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/file_copier.py", line 83, in __call__
    self._link_folders(src, dst, link_folders)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/file_copier.py", line 149, in _link_folders
    os.symlink(link, dst_link)
OSError: [Errno 2] No such file or directory

ERROR: [Errno 2] No such file or directory
```

Operating System: Ubuntu 16.04, 64-bit
Conan version: v1.4.0
Compiler: GCC v5.4.0
Conan command: ```conan create -s compiler.version=5 -s build_type=Debug -s arch=x86_64 . demo/demo```

Note that I have changed the user/channel in the recipe to demo/demo. That is the only change I have made.

**Comment by memsharded** [comment]
Hi @hebaishi 

Thanks very much for reporting! Yes, we are aware of this issue, sorry for the inconvencien. We are about to release 1.4.1 that includes this fix, please stay tuned.
