### ISSUE TITLE
 cannot run tests on Ubuntu 14.04.3

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#3]
Operating system: Mint 17 (based on Ubuntu 14.04.3)

I tried to run the tests for the most recent version like this:
```sh
#!/usr/bin/env sh
git checkout 1cc3490f67c445a64c5a327df39b261b2b9df558
sudo apt-get install python-dev
sudo pip install -r requirements.txt
sudo pip install -r requirements_server.txt
sudo pip install -r requirements_dev.txt
nosetests .
```

This is the output:
```
$ ./run_tests.sh 
HEAD is now at 1cc3490... MIT LICENSED
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
Requirement already satisfied (use --upgrade to upgrade): PyJWT==1.4.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): cfgparse==1.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): passlib==1.6.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): boto==2.38.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): gevent==1.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements_server.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): bottle==0.12.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements_server.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): gunicorn==19.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_server.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /usr/local/lib/python2.7/dist-packages (from gevent==1.0.2->-r requirements_server.txt (line 2))
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements_dev.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): nose-parameterized==0.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_dev.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): mock==1.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements_dev.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): WebTest==2.0.18 in /usr/local/lib/python2.7/dist-packages (from -r requirements_dev.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from WebTest==2.0.18->-r requirements_dev.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): WebOb>=1.2 in /usr/local/lib/python2.7/dist-packages (from WebTest==2.0.18->-r requirements_dev.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): waitress>=0.8.5 in /usr/local/lib/python2.7/dist-packages (from WebTest==2.0.18->-r requirements_dev.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from WebTest==2.0.18->-r requirements_dev.txt (line 4))
Cleaning up...
E
======================================================================
ERROR: Failure: ImportError (No module named conans.model.conan_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/virtual/dev/conan/conans/__init__.py", line 3, in <module>
    from conans.model.conan_file import ConanFile
ImportError: No module named conans.model.conan_file

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

Am I doing something wrong?

**Comment by lasote** [comment]
Its a PYTHONPATH issue but I don't really know why.
Try to:

export PYTHONPATH=$PYTHONPATH:$(pwd)

and then nosetests

**Comment by lasote** [comment]
You should also export CONAN_COMPILER=gcc and CONAN_COMPILER_VERSION=4.8 for testing purposes. Check your gcc version (or maybe clang) and export the right one. I'm working in travis/appveyor integration and trying all this things. If you could update the testing instructions with your experience should be great! thanks

**Comment by TyRoXx** [comment]
Thank you, now it works:
```sh
#!/usr/bin/env sh
export PYTHONPATH=$PYTHONPATH:$(pwd)
export CONAN_COMPILER=gcc
export CONAN_COMPILER_VERSION=4.8
git checkout 1cc3490f67c445a64c5a327df39b261b2b9df558
sudo apt-get install python-dev
sudo pip install -r requirements.txt
sudo pip install -r requirements_server.txt
sudo pip install -r requirements_dev.txt
nosetests .
```

[...]
```
..................................................................................................................................................
----------------------------------------------------------------------
Ran 146 tests in 50.993s

OK
```

I will try and update README.

**Comment by lasote** [comment]
:) thx
