### ISSUE TITLE
help needed, recipe no longer builds

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan#3082]
Windows 7
Python 3.6.5
Conan v1.4.4
Visual Studio 2017

Using the following [recipe](https://github.com/conan-community/conan-bzip2). This recipe worked fine until I updated ```conan``` to ```v1.4.4``` (was on ```v1.2.3```). There is no clear indication what the error is.

I found that using ```subprocess.Popen``` instead of ```os.system``` resulted in a successful call to ```cmake``` (down in ```conans/client/runner.py```). Why use ```os.system``` at all? ```subprocess.Popen``` is much nicer to work with, in my experiences at least. That aside, I really have no idea what is happening and why it is bombing out.

Sorry for including so much output here...

### Raw Output 
```
[conan_env] PS C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6> conan create . sanchiri/unstable -pr sig
bzip2/1.0.6@sanchiri/unstable: Exporting package recipe
bzip2/1.0.6@sanchiri/unstable: The stored package has not changed
bzip2/1.0.6@sanchiri/unstable (test package): Installing C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6\test_package\conanfile.py
Requirements
    bzip2/1.0.6@sanchiri/unstable from local cache
Packages
    bzip2/1.0.6@sanchiri/unstable:ce1f8ff23addde793223a2a82ed7fe355c57a589

bzip2/1.0.6@sanchiri/unstable: WARN: Package is corrupted, removing folder: C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: WARN: Forced build from source
bzip2/1.0.6@sanchiri/unstable: Building your package in C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: Copying sources to build folder
bzip2/1.0.6@sanchiri/unstable: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6@sanchiri/unstable: Calling build()
bzip2/1.0.6@sanchiri/unstable:
bzip2/1.0.6@sanchiri/unstable: ERROR: Package 'ce1f8ff23addde793223a2a82ed7fe355c57a589' build failed
bzip2/1.0.6@sanchiri/unstable: WARN: Build folder C:\Users\sanchiri\.conan\data\
bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
ERROR: bzip2/1.0.6@sanchiri/unstable: Error in build() method, line 46
        cmake.configure(build_dir=".", source_dir="..")
        ConanException: Error -1 while executing cd . && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DFPIC="ON" -Wno-dev -T "v141" ..
```

### Debugger Output, observing conans\client\runner.py

```
[conan_env] PS C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6> conan create . sanchiri/unstable -pr sig
bzip2/1.0.6@sanchiri/unstable: Exporting package recipe
bzip2/1.0.6@sanchiri/unstable: The stored package has not changed
bzip2/1.0.6@sanchiri/unstable (test package): Installing C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6\test_package\conanfile.py
Requirements
    bzip2/1.0.6@sanchiri/unstable from local cache
Packages
    bzip2/1.0.6@sanchiri/unstable:ce1f8ff23addde793223a2a82ed7fe355c57a589

bzip2/1.0.6@sanchiri/unstable: WARN: Package is corrupted, removing folder: C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: WARN: Forced build from source
bzip2/1.0.6@sanchiri/unstable: Building your package in C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: Copying sources to build folder
bzip2/1.0.6@sanchiri/unstable: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6@sanchiri/unstable: Calling build()
> c:\users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\export\conanfile.py(48)build()
-> cmake.configure(build_dir=".", source_dir="..")
(Pdb) b c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py:90
Breakpoint 1 at c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py:90
(Pdb) continue
> c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py(90)_simple_os_call()
-> if not cwd:
(Pdb) cmdretval = os.system(command)
(Pdb) p cmdretval
-1
(Pdb) continue
bzip2/1.0.6@sanchiri/unstable:
bzip2/1.0.6@sanchiri/unstable: ERROR: Package 'ce1f8ff23addde793223a2a82ed7fe355c57a589' build failed
bzip2/1.0.6@sanchiri/unstable: WARN: Build folder C:\Users\sanchiri\.conan\data\
bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
ERROR: bzip2/1.0.6@sanchiri/unstable: Error in build() method, line 46
        cmake.configure(build_dir=".", source_dir="..")
        ConanException: Error -1 while executing cd . && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DFPIC="ON" -Wno-dev -T "v141" ..
Exception ignored in: <async_generator object _ag at 0x000000000287F1E8>
Traceback (most recent call last):
  File "c:\continuum\miniconda3\envs\conan_env\lib\types.py", line 27, in _ag
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 53, in trace_dispatch
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 79, in dispatch_call
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 176, in break_anywhere
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 36, in canonic
AttributeError: 'NoneType' object has no attribute 'abspath'
```

### Debugger Output, observing conans\client\runner.py, using Popen

```
[conan_env] PS C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6> conan create . sanchiri/unstable -pr sig
bzip2/1.0.6@sanchiri/unstable: Exporting package recipe
bzip2/1.0.6@sanchiri/unstable: The stored package has not changed
bzip2/1.0.6@sanchiri/unstable (test package): Installing C:\Users\sanchiri\Downloads\conan-bzip2-release-1.0.6\conan-bzip2-release-1.0.6\test_package\conanfile.py
Requirements
    bzip2/1.0.6@sanchiri/unstable from local cache
Packages
    bzip2/1.0.6@sanchiri/unstable:ce1f8ff23addde793223a2a82ed7fe355c57a589

bzip2/1.0.6@sanchiri/unstable: WARN: Package is corrupted, removing folder: C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: WARN: Forced build from source
bzip2/1.0.6@sanchiri/unstable: Building your package in C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
bzip2/1.0.6@sanchiri/unstable: Copying sources to build folder
bzip2/1.0.6@sanchiri/unstable: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6@sanchiri/unstable: Calling build()
> c:\users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\export\conanfile.py(48)build()
-> cmake.configure(build_dir=".", source_dir="..")
(Pdb) b c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py:90
Breakpoint 1 at c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py:90
(Pdb) continue
> c:\continuum\miniconda3\envs\conan_env\lib\site-packages\conans\client\runner.py(90)_simple_os_call()
-> if not cwd:
(Pdb) import subprocess
(Pdb) cmdretval = subprocess.Popen(command, shell=True)
-- The C compiler identification is MSVC 19.12.25835.0
-- The CXX compiler identification is MSVC 19.12.25835.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
CMake Warning at CMakeLists.txt:17 (MESSAGE):
  ENABLED FPIC


-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/sanchiri/.conan/data/bzip2/1.0.6/sanchiri/unstable/build/ce1f8ff23addde793223a2a82ed7fe355c57a589/bzip2-1.0.6/_build
(Pdb) p cmdretval.wait()
0
(Pdb) continue
bzip2/1.0.6@sanchiri/unstable:
bzip2/1.0.6@sanchiri/unstable: ERROR: Package 'ce1f8ff23addde793223a2a82ed7fe355c57a589' build failed
bzip2/1.0.6@sanchiri/unstable: WARN: Build folder C:\Users\sanchiri\.conan\data\
bzip2\1.0.6\sanchiri\unstable\build\ce1f8ff23addde793223a2a82ed7fe355c57a589
ERROR: bzip2/1.0.6@sanchiri/unstable: Error in build() method, line 46
        cmake.configure(build_dir=".", source_dir="..")
        ConanException: Error -1 while executing cd . && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\sanchiri\.conan\data\bzip2\1.0.6\sanchiri\unstable\package\ce1f8ff23addde793223a2a82ed7fe355c57a589" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DFPIC="ON" -Wno-dev -T "v141" ..
Exception ignored in: <async_generator object _ag at 0x000000000287F1E8>
Traceback (most recent call last):
  File "c:\continuum\miniconda3\envs\conan_env\lib\types.py", line 27, in _ag
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 53, in trace_dispatch
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 79, in dispatch_call
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 176, in break_anywhere
  File "c:\continuum\miniconda3\envs\conan_env\lib\bdb.py", line 36, in canonic
AttributeError: 'NoneType' object has no attribute 'abspath'
```

**Comment by memsharded** [comment]
I have ran a quick test, and here it is working fine:
```
$ git clone https://github.com/conan-community/conan-bzip2
$ cd conan-bzip2
$ conan create . user/testing
```
Windows 10, python2 and python3, VS2017

Maybe it could be something related to the miniconda environment? Could you please try in a regular clean python virtualenv?

**Comment by Lnk2past** [comment]
I don't know what I did, but it was my miniconda environment. I ended up just scrapping the whole env. Thanks for the suggestion @memsharded

**Comment by memsharded** [comment]
You are welcome :)
