### ISSUE TITLE
Criptic exception if float used for version in conanfile.py

### ISSUE THREAD

**Issue by ovidiub13** [conan-io/conan#3204]
Using Conan `1.5.2`, with the following `conanfile.py`:

```
from conans import ConanFile

class FooConan(ConanFile):
    name = "foo"
    version = 1.0
```
When running `conan create . foo/bar` it fails with the following criptic exception:

```
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\conans\client\command.py", line 1219, in run
    method(args[0][1:])
  File "c:\program files\python36\lib\site-packages\conans\client\command.py", line 246, in create
    test_build_folder=args.test_build_folder)
  File "c:\program files\python36\lib\site-packages\conans\client\conan_api.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python36\lib\site-packages\conans\client\conan_api.py", line 303, in create
    reference = ConanFileReference(name, version, user, channel)
  File "c:\program files\python36\lib\site-packages\conans\model\ref.py", line 57, in _new_
    ConanName.validate_name(version, True)
  File "c:\program files\python36\lib\site-packages\conans\model\ref.py", line 38, in validate_name
    if ConanName._validation_pattern.match(name) is None:
TypeError: expected string or bytes-like object

ERROR: expected string or bytes-like object
```

From here it's not clear as to why this exception is thrown. The reason is that the version should be a string, but there is no mention of version in the error, only of the name.

**Comment by memsharded** [comment]
Well, from the trace:

```
reference = ConanFileReference(name, version, user, channel)
ConanName.validate_name(version, True)
if ConanName._validation_pattern.match(name) is None:
TypeError: expected string or bytes-like object
```

I would say that is relatively helpful trace to deduce what could be happening.

**Comment by lasote** [comment]
You could guess it but I'm sure we could do it better than that ugly trace checking types even.

**Comment by joechrisellis** [comment]
Do you guys think it'd be better to automagically convert the float to a string in this context? So if the user specifies `version=1.2`, it gets converted to `version="1.2"`? Or just the error message wants to be less cryptic?

**Comment by memsharded** [comment]
I think it might be better if the user knows that they are strings, and no implicit conversion is done, just my personal opinion.
