### ISSUE TITLE
[TFS-Git repo] can't install config

### ISSUE THREAD

**Issue by cyan21** [conan-io/conan#3238]
When specifying a git repo hosted on TFS 2017, the "conan config install" fails withouth trying to do a "git clone".
It does work when pointing to a github repo
Git repos URL on TFS don't end by ".git"

Conan version : 1.4.5
OS :  Ubuntu 16.04 (xenial)
 
```/home/jfrog/.local/bin/conan config install  --verify-ssl=False http://<TFS_HOST>:8080/tfs/DefaultCollection/Conan-Demo/_git/Conan-config
Trying to download  http://<TFS_HOST>:8080/tfs/DefaultCollection/Conan-Demo/_git/Conan-config

Traceback (most recent call last):
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/command.py", line 1182, in run
    method(args[0][1:])
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/command.py", line 377, in config
    return self._conan.config_install(args.item, verify_ssl)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/conan_api.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/conan_api.py", line 509, in config_install
    return configuration_install(item, self._client_cache, self._user_io.out, verify_ssl)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/conf/config_installer.py", line 126, in configuration_install
    _process_download(item, client_cache, output, tmp_folder, verify_ssl)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/conf/config_installer.py", line 104, in _process_download
    _process_zip_file(zippath, client_cache, output, tmp_folder, remove=True)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/conf/config_installer.py", line 58, in _process_zip_file
    unzip(zippath, tmp_folder)
  File "/home/jfrog/.local/lib/python3.5/site-packages/conans/client/tools/files.py", line 81, in unzip
    with zipfile.ZipFile(filename, "r") as z:
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
ERROR: File is not a zip file
```

**Comment by memsharded** [comment]
Quick question. Even if the URL provided by TFS, what happens if you add ".git" to the end of that http URL? And if you add "/.git" to the end of the URL? Could you please paste here the errors that happen?
Thanks!

**Comment by markgalpin** [comment]
so what seems to be happening is that in configuration_install we have:
         if item.endswith(".git"):
            _process_git_repo(item, client_cache, output, tmp_folder, verify_ssl)

and otherwise it falls to process zip file if it is a URL -- but since the file isn't a zip file, we are getting this stack trace.  We might be able to look for the _git and/or the tfs in the URL to make this distinction for TFS repos?

**Comment by memsharded** [comment]
Yeah, we could look for git or tfs in the url, but seems a bit fragile too (what if /ip/path/to/magit/file).
``git`` itself migth be smart to strip the last ".git" or "/.git" from an URL. Otherwise, I'll suggest some additional syntax to define it is a git repo.
