### ISSUE TITLE
No such file or directory when importing symlinks

### ISSUE THREAD

**Issue by gnarlie** [conan-io/conan#3259]
When importing from a package that uses `symlinks=True`, I get an exception during the install. The link is created, but the target is not.

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1230, in run
    method(args[0][1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 325, in install
    install_folder=args.install_folder)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 79, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 482, in install
    no_imports=no_imports)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 308, in install
    run_imports(conanfile, install_folder, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/importer.py", line 86, in run_imports
    _report_save_manifest(copied_files, import_output, dest_folder, IMPORTS_MANIFESTS)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/importer.py", line 61, in _report_save_manifest
    file_dict[f] = md5sum(abs_path)
  File "/usr/local/lib/python2.7/dist-packages/conans/util/files.py", line 82, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/usr/local/lib/python2.7/dist-packages/conans/util/files.py", line 95, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
IOError: [Errno 2] No such file or directory: u'/home/badams/dev/fathom/lib/libserdes.so'
```

Conan version 1.6.0 (from pip install) on Ubuntu 18.04.

To help us debug your issue please explain:
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by gnarlie** [comment]
This was user error - my import specification was missing the trailing wildcard.

**Comment by memsharded** [comment]
Hi Brian,

Thanks for reporting and following up. I have checked if it is worth to capture the exception and output another error message, but I think that in the end, it might be easier to debug what is happening with the full trace, and this shouldn't be a very common user error.
