### ISSUE TITLE
conan remote list fails on Windows install [bug]

### ISSUE THREAD

**Issue by timdaman** [conan-io/conan#3433]
We are seeing an issue with Conan 1.7.0 but when we roll back to 1.6.1 it goes away.

Python version is 3.6.5
OS is Windows 10, v1803, os build 17134.228

Conan is installed with the following command
`c:\Python36\Scripts\pip3 install --upgrade conan`

Here is the error displayed
```
c:\dev\1\build>conan remote list
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (astroid 1.6.5 (c:\python36\lib\site-packages), Requirement.parse('astroid>=2.0.0'), {'pylint'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\conan-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (astroid 1.6.5 (c:\python36\lib\site-packages), Requirement.parse('astroid>=2.0.0'), {'pylint'})
```

I would expect this command to show a list of remotes currently configured and it does with older versions of Conan.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @timdaman 

Yes, we had to remove some dpendencies constraints to some PyPI dependencies to be able to work in the new Python 3.7. 

I have tried to run a clean installation for Python 3.6 in Windows, and it works, because it is installing Astroid 2.0.4. Is it possible that in your environment you are somehow restricting the Astroid dependency? Because I can read in your traces that your Astroid is somehow stalled in 1.6.5. Could you please try to remove your Astroid dependency first with ``pip`` then install conan again? I think that using virtualenvs to run conan, and isolate it from other python tools in the machine could help too. Please let me know, thanks!!
