### ISSUE TITLE
Unsuccessful upgrade 1.6.1->1.7.1

### ISSUE THREAD

**Issue by db4** [conan-io/conan#3448]
I have tried to upgrade conan via pip:
```
C:\Work>pip install --upgrade  conan
Collecting conan
  Downloading https://files.pythonhosted.org/packages/40/84/dacfc9f4b93e42462c8a9e5771c6ce0d25e0ad359914849e20b310ee7a40/conan-1.7.1.tar.gz (682kB)
    100% |████████████████████████████████| 686kB 1.8MB/s
Requirement not upgraded as not directly required: PyJWT<2.0.0,>=1.4.0 in c:\python37\lib\site-packages (from conan) (1.6.4)
Requirement not upgraded as not directly required: requests<3.0.0,>=2.7.0 in c:\python37\lib\site-packages (from conan) (2.19.1)
Requirement not upgraded as not directly required: colorama<0.4.0,>=0.3.3 in c:\python37\lib\site-packages (from conan) (0.3.9)
Requirement not upgraded as not directly required: PyYAML<3.14.0,>=3.11 in c:\python37\lib\site-packages (from conan) (3.12)
Requirement not upgraded as not directly required: patch==1.16 in c:\python37\lib\site-packages (from conan) (1.16)
Requirement not upgraded as not directly required: fasteners>=0.14.1 in c:\python37\lib\site-packages (from conan) (0.14.1)
Requirement not upgraded as not directly required: six>=1.10.0 in c:\python37\lib\site-packages (from conan) (1.11.0)
Requirement not upgraded as not directly required: node-semver==0.2.0 in c:\python37\lib\site-packages (from conan) (0.2.0)
Requirement not upgraded as not directly required: distro<1.2.0,>=1.0.2 in c:\python37\lib\site-packages (from conan) (1.1.0)
Collecting pylint>=1.9.3 (from conan)
  Downloading https://files.pythonhosted.org/packages/6e/c2/1e97c238877b6a86562d32297eb33a6670b6220e8ec0ca85f67b66dc893f/pylint-2.1.1-py3-none-any.whl (737kB)
    100% |████████████████████████████████| 747kB 1.6MB/s
Requirement not upgraded as not directly required: future==0.16.0 in c:\python37\lib\site-packages (from conan) (0.16.0)
Requirement not upgraded as not directly required: pygments<3.0,>=2.0 in c:\python37\lib\site-packages (from conan) (2.2.0)
Requirement not upgraded as not directly required: astroid>=1.6.5 in c:\python37\lib\site-packages (from conan) (1.6.5)
Requirement not upgraded as not directly required: deprecation<2.1,>=2.0 in c:\python37\lib\site-packages (from conan) (2.0.4)
Requirement not upgraded as not directly required: bottle<0.13,>=0.12.8 in c:\python37\lib\site-packages (from conan) (0.12.13)
Requirement not upgraded as not directly required: pluginbase<1.0,>=0.5 in c:\python37\lib\site-packages (from conan) (0.7)
Requirement not upgraded as not directly required: idna<2.8,>=2.5 in c:\python37\lib\site-packages (from requests<3.0.0,>=2.7.0->conan) (2.6)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in c:\python37\lib\site-packages (from requests<3.0.0,>=2.7.0->conan) (2018.4.16)
Requirement not upgraded as not directly required: urllib3<1.24,>=1.21.1 in c:\python37\lib\site-packages (from requests<3.0.0,>=2.7.0->conan) (1.23)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in c:\python37\lib\site-packages (from requests<3.0.0,>=2.7.0->conan) (3.0.4)
Requirement not upgraded as not directly required: monotonic>=0.1 in c:\python37\lib\site-packages (from fasteners>=0.14.1->conan) (1.5)
Requirement not upgraded as not directly required: mccabe in c:\python37\lib\site-packages (from pylint>=1.9.3->conan) (0.6.1)
Requirement not upgraded as not directly required: isort>=4.2.5 in c:\python37\lib\site-packages (from pylint>=1.9.3->conan) (4.3.4)
Requirement not upgraded as not directly required: lazy-object-proxy in c:\python37\lib\site-packages (from astroid>=1.6.5->conan) (1.3.1)
Requirement not upgraded as not directly required: wrapt in c:\python37\lib\site-packages (from astroid>=1.6.5->conan) (1.10.11)
Requirement not upgraded as not directly required: packaging in c:\python37\lib\site-packages (from deprecation<2.1,>=2.0->conan) (17.1)
Requirement not upgraded as not directly required: pyparsing>=2.0.2 in c:\python37\lib\site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.2.0)

pylint 2.1.1 has requirement astroid>=2.0.0, but you'll have astroid 1.6.5 which is incompatible.
Installing collected packages: pylint, conan
  Found existing installation: pylint 1.8.4
    Uninstalling pylint-1.8.4:
      Successfully uninstalled pylint-1.8.4
  The scripts epylint.exe, pylint.exe, pyreverse.exe and symilar.exe are installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Found existing installation: conan 1.6.1
    Uninstalling conan-1.6.1:
      Successfully uninstalled conan-1.6.1
  Running setup.py install for conan ... done
Successfully installed conan-1.7.1 pylint-2.1.1
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
and got broken conan install:
```
C:\Work>conan remote list
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (astroid 1.6.5 (c:\python37\lib\site-packages), Requirement.parse('astroid>=2.0.0'), {'pylint'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\conan-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (astroid 1.6.5 (c:\python37\lib\site-packages), Requirement.parse('astroid>=2.0.0'), {'pylint'})
```
Looks like a bug somewhere in conan 1.7.1 install. I'm no way an expert in Python packages so let me know if this is not enough to sort out the problem.

**Comment by db4** [comment]
BTW,
```
pip uninstall conan
pip install conan
```
does not help, but
```
pip uninstall conan
pip uninstall astroid
pip install conan
```
solves the problem

**Comment by db4** [comment]
Thanks. How to improve it? `conan remote list fails on Windows install [bug]` title you referenced is also not very helpful: not only `conan remote list` fails but other conan commands as well, this is not  install but upgrade problem etc.

**Comment by danimtb** [comment]
Sorry @db4, I actually meant that the tittle `conan remote list fails on Windows install [bug]` is the one to be improved, yours is totally fine. Thanks for reporting 😄

**Comment by danimtb** [comment]
Closing this as no further action could be done and there are a bunch of new Conan releases now. Thanks!
