### ISSUE TITLE
self.source_folder should be set within ConanFile.imports()

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#3618]
self.source_folder is not set within ConanFile.imports(). I need to copy files from build_requires packages to the source folder.

**Comment by sigiesec** [comment]
I also tried to use
```
inspect.getsourcefile(self.__class__)
```
within my imports method, but this raises an exception:
```
Traceback (most recent call last):
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\command.py", line 1287, in run
    method(args[0][1:])
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\command.py", line 336, in install
    install_folder=args.install_folder)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\conan_api.py", line 82, in wrapper
    return f(*args, **kwargs)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\conan_api.py", line 471, in install
    no_imports=no_imports)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\manager.py", line 169, in install
    run_imports(conanfile, install_folder, output)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\importer.py", line 82, in run_imports
    conanfile.imports()
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conan_template\ConanTemplate.py", line 227, in imports
    dst = os.path.dirname(inspect.getfile(self.__class__))
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\inspect.py", line 613, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: None is a built-in class
```

Under other circumstances, this approach works, such as in:
```
import inspect

class FooBase(object):
    def bar(self):
        print(inspect.getsourcefile(self.__class__))

class FooDerived(FooBase):
    pass
    

FooDerived().bar()
```

**Comment by lasote** [comment]
It is intentionally. Why copying to the `source_folder` and not to the `build_folder`?

**Comment by sigiesec** [comment]
The files to be imported must be located in the source folder (for now, these are .clang-tidy and .clang-format files, which are by default searched for by clang-tidy and clang-format, and the VS clang-format support, in the source tree).

**Comment by sigiesec** [comment]
If I can't access self.source_folder in package, can I do this in some other method that is called when running `conan build --configure`?

**Comment by lasote** [comment]
> The files to be imported must be located in the source folder

But, why? Why `clang-tidy` and `clang-format` are looking for these files in the source_folder and not in the build_folder?

**Comment by sigiesec** [comment]
It's because for each source file they work on, they search for a .clang-tidy/.clang-format file in its directory, then in the directory above etc.

**Comment by lasote** [comment]
Right, thanks, but there are two possibilities:

a) If you are not using [no_copy_source](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=no_copy_source#no-copy-source) (default), the source folder contents will be copied to a build folder, so the files you mention will be imported there before the build() process.

b) If you are specifying `no_copy_source`, the `build_folder` will point to the `source_folder` so you will be also importing to the `source_folder`.

Sorry but I still don't get it.

**Comment by lasote** [comment]
Right, but then you can point the `build_folder` to the "disk source folder" doing: `--build-folder xxx`

**Comment by lasote** [comment]
and ``--source-folder=yyy`` also if it is needed.

**Comment by sigiesec** [comment]
Now you lost me... Apart from that I don't think that it is acceptable to modify our conan calls everywhere just to make this possible and conan knows the source_folder (!), I don't understand what you suggest to do.

Very much simplified, I have a setup like this:
```
/foo/conanfile.py
/foo/CMakeLists.txt
/foo/Bar/include/bar.h
/foo/Bar/src/bar.cpp
```

So in my understanding, /foo is the source folder here.

The build folder might be located elsewhere, e.g. in /build

I would run `conan install /foo` and `conan build --configure /foo` from within the build folder, and end up with
```
/build/conanbuildinfo.cmake
/build/foo-x64-Debug.sln
```
and many more files created by cmake.

So, referring to your last two messages, what would xxx and yyy be, and to what call should they be passed?

**Comment by lasote** [comment]
> Apart from that I don't think that it is acceptable to modify our conan calls everywhere just to make this possible and conan knows the source_folder (!)

The imports do not have access to the `source_folder` **in purpose**. The source folder is intended to be shared between all the different builds and shouldn't depend on any setting/option. So if you import from the dependencies files to the `source` folder you would be messing with the next build.

In the Conan local flow, it can be true or not, depending if you are generating multiple builds from the same sources, so this is your choice. You can:

a) Copy manually the sources to the `build_folder` and call `conan build` with ``--source-folder`` and ``build-folder`` pointing to the same build folder.

b) Use directly the source folder as the build folder.

**Comment by sigiesec** [comment]
a) and b) are no acceptable options.

I am aware of that the source folder is shared between builds, but this build_requires dependency is not dependent on any options (build_type, compiler, etc.).

Of course, care must be taken when copying files to the source folder, and it is our responsibility to define a policy, e.g. whether to overwrite the files if they already exist. But conan should not be in the way of this.

I was hoping to be able to use conan for this purpose. We considered other options such as using git submodules, but we would really like to use conan to have a uniform mechanism. 

I would like to get back to my question from above:
> If I can't access self.source_folder in imports, can I do this in some other method that is called when running conan build --configure?

**Comment by lasote** [comment]
| I was hoping to be able to use conan for this purpose.

So sorry.

| If I can't access self.source_folder in imports, can I do this in some other method that is called when running conan build --configure?

Yes, you can access the `source_folder` in the `build()` method.

**Comment by sigiesec** [comment]
Unfortunately, within the build method, self.copy cannot be called.

**Comment by sigiesec** [comment]
Ok, I am now instantiating my own FileCopier, and this seems to work.

Thanks!
