### ISSUE TITLE
Conan server: missing lock for concurrent uploads

### ISSUE THREAD

**Issue by guyguy333** [conan-io/conan#3624]
Hello,

We're using Conan server with a CI system. During a specific step of the CI pipeline, we upload concurrently packages for various configurations. We use `--all` flag on all upload commands. It implies recipe is overwritten multiple time with the same thing. It is not an issue for us. But here is what happens randomly:

```
Uploading xxxx/1.0@remote/stable to remote 'remote'

Compressing recipe...                                                 
Compressing recipe sources...                                         Please log in to "XXX" to perform this action. Execute "conan user" command.
Remote 'remote' username: Got username 'XXXXX' from environment
Please enter a password for "XXXXX" account: Got password '******' from environment

Uploading conanmanifest.txt                                           

ERROR: 
Error uploading file: conanmanifest.txt, 'b"[Errno 2] No such file or directory: '/data/XXXX/1.0/remote/stable/export/conanmanifest.txt'"'

Uploading conan_sources.tgz                                           

ERROR: Execute upload again to retry upload the failed files: conanmanifest.txt. [Remote: remote]
ERROR: Job failed: exit code 1
```

"No such file or directory" is a server path.

Here is the command used to upload the package:

``` conan upload xxxx@xxxx/stable --all --force --remote remote ```

The disk storing the files is a bit slow and I guess this is  why the issue was not reported before. I looked at Conan server source code.  According to me, there should be a lock somewhere to prevent concurrent overwrite of the same files at the same time. For example:

https://github.com/conan-io/conan/blob/develop/conans/server/service/service.py#L49

I believe what happens is that the file exists and enter into the condition. Then, another concurrent upload remove the file because it already entered in the condition. Finally, the first one is unable to remove the file. It fails and break the upload. It's just a theory anyway.

Thanks,

Guillaume

Conan Version: 1.7.3

Here is a part of the server log:

```
 FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_export.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 51, in put_file
    file_saver.save(os.path.dirname(abs_filepath))
  File "/home/conan/.pythonbase/bin/bottle.py", line 2402, in save
    raise IOError('File exists.')
OSError: File exists.
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conanmanifest.txt'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 51, in put_file
    file_saver.save(os.path.dirname(abs_filepath))
  File "/home/conan/.pythonbase/bin/bottle.py", line 2402, in save
    raise IOError('File exists.')
OSError: File exists.
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 51, in put_file
    file_saver.save(os.path.dirname(abs_filepath))
  File "/home/conan/.pythonbase/bin/bottle.py", line 2402, in save
    raise IOError('File exists.')
OSError: File exists.
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conanfile.py'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conanmanifest.txt'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_sources.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_sources.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/bottle_plugins/authorization_header.py", line 44, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/conan_controller.py", line 56, in get_conanfile_snapshot
    snapshot = conan_service.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/service/service.py", line 155, in get_conanfile_snapshot
    snap = self._server_store.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/store/server_store.py", line 40, in get_conanfile_snapshot
    return self._get_snapshot_of_files(self.export(reference))
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/bottle_plugins/authorization_header.py", line 44, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/conan_controller.py", line 121, in get_package_upload_urls
    urls = conan_service.get_package_upload_urls(package_reference, filesizes)
  File "/home/conan/conan/conans/server/service/service.py", line 221, in get_package_upload_urls
    self._server_store.get_conanfile_snapshot(package_reference.conan)
  File "/home/conan/conan/conans/server/store/server_store.py", line 40, in get_conanfile_snapshot
    return self._get_snapshot_of_files(self.export(reference))
  File "/home/conan/conan/conans/server/store/server_store.py", line 49, in _get_snapshot_of_files
    snapshot = self._storage_adapter.get_snapshot(relative_path)
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in get_snapshot
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in <dictcomp>
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/util/files.py", line 82, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/home/conan/conan/conans/util/files.py", line 95, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conanmanifest.txt'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_export.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_sources.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 51, in put_file
    file_saver.save(os.path.dirname(abs_filepath))
  File "/home/conan/.pythonbase/bin/bottle.py", line 2402, in save
    raise IOError('File exists.')
OSError: File exists.
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conanmanifest.txt'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/file_upload_download_controller.py", line 38, in put
    service.put_file(file_saver, abs_path, token, request.content_length)
  File "/home/conan/conan/conans/server/service/service.py", line 50, in put_file
    os.remove(abs_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_sources.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/bottle_plugins/authorization_header.py", line 44, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/conan_controller.py", line 56, in get_conanfile_snapshot
    snapshot = conan_service.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/service/service.py", line 155, in get_conanfile_snapshot
    snap = self._server_store.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/store/server_store.py", line 40, in get_conanfile_snapshot
    return self._get_snapshot_of_files(self.export(reference))
  File "/home/conan/conan/conans/server/store/server_store.py", line 49, in _get_snapshot_of_files
    snapshot = self._storage_adapter.get_snapshot(relative_path)
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in get_snapshot
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in <dictcomp>
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/util/files.py", line 82, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/home/conan/conan/conans/util/files.py", line 95, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/data/xxxx/1.0/xxxx/stable/export/conan_sources.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/bottle_plugins/authorization_header.py", line 44, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/conan_controller.py", line 56, in get_conanfile_snapshot
    snapshot = conan_service.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/service/service.py", line 155, in get_conanfile_snapshot
    snap = self._server_store.get_conanfile_snapshot(reference)
  File "/home/conan/conan/conans/server/store/server_store.py", line 40, in get_conanfile_snapshot
    return self._get_snapshot_of_files(self.export(reference))
  File "/home/conan/conan/conans/server/store/server_store.py", line 49, in _get_snapshot_of_files
    snapshot = self._storage_adapter.get_snapshot(relative_path)
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in get_snapshot
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 69, in <dictcomp>
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/util/files.py", line 82, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/home/conan/conan/conans/util/files.py", line 95, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
```

**Comment by guyguy333** [comment]
Finally, the issue is also happening with Gunicorn worker argument equals to 1.

```
FileNotFoundError: [Errno 2] No such file or directory: '/data/XXXXX/0.1.0/XXXXXX/stable/export/conan_export.tgz'
Traceback (most recent call last):
  File "/home/conan/conan/conans/server/rest/bottle_plugins/return_handler.py", line 32, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/bottle_plugins/authorization_header.py", line 44, in wrapper
    return callback(*args, **kwargs)  # kwargs has :xxx variables from url
  File "/home/conan/conan/conans/server/rest/controllers/v1/conan_controller.py", line 56, in get_recipe_snapshot
    snapshot = conan_service.get_recipe_snapshot(reference)
  File "/home/conan/conan/conans/server/service/service.py", line 155, in get_recipe_snapshot
    snap = self._server_store.get_recipe_snapshot(reference)
  File "/home/conan/conan/conans/server/store/server_store.py", line 40, in get_recipe_snapshot
    return self._get_snapshot_of_files(self.export(reference))
  File "/home/conan/conan/conans/server/store/server_store.py", line 49, in _get_snapshot_of_files
    snapshot = self._storage_adapter.get_snapshot(relative_path)
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 74, in get_snapshot
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/server/store/disk_adapter.py", line 74, in &lt;dictcomp&gt;
    return {filepath: md5sum(filepath) for filepath in abs_paths}
  File "/home/conan/conan/conans/util/files.py", line 95, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "/home/conan/conan/conans/util/files.py", line 108, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
```

**Comment by memsharded** [comment]
Hi @guyguy333 

Yes, it is possible that there are concurrency issues and locks might be necessary in conan_server. 
Have you tried Artifactory CE? It is free (even for commercial purposes), and not only has more features (like web UI) than conan_server, but also the concurrency and robustness would be way better than the conan_server.

**Comment by guyguy333** [comment]
Thanks @memsharded. Is the source code available for Artifactory CE ? I'm unable to find it.

**Comment by memsharded** [comment]
Artifactory CE is free, not open-source.

**Comment by guyguy333** [comment]
Ok so we have to stick with the open source implementation provided by this repository as we added custom parts (things we can't do with Artifactory CE).

**Comment by monsdar** [comment]
See the linked #4843 for a different error message but probably a similar error-source :/

Right now this happens more often than not, we'll move to Artifactory soon though... So there's a workaround already in the making ;)

**Comment by memsharded** [comment]
Closing this ticket as outdated, at the moment it is not planned to implement this level of concurrency.
