### ISSUE TITLE
Conan info can not provide graph

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3915]
To help us debug your issue please explain:

When trying to get package info I receive the follow error:

```
conan info -r conan-community parallelstl/20181004@conan/stable --graph info.html
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/conans/client/command.py", line 1428, in run
    method(args[0][1:])
  File "/opt/miniconda3/lib/python3.6/site-packages/conans/client/command.py", line 556, in info
    self._outputer.info_graph(args.graph, deps_graph, get_cwd())
  File "/opt/miniconda3/lib/python3.6/site-packages/conans/client/conan_command_output.py", line 96, in info_graph
    grapher.graph_file(graph_filename)
  File "/opt/miniconda3/lib/python3.6/site-packages/conans/client/graph/grapher.py", line 129, in graph_file
    save(filename, self.graph())
  File "/opt/miniconda3/lib/python3.6/site-packages/conans/client/graph/grapher.py", line 151, in graph
    data = data.replace("'", '"')
AttributeError: 'tuple' object has no attribute 'replace'

ERROR: 'tuple' object has no attribute 'replace'
```

#### Environment
Conan Version: 1.9.0
Python Version: 3.6 (miniconda)
OS: Linux

#### Steps to reproduce
    $ conan info -r conan-community parallelstl/20181004@conan/stable --graph index.html

#### Expected result
Create index.html file with ParallelSTL info

#### Actual result
Error (1), including stack trace

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I think this could be related to #3908 ?

**Comment by uilianries** [comment]
Yes, thanks!
