### ISSUE TITLE
[workspaces] Breaking change from commit 57e143594db8e1e25b98215c7fd78dbd68dbb329

### ISSUE THREAD

**Issue by oilol** [conan-io/conan#4111]
From this commit we can have the folowing values in:
  **previous_ref.revision**   one from :  **None, 0 , hash**.
from ( client/graph/graph_builder.py, def _conflicting_references(previous_ref, new_ref))
But on the next line we have assert: 
`assert(previous_ref.revision is not None)`
and get the folowing Traceback because the previous_ref.revision is **None**!:
``
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 1428, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 383, in install
    install_folder=args.install_folder)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 522, in install
    manager.install_workspace(profile, workspace, remote_name, build, update)
  File "/usr/local/lib/python3.7/site-packages/conans/client/manager.py", line 37, in install_workspace
    workspace)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 133, in load_graph
    processed_profile=processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 204, in _load_graph
    graph = builder.load_graph(root_node, check_updates, update, remote_name, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 40, in load_graph
    processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 106, in _load_deps
    remote_name, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 106, in _load_deps
    remote_name, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 106, in _load_deps
    remote_name, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 114, in _load_deps
    require.conan_reference)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 142, in _conflicting_references
    assert(previous_ref.revision is not None)
AssertionError
``
Please remove this assert.
Thanks!
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by oilol** [comment]
This is example:
```
 1) pip3 install conan==1.9.2
 2) conan install  .  -if=build -s build_type=Debug
```
[conan-workspace-example.zip](https://github.com/conan-io/conan/files/2673114/conan-workspace-example.zip)

Everything looks ok.
```
 1) pip3 install conan==1.10.1
 2) conan install  .  -if=build -s build_type=Debug
```
Look at assertion error
But now it is clear for me. I just remove duplicated requires and it is work)

**Comment by oilol** [comment]
For example:
checkout for conan 1.9.2 (pip3 install conan==1.9.2):

in class ConanFileReference ( 66 line, model/ref.py)
add `print` to method    ` def loads(text, validate=True):`, this looks  like this:
`        except ValueError:
            raise ConanException("Wrong package recipe reference %s\nWrite something like "
                                 "OpenCV/1.0.6@user/stable" % text)
        **print('package_ : ', name, 'revision :', revision)**
        obj = ConanFileReference(name, version, user, channel, revision, validate=validate)
        return obj`

Download workspace example:
`git clone https://github.com/memsharded/conan-workspace-example.git`
`conan install . -if=build -pr=`

```
The output:
Using conanws.yml file from /Users/avalasniou/Desktop/trash/conan-workspace-example
package_ :  HelloA revision : None    <--- Revision is **None**
package_ :  HelloB revision : None
package_ :  HelloC revision : None
package_ :  HelloC revision : None
package_ :  HelloB revision : None
package_ :  HelloC revision : None
package_ :  HelloA revision : None
package_ :  HelloC revision : None
package_ :  HelloB revision : None
Workspace: Installing...
```

Try with conan 1.10.1:

`pip3 install conan==1.10.1`

**Comment by oilol** [comment]
Another example: 
[conan-workspace-example-2.zip](https://github.com/conan-io/conan/files/2675010/conan-workspace-example-2.zip)

On conan 1.9.2:  OK
1) conan install  . -if=build -s build_type=Debug .  
2) conan install  . -b -if=build -s build_type=Debug

On conan 1.10.1
1) Error
2) Error

So this is really breaking change...

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this as outdated.
