### ISSUE TITLE
[workspaces] Cannot install with workspace

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4180]
I am using conan 1.11.0 and am on my first attempt to use the workspace feature.

I have a conanws.yml file containing:
```
Application:
        folder: application
        includedirs: Application
        cmakedirs: .

Logging:
        folder: logging
        includedirs: Logging
        cmakedirs: .

root: Application
generator: cmake
name: AppPlusLogg
```

But when running `conan install -if=build` I get the following error:
```
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\model\ref.py", line 116, in loads
    _, name, version, user, channel, revision, _ = ConanFileReference.sep_pattern.split(text)
ValueError: not enough values to unpack (expected 7, got 1)
```

Unfortunately, I cannot see here which "text" is tried to split. Any idea where this might come from?

The output is followed by
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\command.py", line 371, in install
    reference = ConanFileReference.loads(args.path_or_reference)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\model\ref.py", line 119, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference .
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\command.py", line 1427, in run
    method(args[0][1:])
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\command.py", line 382, in install
    install_folder=args.install_folder)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\conan_api.py", line 87, in wrapper
    return f(*args, **kwargs)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\conan_api.py", line 517, in install
    manager.install_workspace(graph_info, workspace, remote_name, build, update)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\client\manager.py", line 45, in install_workspace
    workspace.generate()
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\model\workspace.py", line 114, in generate
    build_folder = workspace_package.build_folder
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\model\workspace.py", line 38, in build_folder
    folder = self._evaluate(self._build_folder)
  File "c:\users\sigiesec\appdata\local\programs\python\python35\lib\site-packages\conans\model\workspace.py", line 70, in _evaluate
    settings = self.conanfile.settings
AttributeError: 'NoneType' object has no attribute 'settings'

ERROR: 'NoneType' object has no attribute 'settings'
```

**Comment by memsharded** [comment]
Hi @sigiesec 

If you haven't used workspaces yet, I would recommend to wait a bit until trying to use them. Right now, the workspaces are put a bit on-hold, until the *editable* packages are released.

I would suggest to track efforts here: #4181, it is likely that they will be released next conan 1.12. Testing and feedback will be very welcome.

The idea is to stabilize editable packages first, then rebase the workspaces on the editable packages.

**Comment by sigiesec** [comment]
Hi @memsharded 

Thanks for the advice. I will give it a look again next year.

I suspected there might be issues, but was unfortunately stopped at a very early stage.

We use cmake-level exports in our conan packages, and I was curious if there is sufficient support for this to be able to work. Do you know if this is considered by the workspace feature?

**Comment by sigiesec** [comment]
I think this problem has been resolved in the meantime. Or maybe this was caused by a wrong order of subprojects? In my example, the root came before its dependency, maybe this is not a correct use? Or should the order be irrelevant? (cf. #4558 )

**Comment by memsharded** [comment]
Hi @sigiesec 

As commented in the other issue, this is about to be superseded by the new Workspaces being based on Editable packages. All the above code in the traceback is no longer there, so I think this issue can be closed, and if it persist in some mode after Conan 1.13, please open a new issue. Thanks!
