### ISSUE TITLE
Can not update Conan on OSX + Python 3

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#4331]
To help us debug your issue please explain:

Hi!

I'm trying to update log4cplus Conan package, but there is an error when OSX jobs are running:

> Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 18.0.0 (/Users/travis/.pyenv/versions/3.7.1/envs/conan/lib/python3.7/site-packages), Requirement.parse('pyOpenSSL<18.0.0,>=16.0.0'), {'conan'})

https://travis-ci.com/bincrafters/conan-log4cplus/jobs/171126589#L4134

Seems like this error only occurs to python 3.7.1, because I've executed a dummy project to check for Python 2.7 when it's working fine: 

https://travis-ci.org/uilianries/conan-hello-openssl/jobs/480933391#L2224

Conan Version: 1.11.2

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Try to search on google if you can find similar issues for other products or try to figure out what is the root cause. If you need help with Mac @jgsogo can help natively

**Comment by uilianries** [comment]
Sure!

**Comment by uilianries** [comment]
@lasote The error comes from CPT:

https://travis-ci.com/bincrafters/conan-log4cplus/jobs/171126589#L4046
> Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]->conan_package_tools)
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB) 

However, Conan requires `pyOpenSSL>=16.0.0, <18.0.0` for OSX:
 
https://github.com/conan-io/conan/blob/develop/conans/requirements_osx.txt#L3

I think the best option is update Conan to accept pyOpenSSL <19.0.0

**Comment by uilianries** [comment]
@memsharded @lasote Why should we force idna, cryptography and pyOpenSSL for [OSX](https://github.com/conan-io/conan/blob/develop/conans/requirements_osx.txt), instead of using [requests[security]](https://github.com/requests/requests/blob/b66908e7b647689793e299edc111bf9910e93ad3/setup.py#L98). All three packages are declared there. I think `requests[security]` should be enough to solve this conflict problem.

**Comment by uilianries** [comment]
What about introduce the dependencies here in Conan, and remove from CPT only? I know, take a ride for dependencies is not cool, but it will solve the version alignment problem, also CPT doesn't call ssl directly.

**Comment by lasote** [comment]
We could try, yes, to remove the deps in CPT.

**Comment by uilianries** [comment]
thanks!
