### ISSUE TITLE
Broken tests in Mac with apple-clang 10.0 as default [PR 4332] [BROKEN DEVELOP]

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4339]
⚠️ ⚠️  PR #4332 breaks in my Mac, there is a test that fails (commit hash e2246c90):

> CMakeGeneratorTest::test_cmake_default_generator_osx

The error is the automatic detection of the clang version by CMake:

```bash
CMake Error at conanbuildinfo.cmake:300 (message):
  Incorrect 'apple-clang' version 'compiler.version=9.0' is not the one
  detected by CMake: 'Clang=10.0'
```

and the full log:

```bash

Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/jgsogo/dev/conan/conan/conans/test/functional/generators/cmake_generator_test.py", line 72, in test_cmake_default_generator_osx
    self._check_build_generator("Macos", "apple-clang", "9.0", "Unix Makefiles")
  File "/Users/jgsogo/dev/conan/conan/conans/test/functional/generators/cmake_generator_test.py", line 58, in _check_build_generator
    client.run("build .")
  File "/Users/jgsogo/dev/conan/conan/conans/test/utils/tools.py", line 615, in run
    raise Exception(exc_message)
Exception: 
------------------------ Command failed (unexpectedly): ------------------------
build .
----------------------------------- Output: ------------------------------------
conanfile.py (foo/0.1@None/None): Running build()

----Running------
> cd '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces' && cmake -G "Unix Makefiles" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="9.0" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces'
-----------------
Logging command output to file '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/conan_run.log'
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at conanbuildinfo.cmake:300 (message):
  Incorrect 'apple-clang' version 'compiler.version=9.0' is not the one
  detected by CMake: 'Clang=10.0'
Call Stack (most recent call first):
  conanbuildinfo.cmake:370 (conan_error_compiler_version)
  conanbuildinfo.cmake:441 (check_compiler_version)
  conanbuildinfo.cmake:59 (conan_check_compiler)
  CMakeLists.txt:6 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/CMakeFiles/CMakeOutput.log".
ERROR: conanfile.py (foo/0.1@None/None): Error in build() method, line 12
	cmake.configure()
	ConanException: Error 1 while executing cd '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces' && cmake -G "Unix Makefiles" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="9.0" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces'

--------------------------------------------------------------------------------


E
======================================================================
ERROR: test_cmake_default_generator_osx (conan.conans.test.functional.generators.cmake_generator_test.CMakeGeneratorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jgsogo/dev/conan/conan/conans/test/functional/generators/cmake_generator_test.py", line 72, in test_cmake_default_generator_osx
    self._check_build_generator("Macos", "apple-clang", "9.0", "Unix Makefiles")
  File "/Users/jgsogo/dev/conan/conan/conans/test/functional/generators/cmake_generator_test.py", line 58, in _check_build_generator
    client.run("build .")
  File "/Users/jgsogo/dev/conan/conan/conans/test/utils/tools.py", line 615, in run
    raise Exception(exc_message)
Exception: 
------------------------ Command failed (unexpectedly): ------------------------
build .
----------------------------------- Output: ------------------------------------
conanfile.py (foo/0.1@None/None): Running build()

----Running------
> cd '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces' && cmake -G "Unix Makefiles" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="9.0" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces'
-----------------
Logging command output to file '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/conan_run.log'
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at conanbuildinfo.cmake:300 (message):
  Incorrect 'apple-clang' version 'compiler.version=9.0' is not the one
  detected by CMake: 'Clang=10.0'
Call Stack (most recent call first):
  conanbuildinfo.cmake:370 (conan_error_compiler_version)
  conanbuildinfo.cmake:441 (check_compiler_version)
  conanbuildinfo.cmake:59 (conan_check_compiler)
  CMakeLists.txt:6 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/CMakeFiles/CMakeOutput.log".
ERROR: conanfile.py (foo/0.1@None/None): Error in build() method, line 12
	cmake.configure()
	ConanException: Error 1 while executing cd '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces' && cmake -G "Unix Makefiles" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="9.0" -DCONAN_LIBCXX="libstdc++" -DCMAKE_INSTALL_PREFIX="/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev '/private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpsmfbdzzoconans/path with spaces'

--------------------------------------------------------------------------------


----------------------------------------------------------------------
Ran 1 test in 1.141s

FAILED (errors=1)

Process finished with exit code 1

```

**Comment by uilianries** [comment]
Is it caused because AppleClang 10 is installed in host machine?

**Comment by uilianries** [comment]
I do not have mac here, but I think it will work the same way on Linux. Lemme try to reproduce here.

**Comment by uilianries** [comment]
Yeah, same error here. I have gcc7 installed, but the test expects gcc 5.
