### ISSUE TITLE
Conan 1.12.0 pip pulling down too new version of pyOpenSSL

### ISSUE THREAD

**Issue by brianembry** [conan-io/conan#4428]
If host system has a pyOpenSSL outside of spec pip appears to pull down version <19.0.0 (which pulls down 18.0.0), and conan dependency is <18.0.0.

Do not appear to have an issue with 1.11.2, seen on mac osx 10.10 and centos5.

```
$ sudo pip2 install --upgrade pip conan
<snip>
Collecting pyOpenSSL<19.0.0,>=16.0.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
<snip>
conan 1.11.2 has requirement pyOpenSSL<18.0.0,>=16.0.0, but you'll have pyopenssl 18.0.0 which is incompatible.
<snip>
[build] $ sh -c 'conan config set log.trace_file=\"/Users/brian/build/conan_home/conan_log.log\" '
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL<18.0.0,>=16.0.0' distribution was not found and is required by conan
```

Full log: from the build server
```

+ sudo pip2 install --upgrade pip conan
The directory '/Users/vagrant/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/vagrant/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
Collecting conan
  Downloading https://files.pythonhosted.org/packages/28/d0/b2800995f7787f000be90df33c48b641538879b4e2a5c21a23a2e092da18/conan-1.12.0.tar.gz (797kB)
Collecting PyJWT<2.0.0,>=1.4.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting requests<3.0.0,>=2.7.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
Collecting colorama<0.5.0,>=0.3.3 (from conan)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting PyYAML<3.14.0,>=3.11 (from conan)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Collecting patch==1.16 (from conan)
  Downloading https://files.pythonhosted.org/packages/da/74/0815f03c82f4dc738e2bfc5f8966f682bebcc809f30c8e306e6cc7156a99/patch-1.16.zip
Collecting fasteners>=0.14.1 (from conan)
  Downloading https://files.pythonhosted.org/packages/14/3a/096c7ad18e102d4f219f5dd15951f9728ca5092a3385d2e8f79a7c1e1017/fasteners-0.14.1-py2.py3-none-any.whl
Collecting six>=1.10.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting node-semver==0.6.1 (from conan)
  Downloading https://files.pythonhosted.org/packages/f1/4e/1d9a619dcfd9f42d0e874a5b47efa0923e84829886e6a47b45328a1f32f1/node-semver-0.6.1.tar.gz
Collecting distro<1.2.0,>=1.0.2 (from conan)
  Downloading https://files.pythonhosted.org/packages/b0/55/29bfd4d4d4149e860ed01aa446108eb17b240997b746c06a2d0c8ce04f69/distro-1.1.0-py2.py3-none-any.whl
Collecting pylint>=1.9.3 (from conan)
  Downloading https://files.pythonhosted.org/packages/59/65/adcffa71fe942313c4d9e9284565d9a9e67798f4771f464e1d5dd58fea88/pylint-1.9.4-py2.py3-none-any.whl (689kB)
Collecting future==0.16.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting pygments<3.0,>=2.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
Collecting astroid>=1.6.5 (from conan)
  Downloading https://files.pythonhosted.org/packages/0e/9b/18b08991c8c6aaa827faf394f4468b8fee41db1f73aa5157f9f5fb2e69c3/astroid-1.6.5-py2.py3-none-any.whl (293kB)
Collecting deprecation<2.1,>=2.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/32/e9/01ffbaf3540ad54476cd7066439d629f1dd73b851cc5c0993ce2c12e1cdd/deprecation-2.0.6-py2.py3-none-any.whl
Collecting tqdm<5,>=4.28.1 (from conan)
  Downloading https://files.pythonhosted.org/packages/76/4c/103a4d3415dafc1ddfe6a6624333971756e2d3dd8c6dc0f520152855f040/tqdm-4.30.0-py2.py3-none-any.whl (47kB)
Collecting idna==2.6 (from conan)
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
Collecting cryptography<2.4.0,>=1.3.4 (from conan)
  Downloading https://files.pythonhosted.org/packages/5d/b1/9863611b121ee524135bc0068533e6d238cc837337170e722224fe940e2d/cryptography-2.3.1-cp27-cp27m-macosx_10_6_intel.whl (1.5MB)
Collecting pyOpenSSL<19.0.0,>=16.0.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
Collecting bottle<0.13,>=0.12.8 (from conan)
  Downloading https://files.pythonhosted.org/packages/32/4e/ed046324d5ec980c252987c1dca191e001b9f06ceffaebf037eef469937c/bottle-0.12.16.tar.gz (72kB)
Collecting pluginbase<1.0,>=0.5 (from conan)
  Downloading https://files.pythonhosted.org/packages/6e/f4/1db0a26c1c7fad81a1214ad1b02839a7bd98d8ba68f782f6edcc3d343441/pluginbase-0.7.tar.gz (40kB)
Collecting urllib3<1.25,>=1.21.1 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting monotonic>=0.1 (from fasteners>=0.14.1->conan)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting singledispatch; python_version < "3.4" (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting mccabe (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/41/d8/a945da414f2adc1d9e2f7d6e7445b27f2be42766879062a2e63616ad4199/isort-4.3.4-py2-none-any.whl (45kB)
Collecting configparser; python_version == "2.7" (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/e9/b1/98e5e3094aac1c0efaeb208fb45f9b42eb1d5681b4c5dac77b05d0fec71a/configparser-3.7.1-py2-none-any.whl
Collecting enum34>=1.1.3; python_version < "3.4" (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting lazy-object-proxy (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/55/08/23c0753599bdec1aec273e322f277c4e875150325f565017f6280549f554/lazy-object-proxy-1.3.1.tar.gz
Collecting wrapt (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gz
Collecting packaging (from deprecation<2.1,>=2.0->conan)
  Downloading https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography<2.4.0,>=1.3.4->conan)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Collecting cffi!=1.11.3,>=1.7 (from cryptography<2.4.0,>=1.3.4->conan)
  Downloading https://files.pythonhosted.org/packages/7e/4a/b647e46faaa2dcfb16069b6aad2d8509982fd63710a325b8ad7db80f18be/cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl (238kB)
Collecting ipaddress; python_version < "3" (from cryptography<2.4.0,>=1.3.4->conan)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting futures (from isort>=4.2.5->pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->deprecation<2.1,>=2.0->conan)
  Downloading https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61kB)
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography<2.4.0,>=1.3.4->conan)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Installing collected packages: pip, PyJWT, urllib3, certifi, idna, chardet, requests, colorama, PyYAML, patch, six, monotonic, fasteners, node-semver, distro, singledispatch, mccabe, backports.functools-lru-cache, enum34, lazy-object-proxy, wrapt, astroid, futures, isort, configparser, pylint, future, pygments, pyparsing, packaging, deprecation, tqdm, asn1crypto, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, bottle, pluginbase, conan
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
  Running setup.py install for patch: started
    Running setup.py install for patch: finished with status 'done'
  Running setup.py install for node-semver: started
    Running setup.py install for node-semver: finished with status 'done'
  Running setup.py install for lazy-object-proxy: started
    Running setup.py install for lazy-object-proxy: finished with status 'done'
  Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
  Running setup.py install for pycparser: started
    Running setup.py install for pycparser: finished with status 'done'
  Running setup.py install for bottle: started
    Running setup.py install for bottle: finished with status 'done'
  Running setup.py install for pluginbase: started
    Running setup.py install for pluginbase: finished with status 'done'
  Running setup.py install for conan: started
    Running setup.py install for conan: finished with status 'done'
Successfully installed PyJWT-1.7.1 PyYAML-3.13 asn1crypto-0.24.0 astroid-1.6.5 backports.functools-lru-cache-1.5 bottle-0.12.16 certifi-2018.11.29 cffi-1.11.5 chardet-3.0.4 colorama-0.4.1 conan-1.12.0 configparser-3.7.1 cryptography-2.3.1 deprecation-2.0.6 distro-1.1.0 enum34-1.1.6 fasteners-0.14.1 future-0.16.0 futures-3.2.0 idna-2.6 ipaddress-1.0.22 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 monotonic-1.5 node-semver-0.6.1 packaging-19.0 patch-1.16 pip-19.0.1 pluginbase-0.7 pyOpenSSL-18.0.0 pycparser-2.19 pygments-2.3.1 pylint-1.9.4 pyparsing-2.3.1 requests-2.21.0 singledispatch-3.4.0.3 six-1.12.0 tqdm-4.30.0 urllib3-1.24.1 wrapt-1.11.1
[Pipeline] isUnix
[Pipeline] echo
UNIX: sudo pip2 install --upgrade conan_package_tools
[Pipeline] sh
+ sudo pip2 install --upgrade conan_package_tools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/vagrant/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/vagrant/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting conan_package_tools
  Downloading https://files.pythonhosted.org/packages/c3/73/fb013ac93efda9cb983c4e9f5b6cd19a5dc1895ddbf18c4ef6691aab48a8/conan_package_tools-0.22.3.tar.gz (49kB)
Requirement already satisfied, skipping upgrade: idna==2.6 in /usr/local/lib/python2.7/site-packages (from conan_package_tools) (2.6)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from conan_package_tools) (1.12.0)
Requirement already satisfied, skipping upgrade: requests[security] in /usr/local/lib/python2.7/site-packages (from conan_package_tools) (2.21.0)
Collecting conan<1.12.0,>=1.7.0 (from conan_package_tools)
  Downloading https://files.pythonhosted.org/packages/65/b5/043375b0c82e39b9ad0f0076dc3c2fb3dee228fd3ef6dc866d63c4a14732/conan-1.11.2.tar.gz (755kB)
Collecting tabulate==0.8.2 (from conan_package_tools)
  Downloading https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz (45kB)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests[security]->conan_package_tools) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests[security]->conan_package_tools) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests[security]->conan_package_tools) (3.0.4)
Requirement already satisfied, skipping upgrade: cryptography>=1.3.4; extra == "security" in /usr/local/lib/python2.7/site-packages (from requests[security]->conan_package_tools) (2.3.1)
Requirement already satisfied, skipping upgrade: pyOpenSSL>=0.14; extra == "security" in /usr/local/lib/python2.7/site-packages (from requests[security]->conan_package_tools) (18.0.0)
Requirement already satisfied, skipping upgrade: PyJWT<2.0.0,>=1.4.0 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (1.7.1)
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.3.3 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.4.1)
Requirement already satisfied, skipping upgrade: PyYAML<3.14.0,>=3.11 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (3.13)
Requirement already satisfied, skipping upgrade: patch==1.16 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (1.16)
Requirement already satisfied, skipping upgrade: fasteners>=0.14.1 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.14.1)
Requirement already satisfied, skipping upgrade: node-semver==0.6.1 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.6.1)
Requirement already satisfied, skipping upgrade: distro<1.2.0,>=1.0.2 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (1.1.0)
Requirement already satisfied, skipping upgrade: pylint>=1.9.3 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (1.9.4)
Requirement already satisfied, skipping upgrade: future==0.16.0 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.16.0)
Requirement already satisfied, skipping upgrade: pygments<3.0,>=2.0 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (2.3.1)
Requirement already satisfied, skipping upgrade: astroid>=1.6.5 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (1.6.5)
Requirement already satisfied, skipping upgrade: deprecation<2.1,>=2.0 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (2.0.6)
Requirement already satisfied, skipping upgrade: tqdm<5,>=4.28.1 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (4.30.0)
Requirement already satisfied, skipping upgrade: bottle<0.13,>=0.12.8 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.12.16)
Requirement already satisfied, skipping upgrade: pluginbase<1.0,>=0.5 in /usr/local/lib/python2.7/site-packages (from conan<1.12.0,>=1.7.0->conan_package_tools) (0.7)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->conan_package_tools) (0.24.0)
Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->conan_package_tools) (1.1.6)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->conan_package_tools) (1.11.5)
Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3" in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->conan_package_tools) (1.0.22)
Requirement already satisfied, skipping upgrade: monotonic>=0.1 in /usr/local/lib/python2.7/site-packages (from fasteners>=0.14.1->conan<1.12.0,>=1.7.0->conan_package_tools) (1.5)
Requirement already satisfied, skipping upgrade: singledispatch; python_version < "3.4" in /usr/local/lib/python2.7/site-packages (from pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (3.4.0.3)
Requirement already satisfied, skipping upgrade: mccabe in /usr/local/lib/python2.7/site-packages (from pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (0.6.1)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (1.5)
Requirement already satisfied, skipping upgrade: isort>=4.2.5 in /usr/local/lib/python2.7/site-packages (from pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (4.3.4)
Requirement already satisfied, skipping upgrade: configparser; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (3.7.1)
Requirement already satisfied, skipping upgrade: lazy-object-proxy in /usr/local/lib/python2.7/site-packages (from astroid>=1.6.5->conan<1.12.0,>=1.7.0->conan_package_tools) (1.3.1)
Requirement already satisfied, skipping upgrade: wrapt in /usr/local/lib/python2.7/site-packages (from astroid>=1.6.5->conan<1.12.0,>=1.7.0->conan_package_tools) (1.11.1)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/python2.7/site-packages (from deprecation<2.1,>=2.0->conan<1.12.0,>=1.7.0->conan_package_tools) (19.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.3.4; extra == "security"->requests[security]->conan_package_tools) (2.19)
Requirement already satisfied, skipping upgrade: futures in /usr/local/lib/python2.7/site-packages (from isort>=4.2.5->pylint>=1.9.3->conan<1.12.0,>=1.7.0->conan_package_tools) (3.2.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/python2.7/site-packages (from packaging->deprecation<2.1,>=2.0->conan<1.12.0,>=1.7.0->conan_package_tools) (2.3.1)
conan 1.11.2 has requirement pyOpenSSL<18.0.0,>=16.0.0, but you'll have pyopenssl 18.0.0 which is incompatible.
Installing collected packages: conan, tabulate, conan-package-tools
  Found existing installation: conan 1.12.0
    Uninstalling conan-1.12.0:
      Successfully uninstalled conan-1.12.0
  Running setup.py install for conan: started
    Running setup.py install for conan: finished with status 'done'
  Running setup.py install for tabulate: started
    Running setup.py install for tabulate: finished with status 'done'
  Running setup.py install for conan-package-tools: started
    Running setup.py install for conan-package-tools: finished with status 'done'
Successfully installed conan-1.11.2 conan-package-tools-0.22.3 tabulate-0.8.2

[build] $ sh -c 'conan config set log.trace_file=\"/Users/brian/build/conan_home/conan_log.log\" '
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyOpenSSL<18.0.0,>=16.0.0' distribution was not found and is required by conan`
``

**Comment by memsharded** [comment]
I am not sure if I understand what is happening, because in fact the range for valid pyOpenSSL has been increased in Conan 1.12 to include it:

```diff
git diff release/1.11.0 -- conans\requirements*
diff --git a/conans/requirements_osx.txt b/conans/requirements_osx.txt
index 39f2a536..91476c97 100644
--- a/conans/requirements_osx.txt
+++ b/conans/requirements_osx.txt
@@ -1,3 +1,3 @@
 idna==2.6 # Solving conflict, somehow is installing 2.7 when requests require 2.6
 cryptography>=1.3.4, <2.4.0
-pyOpenSSL>=16.0.0, <18.0.0
+pyOpenSSL>=16.0.0, <19.0.0
```

I think the problem is ``conan-package-tools`` which  might not have upgraded it. Actually it seems it has been upgraded in develop branch, but the CPT 0.23 hasn't been released yet. We'll release it as soon as possible, thanks for reporting.
