### ISSUE TITLE
Conan 0.11.1 can't install littlecms 2.7

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/conan#449]
```
littlecms/2.7@lasote/stable: Not found, looking in remotes...
littlecms/2.7@lasote/stable: Trying with 'conan.io'...
Downloading conanfile.py
[==================================================]                  
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 9, in <module>
    load_entry_point('conan==0.11.1', 'console_scripts', 'conan')()
  File "/usr/local/lib/python3.4/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/conans/client/command.py", line 772, in main
    error = command.run(args)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/command.py", line 681, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.4/dist-packages/conans/client/command.py", line 340, in install
    generators=args.generator)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/manager.py", line 222, in install
    update, check_updates, integrity, scopes)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/manager.py", line 174, in _get_graph
    deps_graph = builder.load(None, conanfile)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/deps_builder.py", line 336, in load
    self._load_deps(root_node, Requirements(), dep_graph, public_deps, conan_ref, None)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/deps_builder.py", line 365, in _load_deps
    new_node = self._create_new_node(node, dep_graph, require, public_deps, name)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/deps_builder.py", line 420, in _create_new_node
    conanfile_path = self._retriever.get_conanfile(requirement.conan_reference)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/proxy.py", line 131, in get_conanfile
    self._retrieve_conanfile(conan_reference, output)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/proxy.py", line 171, in _retrieve_conanfile
    return _retrieve_from_remote(remote)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/proxy.py", line 156, in _retrieve_from_remote
    result = self._remote_manager.get_conanfile(conan_reference, remote)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/remote_manager.py", line 65, in get_conanfile
    uncompress_files(export_files, export_folder, EXPORT_TGZ_NAME)
  File "/usr/local/lib/python3.4/dist-packages/conans/client/remote_manager.py", line 160, in uncompress_files
    save(os.path.join(folder, file_name), content)
  File "/usr/local/lib/python3.4/dist-packages/conans/util/files.py", line 87, in save
    with open(path, mode) as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/conan/.conan/data/littlecms/2.7/lasote/stable/export/conanfile.py'
```

**Comment by nathanaeljones** [comment]
This appears to be some kind of permissions issue; running `conan install` using sudo resolves the error.

**Comment by lasote** [comment]
Sometimes it happens when you  run conan install in a docker container that share the .conan/data directory.  Docker usually use different users id and leaves the .conan/data directory a little dirty.Or maybe from a previous "sudo" execution.

In any case I recommend not to use sudo and make a recursive "chown youruser:youruser ~/.conan/data -r" to set the right user in the storage.

**Comment by memsharded** [comment]
Hi @nathanaeljones , did you manage to make this work? Anything we could do here in conan, or is it just a docker issue? Thanks!

**Comment by nathanaeljones** [comment]
I did! Chown worked :)

**Comment by memsharded** [comment]
Great, thanks for telling! closing issue :)
