### ISSUE TITLE
tools.OSInfo regression in 1.12.2 (MSYS/Cygwin)

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4540]
running the following commands fail since update to conan 1.12.2:
```
$ conan profile new xxx --detect
ERROR: Error detecting os_info
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/conans/client/command.py", line 1495, in run
    method(args[0][1:])
  File "/usr/lib/python3.6/site-packages/conans/client/command.py", line 1307, in profile
    self._conan.create_profile(profile, args.detect)
  File "/usr/lib/python3.6/site-packages/conans/client/conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/conans/client/conan_api.py", line 894, in create_profile
    self._user_io.out, detect)
  File "/usr/lib/python3.6/site-packages/conans/client/cmd/profile.py", line 41, in cmd_profile_create
    settings = detect_defaults_settings(output)
  File "/usr/lib/python3.6/site-packages/conans/client/conf/detect.py", line 200, in detect_defaults_settings
    _detect_os_arch(result, output)
  File "/usr/lib/python3.6/site-packages/conans/client/conf/detect.py", line 178, in _detect_os_arch
    the_os = detected_os()
  File "/usr/lib/python3.6/site-packages/conans/client/tools/oss.py", line 37, in detected_os
    if OSInfo().is_macos:
  File "/usr/lib/python3.6/site-packages/conans/client/tools/oss.py", line 115, in __init__
    self.os_version = self.get_win_os_version()
  File "/usr/lib/python3.6/site-packages/conans/client/tools/oss.py", line 187, in get_win_os_version
    retcode = ctypes.windll.Ntdll.RtlGetVersion(ctypes.byref(os_version))
AttributeError: module 'ctypes' has no attribute 'windll'
```
```
$ conan profile show default
ERROR: Error detecting os_info
```
in both MSYS2 and Cygwin environments

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
https://github.com/conan-io/conan/pull/4541 was supposed to close this one.
