### ISSUE TITLE
Interrupted transfer produces long trace and leaves bad state

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#459]
If network disconnect during install transfer:

```bash
Poco/1.7.2@lasote/stable: Looking for package 746f954529ab93712c4d76d3ccd58412bc2666ba in remote 'conan.io'
Downloading conan_package.tgz
[==================================================]
Downloading conanmanifest.txt
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\memsharded\Envs\conanpip\Scripts\conan.exe\__main__.py", line 9, in <module>
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\conan.py", line 6, in run
    main(sys.argv[1:])
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\command.py", line 772, in main
    error = command.run(args)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\command.py", line 681, in run
    method(args[0][1:])
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\command.py", line 340, in install
    generators=args.generator)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\manager.py", line 241, in install
    installer.install(deps_graph, build_mode)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\installer.py", line 61, in install
    self._build(nodes_by_level, skip_private_nodes, build_mode)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\installer.py", line 139, in _build
    self._build_node(conan_ref, conan_file, build_mode)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\installer.py", line 162, in _build_node

    if self._remote_proxy.get_package(package_reference, force_build):
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\proxy.py", line 70, in get_package
    return self._retrieve_remote_package(package_reference, output)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\proxy.py", line 280, in _retrieve_remote_package
    self._remote_manager.get_package(package_reference, remote)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\remote_manager.py", line 79, in get_package
    uncompress_files(package_files, destination_dir, PACKAGE_TGZ_NAME)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\remote_manager.py", line 158, in uncompress_files
    for file_name, content in files:
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\rest\rest_client.py", line 344, in download_files
    contents = downloader.download(resource_url)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\rest\uploader_downloader.py", line 31, in download
    response = self.requester.get(url, stream=True, verify=self.verify)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\rest\version_checker.py", line 20, in get
    ret = self.requester.get(url, auth=auth, headers=headers, verify=verify, stream=stream)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by memsharded** [comment]
Released in 0.12
