### ISSUE TITLE
Conan hooks exceptions show not useful stack trace

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#5019]
Having a hook raising an ``Exception`` produces something like:

```bash
ERROR: [HOOK - name_conventions.py] pre_export(): Reference Hello/0.1@user/testing should be all lowercase
Traceback (most recent call last):
  File "c:\users\memsharded\envs\conanpip\lib\site-packages\conans\client\hook_manager.py", line 56, in execute
    method(output=output, **kwargs)
  File "C:\Users\memsharded\.conan\hooks\name_conventions.py", line 4, in pre_export
    raise Exception("Reference %s should be all lowercase" % ref)
Exception: Reference Hello/0.1@user/testing should be all lowercase
```

As this is not very useful, I suggest removing it.

**Comment by jenix21** [comment]
Hello, I uploaded a pull request, which removes traceback in exception message.
Thanks 😄
