### ISSUE TITLE
Conan "No such file or directory" error when installing or packaging a library on Windows 10

### ISSUE THREAD

**Issue by JigsawCorp** [conan-io/conan#5149]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi, I am not too sure how we can find the root of this issue, but for only one library that I am trying to use I am having issues. I am using Conan 1.13.3.

We have some modified boost binaries that we want to put on Conan. At first, I put the binaries with Ubuntu and everything went fine. However, when I try to install said binary with Windows 10, I am not able to. It does download the conan_package.tgz, but it fails when trying to unzip the file. I tried manually downloading the tgz from my nexus repo and unzipping it, and the files are all there. Here's whats happening:

```
C:\work\test\fix\src\cmake> conan install Boost/1.68.0@my_private_repo/dev --profile=default -r=my_private_repo
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Boost/1.68.0@my_private_repo/dev: Retrieving from server 'my_private_repo'
Boost/1.68.0@my_private_repo/dev: Trying with 'my_private_repo'...
Downloading conanmanifest.txt
[==================================================] 58B/58B
Downloading conanfile.py
[==================================================] 417B/417B
Installing package: Boost/1.68.0@my_private_repo/dev
Requirements
    Boost/1.68.0@my_private_repo/dev from 'my_private_repo' - Downloaded
Packages
    Boost/1.68.0@my_private_repo/dev:c32596dcd26b8c708dc3d19cb73738d2b48f12a8 - Download

Boost/1.68.0@my_private_repo/dev: Retrieving package c32596dcd26b8c708dc3d19cb73738d2b48f12a8 from remote 'my_private_repo'
Downloading conanmanifest.txt
[==================================================] 5.1MB/5.1MB
Downloading conaninfo.txt
[==================================================] 404B/404B
Downloading conan_package.tgz
[==================================================] 387.2MB/387.2MB
Decompressing conan_package.tgz:   4%|▍         | 14.7M/369M [00:19<09:15, 669kB/s]Boost/1.68.0@my_private_repo/dev: ERROR: Exception while getting package: c32596dcd26b8c708dc3d19cb73738d2b48f12a8
Boost/1.68.0@my_private_repo/dev: ERROR: Exception: <class 'conans.errors.ConanException'> Error while downloading/extracting files to C:\Users\username\.conan\data\Boost\1.68.0\my_private_repo\dev\package\c32596dcd26b8c708dc3d19cb73738d2b48f12a8
[Errno 2] No such file or directory: 'C:\\Users\\username\\.conan\\data\\Boost\\1.68.0\\my_private_repo\\dev\\package\\c32596dcd26b8c708dc3d19cb73738d2b48f12a8\\doc\\html\\boost_asio\\reference\\async_result_lt__std__packaged_task_lt__Result_lp_Args_ellipsis__rp__gt__comma__Signature__gt_\\completion_handler_type.html'
Folder removed
Boost/1.68.0@my_private_repo/dev: WARN: Trying to remove package folder: C:\Users\username\.conan\data\Boost\1.68.0\my_private_repo\dev\package\c32596dcd26b8c708dc3d19cb73738d2b48f12a8
ERROR: Error while downloading/extracting files to C:\Users\username\.conan\data\Boost\1.68.0\my_private_repo\dev\package\c32596dcd26b8c708dc3d19cb73738d2b48f12a8
[Errno 2] No such file or directory: 'C:\\Users\\username\\.conan\\data\\Boost\\1.68.0\\my_private_repo\\dev\\package\\c32596dcd26b8c708dc3d19cb73738d2b48f12a8\\doc\\html\\boost_asio\\reference\\async_result_lt__std__packaged_task_lt__Result_lp_Args_ellipsis__rp__gt__comma__Signature__gt_\\completion_handler_type.html'
Folder removed
Decompressing conan_package.tgz:   4%|▍         | 14.7M/369M [00:24<09:41, 639kB/s]
```

I tried doing the same on Ubuntu and didn't have any problems. I also did the same with about 10 other packages and never had an issue like this. I have the same problem if I try to package binaries on Windows 10 with this Boost library:

```
C:\boost\1.68.0_vs2015> conan export-pkg ../ Boost/1.68.0@my_private_repo/dev --package-folder=. --profile=default
Exporting package recipe
Linter warnings
    WARN: Linter. Line 1: Unused tools imported from conans
Boost/1.68.0@my_private_repo/dev: A new conanfile.py version was exported
Boost/1.68.0@my_private_repo/dev: Folder: C:\Users\username\.conan\data\Boost\1.68.0\my_private_repo\dev\export
Boost/1.68.0@my_private_repo/dev: WARN: Forced build from source
Packaging to c32596dcd26b8c708dc3d19cb73738d2b48f12a8
Boost/1.68.0@my_private_repo/dev: Exporting to cache existing package from user folder
Boost/1.68.0@my_private_repo/dev: Package folder C:\Users\username\.conan\data\Boost\1.68.0\my_private_repo\dev\package\c32596dcd26b8c708dc3d19cb73738d2b48f12a8
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\command.py", line 1570, in run
    method(args[0][1:])
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\command.py", line 798, in export_pkg
    channel=channel)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\conan_api.py", line 444, in export_pkg
    graph_info=graph_info, force=force)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\cmd\export_pkg.py", line 48, in export_pkg
    hook_manager, conan_file_path, ref)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\packager.py", line 26, in export_pkg
    copier("*", symlinks=True)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\file_copier.py", line 82, in __call__
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, links)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\conans\client\file_copier.py", line 208, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\.conan\\data\\Boost\\1.68.0\\my_private_repo\\dev\\package\\c32596dcd26b8c708dc3d19cb73738d2b48f12a8\\doc\\html\\boost_asio\\reference\\async_result_lt__std__packaged_task_lt__Result_lp_Args_ellipsis__rp__gt__comma__Signature__gt_\\completion_handler_type.html'

ERROR: [Errno 2] No such file or directory: 'C:\\Users\\username\\.conan\\data\\Boost\\1.68.0\\my_private_repo\\dev\\package\\c32596dcd26b8c708dc3d19cb73738d2b48f12a8\\doc\\html\\boost_asio\\reference\\async_result_lt__std__packaged_task_lt__Result_lp_Args_ellipsis__rp__gt__comma__Signature__gt_\\completion_handler_type.html'

```

**Comment by uilianries** [comment]
Hi @JigsawCorp !

Your problem is related to Windows max length path, which is 250 characters.

You need to set [CONAN_USE_ALWAYS_SHORT_PATHS](https://docs.conan.io/en/latest/reference/env_vars.html#conan-use-always-short-paths).

Regards!

**Comment by JigsawCorp** [comment]
@uilianries It works! Thank you so much!
