### ISSUE TITLE
errors from generators aren't descriptive

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5188]
as for conan 1.15, errors from generators aren't very descriptive. for instance, permission errors on Linux/Mac (happen if you run conan in docker, then back to the host).
for example:
```
gtest/1.8.1@bincrafters/testing: Created package revision 95a0a28642a7559ffafe2e4abe1c15c7
gtest/1.8.1@bincrafters/testing (test package): Applying build-requirement: yasm_installer/1.3.0@bincrafters/stable
gtest/1.8.1@bincrafters/testing (test package): Applying build-requirement: ninja_installer/1.8.2@bincrafters/stable
gtest/1.8.1@bincrafters/testing (test package): Generator cmake created conanbuildinfo.cmake
gtest/1.8.1@bincrafters/testing (test package): ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
[Errno 2] No such file or directory: '/home/sse4/conan/conan-gtest/test_package/build/5b8055ce97cc512ddc0e853f0a5b473827542785/conanbuildinfo.cmake'
ERROR: [Errno 2] No such file or directory: '/home/sse4/conan/conan-gtest/test_package/build/5b8055ce97cc512ddc0e853f0a5b473827542785/conanbuildinfo.cmake'
```
for the record - it doesn't say **why** generator cmake has failed. it only says it failed. `Errno 2` is the next error, it's `ENOENT`, about missing `conanbuildinfo.cmake`, which wasn't created because generator failed earlier.
how to reproduce:
```
git@github.com:bincrafters/conan-gtest.git
cd conan-gtest
chmod -R -w test_pacakge
conan create . bincrafters/testing -k
```

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @SSE4 

I am having a look, but I don't know how that could be improved. The problem is here:

```python
       try:
            ...
            save(join(path, generator.filename), content, only_if_modified=True)
        except Exception as e:
            if get_env("CONAN_VERBOSE_TRACEBACK", False):
                output.error(traceback.format_exc())
            output.error("Generator %s(file:%s) failed\n%s"
                         % (generator_name, generator.filename, str(e)))
            raise ConanException(e)
```

Conan is correctly printing the error provided by the OS:
```[Errno 2] No such file or directory: '/home/sse4/conan/conan-gtest/test_package/build/5b8055ce97cc512ddc0e853f0a5b473827542785/conanbuildinfo.cmake'
```

I don't know how to improve over that, any suggestion?

**Comment by SSE4** [comment]
with `CONAN_VERBOSE_TRACEBACK` I have the following output:
```
qlite3/3.28.0@bincrafters/testing (test package): ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/conans/client/generators/__init__.py", line 110, in write_generators
    save(join(path, k), v, only_if_modified=True)
  File "/usr/local/lib/python3.7/site-packages/conans/util/files.py", line 153, in save
    with open(path, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sse4/c3i/conan_index/recipes/sqlite3/3.28.0/test_package/build/7336ebca55c566ecc6b383dffaf3ae6eb18d5225/sqlite3Config.cmake'

sqlite3/3.28.0@bincrafters/testing (test package): ERROR: Generator cmake_find_package_multi(file:None) failed
[Errno 2] No such file or directory: '/Users/sse4/c3i/conan_index/recipes/sqlite3/3.28.0/test_package/build/7336ebca55c566ecc6b383dffaf3ae6eb18d5225/sqlite3Config.cmake'
ERROR: [Errno 2] No such file or directory: '/Users/sse4/c3i/conan_index/recipes/sqlite3/3.28.0/test_package/build/7336ebca55c566ecc6b383dffaf3ae6eb18d5225/sqlite3Config.cmake'
```
there is nothing about an original error (permissions). the only error is Errno 2, which is ENOENT (no such file or directory), which is a just a consequence of the permission error

**Comment by memsharded** [comment]
Yep, nothing we can do here, just the python-system message, not from conan
