### ISSUE TITLE
Bug: conan config install

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#5214]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Following situation:
Running conan 1.15.1 on Linux (Ubuntu 18.4 LTS)
When loading our configuration to a new `CONAN_USER_HOME` and start import our configuration:
`conan config install ~/work/scripts/conan/config/`
I get the following error:
`ERROR: [Errno 2] No such file or directory: '/home/j/tempconan/.conan/remotes.json'`

When I just open in between `conan remote list` it works afterwards.

When running with Conan 1.14.1 it also works. So it must be a bug afterwards.

Here the recipe:
```
mkdir tempconan && cd tempconan
export CONAN_USER_HOME=/home/j/tempconan
conan config install ~/work/scripts/conan/config/
```

And the callstack:
```
j@ubuntu:~/tempconan$ conan config install ~/work/scripts/conan/config/Copying file version.txt to /home/j/tempconan/.conan/.
Copying file artifacts.properties to /home/j/tempconan/.conan/.
Processing conan.conf
Traceback (most recent call last):
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/command.py", line 1607, in run
    method(args[0][1:])
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/command.py", line 478, in config
    target_folder=args.target_folder)
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 621, in config_install
    source_folder=source_folder, target_folder=target_folder)
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/conf/config_installer.py", line 230, in configuration_install
    _process_config(config, cache, output, requester)
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/conf/config_installer.py", line 182, in _process_config
    _process_folder(config, config.uri, cache, output)
  File "/home/j/.local/lib/python3.6/site-packages/conans/client/conf/config_installer.py", line 93, in _process_folder
    os.remove(cache.registry_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/j/tempconan/.conan/remotes.json'

ERROR: [Errno 2] No such file or directory: '/home/j/tempconan/.conan/remotes.json'

```

**Comment by climblinne** [comment]
Checked just again the version, where it happens:
1.14.5 OK
1.15.0 Failure

**Comment by lasote** [comment]
Thanks for reporting, let's try to fix it for next release.
