### ISSUE TITLE
Conan search cannot handle revisions with time that includes an offset

### ISSUE THREAD

**Issue by tmwa** [conan-io/conan#5230]
```
$ conan --version
Conan version 1.15.0
$ uname -a
Linux hostname 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Our Artifactory instance seems to return timestamps with an offset:
`[{'revision': 'b27c3f77818145a86d8657078987b033', 'time': '2019-05-14T16:52:28.383+0100'}]`

ISO 8601 allows this: https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

This is passed to `util/dates.py` which cannot handle it:

```bash
$ conan search MyPackage/1.1.1@username/channel --revisions --remote artifactory

Revisions for 'MyPackage/1.1.1@username/channel' at remote 'artifactory':
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/conans/client/command.py", line 1607, in run
    method(args[0][1:])
  File "/home/user/.local/lib/python3.6/site-packages/conans/client/command.py", line 1090, in search
    self._outputer.print_revisions(ref, info, remote_name=args.remote)
  File "/home/user/.local/lib/python3.6/site-packages/conans/client/conan_command_output.py", line 245, in print_revisions
    for r in revisions]
  File "/home/user/.local/lib/python3.6/site-packages/conans/client/conan_command_output.py", line 245, in <listcomp>
    for r in revisions]
  File "/home/user/.local/lib/python3.6/site-packages/conans/util/dates.py", line 31, in iso8601_to_str
    dt = from_iso8601_to_datetime(iso_str)
  File "/home/user/.local/lib/python3.6/site-packages/conans/util/dates.py", line 27, in from_iso8601_to_datetime
    return datetime.datetime.strptime(iso_str, pattern)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-05-14T16:52:28.383+0100Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

ERROR: time data '2019-05-14T16:52:28.383+0100Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

Notice that at some point `util/dates.py` has appended a "Z" to the date in the wrong place.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by tmwa** [comment]
This seems to be the problem: https://github.com/conan-io/conan/blob/bc8c0cbef266acaae68e9059c3549dc794f549d3/conans/util/dates.py#L12

**Comment by lasote** [comment]
Thanks for reporting. We will solve it for the coming 1.16
