### ISSUE TITLE
Weird random crash in conan

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#5498]
I am currently using conan 1.16.1, but this crash occasionally happens on all versions I've tried (including 1.17.0):

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 1723, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.7/site-packages/conans/client/command.py", line 879, in export_pkg
    channel=channel)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/conans/client/conan_api.py", line 416, in export_pkg
    graph_info=graph_info, force=force, remotes=remotes)
  File "/usr/local/lib/python3.7/site-packages/conans/client/cmd/export_pkg.py", line 25, in export_pkg
    apply_build_requires=False)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 149, in load_graph
    apply_build_requires=apply_build_requires)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_manager.py", line 235, in _load_graph
    graph = builder.load_graph(root_node, check_updates, update, remotes, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 40, in load_graph
    processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 129, in _load_deps
    remotes, processed_profile, new_reqs, new_options)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 175, in _handle_require
    remotes, processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 129, in _load_deps
    remotes, processed_profile, new_reqs, new_options)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 145, in _handle_require
    processed_profile)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/graph_builder.py", line 315, in _create_new_node
    remotes, self._recorder)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/proxy.py", line 33, in get_recipe
    result = self._get_recipe(ref, check_updates, update, remotes, recorder)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/proxy.py", line 53, in _get_recipe
    metadata = self._cache.package_layout(ref).load_metadata()
  File "/usr/local/lib/python3.7/site-packages/conans/paths/package_layouts/package_cache_layout.py", line 170, in load_metadata
    return PackageMetadata.loads(text)
  File "/usr/local/lib/python3.7/site-packages/conans/model/package_metadata.py", line 89, in loads
    data = json.loads(content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

My guess is that it's a sort of race condition because it never happens on my development machine, but regularly happens on our CI servers (multiple jenkins executors share the same conan home folder).

Any idea what could be wrong?

**Comment by danimtb** [comment]
Hi @DoDoENT,

Thanks a lot for reporting the issue as it seems a tricky one. Apparently, it seems that the metadata file or content is not found. Could be a race condition as you pointed out.

Please indicate the Python version you are using and the commands (at least what you think) that could be creating the race condition. I see you are doing a ``conan export-pkg`` there, for example.
Thanks!

**Comment by danimtb** [comment]
Looking in the codebase it seems the ``json.loads()`` in ``PackageMetadata.loads()`` is reading an empty or malformed content in the metadata file and it is causing the exception.

I had a look at the points where the metadata is written and the first one is on the migration process we had when this file is created (seems quite unlikely to be failing at that point) and the second one is covered by a ``with fasteners.InterProcessLock(lock_file):``, so it seems it is protected.

However, the reading of the metadata files are not covered by that context manager and that could be the cause of the issue.

**Comment by danimtb** [comment]
Probably just adding the context manager for the fasteners locking will solve the issue:

```
*class PackageCacheLayout(object):
    ...

    # Metadata
    def load_metadata(self):
        lockfile = self.package_metadata() + ".lock"
        with fasteners.InterProcessLock(lockfile, logger=logger):
            try:
                text = load(self.package_metadata())
            except IOError:
                raise RecipeNotFoundException(self._ref)
            return PackageMetadata.loads(text)
```

**Comment by danimtb** [comment]
I have updated the title of the issue to better reflect what is happening in the issue. Thanks!

**Comment by DoDoENT** [comment]
I've noticed the crash mostly during the `conan install` procedure. But it always happens on my CI machine (Jenkins with 8 executors). It's quite possible that other executors performed other conan tasks in parallel - most probably also `conan install`. But it's also possible that some of them were performing `conan export-pkg`. When testing the package, our CI first performs `conan install`, then `conan build` and finally `conan package`. However, since `conan test` does not support `--package-folder` parameter and expects the package under test to be exported to local cache* and since conan cannot be configured to use multiple caches at the same time**, we need to temporarily export the package to local cache in order to run the `conan test` and then clear the exported package to prevent using it from other executors.

*) the `conan test` looks like a natural continuation of the `install` - `build` - `package` cycle, so it would be great to be able to test the package created with `conan package` command, without the need to export the package into the local cache first
**) here I mean having the ability to have multiple `~/.conan/data` folders. The one would be the default one, used by all Jenkins executors, and another would be the one in which a package for testing would be temporarily exported - probably some temporary directory. This would not only remove the need for supporting `--package-folder` for `conan test` (although I argue that this should be supported, as it seems natural), but would also give the ability to test multiple packages that depend on each other. For example, let's say that my repository contains two packages `A` and `B`. `B` depends on `A` and they always need to be developed together (think of an example with `OcrEngine` and `OcrEngineModelBuilder` from the description of issue #4753). So, in order to ensure that package `B` can be tested with `conan test`, it also needs the same version of package `A`, which is still not exported. If multiple conan cache folders were supported, the Jenkins executor could export both `A` and `B` into its temporary folder to perform the `conan test`, while still using the default conan cache for other dependencies of `A` and `B`.

**Comment by danimtb** [comment]
Thanks for the information about your flow, we will try to address the issue for the next patch release.

I'd suggest you to open other issues for the points you described as feature requests, so they can be further discussed. Thank you!

**Comment by jgsogo** [comment]
Hi! This issue was forgotten in an older release 😞 

The original problem described in this issue is due to several processes sharing the same Conan cache. This is something we cannot recommend at this point, not only because of the race conditions we might find accessing some files (like the one described here), but also because it can lead to UB using some Conan features. For example, if we are using revisions, the Conan cache can contain only one revision at a time, if two executors want to consume different revisions, we may end with an executor including/linking the wrong revision of a dependency.

IMO, we should close this issue, we can improve the concurrency, it is something we know we have to do, but we need to address some other tasks first.

**Comment by DoDoENT** [comment]
@jgsogo , as you wish. You can close it. In the meantime, we reorganized our CI system so that each Jenkins executor gets its own private Conan cache, which is retained between builds (to prevent downloading all the packages each time and there is a weekly job to delete all caches while nothing is being built to make sure disks on servers are not overfilled).

This issue is not relevant for us anymore, however, as you suggested, the concurrency is something conan needs to improve.
