### ISSUE TITLE
"conan install .." fails with ERROR: [Errno 2] No such file or directory: '/apps/abc/conanws.yml'

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#5838]
To help us debug your issue please explain:

`conan install ..`

```
Traceback (most recent call last):
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/ref.py", line 111, in loads
    _, name, version, user, channel, revision, _ = ConanFileReference.sep_pattern.split(text)
ValueError: not enough values to unpack (expected 7, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/user/.local/lib/python3.6/site-packages/conans/client/command.py", line 376, in install
    ref = ConanFileReference.loads(args.path_or_reference)
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/ref.py", line 114, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference ..
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/user/.local/lib/python3.6/site-packages/conans/client/command.py", line 1495, in run
    method(args[0][1:])
  File "/u/user/.local/lib/python3.6/site-packages/conans/client/command.py", line 389, in install
    install_folder=args.install_folder)
  File "/u/user/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 88, in wrapper
    return f(*args, **kwargs)
  File "/u/user/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 511, in install
    workspace = Workspace.get_workspace(wspath, wsinstall_folder)
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/workspace.py", line 102, in get_workspace
    return Workspace.get_workspace(parent, install_folder)
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/workspace.py", line 102, in get_workspace
    return Workspace.get_workspace(parent, install_folder)
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/workspace.py", line 102, in get_workspace
    return Workspace.get_workspace(parent, install_folder)
  [Previous line repeated 3 more times]
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/workspace.py", line 99, in get_workspace
    return Workspace(path, install_folder)
  File "/u/user/.local/lib/python3.6/site-packages/conans/model/workspace.py", line 130, in __init__
    content = load(path)
  File "/u/user/.local/lib/python3.6/site-packages/conans/util/files.py", line 174, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/apps/abc/conanws.yml'
```
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I would need more information. Are you using the workspaces feature? Do you have the `conanws.yml` file in that location? In a different one? Wich files are in your current and parent dir?

Thanks

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
