### ISSUE TITLE
[bug] Executing Conan 1.19.2 in FreeBSD 12.0-RELEASE

### ISSUE THREAD

**Issue by fpelliccioni** [conan-io/conan#5974]
There is an issue trying to execute `Conan 1.19.2` in FreeBSD, Specially in `FreeBSD 12.0-RELEASE`

### Environment Details (include every applicable attribute)
  * Operating System+version:
```
$ freebsd-version
12.0-RELEASE
```
  * Compiler+version: No matter
  * Conan version: 1.19.2
  * Python version:
```
$ python --version
Python 3.6.9
```

### Steps to reproduce (Include if Applicable)
*as root*:
```
    $ ln -s /usr/local/bin/python3.6 /usr/local/bin/python
    $ python --version
    $ pkg install py36-pip
    $ pip --version
    $ export PATH=$PATH:.local/bin/
    $ pip install conan --upgrade --user
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ ./conan user
Traceback (most recent call last):
  File "./conan", line 11, in <module>
    load_entry_point('conan==1.19.2', 'console_scripts', 'conan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/fernando/.local/lib/python3.6/site-packages/conans/conan.py", line 3, in <module>
    from conans.client.command import main
  File "/home/fernando/.local/lib/python3.6/site-packages/conans/client/command.py", line 14, in <module>
    from conans.client.conan_api import (Conan, default_manifest_folder, _make_abs_path)
  File "/home/fernando/.local/lib/python3.6/site-packages/conans/client/conan_api.py", line 22, in <module>
    from conans.client.cmd.user import user_set, users_clean, users_list, token_present
  File "/home/fernando/.local/lib/python3.6/site-packages/conans/client/cmd/user.py", line 1, in <module>
    from conans.client.store.localdb import LocalDB
  File "/home/fernando/.local/lib/python3.6/site-packages/conans/client/store/localdb.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by fpelliccioni** [comment]
Solution:

*as root:*
```
$ portsnap fetch
$ portsnap extract
$ cd /usr/ports/databases/py-sqlite3
$ make clean
$ make PYTHON_VERSION=python3.6 install
```
:)

```
$ conan user
Current user of remote 'conan-center' set to: 'None' (anonymous)
```

**Comment by memsharded** [comment]
Hi @fpelliccioni 

If I understood it correctly, this seems a problem with sqlite in Freebsd that can be solved by **compiling** py-sqlite3 from source, isn't it?

I am thinking of a way this could be automated, but doesn't seem easy with the python/pip tooling. Anyone else have some suggestion?

If not, I guess the best we could do is document this installation procedure properly. Maybe try-except the ``import sqlite3`` to raise an error that is a bit more informative?

**Comment by fpelliccioni** [comment]
Hi @memsharded!
Yes, you are right.
Actually, it is not a Conan bug, but I put it here for people googling could find the solution.

**Comment by isnullxbh** [comment]
I solved this issue by installing the py37-sqlite3 package via pkg (it may be easier for some users to use pkg instead of portsnap). There are other packages for different versions of Python, it can be listed by executing the following command: `pkg search ^py[0-9]+-sqlite3`
