### ISSUE TITLE
[ux] [bug] Improve error raised when 'settings.yml' cannot be parsed

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6044]
If the file `settings.yml` is invalid, Conan raises an ugly error with all the traceback.

---

How to reproduce:
 * Edit `settings.yml` and make it an invalid YAML
 * Run something like `conan create ....`:

```
⇒  conan create dep1 
Traceback (most recent call last):
  File "/Users/jgsogo/dev/conan/conan/conans/client/command.py", line 1911, in run
    method(args[0][1:])
  File "/Users/jgsogo/dev/conan/conan/conans/client/command.py", line 355, in create
    lockfile=args.lockfile)
 
.... lots of traceback  ...

yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 14, column 1:
    os dasf:ffs 
    ^
could not find expected ':'
  in "<unicode string>", line 15, column 12:
        Windows:
               ^

ERROR: while scanning a simple key
  in "<unicode string>", line 14, column 1:
    os dasf:ffs 
    ^
could not find expected ':'
  in "<unicode string>", line 15, column 12:
        Windows:
               ^
```

---

I would expect something easier like: `File 'settings.yml' has invalid YAML format/ cannot be parsed / error reading....` and, if possible, add the information with the line and column.

**Comment by nicememory** [comment]
I'll take a look.
