### ISSUE TITLE
[bug] ContextualVersionConflict due to Pylint -> Astroid -> Six

### ISSUE THREAD

**Issue by testworksau** [conan-io/conan#6074]
Conan depends on pylint: pylint>=2.0,!=2.3.0; python_version >= '3'
Pylint version 2.4.3 depends on astroid: "astroid>=2.3.0,<2.4"
astroid 2.3.3 depends on six~=1.12 (minimum 1.12, so will take 1.13 if available)
conan requires six < 1.13

Result:
> pkg_resources.ContextualVersionConflict: (six 1.13.0 (c:\python36\lib\site-packages), Requirement.parse('six<1.13,>=1.10.0'), {'conan'})

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version:
  * Conan version: 1.19.4
  * Python version: 3.6.7

### Steps to reproduce (Include if Applicable)
Install conan in python

As an aside, I'm curious as to why Conan requires Pylint to build conan packages.

**Comment by jgsogo** [comment]
I see that Astroid 2.3.3 depends on `six~=1.12`: https://github.com/PyCQA/astroid/blob/ace7b2967ea762ec43fc7be8ab9c8007564d9be2/astroid/__pkginfo__.py#L26

The last change has been introduced by Pylint relaxing Astroid here (https://github.com/PyCQA/pylint/commit/16cb696cba36ae4f8710e7a40ee48f07abbe976c), now it is `astroid>=2.3.0,<=2.5` instead of `<2.4`. 

But none of this is originating the issue, the problem is the availability of six `1.13`, if you have it in your working environment, or any dependency selects it first, then Conan will fail to install. I think we can/should relax our six requirement.

----

Why Conan uses pylint? Because we are linting the recipes and warning the user (someone may rely in these warnings). This is something we'd really like to remove from Conan codebase into a hook: https://github.com/conan-io/conan/issues/4454

**Comment by jgsogo** [comment]
Hi, @testworksau . Although theoretically it can be a conflict there, we've been running some installations (Windows, Mac, Linux) and it always works, `pip` handles the `six` version properly. 

How did you come across this issue? Anything else besides `pip install conan`?

**Comment by uilianries** [comment]
Hi @testworksau ! Which pip version are you running? `pip --version`

**Comment by testworksau** [comment]
Hi @uilianries - here's an excerpt of a log on a brand new, never had anything run on it before build agent. 

>Which pip version are you running?

19.3.1:
> Requirement already up-to-date: pip in c:\python36\lib\site-packages (19.3.1)

We install conan and conan-package-tools in each of our conan repositories via a single python requirement, named `iress-conan-utils. This has the following dependencies defined:

>conan_package_tools>=0.30.3,<0.31.0
>conan>=1.19.4,<1.20.0
>lxml
>javaproperties
>networkx
>pydot
>PyGithub

PyGitHub and javaproperties both require Six (the former = Any, the latter = ~=1.4)

From there:

```
Looking in indexes: simple
Collecting iress-conan-utils
  Downloading iress-conan-utils/iress_conan_utils-4.0.66-py3-none-any.whl (113kB)
Collecting PyGithub
  Downloading packages/packages/f4/86/7206d9b47cfdd5880081fdd1c94d9615cb6e10f4db1e98eb5b358839bc2a/PyGithub-1.44.1.tar.gz (110kB)
Collecting conan<1.20.0,>=1.19.4
  Downloading packages/packages/9d/29/ed39c9cb9a2a802fa991e5025a31e04b24add3a395d7fc22df42442700eb/conan-1.19.4.tar.gz (894kB)
Collecting networkx
  Downloading packages/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl (1.6MB)
Collecting lxml
  Downloading packages/packages/6f/6d/d54317403070fcaae973f38b9c298e4b4c101b469ae51afa7c1370e5c35b/lxml-4.4.1-cp36-cp36m-win_amd64.whl (3.7MB)
Collecting javaproperties
  Downloading packages/packages/3e/ab/273a862537551fc7845871c59abc2eecb74ae53633c1f019d16eb5c2e121/javaproperties-0.5.2-py2.py3-none-any.whl
Collecting pydot
  Downloading packages/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Collecting conan-package-tools<0.31.0,>=0.30.3
  Downloading packages/packages/b1/31/4e7a3f99972e8743b3d325ba9f23ccafbad68bbce0815bdbfc4479ec1cd5/conan_package_tools-0.30.3.tar.gz (58kB)
Collecting deprecated
  Downloading packages/packages/f6/89/62912e01f3cede11edcc0abf81298e3439d9c06c8dce644369380ed13f6d/Deprecated-1.2.7-py2.py3-none-any.whl
Collecting pyjwt
  Downloading packages/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting requests>=2.14.0
  Downloading packages/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting six
  Downloading packages/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.4,!=1.25.5
  Downloading packages/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
Collecting colorama<0.5.0,>=0.3.3
  Downloading packages/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting PyYAML<6.0,>=3.11
  Downloading packages/packages/76/da/60f8d638d81d64db4ed3c279c22eb3a1eebfcde6130fee678940e603b930/PyYAML-5.1.2-cp36-cp36m-win_amd64.whl (214kB)
Collecting patch==1.16
  Downloading packages/packages/da/74/0815f03c82f4dc738e2bfc5f8966f682bebcc809f30c8e306e6cc7156a99/patch-1.16.zip
Collecting fasteners>=0.14.1
  Downloading packages/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
Collecting node-semver==0.6.1
  Downloading packages/packages/08/51/6cf3a2b18ca35cbe4ad3c7538a7c3dc0cb24e71629fb16e729c137d06432/node_semver-0.6.1-py3-none-any.whl
Collecting distro<1.2.0,>=1.0.2
  Downloading packages/packages/b0/55/29bfd4d4d4149e860ed01aa446108eb17b240997b746c06a2d0c8ce04f69/distro-1.1.0-py2.py3-none-any.whl
Collecting future<0.19.0,>=0.16.0
  Downloading packages/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
Collecting pygments<3.0,>=2.0
  Downloading packages/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl (883kB)
Collecting deprecation<2.1,>=2.0
  Downloading packages/packages/b9/2a/d5084a8781398cea745c01237b95d9762c382697c63760a95cc6a814ad3a/deprecation-2.0.7-py2.py3-none-any.whl
Collecting tqdm<5,>=4.28.1
  Downloading packages/packages/b9/08/8505f192efc72bfafec79655e1d8351d219e2b80b0dec4ae71f50934c17a/tqdm-4.38.0-py2.py3-none-any.whl (53kB)
Collecting Jinja2<3,>=2.3
  Downloading packages/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125kB)
Collecting python-dateutil<3,>=2.7.0
  Downloading packages/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
Collecting bottle<0.13,>=0.12.8
  Downloading packages/packages/69/d1/efdd0a5584169cdf791d726264089ce5d96846a8978c44ac6e13ae234327/bottle-0.12.17-py3-none-any.whl (89kB)
Collecting pluginbase<1.0,>=0.5
  Downloading packages/packages/6e/f4/1db0a26c1c7fad81a1214ad1b02839a7bd98d8ba68f782f6edcc3d343441/pluginbase-0.7.tar.gz (40kB)
Collecting pylint!=2.3.0,>=2.0
  Downloading packages/packages/e9/59/43fc36c5ee316bb9aeb7cf5329cdbdca89e5749c34d5602753827c0aa2dc/pylint-2.4.4-py3-none-any.whl (302kB)
Collecting astroid>=2.2.0
  Downloading packages/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl (205kB)
Collecting decorator>=4.3.0
  Downloading packages/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl
Collecting pyparsing>=2.1.4
  Downloading packages/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl (67kB)
Collecting tabulate==0.8.2
  Downloading packages/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz (45kB)
Collecting wrapt<2,>=1.10
  Downloading packages/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting chardet<3.1.0,>=3.0.2
  Downloading packages/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<2.9,>=2.5
  Downloading packages/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting certifi>=2017.4.17
  Downloading packages/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
Collecting monotonic>=0.1
  Downloading packages/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting packaging
  Downloading packages/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23
  Downloading packages/packages/b9/82/833c7714951bff8f502ed054e6fbd8bd00e083d1fd96de6a46905cf23378/MarkupSafe-1.1.1-cp36-cp36m-win_amd64.whl
Collecting isort<5,>=4.2.5
  Downloading packages/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl (42kB)
Collecting mccabe<0.7,>=0.6
  Downloading packages/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8"
  Downloading packages/packages/fb/fc/a96a9ebe9e0f86a9ac65e0dd0d2dd02f3cc43b838c150169a5b56739b945/typed_ast-1.4.0-cp36-cp36m-win_amd64.whl (155kB)
Collecting lazy-object-proxy==1.4.*
  Downloading packages/packages/ae/fe/98f7c4717f1581eefc19eac54d430e4e47722d9b0dc5a7e485c3e42a5ff2/lazy_object_proxy-1.4.3-cp36-cp36m-win_amd64.whl
Installing collected packages: wrapt, deprecated, pyjwt, urllib3, chardet, idna, certifi, requests, six, PyGithub, colorama, PyYAML, patch, monotonic, fasteners, node-semver, distro, future, pygments, pyparsing, packaging, deprecation, tqdm, MarkupSafe, Jinja2, python-dateutil, bottle, pluginbase, typed-ast, lazy-object-proxy, astroid, isort, mccabe, pylint, conan, decorator, networkx, lxml, javaproperties, pydot, tabulate, conan-package-tools, iress-conan-utils
    Running setup.py install for wrapt: started
W:ERROR: conan 1.19.4 has requirement six<1.13,>=1.10.0, but you'll have six 1.13.0 which is incompatible.
W:ERROR: conan-package-tools 0.30.3 has requirement six<1.13.0,>=1.10.0, but you'll have six 1.13.0 which is incompatible.
```

**Comment by lasote** [comment]
I cannot reproduce the issue not even in Windows py3 with the list of requirements you provided ends just ok. Even if I install first `PyGitHub`, later six gets downgraded to the compatible version conan requires.

**Comment by testworksau** [comment]
@lasote well I don't know what more I can tell you - the log above clearly shows it is happening. 

I'm not in the habit of going to all of this effort to create a bug report for no reason...

**Comment by nleo** [comment]
Same problem

```
# conan --version
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/usr/lib/python3/dist-packages), Requirement.parse('six~=1.12'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/usr/lib/python3/dist-packages), Requirement.parse('six~=1.12'), {'astroid'})
```

**Comment by nleo** [comment]
I tryed to dowgrade
```
# pip3 install conan==1.11.3
Collecting conan==1.11.3
  Downloading https://files.pythonhosted.org/packages/a4/e0/3b2bf8102423789841b6c74178905819a7b69ccf37767f5cfeef4d1e399f/conan-1.11.3.tar.gz (756kB)
     |████████████████████████████████| 757kB 166kB/s 
Requirement already satisfied: PyJWT<2.0.0,>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (1.7.1)
Requirement already satisfied: PyYAML<3.14.0,>=3.11 in /usr/lib/python3/dist-packages (from conan==1.11.3) (3.12)
Requirement already satisfied: astroid>=1.6.5 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (2.3.3)
Requirement already satisfied: bottle<0.13,>=0.12.8 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.12.17)
Requirement already satisfied: colorama<0.5.0,>=0.3.3 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.4.1)
Requirement already satisfied: deprecation<2.1,>=2.0 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (2.0.7)
Requirement already satisfied: distro<1.2.0,>=1.0.2 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (1.1.0)
Requirement already satisfied: fasteners>=0.14.1 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.15)
Requirement already satisfied: future==0.16.0 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.16.0)
Requirement already satisfied: node-semver==0.6.1 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.6.1)
Requirement already satisfied: patch==1.16 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (1.16)
Requirement already satisfied: pluginbase<1.0,>=0.5 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (0.7)
Requirement already satisfied: pygments<3.0,>=2.0 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (2.4.2)
Requirement already satisfied: pylint>=1.9.3 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (2.4.4)
Requirement already satisfied: requests<3.0.0,>=2.7.0 in /usr/lib/python3/dist-packages (from conan==1.11.3) (2.18.4)
Requirement already satisfied: six<1.13,>=1.10.0 in /usr/lib/python3/dist-packages (from conan==1.11.3) (1.11.0)
Requirement already satisfied: tqdm<5,>=4.28.1 in /usr/local/lib/python3.6/dist-packages (from conan==1.11.3) (4.38.0)
Requirement already satisfied: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from astroid>=1.6.5->conan==1.11.3) (1.4.0)
Requirement already satisfied: lazy-object-proxy==1.4.* in /usr/local/lib/python3.6/dist-packages (from astroid>=1.6.5->conan==1.11.3) (1.4.3)
Requirement already satisfied: wrapt==1.11.* in /usr/local/lib/python3.6/dist-packages (from astroid>=1.6.5->conan==1.11.3) (1.11.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from deprecation<2.1,>=2.0->conan==1.11.3) (19.2)
Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python3.6/dist-packages (from fasteners>=0.14.1->conan==1.11.3) (1.5)
Requirement already satisfied: isort<5,>=4.2.5 in /usr/local/lib/python3.6/dist-packages (from pylint>=1.9.3->conan==1.11.3) (4.3.21)
Requirement already satisfied: mccabe<0.7,>=0.6 in /usr/local/lib/python3.6/dist-packages (from pylint>=1.9.3->conan==1.11.3) (0.6.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->deprecation<2.1,>=2.0->conan==1.11.3) (2.4.5)
Installing collected packages: conan
  Found existing installation: conan 1.18.5
    Uninstalling conan-1.18.5:
      Successfully uninstalled conan-1.18.5
    Running setup.py install for conan ... done
Successfully installed conan-1.11.3
```
no luck

**Comment by nleo** [comment]
Tried different vertions:

```
pip3 install conan
pip3 install conan==1.18.5
pip3 install conan==1.11.3
```

**Comment by lasote** [comment]
@nleo we need to know which packages do you previously have in the environment you are trying to install conan.

**Comment by memsharded** [comment]
> Literally all of the other dependencies I have mentioned only specify a minimum version for six. Why is Conan so restrictive?

Hi @testworksau 

I am sorry that you are experiencing this problem. We are not being that restrictive for no reason, the problem is that Conan dependencies (pylint, astroid), decided to hardcode a fixed dependency to ``six`` in their latest release, massively breaking us. We have tried to adapt to it, and minimizing the impact of such restrictive policy they imposed, we had to release patches for all previous Conan versions down to 1.7, that was a huge effort for us too. But it is being difficult to reproduce it or even reduce the impact for other scenarios where users have other environments.

**Comment by nleo** [comment]
I have fresh installation of Linux Mint 19.2

I installed youtube-dl

And try to compile a lib, on that depends rails app, on which I'm working on. 

I installed conan, and can't compile a lib.

That's all.

I'm not C++ or Python developer.

```
$ cat conanfile.txt 
[requires]
jsonformoderncpp/2.1.1@vthiery/stable
catch2/2.2.1@bincrafters/stable

[generators]
cmake 
```

C++ lib shares common logick though rails, Android, and iOS

```
sudo apt-get install cmake swig python-pip
pip install conan
```

**Comment by lasote** [comment]
@nleo thanks for the info. Will investigate and report.

**Comment by nleo** [comment]
I tried repoduce on VB, unsuccessfully

Install ubuntu-18.04.3-live-server-amd64.iso on VBox

```
apt update && apt upgrade

apt install -y python3-pip python3-setuptools
pip3 install --upgrade pip
pip3 install --upgrade youtube_dl
pip3 install conan
```

```
# pip3 install conan
oot/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built conan future patch-ng pluginbase wrapt
ERROR: astroid 2.3.3 has requirement six~=1.12, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: bottle, pyparsing, packaging, deprecation, distro, monotonic, fasteners, future, node-semver, patch-ng, pluginbase, pygments, python-dateutil, tqdm, lazy-object-proxy, wrapt, typed-ast, astroid, mccabe, isort, pylint, conan
Successfully installed astroid-2.3.3 bottle-0.12.17 conan-1.20.3 deprecation-2.0.7 distro-1.1.0 fasteners-0.15 future-0.18.2 isort-4.3.21 lazy-object-proxy-1.4.3 mccabe-0.6.1 monotonic-1.5 node-semver-0.6.1 packaging-19.2 patch-ng-1.17.1 pluginbase-0.7 pygments-2.4.2 pylint-2.4.4 pyparsing-2.4.5 python-dateutil-2.8.1 tqdm-4.38.0 typed-ast-1.4.0 wrapt-1.11.2
```

`conan -v` - works

```
# conan -v
Conan version 1.20.3
```

And build works - ok

**Comment by lasote** [comment]
In my case, playing with Mint in docker, everything installs correctly but then running conan:

```
pkg_resources.ContextualVersionConflict: (six 1.11.0 (/usr/lib/python3/dist-packages), Requirement.parse('six~=1.12'), {'astroid'})
```
If I install `pip install six==1.12` the problem is solved. 

So, we have possibles issues with the lower value for the six range and also for the higher...
I think we should try to remove the dependency to astroid/pylint in next release and try to do a plugin, this version missmatch with astroid is a never ending issue.

**Comment by testworksau** [comment]
> I am sorry that you are experiencing this problem. We are not being that restrictive for no reason, the problem is that Conan dependencies (pylint, astroid), decided to hardcode a fixed dependency to `six` in their latest release, massively breaking us. 

Hi @memsharded - I understand the original reason for your hard pin, but it shouldn't be required anymore.

I've compiled a bit of a timeline:

`Sep 25 2019` astroid [hard pins six to 1.12](https://github.com/PyCQA/astroid/commit/e1b4e11e383bf281544f1300e41eea2ac6ab251c#diff-1e8a54c814195e2e0b781b5c41b2bf58) which is the latest version at the time. This change is released in astroid 2.3.1. Previously, there was no upper limit. 

conan continues to work fine as conan's six version is >= 1.10

`Nov 6 2019` six released a new version, [1.13](https://github.com/benjaminp/six/releases/tag/1.13.0). 

conan breaks as it selects six 1.13 instead of 1.12

`Nov 6 2019` conan [hard pins six to 1.12](https://github.com/conan-io/conan/commit/476032e4f54edec6c64acc285a03e90905cbe4a7#diff-37885be8e16baf1d68f08f4273221d7b), via @uilanries, to ensure the astroid hard pin is met. 


`Nov 6 2019` [conan relaxes six hard pin back to six >= 1.10 but reduces upper limit to 1.12.x](https://github.com/conan-io/conan/commit/c8969efe40e40ec7368e2f412c9f212064acc709#diff-37885be8e16baf1d68f08f4273221d7b). 

conan starts working again for most 

`Nov 7 2019` [astroid relaxes the pin of six to minimum six 1.12](https://github.com/PyCQA/astroid/commit/4a244535ecb5530a1c346f8bd39800f3282f3396#diff-1e8a54c814195e2e0b781b5c41b2bf58), via @uilanries, and releases astroid 2.3.3 

`Nov 13 2019` [pylint changes to allow astroid 2.4.x as well as 2.3.x](https://github.com/PyCQA/pylint/commit/16cb696cba36ae4f8710e7a40ee48f07abbe976c#diff-3c034662e223058fec97dcfc3b4af8d0). It has no direct dependency on six, only an indirect dependency via astroid. The change to relax astroid has no effect on conan as there is no version 2.4.x of astroid *yet*.

Correct me if I'm wrong, but based on the information above, on the 7th November (after the new astroid release), the conan hard pin could have been relaxed to six~=1.12 to match [astroids new minimum requirements](https://github.com/PyCQA/astroid/blob/master/astroid/__pkginfo__.py#L26). 

Given:

- Versions of astroid prior to 2.3.1 had no bounds specified on six
- Only version 2.3.2 had the hard pin to six 1.12

I can't see why modifying conan to require six~=1.12 would break anyone.

**Comment by memsharded** [comment]
astroid and pylint dependencies have been removed from the conan codebase. They were required only for the recipe linter, and that has been moved to a hook. This will be effective in Conan 1.21 to be released soon.

**Comment by Foadsf** [comment]
I just had the same problem on macOS:

> ERROR: astroid 2.3.3 has requirement wrapt==1.11.*, but you'll have wrapt 1.12.0 which is incompatible.

for the moment downgrading `wrapt` should help. From [here](https://stackoverflow.com/a/5226504/4999991) run:

    pip3 install -Iv 'wrapt==<veriosn>'

**Comment by memsharded** [comment]
Hi @Foadsf 

Pylint and Astroid are no longer Conan dependencies: https://github.com/conan-io/conan/blob/develop/conans/requirements.txt

If you are using a recent Conan version, this shouldn't be an issue anymore, please check.
