### ISSUE TITLE
[bug] Sporadic FileNotFoundError during upload (conan_export.tgz.dirty)

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#6141]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04
  * Compiler+version: clang 8.0
  * Conan version: 1.20.3
  * Python version: 3.6.5

### Steps to reproduce (Include if Applicable)

I don't really know - this happens rarely during uploads. Might be a race condition.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
[2019-11-27T11:46:38.974Z] Traceback (most recent call last):
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/command.py", line 1938, in run
[2019-11-27T11:46:38.974Z]     method(args[0][1:])
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/command.py", line 1400, in upload
[2019-11-27T11:46:38.974Z]     retry_wait=args.retry_wait, integrity_check=args.check)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/conan_api.py", line 81, in wrapper
[2019-11-27T11:46:38.974Z]     return f(api, *args, **kwargs)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/conan_api.py", line 881, in upload
[2019-11-27T11:46:38.974Z]     retry, retry_wait, integrity_check, policy, query=query)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 89, in upload
[2019-11-27T11:46:38.974Z]     integrity_check, policy, remote, upload_recorder, remotes)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 190, in _upload_ref
[2019-11-27T11:46:38.974Z]     self._upload_recipe(ref, conanfile, retry, retry_wait, policy, recipe_remote, remotes)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 222, in _upload_recipe
[2019-11-27T11:46:38.974Z]     the_files = self._compress_recipe_files(ref)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 326, in _compress_recipe_files
[2019-11-27T11:46:38.974Z]     self._output)
[2019-11-27T11:46:38.974Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 499, in _compress_recipe_files
[2019-11-27T11:46:38.975Z]     add_tgz(EXPORT_TGZ_NAME, export_tgz_path, files, symlinks, "Compressing recipe...")
[2019-11-27T11:46:38.975Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 496, in add_tgz
[2019-11-27T11:46:38.975Z]     tgz_path = compress_files(tgz_files, tgz_symlinks, tgz_name, dest_folder, output)
[2019-11-27T11:46:38.975Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/client/cmd/uploader.py", line 548, in compress_files
[2019-11-27T11:46:38.975Z]     tgz.close()
[2019-11-27T11:46:38.975Z]   File "/usr/local/pyenv/versions/3.6.4/lib/python3.6/contextlib.py", line 88, in __exit__
[2019-11-27T11:46:38.975Z]     next(self.gen)
[2019-11-27T11:46:38.975Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/util/files.py", line 64, in set_dirty_context_manager
[2019-11-27T11:46:38.975Z]     clean_dirty(folder)
[2019-11-27T11:46:38.975Z]   File "/data/jenkins/conan_build/2095192381/conan/lib/conan-1.20.3-71-linux-py36.pyz/conans/util/files.py", line 52, in clean_dirty
[2019-11-27T11:46:38.975Z]     os.remove(dirty_file)
[2019-11-27T11:46:38.975Z] FileNotFoundError: [Errno 2] No such file or directory: '/data/jenkins/conan_build/2095192381/conan/.conan/data/libidn/2.0.5-30/rcombs/eae-license/export/conan_export.tgz.dirty'
```

**Comment by memsharded** [comment]
Hi @sztomi 

Can you give a bit of context of the upload command? are you using the basic ``conan upload``, or do you have some wrapper around it? Are you parallelizing the upload (I suspect, if you are thinking about race conditions)?

**Comment by tru** [comment]
Yeah we parallelize uploads by running multiple conan uploads. It has been working fine until we upgraded from 1.4.

I did see something was merged with native parallel uploads - how does that work and maybe we can switch to that?

**Comment by memsharded** [comment]
Yes, it is merged in develop branch (available in test-pypi) will be released next Conan 1.21. Passing the ``--parallel`` argument to ``conan upload`` will enable it.
If you could give it a try, that would be great.

Meanwhile, I am going to have a look at the current upload code for that race condition.

**Comment by memsharded** [comment]
I have had a look, my summary:

- Uploads have never been protected by locks 😱 
- Is it possible that you were uploading first the recipes, to avoid race conditions, then upload in parallel all the binaries? That should avoid the race conditions.
- If nothing has changed in your end, it is possible that the race condition was potentially there, just got more likely to happen with changes in the upload code.

I would recommend to check the built-in parallel upload support and report, maybe it is not necessary to provide any kind of concurrency support if the built-in is good enough. Thanks!

**Comment by sztomi** [comment]
Yeah, we did not change this code (yet), it's only the conan version bump. 

We already upload the recipes first (our build exports and uploads all recipes; then starts building each profile in parallel, i.e. Artifactory the builder nodes can get the recipes from Artifactory). 

I'm happy to check the prerelease on testpypi, but last time I tried that, I could not install it because deps of conan were not on testpypi. What can I do to work around that?

**Comment by memsharded** [comment]
Hi @sztomi 

I think the dependencies have never been in testpypi, only the Conan package. I have tried with: 
```bash
pip install -i https://test.pypi.org/simple/ conan==1.10.0.dev1543224779
```
And it is still broken. Or maybe dependencies have been removed. What can be done is:
```bash
pip install conan
pip install patch-ng -U
pip install -i https://test.pypi.org/simple/ conan
```

I have been reviewing the code, and identified the source of the race conditions. It is the "dirty" tracker itself, it was not existing in Conan 1.4, was added many releases ago. It doesn't seem easy to fix, it will probably involve adding locks over the packages, so please let me know how it goes with the built-in parallel uploads and we will decide from there. Thanks!

**Comment by sztomi** [comment]
We'd like to move to the parallel upload feature, but the docs seem a bit lacking. The only example is uploading everything (by passing `*`). Is that the only way to invoke it? Our current code tracks the upload status of each package. Is that possible by reading the JSON output? Can we have an example of that in the docs?

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, parallel uploads will first upload the recipe and then each binary concurrently
