### ISSUE TITLE
Changing setting CONAN_USER_HOME_SHORT to None results in errors

### ISSUE THREAD

**Issue by nussbrot** [conan-io/conan#6379]
After reading https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home-short
i thought i can now set  CONAN_USER_HOME_SHORT to None and override conanfile.py setting short_path=True. 
However, doing this after already having installed packages with short_paths =true and trying to install the same packages again gives me this error, which i do not understand:

```
Traceback (most recent call last):
  File "c:\venvs\py38-test\lib\site-packages\conans\client\command.py", line 1947, in run
    method(args[0][1:])
  File "c:\venvs\py38-test\lib\site-packages\conans\client\command.py", line 470, in install
    info = self._conan.install(path=args.path_or_reference,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "c:\venvs\py38-test\lib\site-packages\conans\client\conan_api.py", line 553, in install
    deps_install(app=self.app,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\manager.py", line 46, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_manager.py", line 109, in load_graph
    return self._resolve_graph(root_node, graph_info, build_mode, check_updates, update, remotes,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_manager.py", line 230, in _resolve_graph
    deps_graph = self._load_graph(root_node, check_updates, update,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_manager.py", line 340, in _load_graph
    self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_manager.py", line 277, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_binaries.py", line 321, in evaluate_graph
    self._evaluate_node(node, build_mode, update, remotes)
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_binaries.py", line 167, in _evaluate_node
    self._process_node(node, pref, build_mode, update, remotes)
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_binaries.py", line 220, in _process_node
    self._evaluate_cache_pkg(node, package_layout, pref, metadata,  remote, remotes, update,
  File "c:\venvs\py38-test\lib\site-packages\conans\client\graph\graph_binaries.py", line 97, in _evaluate_cache_pkg
    assert node.prev, "PREV for %s is None: %s" % (str(pref), metadata.dumps())
AssertionError: PREV for test/test@test/test:ed4555d8a4e47e416cd9741d38e3e08abdd319f7 is None: {"recipe": {"revision": "0", "remote": "conan-local", "properties": {}, "checksums": {"conanmanifest.txt": {"md5": "21f3722a32c628942a1e5764f5f889d3", "sha1": "43d3f1180c97426756fd40e90c1b31e37aae788f"}, "conanfile.py": {"md5": "79b0f834bde95b6e170325a0234641e9", "sha1": "859bf52706552dee9e553aeb92543867485686ce"}}}, "packages": {"ed4555d8a4e47e416cd9741d38e3e08abdd319f7": {"revision": null, "recipe_revision": null, "remote": null, "properties": {}, "checksums": {}}}}
```

Note that the problem is gone when i delete the cache before installing.

**Comment by czoido** [comment]
Hi @nussbrot,
It's normal that it fails because you are first populating the cache in the short_paths folder and changing it to the "regular" cache. Then it's very likely that Conan will try to get files from the regular cache but those files will be in the short_paths folder.
I would advise to never change `CONAN_USER_HOME_SHORT` when you have already populated the cache.

**Comment by nussbrot** [comment]
Hi @czoido, thanks. Yeah it helps and maybe it helps others, too. Maybe you could update the documentation to include that changing this setting breaks the cache?
Or maybe it is even possible to generate a more meaningful error message?

**Comment by memsharded** [comment]
CONAN_USER_HOME_SHORT  removed in 2.0, closing as outdated, thanks!
