### ISSUE TITLE
[feature] Improve encoding error message

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#6422]
```
$ conan export-pkg -sf=tests/tmp/source -bf=tests/tmp/build-shared_debug tests user/testing
Exporting package recipe
pkg/0.1.0@user/testing exports_sources: Copied 3 files: ._Icon, .mxm, .stlay
...
pkg/0.1.0@user/testing: A new conanfile.py version was exported
pkg/0.1.0@user/testing: Folder: /tmp/conan/.conan/data/pkg/0.1.0/user/testing/export
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/client/command.py", line 1947, in run
    method(args[0][1:])
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/client/command.py", line 953, in export_pkg
    ignore_dirty=args.ignore_dirty)
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/client/conan_api.py", line 81, in wrapper
    return f(api, *args, **kwargs)
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/client/conan_api.py", line 413, in export_pkg
    graph_lock=graph_info.graph_lock, ignore_dirty=ignore_dirty)
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/client/cmd/export.py", line 154, in cmd_export
    manifest.save(package_layout.export())
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/model/manifest.py", line 110, in save
    save(path, repr(self))
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/util/files.py", line 183, in save
    new_content = to_file_bytes(content, encoding)
  File "/opt/pyenv/versions/3.5.2/lib/python3.5/site-packages/conans/util/files.py", line 201, in to_file_bytes
    content = bytes(content, encoding)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcef' in position 14155: surrogates not allowed
ERROR: 'utf-8' codec can't encode character '\udcef' in position 14155: surrogates not allowe
```

This error happens when Conan reads the names of the files exported and tries to write them in the conanmanifest.txt file. We now these encoding errors are always problematic and that they are affected by the Python version. However, I think we can improve the error message and guide better the users so they can debug and find the offending characters.

cc/ @joaquin-herrero

**Comment by memsharded** [comment]
I think this was solved time ago when moving to minimum Python 3.6 and utf-8 for all conan files, closing this as outdated, but please @joaquin-herrero, open a new ticket if this is still an issue, thanks!
