### ISSUE TITLE
"USERNAME" envvar is not available in Appveyor

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6503]
Under some circumstances, the environment variable `USERNAME` is not available in Windows (ie [this job in Appveyor](https://ci.appveyor.com/project/ConanOrgCI/examples/builds/30697691/job/roeajyx3eqy89d4n)), if using `short_paths = True` (like `emsdk_installer/1.38.29@bincrafters/stable`) Conan will raise an ugly traceback:

```
[00:02:12] Traceback (most recent call last):
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\command.py", line 1969, in run
[00:02:12]     method(args[0][1:])
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\command.py", line 352, in create
[00:02:12]     info = self._conan.create(args.path, name, version, user, channel,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
[00:02:12]     return f(api, *args, **kwargs)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\conan_api.py", line 361, in create
[00:02:12]     create(self.app, ref, graph_info, remotes, update, build_modes,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\cmd\create.py", line 45, in create
[00:02:12]     deps_install(app=app,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\manager.py", line 46, in deps_install
[00:02:12]     deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_manager.py", line 109, in load_graph
[00:02:12]     return self._resolve_graph(root_node, graph_info, build_mode, check_updates, update, remotes,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_manager.py", line 230, in _resolve_graph
[00:02:12]     deps_graph = self._load_graph(root_node, check_updates, update,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_manager.py", line 340, in _load_graph
[00:02:12]     self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_manager.py", line 324, in _recurse_build_requires
[00:02:12]     self._recurse_build_requires(graph, builder,
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_manager.py", line 277, in _recurse_build_requires
[00:02:12]     self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_binaries.py", line 321, in evaluate_graph
[00:02:12]     self._evaluate_node(node, build_mode, update, remotes)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_binaries.py", line 167, in _evaluate_node
[00:02:12]     self._process_node(node, pref, build_mode, update, remotes)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\client\graph\graph_binaries.py", line 208, in _process_node
[00:02:12]     package_folder = package_layout.package(pref)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\paths\package_layouts\package_cache_layout.py", line 30, in wrap
[00:02:12]     return path_shortener(p, self._short_paths)
[00:02:12]   File "C:\projects\examples\.tox\py38-conandev\lib\site-packages\conans\util\windows.py", line 69, in path_shortener
[00:02:12]     userdomain, username = os.getenv("USERDOMAIN"), os.environ["USERNAME"]
[00:02:12]   File "c:\python38\lib\os.py", line 673, in __getitem__
[00:02:12]     raise KeyError(key) from None
[00:02:12] KeyError: 'USERNAME'
[00:02:12] 
[00:02:12] ERROR: 'USERNAME'
```

We need to handle this situation.

**Comment by uilianries** [comment]
Indeed, Appveyor doesn't offer such env var: https://www.appveyor.com/docs/environment-variables/

**Comment by uilianries** [comment]
Maybe running `whoami` command and getting its output

**Comment by jgsogo** [comment]
The problem was on me, I was not passing those environments variables to the actual scripts been executed. Let's close it until someone reports the issue.
