### ISSUE TITLE
No file libz.so?

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/conan#673]
I don't know that this is a bug in conan, but I'm having trouble making headway on how to debug it.

```
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 9, in <module>
    load_entry_point('conan==0.15.0', 'console_scripts', 'conan')()
  File "/usr/local/lib/python2.7/dist-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 861, in main
    error = command.run(args)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 760, in run
    method(args[0][1:])
  File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 536, in export
    self._manager.export(args.user, current_path, keep_source)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 125, in export
    conan_ref, conan_file.short_paths, keep_source)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/export.py", line 21, in export_conanfile
    _export(file_patterns, origin_folder, destination_folder, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/export.py", line 81, in _export
    copier(pattern)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/file_copier.py", line 88, in __call__
    shutil.copy2(abs_src_name, abs_dst_name)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/conan/imageflow/tests/libpng/lib/libz.so.1'
```

**Comment by nathanaeljones** [comment]
It seems like a bunch of temporary files in `/home/conan/imageflow/tests/libpng` triggered this. I didn't realize conan looked recursively for things.

**Comment by memsharded** [comment]
Yes, it depends on the patterns used in ``exports``, if you are using ``*``, then, yes it will go recursively down all the folders besides the conanfile. I usually try to run builds out-of-source to avoid these kind of issues. Or have the things I want to export in a ``src`` subfolder or something, then I use the ``exports = "src/*"`` pattern.

**Comment by nathanaeljones** [comment]
Thanks. I didn't expect \* to be recursive. Good to know!

**Comment by memsharded** [comment]
Yes, actually all copy pattern operations (imports, package) are filepath based, so they will go into nested subfolders.
