### ISSUE TITLE
Conan install fails in the docker enviroment with below message

### ISSUE THREAD

**Issue by manojkdi** [conan-io/conan#6756]
tic2000codegen/20.2.0.B1-0@library-c2000/ga: Already installed!
conanfile.py (TopograndeBootROM/None@None/None): Applying build-requirement: tic2000codegen/20.2.0.B1-0@library-c2000/ga
conanfile.py (TopograndeBootROM/None@None/None): Generator txt created conanbuildinfo.txt
conanfile.py (TopograndeBootROM/None@None/None): ERROR: Generator txt(file:conanbuildinfo.txt) failed
[Errno 2] No such file or directory: '/project/conanbuildinfo.txt'
ERROR: [Errno 2] No such file or directory: '/project/conanbuildinfo.txt'

/project is the  shared volume of conan

**Comment by danimtb** [comment]
HI @manojkdi,

it is difficult to say what is the issue without a minimal description of your dependency graph. Could you please add some more details about your case? What commands are you running? Is the environment something relevant to reproduce this issue?

**Comment by manojkdi** [comment]
I am running the following conan command inside  docker
powershell 'docker-compose run --rm topograndebootrom conan install . -g virtualenv'

and the conan install fails with error message as stated.

**Comment by manojkdi** [comment]
This is becoming a very critical issue for me. This issue is intermittent, some times the Conan install proceeds smoothly without any issue.

**Comment by danimtb** [comment]
Sorry, I don't have enough information to help you. I will need some reproducible way to test this and see where it fails. I can recommend you enabling some debug variables like https://docs.conan.io/en/latest/reference/env_vars.html#conan-trace-file, increase the debug level and so to see if we can figure out what is happening

**Comment by manojkdi** [comment]
In the success case the log looks something like this
17:34:24  
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Installing package
17:34:24  Requirements
17:34:24  Packages
17:34:24  Build requirements
17:34:24      tic2000codegen/20.2.1.LTS-0@library-c2000/ga from 'art' - Cache
17:34:24  Build requirements packages
17:34:24      tic2000codegen/20.2.1.LTS-0@library-c2000/ga:be241241e9d4718e5bab4eb33935bbb69606bb0c - Cache
17:34:24  
17:34:24  tic2000codegen/20.2.1.LTS-0@library-c2000/ga: Already installed!
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Applying build-requirement: tic2000codegen/20.2.1.LTS-0@library-c2000/ga
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Generator txt created conanbuildinfo.txt
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Generator virtualenv created activate.sh
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Generator virtualenv created deactivate.sh
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Generated conaninfo.txt
17:34:24  conanfile.py (TopograndeBootROM/None@None/None): Generated graphinfo

**Comment by manojkdi** [comment]
Let me know if this helps

**Comment by manojkdi** [comment]
The command being run is conan install . -g virtualenv
 and is run as part of docker entry point script

**Comment by danimtb** [comment]
Maybe the `/project` folder is not available? I am not sure, but this is something very tested and it doesn't fail.

**Comment by manojkdi** [comment]
No it is available and this failure is intermittent.

**Comment by manojkdi** [comment]
By the time docker entrypoint script starts the shared volume project is
mounted as per docker documentation.

**Comment by uilianries** [comment]
Hi @manojkdi which docker image are you running? Did you try Conan docker images?

https://hub.docker.com/u/conanio

They are very stable and used in Conan CI.

**Comment by manojkdi** [comment]
I am using docker images which are built inside our company. They come prebuilt with Conan. As suggested by @danimtb  I added trace log so now **Conan intermittently fails with this error**

3:26:37  Traceback (most recent call last):


13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/model/ref.py", line 111, in loads
13:26:37      _, name, version, user, channel, revision, _ = ConanFileReference.sep_pattern.split(text)
13:26:37  ValueError: not enough values to unpack (expected 7, got 1)
13:26:37  
13:26:37  During handling of the above exception, another exception occurred:
13:26:37  
13:26:37  Traceback (most recent call last):
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 388, in install
13:26:37      ref = ConanFileReference.loads(args.path_or_reference)
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/model/ref.py", line 114, in loads
13:26:37      "OpenCV/1.0.6@user/stable" % text)
13:26:37  conans.errors.ConanException: Wrong package recipe reference .
13:26:37  Write something like OpenCV/1.0.6@user/stable
13:26:37  
13:26:37  During handling of the above exception, another exception occurred:
13:26:37  
13:26:37  Traceback (most recent call last):
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 1607, in run
13:26:37      method(args[0][1:])
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 401, in install
13:26:37      install_folder=args.install_folder)
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/client/conan_api.py", line 89, in wrapper
13:26:37      log_command(f.__name__, kwargs)
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/util/tracer.py", line 149, in log_command
13:26:37      _append_action("COMMAND", {"name": name, "parameters": parameters})
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/util/tracer.py", line 63, in _append_action
13:26:37      _append_to_log(props)
13:26:37    File "/usr/local/lib/python3.6/dist-packages/conans/util/tracer.py", line 53, in _append_to_log
13:26:37      with fasteners.InterProcessLock(filepath + ".lock", logger=logger):
13:26:37    File "/usr/local/lib/python3.6/dist-packages/fasteners/process_lock.py", line 179, in __enter__
13:26:37      gotten = self.acquire()
13:26:37    File "/usr/local/lib/python3.6/dist-packages/fasteners/process_lock.py", line 156, in acquire
13:26:37      self._do_open()
13:26:37    File "/usr/local/lib/python3.6/dist-packages/fasteners/process_lock.py", line 128, in _do_open
13:26:37      self.lockfile = open(self.path, 'a')
13:26:37  FileNotFoundError: [Errno 2] No such file or directory: b'/project/conan_trace.log.lock'
13:26:37  
13:26:37  ERROR: [Errno 2] No such file or directory: b'/project/conan_trace.log.lock'

Attacing the docker-entrypoint.sh for reference. 

**#!/bin/bash
set -e
dos2unix $(find ./tools/ -type f -name "*.sh")
dos2unix $(find ./build_csp/ -type f -name "*.sh")
dos2unix $(find ./process/ -type f -name "*.sh")
ls /project export CONAN_TRACE_FILE=/project/conan_trace.log
#needed for klocwork workaround for MISRA.ETYPE.ASSIGN.2012 
cp -f /project/tools/cl2000_filter.py /$KLOCWORK_INSTALL_DIR/config/
cp -f /project/tools/cl2000_filter.py /$KLOCWORK_INSTALL_DIR/server/config/
cp /project/tools/.ti_foqus /home/developer
#adding ls to ensure caching and failures of conan install
ls /project && conan install . -g virtualenv
source activate.sh
export C2000_C_DIR=$CCS_C2000COMPILER/include;
exec "$@"**

**Comment by uilianries** [comment]
I see 2 errors:

>  13:26:37 conans.errors.ConanException: Wrong package recipe reference .

You need to check the package reference. It must contain `name/version@user/channel`. If some value is declared in the recipe, you skip and pass only what need, e.g. `conan create . user/channel`. You can obtain more information here: https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#requires

>  13:26:37 FileNotFoundError: [Errno 2] No such file or directory: b'/project/conan_trace.log.lock'

It seems be you are using a volume, but is not pointing to the correct path, OR, you have a permission limitation, like your user is not able to write on root folder in the container.

I don't recommend you running root as default user. It's a security flaw well explored, I do recommend running a non-root user. You can obtain more information about the security problem here:

- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://docs.docker.com/engine/security/security/

**Comment by danimtb** [comment]
Closing this as there is no recent activity on the issue and we were not able to reproduce it. Thank you
