### ISSUE TITLE
Python2 failure in cygwin patch

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6784]
This patch has introduced a python 2 incompatibility: 
FileNotFoundError is not defined in python 2.

```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\conans\client\command.py", line 2002, in run
    method(args[0][1:])
  File "c:\python27\lib\site-packages\conans\client\command.py", line 495, in install
    lockfile=args.lockfile)
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 89, in wrapper
    return f(api, *args, **kwargs)
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 573, in install
    recorder=recorder)
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 54, in deps_install
    False, update, remotes, recorder)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_manager.py", line 114, in load_graph
    recorder, apply_build_requires=apply_build_requires)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_manager.py", line 240, in _resolve_graph
    graph_lock=graph_lock)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_manager.py", line 349, in _load_graph
    apply_build_requires=apply_build_requires)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_manager.py", line 281, in _recurse_build_requires
    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_binaries.py", line 334, in evaluate_graph
    self._evaluate_node(node, build_mode, update, remotes)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_binaries.py", line 167, in _evaluate_node
    self._process_node(node, pref, build_mode, update, remotes)
  File "c:\python27\lib\site-packages\conans\client\graph\graph_binaries.py", line 208, in _process_node
    package_folder = package_layout.package(pref)
  File "c:\python27\lib\site-packages\conans\paths\package_layouts\package_cache_layout.py", line 31, in wrap
    return path_shortener(p, self._short_paths)
  File "c:\python27\lib\site-packages\conans\util\windows.py", line 92, in path_shortener
    except (subprocess.CalledProcessError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
```

_Originally posted by @Pollux42 in https://github.com/conan-io/conan/pull/6741#issuecomment-608045798_

**Comment by memsharded** [comment]
Hi @Pollux42

Certainly this is an unintended issue. Not sure how this escaped our CI, will check asap and release a minor fix if that is the case.

In any case, please note that Python2 support has been deprecated in Conan and it will be soon completely removed. Please upgrade to Python3 as soon as possible. Note that you can upgrade to Python3 just for Conan if you have other python apps, using python virtualenvs.

**Comment by memsharded** [comment]
Opened a 1.24.1 release branch with a fix for this: https://github.com/conan-io/conan/tree/release/1.24.1

**Comment by Pollux42** [comment]
Hi @memsharded 

I'm not surprised about dropping python 2 support from conan. But if this is the case you should state it on pypi. (https://pypi.org/project/conan/ says that conan still support python 2)

And thank you about your advice on virtualenvs, indeed we should do that.

**Comment by memsharded** [comment]
Oh, that is true, PyPI still says that. We have clearly stated both in the documentation: https://docs.conan.io/en/latest/installation.html and in the Conan command itself, when it prompts now an interactive message to proceed, requiring user interaction if still running on Python 2. Haven't you seen such command line messages?

We haven't removed it yet from PyPI, because you can still get it. It is deprecated, but not removed. We still run CI with Python27 (the reason that error passed CI is because it is in a section of Windows cacls, that is very difficult to test in automatic testing).

**Comment by jgsogo** [comment]
Hi, @Pollux42 

We'll try to keep compatibility with Python 2 for some releases (unless we find any blocker, like a dependency not supporting it or a new core feature that requires Python 3) but we are really trying to deprecate it and move all our users to Python 3.

@memsharded , should we remove the category `Programming Language :: Python :: 2` from pypi? People will still be able to install it using old pythons, it isn't something that `pip` will identify and block the installation.  Please, correct me if I'm wrong, but I think that `pip` will only block that installation if we use `Python :: 3 :: Only` category.

**Comment by memsharded** [comment]
> @memsharded , should we remove the category Programming Language :: Python :: 2 from pypi? People will still be able to install it using old pythons, it isn't something that pip will identify and block the installation. Please, correct me if I'm wrong, but I think that pip will only block that installation if we use Python :: 3 :: Only category.

Yes, I was afraid of breaking some installations, but if it really doesn't break, then yes, we can remove it from PyPI too.

**Comment by jgsogo** [comment]
Close via https://github.com/conan-io/conan/pull/6786
