### ISSUE TITLE
[bug] tools.which() finds tool 7zr.exe on Windows Server 2012 R2, but can't invoke it

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6866]
### Environment Details (include every applicable attribute)
  * Operating System+version Windows Server 2012 R2
  * Compiler+version: vs2015 v140
  * Conan version: Conan version 1.20.4
  * Python version: N/A

### Steps to reproduce (Include if Applicable)

At my org, we can't use pre-built binaries from outside, but we can use conan-center-index recipes.  I'm trying to build https://github.com/conan-io/conan-center-index/blob/master/recipes/7zip/19.00/conanfile.py#L33-L34 but it has:

```
        if not tools.which("7zr"):
            self.build_requires("lzma_sdk/9.20")
```

instead of looking for this requirement and not finding it, my Jenkins job seems to blow right past that check:

```
make/4.2.1: Downloaded recipe revision 2516c4ecfaf0129339951b0be88ed356
DEBUG :uploader_downloader.py[186]: DOWNLOAD: https://artprod.dev.mycorp.com/artifactory/api/conan/bb-conan-nx-stable-local/v2/conans/make/4.2.1/_/_/revisions/2516c4ecfaf0129339951b0be88ed356/packages/456f15897172eef340fcbac8a70811f2beb26a93/revisions/b4809fcb649c41b3d2ab43d60abb62e7/files/conaninfo.txt [2020-04-15 14:11:19,602]
[19.00] $ cmd.exe /C "conan_build_info E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\conan_log.log --output E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\recipes\7zip\19.00@tmp\artifactory\conan6212455936633652520build-info && exit %%ERRORLEVEL%%"
[Pipeline] runConanCommand
[19.00] $ cmd.exe /C "conan graph lock . --profile vs2015_14_v140_Release --build=missing && exit %%ERRORLEVEL%%"
DEBUG :conan_api.py   [163]: INIT: Using config 'E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\conan.conf' [2020-04-15 14:11:21,083]
DEBUG :tracer.py      [155]: CONAN_API: create_lock(remote_name=None,settings=None,options=None,env=None,profile_names=['vs2015_14_v140_Release'],update=False,lockfile=None,build=['missing']) [2020-04-15 14:11:21,086]
DEBUG :profile_loader.py[104]: PROFILE LOAD: E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\profiles\default [2020-04-15 14:11:21,090]
DEBUG :profile_loader.py[104]: PROFILE LOAD: E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\profiles\vs2015_14_v140_Release [2020-04-15 14:11:21,092]
DEBUG :graph_builder.py[40]: GRAPH: Time to load deps 0.0010006427764892578 [2020-04-15 14:11:21,170]
DEBUG :graph_builder.py[342]: GRAPH: new_node: make/4.2.1 [2020-04-15 14:11:21,189]
DEBUG :rest_client_common.py[160]: REST: ping: https://artprod.dev.mycorp.com/artifactory/api/conan/bb-conan-nx-stable-local/v1/ping [2020-04-15 14:11:21,192]
DEBUG :rest_client.py [38]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions'] [2020-04-15 14:11:21,498]
DEBUG :rest_client_common.py[185]: REST: get: https://artprod.dev.mycorp.com/artifactory/api/conan/bb-conan-nx-stable-local/v2/conans/make/4.2.1/_/_/revisions/2516c4ecfaf0129339951b0be88ed356/packages/456f15897172eef340fcbac8a70811f2beb26a93/latest [2020-04-15 14:11:21,498]
DEBUG :uploader_downloader.py[186]: DOWNLOAD: https://artprod.dev.mycorp.com/artifactory/api/conan/bb-conan-nx-stable-local/v2/conans/make/4.2.1/_/_/revisions/2516c4ecfaf0129339951b0be88ed356/packages/456f15897172eef340fcbac8a70811f2beb26a93/revisions/b4809fcb649c41b3d2ab43d60abb62e7/files/conaninfo.txt [2020-04-15 14:11:21,583]
Requirements
Packages
Build requirements
    make/4.2.1 from '8f62b007-3733-4ed1-a191-e3b8b15a3ef4' - Cache
Build requirements packages
    make/4.2.1:456f15897172eef340fcbac8a70811f2beb26a93 - Download
[...]


make/4.2.1: Package installed 456f15897172eef340fcbac8a70811f2beb26a93
make/4.2.1: Downloaded package revision b4809fcb649c41b3d2ab43d60abb62e7
make/4.2.1: Creating CONAN_MAKE_PROGRAM environment variable: E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\.co\84880d\1\bin\gnumake.exe
7zip/19.00: Applying build-requirement: make/4.2.1
7zip/19.00: Configuring sources in E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\.co\b716f1\1
DEBUG :uploader_downloader.py[186]: DOWNLOAD: https://www.7-zip.org/a/7z1900-src.7z [2020-04-15 14:11:25,287]
ERROR: Traceback (most recent call last):
  File "conan\conans\errors.py", line 34, in conanfile_exception_formatter
  File "conan\conans\client\source.py", line 128, in _run_source
  File "E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\data\7zip\19.00\_\_\export\conanfile.py", line 29, in source
    self._uncompress_7z(filename)
  File "E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\data\7zip\19.00\_\_\export\conanfile.py", line 40, in _uncompress_7z
    self.run("7zr x {}".format(filename))
  File "conan\conans\model\conan_file.py", line 275, in run
conans.errors.ConanException: Error 1 while executing 7zr x 7z1900-src.7z





----Running------
> 7zr x 7z1900-src.7z
-----------------
'7zr' is not recognized as an internal or external command,

operable program or batch file.
```

I definitely don't have 7zr as can be seen by the error later, so `tools.which("7zr")` should have been false.

**Comment by uilianries** [comment]
Hi @michaelmaguire !

It's working for me, but I'm running Windows 10:

```
λ conan --version
Conan version 1.20.4
λ conan create . 19.00@
Exporting package recipe
Linter warnings
    WARN: Linter. Line 54: TODO: Enable non-Windows methods in configure
    WARN: Linter. Line 84: TODO: Package the libraries: binaries and headers (add the rest of settings)
7zip/19.00 exports: File 'conandata.yml' found. Exporting it...
7zip/19.00 exports: Copied 1 '.yml' file: conandata.yml
7zip/19.00: A new conanfile.py version was exported
7zip/19.00: Folder: C:\Users\uilia\AppData\Local\Temp\conan_home\.conan\data\7zip\19.00\_\_\export
7zip/19.00: Exported revision: c27d5e7921f7073e3021cbc591071a60
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

7zip/19.00: Forced build from source
7zip/19.00 (test package): Installing package
Requirements
    7zip/19.00 from local cache - Cache
Packages
    7zip/19.00:456f15897172eef340fcbac8a70811f2beb26a93 - Build
Build requirements
    lzma_sdk/9.20 from 'conan-center' - Cache
    make/4.2.1 from 'conan-center' - Cache
Build requirements packages
    lzma_sdk/9.20:456f15897172eef340fcbac8a70811f2beb26a93 - Cache
    make/4.2.1:456f15897172eef340fcbac8a70811f2beb26a93 - Cache

lzma_sdk/9.20: Already installed!
lzma_sdk/9.20: WARN: Lib folder doesn't exist, can't collect libraries: C:\Users\uilia\AppData\Local\Temp\conan_home\.conan\data\lzma_sdk\9.20\_\_\package\456f15897172eef340fcbac8a70811f2beb26a93\lib
lzma_sdk/9.20: Appending PATH environment variable: C:\Users\uilia\AppData\Local\Temp\conan_home\.conan\data\lzma_sdk\9.20\_\_\package\456f15897172eef340fcbac8a70811f2beb26a93\bin
make/4.2.1: Already installed!
make/4.2.1: Creating CONAN_MAKE_PROGRAM environment variable: C:\Users\uilia\AppData\Local\Temp\conan_home\.conan\data\make\4.2.1\_\_\package\456f15897172eef340fcbac8a70811f2beb26a93\bin\gnumake.exe
7zip/19.00: Applying build-requirement: lzma_sdk/9.20
7zip/19.00: Applying build-requirement: make/4.2.1
7zip/19.00: Configuring sources in C:\Users\uilia\AppData\Local\Temp\conan_home\.conan\data\7zip\19.00\_\_\source
Downloading 7z1900-src.7z: 100%|##########| 1.02M/1.02M [00:01<00:00, 879kB/s]


7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: 7z1900-src.7z
```

I think it can be related to Windows Server 2012 R2. Are you able to download that recipe and check the `which`?

```
def build_requirements(self):
    result = tools.which("7zr"):
    self.output.info("WHICH: %s" % result)
    if not result:
        self.build_requires("lzma_sdk/9.20")
```

BTW, `which` returns the 7zr path, or False. I can't return True due its implementation.

**Comment by michaelmaguire** [comment]
> Are you able to download that recipe and check the which?

@uilianries which recipe do you mean?  You mean just modify the recipe to add the self.output?

**Comment by michaelmaguire** [comment]
Tried your suggestion.  Looks like `7zr` is somehow how present enough on my system that tools.which() can find it, but not present enough that I can actually invoke it:

```
7zip/19.00: WHICH: D:\msys64\usr\bin\7zr
7zip/19.00 (test package): Installing package
Requirements
    7zip/19.00 from local cache - Cache
Packages
    7zip/19.00:456f15897172eef340fcbac8a70811f2beb26a93 - Build
Build requirements
    make/4.2.1 from '8959fec4-9eac-4829-aed3-56d1c7aca24a' - Cache
Build requirements packages
    make/4.2.1:456f15897172eef340fcbac8a70811f2beb26a93 - Download

make/4.2.1: Retrieving package 456f15897172eef340fcbac8a70811f2beb26a93 from remote '8959fec4-9eac-4829-aed3-56d1c7aca24a' 
Downloading conanmanifest.txt


Downloading conaninfo.txt


Downloading conan_package.tgz




make/4.2.1: Package installed 456f15897172eef340fcbac8a70811f2beb26a93
make/4.2.1: Downloaded package revision b4809fcb649c41b3d2ab43d60abb62e7
make/4.2.1: Creating CONAN_MAKE_PROGRAM environment variable: E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\.co\84880d\1\bin\gnumake.exe
7zip/19.00: Applying build-requirement: make/4.2.1
7zip/19.00: Configuring sources in E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\.co\b716f1\1
DEBUG :uploader_downloader.py[186]: DOWNLOAD: https://www.7-zip.org/a/7z1900-src.7z [2020-04-15 18:16:50,982]
ERROR: Traceback (most recent call last):
  File "conan\conans\errors.py", line 34, in conanfile_exception_formatter
  File "conan\conans\client\source.py", line 128, in _run_source
  File "E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\data\7zip\19.00\_\_\export\conanfile.py", line 29, in source
    self._uncompress_7z(filename)
  File "E:\nX\nX_nightlybuild\workspace\ALPHA_test_Conan_pipeline@2\uh\.conan\data\7zip\19.00\_\_\export\conanfile.py", line 47, in _uncompress_7z
    self.run("7zr x {}".format(filename))
  File "conan\conans\model\conan_file.py", line 275, in run
conans.errors.ConanException: Error 1 while executing 7zr x 7z1900-src.7z





----Running------
> 7zr x 7z1900-src.7z
-----------------
'7zr' is not recognized as an internal or external command,

operable program or batch file.
```

**Comment by uilianries** [comment]
@michaelmaguire This is no a Conan bug, but a recipe problem. The PR https://github.com/conan-io/conan-center-index/pull/1373 should fix this situation.

**Comment by michaelmaguire** [comment]
Thanks for that.  I had a question about that PR which I raised in that PR: https://github.com/conan-io/conan-center-index/pull/1373#issuecomment-614622592
