### ISSUE TITLE
error removing unicode named file

### ISSUE THREAD

**Issue by a-teammate** [conan-io/conan#687]
Im trying to remove (or rebuild, we) `Pugixml/1.7@AlbanSeurat/testing` on windows (10).

I get the following errors:

```
[==================================================]
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<string>", line 6, in run
  File "conan\conans\client\command.py", line 861, in main
  File "conan\conans\client\command.py", line 760, in run
  File "conan\conans\client\command.py", line 389, in install
  File "conan\conans\client\manager.py", line 273, in install
  File "conan\conans\client\manager.py", line 178, in _get_graph
  File "conan\conans\client\deps_builder.py", line 315, in load
  File "conan\conans\client\deps_builder.py", line 354, in _load_deps
  File "conan\conans\client\deps_builder.py", line 350, in _load_deps
  File "conan\conans\client\deps_builder.py", line 404, in _create_new_node
  File "conan\conans\client\proxy.py", line 139, in get_recipe
  File "conan\conans\client\proxy.py", line 185, in _retrieve_recipe
  File "conan\conans\client\proxy.py", line 170, in _retrieve_from_remote
  File "conan\conans\client\remote_manager.py", line 101, in get_recipe
  File "conan\conans\paths.py", line 67, in _rm_conandir
  File "conan\conans\util\files.py", line 122, in rmdir
  File "shutil.py", line 247, in rmtree
  File "shutil.py", line 247, in rmtree
  File "shutil.py", line 247, in rmtree
  File "shutil.py", line 252, in rmtree
  File "conan\conans\util\files.py", line 112, in _change_permissions
WindowsError: [Error 123] Die Syntax f³r den Dateinamen, Verzeichnisnamen oder die Datentrõgerbezeichnung ist falsch: 'C:\\Users\\madoe\\.conan\\data\\Pugixml\\1.7\\AlbanSeurat\\testing\\source\\pugixml\\tests\\data\\????.xml'
conan returned -1

C:\Users\madoe\Documents\GitHub\conan-InexorGlueGen>conan remove pugixml*
Are you sure you want to delete from 'pugixml/1.7@AlbanSeurat/testing' (yes/no): yes
ERROR: pugixml/1.7@AlbanSeurat/testing: Unable to remove src folder
        [Error 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\madoe\\.conan\\data\\pugixml\\1.7\\AlbanSeurat\\testing\\source\\pugixml\\tests\\data\\????.xml'
```
It's complaining about syntax errors, which are (highly probably) caused by a file called `тест.xml`.

**Comment by a-teammate** [comment]
Okay, this is obviously a duplicate from #653 and #191 sorry for that.
 I'll try with python3

**Comment by memsharded** [comment]
Hi!

Yes, the commit is only intended to avoid the crash of the error message. We tried to provide full unicode support for paths and filenames, but failed. It will be easier to implement when deprecating python 2.7, but for now, it has to be supported. Python 3 might fail too, as you noticed.

Sorry for that, by now the only way is just to avoid completely unicode in file/path names.
