### ISSUE TITLE
[feature] (scm_to_conandata) support parallel building of different build configurations

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#6956]
In my CI job want to build multiple configurations (different compilers) of the same commit in parallel.

I'm getting issues when conan [stores the scm revision in conandata.yml](https://github.com/conan-io/conan/blob/ddf9cca9ea45879986adec8b0308a0519226bbac/conans/client/cmd/export.py#L283).  It detects that the reserved `.conan` field is already filled by one of the parallel builds and raises an error:

```
ERROR: Field '.conan' inside 'conandata.yml' file is reserved to Conan usage.
script returned exit code 1
```

Is it possible to change this check to support my use case?
I don't see why this should be an issue if the revision information is the exact same across the parallel builds.

I also just want to mention that it is not feasible for me, storage-wise, to use a separate cache for each build configuration.

**Comment by jgsogo** [comment]
Hi, @GordonJess!

The Conan cache doesn't support concurrency/parallelism right now (commands with a `parallel` argument are an exception). Nevertheless, there are some operations that could work in parallel. Here you can avoid that collision by running `conan export <path> <ref>` once and then `conan install <ref> --build=ref` for your other jobs, it could work if all the dependencies are already installed (if not, run `conan install` first for each job and then `conan install --build` in parallel)... of course every job must compute a different package id.

This is a workaround, but it could work.

We are thinking about what can run in parallel and some changes to the cache that could make it possible, it is on the roadmap.

**Comment by DukeOfKirkcaldy** [comment]
Thanks for the tip @jgsogo!

Your workaround helped me avoid the specific `scm_to_conandata` error message, but there are still issues with the parallelism here...

In the same parallel streams, after building the packages for a specific configuration (i.e. compiler), I am integrating them into their associated consumer projects according to the recommended method:

```
dir ("${env.WORKSPACE}/${env.COMPILER}/build/integrations") {
  
  def config_built_pkgs = built_pkgs.groupBy{ it.compiler }[ env.COMPILER ] // packages built for the current configuration
  def integrations = ci_config.build_configurations.findAll { it.compiler == env.COMPILER }.collectMany { it.integrations }
  def build_policies = config_built_pkgs.collect { "--build=${it.id.split('#')[0]}" }.join(' ') + " --build=outdated --build=cascade"
  
  parallel integrations.collectEntries { integration_target ->
    
    [
      "integrate into ${integration_target}": {
        
        def integration_dir = integration_target.replaceAll("[@#:]", "/")
        def build_order = []
        
        dir(integration_dir) {

          // determine initial build order of which packages to rebuilt
          command("conan graph build-order . --json=${CONAN_JSON_OUT_BUILD_ORDER} ${build_policies}")
          
          build_order = readJSON(file: "${CONAN_JSON_OUT_BUILD_ORDER}").drop(1) // drop new pkgs (already built)

          while(build_order) {
            
            def updated_lockfiles = []

            // integrate changes into affected packages
            parallel build_order[0].collectEntries { affected_pkg ->
              
              def affected_pkg_ref = affected_pkg[1].split("#")[0] // drop rev info
              def affected_pkg_dir  = affected_pkg_ref.replaceAll("[@#:]", "/")
              
              [
                "build ${affected_pkg_ref}": {
                  
                 // copy main lockfile into build folder
                  writeFile(file: "${affected_pkg_dir}/conan.lock", text: readFile("conan.lock"))
                  
                  dir(affected_pkg_dir) {
                    
                    // rebuild the affected pkg
                    withCredentials ([usernamePassword(credentialsId: 'cred_name', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
                      command("conan install ${affected_pkg_ref} --build=${affected_pkg_ref} --lockfile=.")
                    }
                    
                    // find updated lockfile
                    def updated_lockfile = pwd() + "/conan.lock"
                    updated_lockfiles << updated_lockfile
                    
                    // store pkg info
                    built_pkgs << ["id": affected_pkg, "lockfile": updated_lockfile, "compiler": env.COMPILER]
                    
                  }
                  
                }
              ]
            
            }
            
            // update the main lockfile with rebuilt pkgs
            updated_lockfiles.each {
              command("conan graph update-lock . ${it}")
            }
            
            // recompute if any more packages need to be rebuilt
            command("conan graph build-order . --json=${CONAN_JSON_OUT_BUILD_ORDER} ${build_policies}")
            build_order = readJSON(file: "${CONAN_JSON_OUT_BUILD_ORDER}").drop(1) // drop new pkgs (already built)

          }
        }
        
    ...
    
}
```

Somehow this integration process is interfering with packages still building in parallel streams.  More specifically, conan can't find `conanmanifest.txt`.  I can see that file is in fact there in the workspace, at least once all processes end.

```
[conan install <ref> --build=<ref> --lockfile=.]
ERROR: [Errno 2] No such file or directory: 'C:\\Jenkins\\workspace\\job\\CI-PkgA\\conan_cache\\.conan\\data\\PkgA\\2.0.0\\user\\channel\\export\\conanmanifest.txt'

script returned exit code 1
```

Any more suggestions for a workaround?

Looking forward to more support for parallel in the future!

**Comment by DukeOfKirkcaldy** [comment]
Also related.
(the package path below is one of a build_requirement)

```
name/version@user/channel is locked by another concurrent conan process, wait...

If not the case, quit, and do 'conan remove --locks'

Traceback (most recent call last):

  File "c:\python37\lib\shutil.py", line 402, in _rmtree_unsafe

    os.rmdir(path)

OSError: [WinError 145] The directory is not empty: 'C:\\Jenkins\\workspace\\job\\PkgA\\conan_cache\\.conan\\data\\name\\version\\user\\channel\\package\\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "c:\python37\lib\site-packages\conans\client\command.py", line 2002, in run

    method(args[0][1:])

  File "c:\python37\lib\site-packages\conans\client\command.py", line 1848, in graph

    build=args.build)

  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 89, in wrapper

    return f(api, *args, **kwargs)

  File "c:\python37\lib\site-packages\conans\client\conan_api.py", line 1253, in create_lock

    False, remotes, recorder)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_manager.py", line 114, in load_graph

    recorder, apply_build_requires=apply_build_requires)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_manager.py", line 240, in _resolve_graph

    graph_lock=graph_lock)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_manager.py", line 349, in _load_graph

    apply_build_requires=apply_build_requires)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_manager.py", line 323, in _recurse_build_requires

    nodes_subset=nodessub, root=node)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_manager.py", line 281, in _recurse_build_requires

    self._binary_analyzer.evaluate_graph(graph, build_mode, update, remotes, nodes_subset, root)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_binaries.py", line 334, in evaluate_graph

    self._evaluate_node(node, build_mode, update, remotes)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_binaries.py", line 167, in _evaluate_node

    self._process_node(node, pref, build_mode, update, remotes)

  File "c:\python37\lib\site-packages\conans\client\graph\graph_binaries.py", line 208, in _process_node

    package_folder = package_layout.package(pref)

  File "c:\python37\lib\site-packages\conans\paths\package_layouts\package_cache_layout.py", line 31, in wrap

    return path_shortener(p, self._short_paths)

  File "c:\python37\lib\site-packages\conans\util\windows.py", line 60, in path_shortener

    rmdir(path)

  File "c:\python37\lib\site-packages\conans\util\files.py", line 248, in rmdir

    shutil.rmtree(path, onerror=_change_permissions)

  File "c:\python37\lib\shutil.py", line 516, in rmtree

    return _rmtree_unsafe(path, onerror)

  File "c:\python37\lib\shutil.py", line 404, in _rmtree_unsafe

    onerror(os.rmdir, path, sys.exc_info())

  File "c:\python37\lib\site-packages\conans\util\files.py", line 243, in _change_permissions

    raise OSError("Cannot change permissions for {}! Exception info: {}".format(path, exc_info))

OSError: Cannot change permissions for C:\Jenkins\workspace\job\PkgA\conan_cache\.conan\data\name\version\user\channel\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9! Exception info: (<class 'OSError'>, OSError(41, 'The directory is not empty'), <traceback object at 0x0000019D438D8BC8>)
```

**Comment by jgsogo** [comment]
About the first issue with the `conanmanifest.txt` maybe it is just two processes trying to access it at the same time and one of them blocking it... Reading should be non-blocking and I see no reason why Conan could be writing to that file if the recipe is already exported. 

The error in your second comment. I see the traces but I wonder how it gets from the `remove --locks'  message (it should wait there) to the `os.rmdir(path)`. Then it looks like it tries to remove the package folder but it cannot probably because another process is using something inside that folder.

These are errors really hard to tackle if the application is not ready to be used in a concurrent environment. The next workarounds I can suggest to you are related to remove pieces of your parallelism until it works (with the risk that it can fail in any future run). 😞

**Comment by memsharded** [comment]
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.
