### ISSUE TITLE
[question] Can not use conan inside a docker container with Jenkins

### ISSUE THREAD

**Issue by binhpht** [conan-io/conan#6975]
Hi, I am using Jenkins to build the project with conan docker container,
I define a stage like this 
```
stage('Build Conan ') {
		       agent { label 'jenkins' docker 'conanio/gcc7' }
                    steps {
                        script {
                             sh script:'''
                                        #!/bin/bash
                                        echo "This is start $(pwd)"
                                        conan
                                        sudo pip install conan --upgradex
                        }
                    }
		}
```
However, it has error like this
```
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.5/bin/conan", line 11, in <module>
    load_entry_point('conan==1.24.1', 'console_scripts', 'conan')()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/command.py", line 2134, in main
    conan_api, _, _ = Conan.factory()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 218, in factory
    return cls(), None, None
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 230, in __init__
    migrator = ClientMigrator(self.cache_folder, Version(client_version), self.out)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/migrations.py", line 26, in __init__
    self.cache = ClientCache(cache_folder, out)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cache/cache.py", line 73, in __init__
    self._store_folder = self.config.storage_path or self.cache_folder
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cache/cache.py", line 145, in config
    save(self.conan_conf_path, normalize(get_default_client_conf()))
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/util/files.py", line 190, in save
    with open(path, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/.conan/conan.conf'
```

Do you have any idea why this happens, thanks 
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! 

Conan uses a cache in the local machine to store some configuration files and data about the packages. If you don't configure Conan to use a different folder (using the environment variable `CONAN_USER_HOME`) it will try to use a directory `.conan` inside the _user local folder_ (whatever it is the expansion of `~` folder). Depending on the _user local folder_ for the user running Conan, it will resolve to a different directory and, depending on your filesystem and permissions that directory might exists or not and be usable or not.

Hope this answer your question. Thanks!

**Comment by binhpht** [comment]
Hi, the problem is that it works well on docker container in my machine but has error in Jenkins ( Jenkins also was deployed via docker). The issue was solved by providing -root account for docker container. 
Like 
`docker run -u root -v /home/jenkins/CI/:/home/conan/project --rm conanio/gcc7-armv7hf bash 
`
Thanks.
