### ISSUE TITLE
[bug] Failed to run in parallel `conan info` + `conan export-pkg`.

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#6977]
```py
# conanfile.py

from conans import ConanFile
from os.path import join
from time import sleep


class TestA(ConanFile):
    name = "TestA"
    version = "1.0.0"
    description = "TestA"
    settings = "os", "compiler", "build_type", "arch"

    def config_options(self):
        self.output.info("--- TestA: 01. config_options ---")
        super().config_options()

    def configure(self):
        self.output.info("--- TestA: 02. configure ---")
        super().configure()

    def requirements(self):
        self.output.info("--- TestA: 03. requirements ---")

    def package_id(self):
        self.output.info("--- TestA: 04. package_id ---")
        super().package_id()

    def build_requirements(self):
        self.output.info("--- TestA: 05. build_requirements ---")

    def build_id(self):
        self.output.info("--- TestA: 06. build_id ---")

    def system_requirements(self):
        self.output.info("--- TestA: 07. system_requirements ---")
        super().system_requirements()

    def source(self):
        self.output.info("--- TestA: 08. source ---")
        super().source()

    def imports(self):
        self.output.info("--- TestA: 09. imports ---")

    def build(self):
        self.output.info("--- TestA: 10. build ---")
        super().build()

    def package(self):
        self.output.info("--- TestA: 11. package ---")
        super().package()
        self.copy("*.a", src=".", dst="lib")
        with open(join(self.package_folder, "config.txt"), "wt") as fh:
            self.output.info("--- sleep(10)")
            sleep(10)
            fh.write("testA\n")

    def package_info(self):
        self.output.info("--- TestA: 12. package_info ---")
        super().package_info()
        self.cpp_info.libs = ["lib1", "lib2", "lib3"]
```

```bat
rem test.cmd

set CONAN_LOGGING_LEVEL=10
set CONAN_USER_HOME=%~dp0

cls

conan remove "test*" -f
conan remote add test https://google.com -f

start "info" cmd /k conan info TestA/1.0.0@test/develop

echo/
pushd testA
start "export-pkg" cmd /k conan export-pkg . test/develop
popd
```
 The output:  `conan info`
```
DEBUG :conan_api.py   [171]: INIT: Using config 'C:\Dev\Projects\conan-test\conan_export+info\.conan\conan.conf' [2020-05-08 01:18:43,835]
DEBUG :tracer.py      [156]: CONAN_API: info(remote_name=None,settings=None,options=None,env=None,profile_names=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None),update=False,install_folder=None,build=None,lockfile=None) [2020-05-08 01:18:43,836]
DEBUG :profile_loader.py[113]: PROFILE LOAD: C:\Dev\Projects\conan-test\conan_export+info\.conan\profiles\default [2020-05-08 01:18:43,837]
INFO  :settings_preprocessor.py[57]: Setting 'compiler.runtime' not declared, automatically adjusted to 'MD' [2020-05-08 01:18:43,858]
TestA/1.0.0@test/develop: Not found in local cache, looking in remotes...
TestA/1.0.0@test/develop: Trying with 'conan-center'...
DEBUG :rest_client_common.py[156]: REST: ping: https://conan.bintray.com/v1/ping [2020-05-08 01:18:43,864]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions'] [2020-05-08 01:18:44,584]
DEBUG :rest_client_common.py[183]: REST: get: https://conan.bintray.com/v1/conans/TestA/1.0.0/test/develop/download_urls [2020-05-08 01:18:44,585]
DEBUG :rest_client_common.py[29]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-05-08 01:18:44,779]
TestA/1.0.0@test/develop: Trying with 'test'...
DEBUG :rest_client_common.py[156]: REST: ping: https://google.com/v1/ping [2020-05-08 01:18:44,781]
DEBUG :rest_client_common.py[29]: REST ERROR: <class 'conans.errors.NotFoundException'> [2020-05-08 01:18:44,903]
ERROR: Unable to find 'TestA/1.0.0@test/develop' in remotes
```
The output: `conan export-pkg`
```
DEBUG :conan_api.py   [171]: INIT: Using config 'C:\Dev\Projects\conan-test\conan_export+info\.conan\conan.conf' [2020-05-08 01:18:43,834]
DEBUG :tracer.py      [156]: CONAN_API: export_pkg(conanfile_path=.,name=None,version=None,source_folder=None,build_folder=None,package_folder=None,install_folder=None,profile_names=None,env=None,settings=None,options=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None),force=False,user=test,channel=develop,lockfile=None,ignore_dirty=False) [2020-05-08 01:18:43,836]
DEBUG :profile_loader.py[113]: PROFILE LOAD: C:\Dev\Projects\conan-test\conan_export+info\.conan\profiles\default [2020-05-08 01:18:43,838]
INFO  :settings_preprocessor.py[57]: Setting 'compiler.runtime' not declared, automatically adjusted to 'MD' [2020-05-08 01:18:43,859]
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
DEBUG :export.py      [110]: EXPORT: C:\Dev\Projects\conan-test\conan_export+info\testA\conanfile.py [2020-05-08 01:18:43,864]
Exporting package recipe
TestA/1.0.0@test/develop: TestA/1.0.0@test/develop is locked by another concurrent conan process, wait...
TestA/1.0.0@test/develop: If not the case, quit, and do 'conan remove --locks'
Traceback (most recent call last):
  File "c:\dev\tools\python3\lib\site-packages\conans\client\command.py", line 2002, in run
    method(args[0][1:])
  File "c:\dev\tools\python3\lib\site-packages\conans\client\command.py", line 954, in export_pkg
    info = self._conan.export_pkg(conanfile_path=args.path,
  File "c:\dev\tools\python3\lib\site-packages\conans\client\conan_api.py", line 89, in wrapper
    return f(api, *args, **kwargs)
  File "c:\dev\tools\python3\lib\site-packages\conans\client\conan_api.py", line 419, in export_pkg
    new_ref = cmd_export(self.app, conanfile_path, name, version, user, channel, True,
  File "c:\dev\tools\python3\lib\site-packages\conans\client\cmd\export.py", line 130, in cmd_export
    shutil.copy2(conanfile_path, package_layout.conanfile())
  File "c:\dev\tools\python3\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\dev\tools\python3\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Dev\\Projects\\conan-test\\conan_export+info\\.conan\\data\\TestA\\1.0.0\\test\\develop\\export\\conanfile.py'

ERROR: [Errno 2] No such file or directory: 'C:\\Dev\\Projects\\conan-test\\conan_export+info\\.conan\\data\\TestA\\1.0.0\\test\\develop\\export\\conanfile.py'
```

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

This case might be similar to the other issue, it is not a bug, it is an expected race condition because the Conan cache is not concurrent in the general case. ``conan info`` reconstructs the whole dependency graph, down to the binary level. You cannot be concurrently modifying the graph with ``conan export-pkg`` while you are computing that dependency graph.

**Comment by AbrilRBS** [comment]
Closing as solved as we didnt hear back from you and the answer addresses the point correctly :)

**Comment by AbrilRBS** [comment]
Check https://github.com/conan-io/conan/issues/15840 for updates on our work on cache concurrency
