### ISSUE TITLE
[bug] Error while downloading/extracting files with download_cache enabled

### ISSUE THREAD

**Issue by vklindukh** [conan-io/conan#7043]
conan randomly fails when download dependency (conan packages) if properties storage.download_cache enabled and general.parallel_download set to > 1

### Environment Details (include every applicable attribute)
  * Ubuntu 18.04 inside docker container
  * GCC 7.4
  * Conan version 1.24.0
  * Python 3.7.7

### Steps to reproduce (Include if Applicable)
1. multiply docker containers (ubuntu 18.04) running with same volume  ```/conan/download_cache/data``` mounted into each container
2. inside docker container: conan configured to use download_cache and parallel download enabled
```conan config set storage.download_cache="/conan/download_cache/data"```
```conan config set general.parallel_download=8```
3. inside docker container: run ```conan create ..``` , which starts downloading dependencies (10-20 conan packages) from Artifactory
4. periodically (1 out of 10 attempts) conan fails while downloading dependency, see logs below. After re-run ```conan create ..``` most luckily dependency successfully downloaded.
5. this error never happens if storage.download_cache not enabled!

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
<CONAN PACKAGE NAME>: ERROR: Exception while getting package: <CONAN PACKAGE ID>
<CONAN PACKAGE NAME>: ERROR: Exception: <class 'conans.errors.ConanException'> Error while downloading/extracting files to <LOCAL PATH TO CONAN PACKAGE> 
Compressed file ended before the end-of-stream marker was reached
Folder removed

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/conans/client/remote_manager.py", line 292, in uncompress_file
    tar_extract(file_handler, dest_folder)
  File "/usr/local/lib/python3.7/dist-packages/conans/util/files.py", line 358, in tar_extract
    the_tar.extractall(path=destination_dir, members=safemembers(the_tar))
  File "/usr/lib/python3.7/tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.7/tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.7/tarfile.py", line 2161, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.7/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/usr/lib/python3.7/gzip.py", line 287, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 493, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by memsharded** [comment]
The cache synchronization mechanism is an InterProcessLock (from fasteners library), which is implemented via file locks. Being it a mechanism for inter-process, I am not sure it will work as a distributed synchronization, and multiple docker images sharing a cache might be the case. 

Are all the docker images using the same users, permissions, configuration, etc over the shared folder? Is the problem still happening with 1 docker only? 

I would start investigating the fasteners behavior in a shared folder with docker images.

**Comment by vklindukh** [comment]
> The cache synchronization mechanism is an InterProcessLock (from fasteners library), which is implemented via file locks. Being it a mechanism for inter-process, I am not sure it will work as a distributed synchronization, and multiple docker images sharing a cache might be the case.
> 
> Are all the docker images using the same users, permissions, configuration, etc over the shared folder? Is the problem still happening with 1 docker only?
> 
> I would start investigating the fasteners behavior in a shared folder with docker images.

Most likely at that particular moment only 1 docker container has been running. However the environment is dynamic (K8S cluster) and it's hard to catch, which process are running on particular K8s node when error occurred.

docker containers running with same user, same mount path to conan download cache, same conan version. The possible differences between containers are
- build_type (Debug/Release)
- gcc compiler (gcc54/gcc74)

**Comment by memsharded** [comment]
We need to investigate this further. In the meantime, I'd suggest the following:

- disable the download_cache
- Use a local ArtifactoryCE to share among those images, in the same server. The downloads will be really fast, and the slowest part, which is the unzipping, still happens when using the download_cache. Please let me know if this helps.

**Comment by memsharded** [comment]
> Use a local ArtifactoryCE to share among those images, in the same server. The downloads will be really fast, and the slowest part, which is the unzipping, still happens when using the download_cache. Please let me know if this helps.

To make sure: It is possible to setup ArtifactoryCE that is running locally to act as a cache of other remote Artifactory, with the Artifatory ``remote`` (and also ``virtual`` for aggregations) repositories.

**Comment by vklindukh** [comment]
With download_cache disabled it works perfect and never throws error.
We are using locally installed Artifactory server with Commercial license. Download+unpacking takes up to 5 minutes, we have lot of conan dependencies and some of that conan packages are really heavy (1-2G)

**Comment by AbrilRBS** [comment]
Closing, this is a Conan 1 issue and no further support for it is expected, and in Conan 2 the download cache was made more robust so that these errors should not pop up
