### ISSUE TITLE
[bug] Conan config install list breaks if config file is missing

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#7271]
The PR https://github.com/conan-io/conan/pull/7263 inserts a new feature, which breaks when conan cache is clear.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: Any
  * Conan version: 1.27.0-dev
  * Python version: 3.8.1

### Steps to reproduce (Include if Applicable)

1) Set a new (empty) conan cache folder
2) Run `conan config install --list`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
export CONAN_USER_HOME=/tmp/conan
conan config install --list
Traceback (most recent call last):
  File "/home/uilian/Development/conan/conan/venv/lib/python3.8/site-packages/conans/client/command.py", line 2051, in run
    method(args[0][1:])
  File "/home/uilian/Development/conan/conan/venv/lib/python3.8/site-packages/conans/client/command.py", line 608, in config
    configs = self._conan.config_install_list()
  File "/home/uilian/Development/conan/conan/venv/lib/python3.8/site-packages/conans/client/conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "/home/uilian/Development/conan/conan/venv/lib/python3.8/site-packages/conans/client/conan_api.py", line 607, in config_install_list
    return json.loads(load(self.app.cache.config_install_file))
  File "/home/uilian/Development/conan/conan/venv/lib/python3.8/site-packages/conans/util/files.py", line 218, in load
    with open(path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/conan/.conan/config_install.json'

ERROR: [Errno 2] No such file or directory: '/tmp/conan/.conan/config_install.json'
```

**Comment by memsharded** [comment]
Please @uilianries submit a fix if possible. Thanks!
