### ISSUE TITLE
TypeError: 'ConfigureEnvironment' object is not iterable

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#741]
after upgrade to 0.16, the following error happens on Windows:

```
Traceback (most recent call last):
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\Scripts\conan-script.py", line 11, in <module>
    load_entry_point('conan==0.16.0', 'console_scripts', 'conan')()
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\conan.py", line 6, in run
    main(sys.argv[1:])
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\command.py", line 930, in main
    error = command.run(args)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\command.py", line 832, in run
    method(args[0][1:])
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\command.py", line 440, in install
    no_imports=args.no_imports)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\manager.py", line 295, in install
    installer.install(deps_graph, build_mode)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\installer.py", line 60, in install
    self._build(nodes_by_level, skip_private_nodes, build_mode)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\installer.py", line 145, in _build
    self._build_node(conan_ref, conan_file, build_mode)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\client\installer.py", line 212, in _build_node
    with environment_append(conan_file.env):
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\conans\tools.py", line 31, in environment_append
    os.environ.update(env_vars)
  File "C:\Users\SSE4\AppData\Local\Programs\Python\Python35-32\lib\_collections_abc.py", line 778, in update
    for key, value in other:
TypeError: 'ConfigureEnvironment' object is not iterable
```

I've taken a quick look at ConfigureEnvironment class, and I don't see how is it could be iterable, and how the following code is expected to work:

```
@contextmanager
def environment_append(env_vars):
    old_env = dict(os.environ)
    os.environ.update(env_vars)
    yield
    os.environ.clear()
    os.environ.update(old_env)
```

does ConfigureEnvironment object miss some fields to make it iterable?
or may be environment_append method should be changed somehow?

**Comment by SSE4** [comment]
oops, it was an error in my conanfile.py - I accidentally assigned self.env. sorry for the false alaram.

**Comment by memsharded** [comment]
Never mind! Much better a reported false positive that a not reported true positive. Thanks!
