### ISSUE TITLE
[question] Unable to download boost 1.74.0-rc2 using conan

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7541]
[Soon, boost 1.74.0 will be released](https://lists.boost.org/boost-users/2020/08/90569.php)
I wanted to test the boost CCI recipe by adding 1.74.0-rc2.
So I added the following data to `conandata.yml` (no `-rc2` suffex because the extracted directory also does not have this suffix):
```yml
sources:
  1.74.0:
    url: "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0_rc2.tar.bz2"
    sha256: "83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1."
```

When running `conan create . boost/1.74.0@`, the following error happens:
```
ERROR: Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/source.py", line 143, in _run_source
    conanfile.source()
  File "/home/maarten/.conan/data/boost/1.74.0-rc2/_/_/export/conanfile.py", line 226, in source
    tools.get(**self.conan_data["sources"][self.version],)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/tools.py", line 82, in get
    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/tools/net.py", line 25, in get
    md5=md5, sha1=sha1, sha256=sha256)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/tools/net.py", line 114, in download
    _download_file(url)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/tools/net.py", line 101, in _download_file
    sha1=sha1, sha256=sha256)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/rest/download_cache.py", line 51, in download
    self._check_checksum(cached_path, md5, sha1, sha256)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/rest/download_cache.py", line 29, in _check_checksum
    check_sha256(cache_path, sha256)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/tools/files.py", line 171, in check_sha256
    check_with_algorithm_sum("sha256", file_path, signature)
  File "/home/maarten/.local/lib/python3.7/site-packages/conans/client/tools/files.py", line 159, in check_with_algorithm_sum
    real_signature))
conans.errors.ConanException: sha256 signature failed for '35338b277032d18240e092c38e34685de55c0da91336596587b34fd2fc100dfe' file. 
 Provided signature: 83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1.  
 Computed signature: 83bfc1507731a0906e387fc28b7ef5417d591429e51e788417fe9ff025e116b1
```

Adding `verify=False` to the call of `tools.get` does not change the behavior.

Downloading and extracting the archive manually using `wget` + `tar` works.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

conan 1.28.1, python 3.7.7, Fedora Linux 30

**Comment by lasote** [comment]
I think the issue is the dot at the end of the hash:

```
sha256: "XXXXXXXXX25e116b1." <=
```

**Comment by madebr** [comment]
Thanks for being my compiler @lasote  :hear_no_evil:
