### ISSUE TITLE
Conan crashes when conflictiong versions are present in a conanfile

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#757]
Hi,

when I put two versions of the same dependency in my conanfile.txt, conan crashes with python exceptions.
I know that this is not a valid use case, but conan should handle this more gracefully 

Reproduce (conan 0.16.1, Windows):
use the following conanfile.txt and call `conan install`:
```
[requires]
foo/0.1@user/testing
foo/0.2@user/testing
```
output:
```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<string>", line 6, in run
  File "conan\conans\client\command.py", line 931, in main
  File "conan\conans\client\command.py", line 833, in run
  File "conan\conans\client\command.py", line 441, in install
  File "conan\conans\client\manager.py", line 276, in install
  File "conan\conans\client\manager.py", line 176, in _get_graph
  File "conan\conans\client\loader.py", line 181, in load_conan_txt
  File "conan\conans\client\loader.py", line 193, in parse_conan_txt
  File "conan\conans\model\requires.py", line 121, in add
AttributeError: 'NoneType' object has no attribute 'werror'
conan returned -1

```
Expected output:
```
ERROR: dependencies foo/0.1@user/testing and foo/0.2@user/testing conflict
```

**Comment by memsharded** [comment]
Thanks for reporting, I have just submitted a fix: https://github.com/conan-io/conan/pull/758

I have changed the default behavior of only warning, now it will always be an Exception, to be sure the error is caught and properly addressed.

Added to 0.17, so it is released tomorrow.
