### ISSUE TITLE
[question] Why is my conan remote clean command failing?

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#7836]
I am running: 'conan remote clean' but I receive the following error messages:

```
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 2103, in run
  File "conan\conans\client\command.py", line 1610, in remote
  File "conan\conans\client\conan_api.py", line 94, in wrapper
  File "conan\conans\client\conan_api.py", line 1062, in remote_clean
  File "conan\conans\client\cache\remote_registry.py", line 355, in clear
  File "contextlib.py", line 81, in __enter__
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 186, in update_metadata
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 172, in load_metadata
  File "conan\conans\model\package_metadata.py", line 95, in loads
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Expecting value: line 1 column 1 (char 0)
```

I have conan configured and running on several identical machines with the same configuration and it is working on them but despite many comparisons and reinstalls, I can't get it to work on this one.

Running on Windos 10 x64 with conan 1.26 (Have also tried 1.29 with same result).  Python 3.9.  Other conan commands run.

Thanks in advance for your assistance.

**Comment by memsharded** [comment]
Have you tried removing the cache, just in case the remotes file definition has been corrupted? (you can check the file in the ``<userhome>/.conan/remotes.json``)

**Comment by gprosch** [comment]
Yes, I get the same result 

```
# conan remote clean
**WARN: Remotes registry file missing, creating default one in C:\Users\IDBOTFSBuild.BFR\.conan\remotes.json**
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 2035, in run
  File "conan\conans\client\command.py", line 1581, in remote
  File "conan\conans\client\conan_api.py", line 92, in wrapper
  File "conan\conans\client\conan_api.py", line 1010, in remote_clean
  File "conan\conans\client\cache\remote_registry.py", line 355, in clear
  File "contextlib.py", line 81, in __enter__
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 186, in update_metadata
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 172, in load_metadata
  File "conan\conans\model\package_metadata.py", line 95, in loads
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Expecting value: line 1 column 1 (char 0)
```
The JSON validates and I can even copy this file to my other machine and it works fine.

**Comment by memsharded** [comment]
This is very weird. Could you please try the following?:

- Completely remove the Conan cache in ``<userhome>/.conan`` and try again?
- Capture the dependencies (``pip list``) in the failing machine and compare with the same in some of the working machines?

**Comment by gprosch** [comment]
Removing the .conan folder has resolved this issue!  Thank you for the assistance.

Greg

**Comment by gprosch** [comment]
Resolved as noted above.

**Comment by memsharded** [comment]
Thanks for following up and closing.

It is possible that one **package_metada.json** file was corrupted at some point, a crashed program, an interrupted download... In general the cache can be treated as a cache, and then could be removed/cleaned/deleted without issues. Everything that is custom configuration that is stored in the cache should live in a git repo that you can ``conan config install <url>`` quickly to install your desired configuration of remotes, settings, etc.

**Comment by gprosch** [comment]
I really don’t think so.  I ran it through the json validator and it came up clean.  I copied remotes.json from a working machine and it failed with the same error.  I even deleted it and allowed conan to recreate it as you suggested and it errored.  Nothing worked until I removed the whole .conan folder.

**Comment by memsharded** [comment]
yes, sorry, my mistake, I meant one package_metada.json  file. There is one per package in the cache.

**Comment by gprosch** [comment]
Yes, it is entirely possible that one or more of those metadata files could have been corrupted by an process interruption/failure.  I did save the folder and its contents under a different name if it would be helpful to look at them.
