### ISSUE TITLE
[question] Help needed with errors during conan remote clean

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#7837]
I am running: 'conan remote clean' but I receive the following error messages:

```
Traceback (most recent call last):
  File "conan\conans\client\command.py", line 2103, in run
  File "conan\conans\client\command.py", line 1610, in remote
  File "conan\conans\client\conan_api.py", line 94, in wrapper
  File "conan\conans\client\conan_api.py", line 1062, in remote_clean
  File "conan\conans\client\cache\remote_registry.py", line 355, in clear
  File "contextlib.py", line 81, in __enter__
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 186, in update_metadata
  File "conan\conans\paths\package_layouts\package_cache_layout.py", line 172, in load_metadata
  File "conan\conans\model\package_metadata.py", line 95, in loads
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR: Expecting value: line 1 column 1 (char 0)
```

I have conan configured and running on several identical machines with the same configuration and it is working on them but despite many comparisons and reinstalls, I can't get it to work on this one.

Running on Windos 10 x64 with conan 1.26 (Have also tried 1.29 with same result).  Python 3.9.  Other conan commands run.

Thanks in advance for your assistance.

**Comment by memsharded** [comment]
Duplicate to https://github.com/conan-io/conan/issues/7836
