### ISSUE TITLE
Conan crashes with there is a duplicate private package

### ISSUE THREAD

**Issue by bjoernpollex** [conan-io/conan#79]
I've run into a scenario where I have two packages where A depends on B, and both have C as a private dependency (C is a unit-testing framework). In this case, when running `conan install` on A, it crashes with the following stack-trace:

```
HEADER ONLY
Requirements
    Boost/1.60.0@lasote/stable
    catch/1.3.0@bjoern/testing
    catch/1.3.0@bjoern/testing
    filesystem/1.0.0@bjoern/testing
    io/1.0.0@bjoern/testing
    zlib/1.2.8@lasote/stable
Traceback (most recent call last):
  File "/Users/bjoern/.pipsi/bin/conan", line 11, in <module>
    sys.exit(run())
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/conan.py", line 6, in run
    main(sys.argv[1:])
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/command.py", line 432, in main
    error = command.run(args)
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/command.py", line 367, in run
    method(args[0][1:])
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/command.py", line 186, in install
    build_mode=args.build)
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/manager.py", line 122, in install
    installer.install(deps_graph, build_mode)
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/installer.py", line 70, in install
    skip_private_nodes = self._compute_private_nodes(deps_graph, build_mode)
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/client/installer.py", line 110, in _compute_private_nodes
    package_folder = self._paths.package(package_reference)
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/paths.py", line 92, in package
    return normpath(join(self.conan(package_reference.conan), PACKAGES_FOLDER,
  File "/Users/bjoern/.pipsi/virtualenvs/conan/lib/python2.7/site-packages/conans/paths.py", line 45, in conan
    assert isinstance(conan_reference, ConanFileReference)
AssertionError
```
Now if I remove the `"private"` for package C from A, everything runs fine. Is this intended behaviour, or a bug?
Btw, I've tried using this as a way to specify dependencies that are used only for development (e.g. for running the unit-tests), but should not be propagated to users of the project. Is this the recommended way to achieve this, or would suggest something else? I could for instance also use an option like `--with-tests`.

**Comment by memsharded** [comment]
It seems it is a bug, not intended behaviour, I will check it asap.

Conditional dependencies can be defined, and you could use options to enable/disable them. Check: http://docs.conan.io/en/latest/reference/conanfile.html#requirements

However, this is possibly not very idiomatic, and scopes (dev, production), or a higher level could be defined, lets open a specific issue for it

**Comment by memsharded** [comment]
Bug confirmed, already submitted fix in PR: https://github.com/conan-io/conan/pull/84 to release/0.6 branch, so it should be ready for next release (next monday).

**Comment by bjoernpollex** [comment]
Awesome, thanks for the speedy fix!
