### ISSUE TITLE
[question] Using CONAN_USER_HOME from scratch

### ISSUE THREAD

**Issue by ngrodzitski** [conan-io/conan#7948]
I use docker. And keep a volume for CONAN_USER_HOME (mounted to `/_conan_home` when running). On new machine machine it is empty. If I try to use `conan install` I got the following error:

```
Traceback (most recent call last):
  File "/usr/bin/conan", line 11, in <module>
    load_entry_point('conan==1.30.2', 'console_scripts', 'conan')()
  File "/usr/lib/python3.8/site-packages/conans/conan.py", line 11, in run
    main(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/conans/client/command.py", line 2248, in main
    conan_api, _, _ = Conan.factory()
  File "/usr/lib/python3.8/site-packages/conans/client/conan_api.py", line 228, in factory
    return cls(), None, None
  File "/usr/lib/python3.8/site-packages/conans/client/conan_api.py", line 240, in __init__
    migrator = ClientMigrator(self.cache_folder, Version(client_version), self.out)
  File "/usr/lib/python3.8/site-packages/conans/client/migrations.py", line 27, in __init__
    self.cache = ClientCache(cache_folder, out)
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 79, in __init__
    self._store_folder = self.config.storage_path or self.cache_folder
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 151, in config
    self.initialize_config()
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 256, in initialize_config
    save(self.conan_conf_path, normalize(get_default_client_conf()))
  File "/usr/lib/python3.8/site-packages/conans/util/files.py", line 200, in save
    with open(path, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/_conan_home/.conan/conan.conf'
```

I tried to do `conan config init`
```
$ conan config init
Traceback (most recent call last):
  File "/usr/bin/conan", line 11, in <module>
    load_entry_point('conan==1.30.2', 'console_scripts', 'conan')()
  File "/usr/lib/python3.8/site-packages/conans/conan.py", line 11, in run
    main(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/conans/client/command.py", line 2248, in main
    conan_api, _, _ = Conan.factory()
  File "/usr/lib/python3.8/site-packages/conans/client/conan_api.py", line 228, in factory
    return cls(), None, None
  File "/usr/lib/python3.8/site-packages/conans/client/conan_api.py", line 240, in __init__
    migrator = ClientMigrator(self.cache_folder, Version(client_version), self.out)
  File "/usr/lib/python3.8/site-packages/conans/client/migrations.py", line 27, in __init__
    self.cache = ClientCache(cache_folder, out)
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 79, in __init__
    self._store_folder = self.config.storage_path or self.cache_folder
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 151, in config
    self.initialize_config()
  File "/usr/lib/python3.8/site-packages/conans/client/cache/cache.py", line 256, in initialize_config
    save(self.conan_conf_path, normalize(get_default_client_conf()))
  File "/usr/lib/python3.8/site-packages/conans/util/files.py", line 200, in save
    with open(path, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/_conan_home/.conan/conan.conf'
```

On my local machine it work (the same version).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by ngrodzitski** [comment]
So the question is what is a correct way to use CONAN_USER_HOME on fresh machine?

**Comment by ngrodzitski** [comment]
Dockerfile:
```
FROM alpine:3.12

RUN apk add --no-cache g++ \
    libxcb-dev \
    libxrender-dev \
    mesa-dev \
    xcb-util-renderutil-dev \
    xcb-util-dev \
    fontconfig-dev \
    freetype-dev \
    libxi-dev \
    libxext-dev \
    libx11-dev \
    libsm-dev \
    libice-dev \
    gperf \
    bison \
    python2 \
    python3 \
    py3-pip \
    ncurses \
    file \
    linux-headers \
    perl \
    flex \
    linux-headers \
    gdb \
    musl-dev \
    cmake \
    extra-cmake-modules \
    make \
    vim \
    xz \
    zip \
    unzip \
    ncurses \
    util-linux \
    libc6-compat \
    ninja \
    aria2 \
    openssl-dev \
    openssl-libs-static \
    binutils-gold \
    git

RUN pip3 install conan conan-package-tools Cheetah3 
```

**Comment by memsharded** [comment]
Hi @ngrodzitski 

I am having a look at this issue, and the CONAN_USER_HOME var should work fine. I am validating here with some tests, so far seems good.
The ``save()`` call that is failing actually contains a ``os.makedirs()`` call to create the necessary intermediate directories. If that is failing to create the directory, it might be due to some permissions issue.

Could you please try defining the CONAN_USER_HOME variable first in your native environment and trying natively, not in docker? Just to make sure the flow works. Then, probably check the permissions of the volume.

Let me know how it goes, thanks!

**Comment by ngrodzitski** [comment]
Yep, I can confirm it is a permissions issue.
The catch was that on "old" CI setup we mounted local directories and now switching to volumes.

**Comment by memsharded** [comment]
> Yep, I can confirm it is a permissions issue.

Great, thanks for following up!

**Comment by uilianries** [comment]
Hello @ngrodzitski Conan offers official Docker images, so you don't need to elaborate a new Docker recipe for each new compiler version:

https://hub.docker.com/u/conanio
https://github.com/conan-io/conan-docker-tools/

**Comment by uilianries** [comment]
Anyway, I think the error is not clear in terms of feedback:

```
$ conan config init
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.5/bin/conan", line 11, in <module>
    load_entry_point('conan==1.30.2', 'console_scripts', 'conan')()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/conan.py", line 11, in run
    main(sys.argv[1:])
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/command.py", line 2248, in main
    conan_api, _, _ = Conan.factory()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 228, in factory
    return cls(), None, None
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/conan_api.py", line 240, in __init__
    migrator = ClientMigrator(self.cache_folder, Version(client_version), self.out)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/migrations.py", line 27, in __init__
    self.cache = ClientCache(cache_folder, out)
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cache/cache.py", line 79, in __init__
    self._store_folder = self.config.storage_path or self.cache_folder
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cache/cache.py", line 151, in config
    self.initialize_config()
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/client/cache/cache.py", line 256, in initialize_config
    save(self.conan_conf_path, normalize(get_default_client_conf()))
  File "/opt/pyenv/versions/3.7.5/lib/python3.7/site-packages/conans/util/files.py", line 200, in save
    with open(path, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/_conan_home/.conan/conan.conf'

```

I would prefer receiving a nice feedback like:

```
$ conan config init
ERROR: Permission denied, can not configure conan home at '/_conan_home/.conan'. Please, check your write permission.
```

**Comment by memsharded** [comment]
Yeah this is a cause of a too broad or unmanaged exception in:

```python
def save(path, content, only_if_modified=False, encoding="utf-8"):

    try:
        os.makedirs(os.path.dirname(path))
    except Exception:
        pass
...
    if only_if_modified and os.path.exists(path):

```

I think this can be improved, raising earlier a more clear ConanException. The os.makedirs() should only fail with the "folder already exists" failure, but not permissions one. If you want to submit a PR improving this @uilianries, it will be welcome. But please be aware of py27-py3 differences, as well of risk of breaking because of unexpected regressions.

**Comment by ngrodzitski** [comment]
> Hello @ngrodzitski Conan offers official Docker images, so you don't need to elaborate a new Docker recipe for each new compiler version:
> 
> https://hub.docker.com/u/conanio
> https://github.com/conan-io/conan-docker-tools/

Yes, thanks, @uilianries 
I'm aware of it, but I need alpine as a ready to go [musl](https://www.musl-libc.org/) based build environment to get fully statically linked executable that runs without libc version conflicts on many old/new linux distrbs (where an app is required). Please, point me if there is something to do the same trick

**Comment by uilianries** [comment]
> Yes, thanks, @uilianries
> I'm aware of it, but I need alpine as a ready to go [musl](https://www.musl-libc.org/) based build environment to get fully statically linked executable that runs without libc version conflicts on many old/new linux distrbs (where an app is required). Please, point me if there is something to do the same trick

Unfortunately not, any question related to libc version requires a big change. Thus you are doing right, keep your version.
