### ISSUE TITLE
[bug] self.user_info_build does not contain user_info variables of build_requirement

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8313]
When using cross build profiles, the *user_info* variables of a *build requirement* are not available in [*self.user_info_build*](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#user-info-build).

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 16
  * Conan version: 1.32.1
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)

1. Use the `strawberry` recipe from this pull request: https://github.com/conan-io/conan-center-index/pull/4210
2. Build this recipe with a host and build profile:
    ```python
    from conans import ConanFile
    class T(ConanFile):
        def build_requirements(self):
            self.build_requires("strawberryperl/5.30.0.1")
        def build(self):
            self.output.info("perl: {}".format(self.user_info_build["strawberryperl"].perl))
    ```

Profiles (copy from log):
```
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

<details>

<summary>conan create c1.py t1/0.1@ -pr:h msvc16_x64 -pr:b msvc16_x64</summary>

```
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): ERROR: [RECIPE METADATA (KB-H003)] Conanfile doesn't have 'url' attribute.  (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H003) 
[HOOK - conan-center.py] pre_export(): ERROR: [RECIPE METADATA (KB-H003)] Conanfile doesn't have 'license' attribute.  (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H003) 
[HOOK - conan-center.py] pre_export(): ERROR: [RECIPE METADATA (KB-H003)] Conanfile doesn't have 'description' attribute.  (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H003) 
[HOOK - conan-center.py] pre_export(): ERROR: [RECIPE METADATA (KB-H003)] Conanfile doesn't have 'homepage' attribute.  (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H003) 
[HOOK - conan-center.py] pre_export(): WARN: [RECIPE METADATA (KB-H003)] Conanfile doesn't have 'topics' attribute. 
[HOOK - conan-center.py] pre_export(): WARN: [HEADER_ONLY, NO COPY SOURCE (KB-H005)] This recipe is a header only library as it does not declare 'settings'. Please include 'no_copy_source' to avoid unnecessary copy steps
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 25.0576171875 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): ERROR: [TEST PACKAGE FOLDER (KB-H024)] There is no 'test_package' for this recipe (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H024) 
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File 'C:\Users\maarten\AppData\Roaming\JetBrains\PyCharmCE2020.3\scratches\conanbuildinfo.txt' does not end with an endline (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H041) 
[HOOK - conan-center.py] pre_export(): ERROR: [NO FINAL ENDLINE (KB-H041)] File 'C:\Users\maarten\AppData\Roaming\JetBrains\PyCharmCE2020.3\scratches\scratch.py' does not end with an endline (https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#KB-H041) 
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [NO ASCII CHARACTERS (KB-H047)] OK
Exporting package recipe
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
t1/0.1: The stored package has not changed
t1/0.1: Exported revision: 8df5eae66d09af0a8a90a2cdba0a5c7f
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]

t1/0.1: Forced build from source
Installing package: t1/0.1
Requirements
    t1/0.1 from local cache - Cache
Packages
    t1/0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
Build requirements
    strawberryperl/5.30.0.1 from 'conan-center' - Cache
Build requirements packages
    strawberryperl/5.30.0.1:ca33edce272a279b24f87dc0d4cf5bbdcffbc187 - Cache

Installing (downloading, building) binaries...
strawberryperl/5.30.0.1: Already installed!
strawberryperl/5.30.0.1: Appending PATH environment variable: C:\.conan\6cde9b\1\bin
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
t1/0.1: Applying build-requirement: strawberryperl/5.30.0.1
t1/0.1: WARN: Build folder is dirty, removing it: C:\Users\maarten\.conan\data\t1\0.1\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
t1/0.1: Copying sources to build folder
t1/0.1: Building your package in C:\Users\maarten\.conan\data\t1\0.1\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
t1/0.1: Generator txt created conanbuildinfo.txt
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
t1/0.1: Calling build()
t1/0.1: 
t1/0.1: ERROR: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' build failed
t1/0.1: WARN: Build folder C:\Users\maarten\.conan\data\t1\0.1\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: Traceback (most recent call last):
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\model\user_info.py", line 15, in __getattr__
    return self._values_[name]
KeyError: 'perl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\maarten\.conan\data\t1\0.1\_\_\export\conanfile.py", line 6, in build
    self.output.info("perl: {}".format(self.user_info_build["strawberryperl"].perl))
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\model\user_info.py", line 17, in __getattr__
    raise AttributeError
AttributeError
```

</details>

**Comment by stefan-floeren** [comment]
This should be fixed with https://github.com/conan-io/conan-center-index/pull/6338.

@madebr, can you please verify?

**Comment by madebr** [comment]
Yes. Thanks for fixing the typo.
