### ISSUE TITLE
[bug] Conan crashes after packaging step on v1.33.0+

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#8489]
Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16/18
  * Compiler+version: -
  * Conan version: 1.33[.1]
  * Python version:3.5/6

I came across this bug/crash on Conan 1.33.0 and 1.33.1. I'm not sure what triggers it and unfortunately I can't share the recipe that fails for us since it is an internal tool. I know this is an incomplete bug report, but maybe you can figure something out.

We build inside a poetry virtual environment, using the two profiles approach (pr:h/pr:b). Since this is automated, when we build a desktop tool we end up with pr:b=pr:h. I'm not sure if it is related, but I'm giving you as much context as possible.
With conan <= 1.32.1, this works perfectly. Starting 1.33.0 we get:

```
$ poetry run conan create recipes/coolTool/all coolToo/coolVersion@us/stable -pr:h x86_64_gcc8 -pr:b x86_64_gcc
coolTool/coolVersion@us/stable: Calling build()
..
coolTool/coolVersion@us/stable: Calling package()
coolTool/coolVersion@us/stable package(): Packaged 1084 '.cmake' files
coolTool/coolVersion@us/stable package(): Packaged 253 '.so' files
coolTool/coolVersion@us/stable package(): Packaged 9 '.0' files
coolTool/coolVersion@us/stable package(): Packaged 1 '.13' file: xxx
coolTool/coolVersion@us/stable package(): Packaged 3 '.a' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 2 '.2' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 2 '.1' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 821 files
coolTool/coolVersion@us/stable package(): Packaged 781 '.py' files
coolTool/coolVersion@us/stable package(): Packaged 564 '.c' files
coolTool/coolVersion@us/stable package(): Packaged 249 '.txt' files
coolTool/coolVersion@us/stable package(): Packaged 13 '.lnt' files
coolTool/coolVersion@us/stable package(): Packaged 2047 '.h' files
coolTool/coolVersion@us/stable package(): Packaged 91 '.em' files
coolTool/coolVersion@us/stable package(): Packaged 186 '.xml' files
coolTool/coolVersion@us/stable package(): Packaged 2 '.xsl' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 4 '.xsd' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 3 '.ini' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 1 '.cfg' file: xxx
coolTool/coolVersion@us/stable package(): Packaged 2 '.lark' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 323 '.bash' files
coolTool/coolVersion@us/stable package(): Packaged 323 '.zsh' files
coolTool/coolVersion@us/stable package(): Packaged 34 '.in' files
coolTool/coolVersion@us/stable package(): Packaged 5 '.bat' files
coolTool/coolVersion@us/stable package(): Packaged 1483 '.sh' files
coolTool/coolVersion@us/stable package(): Packaged 4 '.pc' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 1476 '.dsv' files
coolTool/coolVersion@us/stable package(): Packaged 989 '.ps1' files
coolTool/coolVersion@us/stable package(): Packaged 4 '.yaml' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 34 '.srv' files
coolTool/coolVersion@us/stable package(): Packaged 188 '.idl' files
coolTool/coolVersion@us/stable package(): Packaged 227 '.msg' files
coolTool/coolVersion@us/stable package(): Packaged 4 '.action' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 189 '.cpp' files
coolTool/coolVersion@us/stable package(): Packaged 6 '.md' files
coolTool/coolVersion@us/stable package(): Packaged 2 '.gz' files: xxx
coolTool/coolVersion@us/stable package(): Packaged 1610 '.hpp' files
coolTool/coolVersion@us/stable package(): Packaged 1 '.rst' file: LICENSE.rst
coolTool/coolVersion@us/stable: Package 'c0519e2d9702ec12d057bb15adb7a02baaf18107' created
coolTool/coolVersion@us/stable: Created package revision ed5e616e5b126927255383cf3028b229
Traceback (most recent call last):
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/command.py", line 2115, in run
    method(args[0][1:])
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/command.py", line 376, in create
    profile_build=profile_build)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/conan_api.py", line 388, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/cmd/create.py", line 91, in create
    recorder=recorder)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/manager.py", line 78, in deps_install
    graph_info=graph_info)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/installer.py", line 308, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/installer.py", line 444, in _build
    self._propagate_info(root_node, using_build_profile)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/client/installer.py", line 584, in _propagate_info
    conan_file.deps_cpp_info.add(n.ref.name, dep_cpp_info)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/model/build_info.py", line 643, in add
    super(DepsCppInfo, self).update(cpp_info)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/model/build_info.py", line 402, in update
    self.build_modules = merge_dicts(self.build_modules, dep_cpp_info.build_modules_paths)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/model/build_info.py", line 542, in build_modules_paths
    return self._aggregated_values("build_modules_paths", agg_func=merge_dicts)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/model/build_info.py", line 488, in _aggregated_values
    values = getattr(self._cpp_info, item)
  File "/home/eric/conan/.poetry/virtualenvs/conan-xDmGILzz-py3.6/lib/python3.6/site-packages/conans/model/build_info.py", line 157, in build_modules_paths
    tmp = dict_to_abs_paths(BuildModulesDict(self.build_modules), self.rootpath)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

ERROR: dictionary update sequence element #0 has length 1; 2 is required
```

A bit a digging took me to the problematic funcion, in this snippet
```
    @property
    def build_modules_paths(self):
        if self._build_modules_paths is None:
            if isinstance(self.build_modules, list):  # FIXME: This should be just a plain dict
                conan_v2_behavior("Use 'self.cpp_info.build_modules[\"<generator>\"] = "
                                  "{the_list}' instead".format(the_list=self.build_modules))
                self.build_modules = BuildModulesDict.from_list(self.build_modules)
            tmp = dict_to_abs_paths(BuildModulesDict(self.build_modules), self.rootpath)
            self._build_modules_paths = tmp
        return self._build_modules_paths
```
And the problem seems to be that `self.build_modules` is a string and the code expects dictionaries or lists.

I hope this is a good enough report. Let me know if you need more data.

**Comment by ericriff** [comment]
OK so I figured it out.
The problem was me doing
```
        self.cpp_info.build_modules = os.path.join(self.package_folder, "share")
```
Which doesn't work anymore (since version 1.33.0)

Appending fixes the issue.
```
        self.cpp_info.build_modules.append(os.path.join(self.package_folder, "share"))
```

If that assignment isn't allowed anymore we should show a clearer message to the user.

**Comment by danimtb** [comment]
Hi @ericriff,

Yes, the syntax was changed indeed and now you need to specify the generator in the `cpp_info`. In your case it should be something similar as:

```
self.cpp_info.build_modules["cmake"].append(os.path.join(self.package_folder, "share"))  # example for cmake generator
```

We did a non-breaking conversion for cmake build modules (files with *.cmake*), adding them automatically to all the Conan built-in cmake generators. In your case, you are using a directory instead of a file, which I am not sure it is supported and I am sure it is a case that we are not testing. See the documentation here https://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info

**Comment by danimtb** [comment]
Closing this as solved. Thank you!
