### ISSUE TITLE
[bug] M1 : tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#8503]
reported by @a4z on slack

```
DEBUG :file_downloader.py[129]: DOWNLOAD: https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.3.tar.xz [2021-02-14 19:02:03,744]
Downloading pkgconf-1.7.3.tar.xz completed [286.28k]                                     
ERROR: Traceback (most recent call last):
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/client/source.py", line 145, in _run_source
    conanfile.source()
  File "/Users/a4z/elux/zenv1/.conan/data/pkgconf/1.7.3/_/_/export/conanfile.py", line 45, in source
    tools.get(**self.conan_data["sources"][self.version])
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/tools.py", line 83, in get
    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/client/tools/net.py", line 25, in get
    unzip(filename, destination=destination, keep_permissions=keep_permissions, pattern=pattern,
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/client/tools/files.py", line 89, in unzip
    return untargz(filename, destination, pattern, strip_root)
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/site-packages/conans/client/tools/files.py", line 159, in untargz
    with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:
  File "/Users/a4z/.asdf/installs/python/3.9.1/lib/python3.9/tarfile.py", line 1616, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
works on x86_64, but not M1
I don't have M1 to debug right now

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by SSE4** [comment]
just in case, that's the python code that raises:
https://github.com/python/cpython/blob/v3.9.1/Lib/tarfile.py#L1616

**Comment by a4z** [comment]
Thank you so much @SSE4 for reporting this, and the other issues! This is really great help.

Also thanks for pointing at the problem in pyth
on.
I will check if I can create a small script with some unpack code that is similar to what conan does and see how that works

**Comment by a4z** [comment]
I could reproduce the problem with this little script

```
import tarfile
my_tar = tarfile.open('pkgconf-1.7.3.tar.xz')
my_tar.extractall('./pkgconf-1.7.3')
my_tar.close()
```

changed python version, and it's gone, so that is not a conan issue but one in my local python , that was build from source via asdf.

Therefore, this issue can be closed since it is not a conan issue
Can you do so please, @SSE4 ?
