### ISSUE TITLE
Conan Error when using short_path = True with conan from windows installer

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#860]
Hi,

I try to build my component using test_package. As I have run in windows path problems, I added short_path = True to my component. Then, I get the following error (Conan 0.18.1):
```
My.Company.Commons/1.9.0-unreleased@demo/testing: WARN: Forced build from source
My.Company.Commons/1.9.0-unreleased@demo/testing: Building your package in D:/.conan\zd1xwu\1
My.Company.Commons/1.9.0-unreleased@demo/testing: Configuring sources in D:/.conan\aezj6j\1
Traceback (most recent call last):
  File "conan\conans\conan.py", line 10, in <module>
  File "conan\conans\conan.py", line 6, in run
  File "conan\conans\client\command.py", line 1029, in main
  File "conan\conans\client\command.py", line 943, in run
  File "conan\conans\client\command.py", line 339, in test_package
  File "conan\conans\client\manager.py", line 338, in install
  File "conan\conans\client\installer.py", line 60, in install
  File "conan\conans\client\installer.py", line 145, in _build
  File "conan\conans\client\installer.py", line 243, in _build_conanfile
  File "conan\conans\client\installer.py", line 322, in _build_package
  File "conan\conans\client\source.py", line 41, in config_source
  File "shutil.py", line 189, in copytree
  File "shutil.py", line 189, in copytree
  File "shutil.py", line 183, in copytree
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 4: ordinal not in range(128)
Failed to execute script conan
```

**Comment by memsharded** [comment]
Seems like a unicode character in the path, which probably can be handled, but I am not sure where it could come from. Which python version are you running and how did you installed conan?

Is your userhome directory in D:/?

**Comment by claasd** [comment]
I used the windows conan installer.
The problem might be that my `HOMEDRIVE=X:` (a network share) and my `HOMEPATH=\`. I cannot change that (corporate laptop).

Best Claas

**Comment by claasd** [comment]
I switched to pip installed conan with python 2.5.2 on windows, no it works.
Seems to be a problem either with python2.7 or with the PyExe stuff.

#worksforme

**Comment by memsharded** [comment]
Sorry, "no it works" meant "now it works"?
Pip installed with python2.7 doesn't work? Why 2.5.2?

Definitely the installers (generated with pyinstaller) have some issues, the recommended way is using the pip install (that doesn't use pyinstaller).

Please clarify. Thanks very much for your help!

**Comment by claasd** [comment]
Sorry, I need to re-read my posting. 
I switched to pip installed conan with python **3**.5.2, now it works!
Apologies ;-)

**Comment by memsharded** [comment]
No worries, good news! :)

The thing, as it seems yet another installer issue, and the problem with those is that they are almost impossible to debug, because they are in the executable that pyinstaller is generating, I suggest to close the issue, and increment even more our strong recommendation to use always the pip package. Thanks!

**Comment by memsharded** [comment]
So seems no action on our side at the moment, let's close it by now, please re-open if this becomes a stopper again.
