### ISSUE TITLE
[bug] empty library paths of dependencies are visible through AutotoolsBuildEnvironment.library_paths

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8816]
When a dependency wants to hide its library folders, these are visible nonetheless through `AutotoolsBuildEnvironment.library_paths`.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 17 2019
  * Conan version: 1.35.1
  * Python version: 3.9.4

### Steps to reproduce (Include if Applicable)

Let's create a simple dependency conan recipe that builds a library, but is hiding its library folder.
Then create a consumer and check whether the library folder is actually not visible.

1. Create `dependency_conan.py`:
    ```python
    from conans import ConanFile, tools, CMake
    import textwrap
    class DepConan(ConanFile):
        name = "dependency_nolibdir"
        version = "0.1"
        settings = "os", "arch", "compiler", "build_type"
        def build(self):
            tools.save("dummy.c", textwrap.dedent("""\
                int sum(int a, int b) {
                    return a + b;
                }
            """))
            tools.save("CMakeLists.txt", textwrap.dedent("""\
                cmake_minimum_required(VERSION 3.0)
                project(dep C)
                add_library(hidden_dependency STATIC dummy.c)
                install(TARGETS hidden_dependency LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)
            """))
            cmake = CMake(self)
            cmake.configure()
            cmake.build()
        def package(self):
            cmake = CMake(self)
            cmake.install()
        def package_Info(self):
            # hide the lib folder
            self.cpp_info.libdirs = []
    ```
2. Create `main_conan.py`:
    ```python
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
    import os
    class DepConan(ConanFile):
        name = "main_project"
        version = "0.1"
        settings = "os", "arch", "compiler", "build_type"
        requires = "dependency_nolibdir/0.1"
        def build(self):
            autotools = AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows)
            for p in autotools.library_paths:
                for f in os.listdir(p):
                    if "hidden_dependency" in f:
                        raise Exception(f"{p} contains hidden_dependency ({f})")
    ```
3. Create the dependency, by running:
    ```cmd
    conan create dependency_conan.py
    ```
4. Create the main project, by running
    ```cmd
    conan create main_conan.py
    ```
### Logs (Executed commands with output) (Include/Attach if Applicable)

```
main_project/0.1: Calling build()
main_project/0.1:
main_project/0.1: ERROR: Package 'fe5c17d1619573ff259808e566bf7a41620126b1' build failed
main_project/0.1: WARN: Build folder C:\Users\maarten\.conan\data\main_project\0.1\_\_\build\fe5c17d1619573ff259808e566bf7a41620126b1
ERROR: Traceback (most recent call last):
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Users\maarten\AppData\Roaming\Python\Python39\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\maarten\.conan\data\main_project\0.1\_\_\export\conanfile.py", line 13, in build
    raise Exception(f"{p} contains hidden_dependency ({f})")
Exception: C:\Users\maarten\.conan\data\dependency_nolibdir\0.1\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\lib contains hidden_dependency (hidden_dependency.lib)
```

**Comment by memsharded** [comment]
Not a bug, it seems that you have a typo:

```diff
-def package_Info(self):
+def package_info(self):
```

Your ``self.cpp_info.libdirs = []`` is not being called.

**Comment by memsharded** [comment]
I think this can be closed, thanks for reporting, let me know if you have any further issue.

**Comment by madebr** [comment]
Doh! :man_facepalming: 

Thanks for troubleshooting!
