### ISSUE TITLE
[bug] KeyError: 'USERNAME' on windows while _processWARN: websocketpp/0.8.1: requirement boost/1.74.0 overridden by your conanfile to boost/1.75.0 

### ISSUE THREAD

**Issue by Macfly** [conan-io/conan#8859]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Version	10.0.19043 Build 19043
  * Compiler+version: MSVC 19.28.29333.0
  * Conan version: 1.35.2
  * Python version: 3.8.8

### Steps to reproduce (Include if Applicable)
having a dependency overridden.
The same process works with CLang and GCC under WSL.

### Logs (Executed commands with output) (Include/Attach if Applicable)
C:\Users\Coco\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\211.7142.21\bin\cmake\win\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - NMake Makefiles" C:\Users\Coco\CLionProjects\crypto_amm
-- The CXX compiler identification is MSVC 19.28.29333.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No colored compiler diagnostic set for 'MSVC' compiler.
-- ccache found and enabled
-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
-- Conan: checking conan executable
-- Conan: Found program C:/Program Files (x86)/Conan/conan/conan.exe
-- Conan: Version found Conan version 1.35.2

-- Conan: Adding bincrafters remote repository (https://api.bintray.com/conan/bincrafters/public-conan) verify ssl (True)
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Detected VS runtime: MDd
-- Conan: Settings= -s;arch=x86;-s;build_type=Debug;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MDd
-- Conan: checking conan executable
-- Conan: Found program C:/Program Files (x86)/Conan/conan/conan.exe
-- Conan: Version found Conan version 1.35.2

-- Conan executing: C:/Program Files (x86)/Conan/conan/conan.exe install . -s arch=x86 -s build_type=Debug -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MDd -g=cmake --build=missing
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Traceback (most recent call last):
  File "conans\client\command.py", line 2164, in run
  File "conans\client\command.py", line 513, in install
  File "conans\client\conan_api.py", line 93, in wrapper
  File "conans\client\conan_api.py", line 610, in install
  File "conans\client\manager.py", line 59, in deps_install
  File "conans\client\graph\graph_manager.py", line 120, in load_graph
  File "conans\client\graph\graph_manager.py", line 255, in _resolve_graph
  File "conans\client\graph\graph_manager.py", line 365, in _load_graph
  File "conans\client\graph\graph_manager.py", line 343, in _recurse_build_requires
  File "conans\client\graph\graph_manager.py", line 327, in _recurse_build_requires
  File "conans\client\graph\graph_manager.py", line 286, in _recurse_build_requires
  File "conans\client\graph\graph_binaries.py", line 389, in evaluate_graph
  File "conans\client\graph\graph_binaries.py", line 176, in _evaluate_node
  File "conans\client\graph\graph_binaries.py", line 241, in _processWARN: websocketpp/0.8.1: requirement boost/1.74.0 overridden by your conanfile to boost/1.75.0 
ERROR: 'USERNAME'
_node
  File "conans\paths\package_layouts\package_cache_layout.py", line 133, in package_id_exists
  File "conans\paths\package_layouts\package_cache_layout.py", line 32, in wrap
  File "conans\util\windows.py", line 88, in path_shortener
  File "os.py", line 669, in __getitem__
KeyError: 'USERNAME'

CMake Error at cmake-build-debug-visual-studio/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-build-debug-visual-studio/conan.cmake:759 (old_conan_cmake_install)
  cmake/Conan.cmake:19 (conan_cmake_run)
  CMakeLists.txt:80 (run_conan)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Coco/CLionProjects/crypto_amm/cmake-build-debug-visual-studio/CMakeFiles/CMakeOutput.log".

[Failed to reload]

**Comment by memsharded** [comment]
Apparently you don't have defined in your windows environment the USERNAME environment variable, which is very weird.
This is raising this error, after a chain of coincidences:
- The boost recipe requires short-paths in Windows.
- The short_paths storage is c:/.conan, which can be a NTFS folder and might require to give current user permissions to access.
- Such permissions require the current user, then the access t USERNAME

We are already working to build a new cache, that will avoid the short-paths completely so this will not be necessary.
Probably the best workaround meanwhile would be to define the USERNAME env-var in your system correctly. Please try to do that if possible and let me know.

**Comment by Macfly** [comment]
yes it worked after setting USERNAME env var.
Thanks for the help.

**Comment by memsharded** [comment]
We can close this as solved in 2.0, because Conan 2.0 doesn't depend anymore on the USERNAME env-var in Win.
