### ISSUE TITLE
[bug] imports method is faulty

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#9084]
-----> [conanfile.py.txt](https://github.com/conan-io/conan/files/6630481/conanfile.py.txt) 

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux 20.04
  * Compiler+version: gcc 10.0
  * Conan version: 1.37.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
rename a file from attachment conanfile.py.txt -> conanfile.py
call
conan create . testimporter/1.0.0@ 

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: [Errno 2] No such file or directory: '/home/andrei/.conan/data/testimporter/1.0.0/_/_/build/432726d20293ea1938a919e27acfc5e8f6d4acd9/bin/libvulkan.so'

It seems, that sym links are ignored, while copying
[log.txt](https://github.com/conan-io/conan/files/6630796/log.txt)

**Comment by AndreyMlashkin** [comment]
I have also tried to disable symlinks:
       self.copy("*.so",            dst="bin", src="lib"    , keep_path=True, symlinks=False)
But I am getting an exception:

Traceback (most recent call last):
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/command.py", line 2176, in run
    method(args[0][1:])
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/command.py", line 374, in create
    info = self._conan.create(args.path, name, version, user, channel,
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/conan_api.py", line 386, in create
    create(self.app, ref, graph_info, remotes, update, build_modes,
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/cmd/create.py", line 81, in create
    deps_install(app=app,
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/manager.py", line 81, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 316, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 451, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 539, in _handle_node_cache
    pref = self._build_package(node, output, keep_build, remotes)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 578, in _build_package
    pref = builder.build_package(node, keep_build, self._recorder, remotes)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 226, in build_package
    self._build(conanfile, pref)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/installer.py", line 142, in _build
    copied_files = run_imports(conanfile)
  File "/home/andrei/.local/lib/python3.8/site-packages/conans/client/importer.py", line 81, in run_imports
    conanfile.imports()
  File "/home/andrei/.conan/data/testimporter/1.0.0/_/_/export/conanfile.py", line 25, in imports
    self.copy("*.so",            dst="bin", src="lib"    , keep_path=True, symlinks=False)
TypeError: __call__() got an unexpected keyword argument 'symlinks'

ERROR: __call__() got an unexpected keyword argument 'symlinks'

**Comment by AndreyMlashkin** [comment]
As I understand, conan shall just add '-L' to cp command, while symlinks are deactivated, which shall resolve the problem

**Comment by memsharded** [comment]
``imports()`` method has been removed in 2.0.

Conan 1.X already recommends using a explicit ``copy()`` in the ``generate()`` method instead of imports.
Closing this ticket as outdated and not planned, don't hesitate to create new tickets for any further question, thanks!
