### ISSUE TITLE
conanmanifest.txt: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by r1d1shka** [conan-io/conan#9236]
Hi!

I try to build project with next conanfile.txt (Windows server 2019 x64):
```
[requires]
cgal/5.2
jsoncpp/1.9.0@theirix/stable
geographiclib/1.50.1
tinyxml2/8.0.0
gdal/3.2.1
yaml-cpp/0.6.3
eigen/3.3.7@conan/stable

[generators]
MSBuildDeps

[options]
gdal:with_sqlite3=True
```

Haven't had any problems for a while, but today there was an error:

```
20:12:28  Configuration:
20:12:28  [settings]
20:12:28  arch=x86_64
20:12:28  arch_build=x86_64
20:12:28  build_type=Release
20:12:28  compiler=Visual Studio
20:12:28  compiler.runtime=MD
20:12:28  compiler.toolset=v142
20:12:28  compiler.version=16
20:12:28  os=Windows
20:12:28  os_build=Windows
20:12:28  [options]
20:12:28  [build_requires]
20:12:28  [env]
20:12:28  
20:12:35  Traceback (most recent call last):
20:12:35    File "conans\client\command.py", line 2176, in run
20:12:35    File "conans\client\command.py", line 519, in install
20:12:35    File "conans\client\conan_api.py", line 93, in wrapper
20:12:35    File "conans\client\conan_api.py", line 612, in install
20:12:35    File "conans\client\manager.py", line 60, in deps_install
20:12:35    File "conans\client\graph\graph_manager.py", line 120, in load_graph
20:12:35    File "conans\client\graph\graph_manager.py", line 272, in _resolve_graph
20:12:35    File "conans\client\graph\graph_manager.py", line 380, in _load_graph
20:12:35    File "conans\client\graph\graph_manager.py", line 303, in _recurse_build_requires
20:12:35    File "conans\client\graph\graph_binaries.py", line 406, in evaluate_graph
20:12:35    File "conans\client\graph\graph_binaries.py", line 188, in _evaluate_node
20:12:35    File "conans\client\graph\graph_binaries.py", line 259, in _process_node
20:12:35    File "conans\client\graph\graph_binaries.py", line 87, in _evaluate_cache_pkg
20:12:35    File "conans\client\graph\graph_binaries.py", line 26, in _check_update
20:12:35    File "conans\model\manifest.py", line 91, in load
20:12:35    File "conans\util\files.py", line 232, in load
20:12:35  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.conan\\data\\libgeotiff\\1.6.0\\_\\_\\package\\68a76e0b6d40fdecb9d227b8ad5c22ab7efac263\\conanmanifest.txt'
20:12:35  
20:12:35  WARN: cgal/5.2: requirement eigen/3.3.9 overridden by your conanfile to eigen/3.3.7@conan/stable 
20:12:35  WARN: libgeotiff/1.6.0: requirement proj/8.1.0 overridden by gdal/3.2.1 to proj/8.0.1 
20:12:35  WARN: proj/8.0.1: requirement sqlite3/3.36.0 overridden by libgeotiff/1.6.0 to sqlite3/3.35.5 
20:12:35  ERROR: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.conan\\data\\libgeotiff\\1.6.0\\_\\_\\package\\68a76e0b6d40fdecb9d227b8ad5c22ab7efac263\\conanmanifest.txt'

```
Can you please tell me how can I fix this? Thanks...

**Comment by memsharded** [comment]
Hi @r1d1shka 

First, one quick reminder: packages with @user/channel like ``eigen/3.3.7@conan/stable`` are legacy, they will not be in the new ``conancenter=https://center.conan.io`` remote, better start using as soon as possible the ``eigen/3.3.9`` from https://conan.io/center/eigen

Then it seems that something went really wrong in your cache. Someone removed some files, some download was killed, or some install aborted. Conan has some mechanisms to try to guarantee the integrity of the packages, but it might not cover every possible error. I would recommend to completely remove the ``conan remove libgeotiff* -f`` package, make sure the folder ``C:\\Users\\Administrator\\.conan\\data\\libgeotiff`` is also removed, and try again.

Also, a couple of recommendations:
- even if you are running in the server, you shouldn't be using the Administrator user, but some other user way less privileged.
- In CI jobs, do not always use the same Conan cache. It is not designed for concurrency, so if you start to have  multiple concurrent CI jobs using ``C:\\Users\\Administrator\\.conan\\``, you can have race conditions in the cache.

**Comment by r1d1shka** [comment]
Thanks! Your advice helped to solve the problem
