### ISSUE TITLE
Conan log file requires absolute path

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#925]
If relative path is provided fails with trace:

```
ERROR: The specified path doesn't exist: 'mylog.txt'
Traceback (most recent call last):
  File "C:/Users/memsharded/scripts/conan.py", line 16, in <module>
    main(sys.argv[1:])
  File "C:/Users/memsharded/conanws/conan/conans\client\command.py", line 1059, in main
    error = command.run(args)
  File "C:/Users/memsharded/conanws/conan/conans\client\command.py", line 969, in run
    log_exception(exc, msg)
  File "C:/Users/memsharded/conanws/conan/conans\util\tracer.py", line 127, in log_exception
    _append_action("EXCEPTION", {"class": str(exc.__class__.__name__), "message": message})
  File "C:/Users/memsharded/conanws/conan/conans\util\tracer.py", line 60, in _append_action
    _append_to_log(props)
  File "C:/Users/memsharded/conanws/conan/conans\util\tracer.py", line 48, in _append_to_log
    if _get_tracer_file():
  File "C:/Users/memsharded/conanws/conan/conans\util\tracer.py", line 39, in _get_tracer_file
    raise ConanException("The specified path doesn't exist: '%s'" % trace_path)
conans.errors.ConanException: The specified path doesn't exist: 'mylog.txt'

```
I would say that every traceback is a bug, I'd prefer that relative paths are also supported for log files, but if not, manage it properly.

**Comment by lasote** [comment]
A relative path is not a good idea, a lot of different files could be spread if you change your current dir.
I've controlled the error to not show ugly traces and will be available at 0.19.
