### ISSUE TITLE
[bug] Searching the reference of an editable package fails with a traceback

### ISSUE THREAD

**Issue by t6tb7n** [conan-io/conan#9261]
### Environment Details
  * Operating System+version: Arch Linux
  * Compiler+version: 
  * Conan version: 1.38.0
  * Python version: 3.9.5

### Steps to reproduce

1. Create a project with the following recipe and layout description file:

```
from conans import ConanFile, CMake, tools

class PkgaConan(ConanFile):
    name = "pkga"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    generators = "cmake_find_package"
    exports_sources = "./*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def build(self):
        cmake = CMake(self, generator='Ninja')
        cmake.configure()
        cmake.build()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["pkga"]

```
```
[includedirs]
build/package/include

[libdirs]
build/package/lib
```

2. Put the package in editable mode: `conan editable add . pkga/0.1.0 -l layout`
3. Search for the package with the full reference: `conan search pkga/0.1.0@`

### Logs (Executed commands with output)

```
❯ conan search pkga/0.1.0@
Traceback (most recent call last):
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/command.py", line 2213, in run
    method(args[0][1:])
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/command.py", line 1398, in search
    info = self._conan.search_packages(repr(ref), query=args.query,
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 965, in search_packages
    references = search.search_packages(ref, remote_name, query=query, outdated=outdated)
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/cmd/search.py", line 50, in search_packages
    return self._search_packages_in_local(ref, query, outdated)
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/client/cmd/search.py", line 63, in _search_packages_in_local
    packages_props = search_packages(package_layout, query)
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/search/search.py", line 138, in search_packages
    infos = _get_local_infos_min(package_layout)
  File "/home/tibo/.local/lib/python3.9/site-packages/conans/search/search.py", line 145, in _get_local_infos_min
    package_ids = package_layout.package_ids()
AttributeError: 'PackageEditableLayout' object has no attribute 'package_ids'

ERROR: 'PackageEditableLayout' object has no attribute 'package_ids'
```

**Comment by memsharded** [comment]
Proposing a fix in https://github.com/conan-io/conan/pull/9262

To clarify: the fix is improve the error message and avoid the traceback. It is not possible to list the binaries of a package in editable mode. 

Thanks for reporting!
