### ISSUE TITLE
[question] Unicode exception in SCM under Docker

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#9274]
Hello,
we have a large repo which we are exporting via scm (auto URL and revision).
It works fine under Windows, but fails under Docker/Ubuntu 18.04

Do you have any suggestion how could I debug this easily? Or simply I have to compile Conan from source and put bunch of print()s here and there?
Thanks,
 
######## conan export feature_conan_transition+37-81cc044-dirty@
Exporting package recipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 2213, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.6/dist-packages/conans/client/command.py", line 1111, in export
    ignore_dirty=args.ignore_dirty)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/conan_api.py", line 866, in export
    graph_lock=graph_lock, ignore_dirty=ignore_dirty)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/cmd/export.py", line 148, in cmd_export
    _export_scm(scm_data, local_src_folder, scm_sources_folder, output)
  File "/usr/local/lib/python3.6/dist-packages/conans/client/cmd/export.py", line 449, in _export_scm
    excluded = SCM(scm_data, origin_folder, output).excluded_files
  File "/usr/local/lib/python3.6/dist-packages/conans/model/scm.py", line 122, in excluded_files
    return self.repo.excluded_files()
  File "/usr/local/lib/python3.6/dist-packages/conans/client/tools/scm.py", line 234, in excluded_files
    paths = to_file_bytes("\n".join(file_paths))
  File "/usr/local/lib/python3.6/dist-packages/conans/util/files.py", line 219, in to_file_bytes
    content = bytes(content, encoding)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 165683-165685: surrogates not allowed

**Comment by harsszegi** [comment]
Ok, our issue is that we have a "strange" file in our repository for Unicode tests and this gives the creep to Conan/Python (after Docker converts a bad Unicode name for sure).

Is it possible to tune up files/to_file_bytes like this?:

def to_file_bytes(content, encoding="utf-8", error = "strict"):
and then in the function "content = bytes(content, encoding, error)"

and obviously in scm/excluded_files:

paths = to_file_bytes("\n".join(file_paths), "utf-8", "replace")

Yeah I fully understand that this is again some Windows host, Linux container hackery, but if there would be an option in scm at least to allow this, it would unblock us. Please think about it!
Thanks,

**Comment by harsszegi** [comment]
On the other hand, you might close this, as obviously we can work this around with properly defining our Dockerfile via adding "ENV LANG C.UTF-8" to it
