### ISSUE TITLE
[bug] Rocky linux 8.4 :  pkg_resources.ContextualVersionConflict: (urllib3 1.25.11

### ISSUE THREAD

**Issue by alexisfrjp** [conan-io/conan#9329]
Similar: https://github.com/conan-io/conan/issues/8041

### Environment Details (include every applicable attribute)
  * Operating System+version: **Rocky Linux release 8.4 (Green Obsidian)**
  * Compiler+version: **gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)**
  * Conan version:  **conan (1.39.0)**
  * Python version: **Python 3.6.8**

### Steps to reproduce (Include if Applicable)
1. Install conan on a fresh linux install: `pip3 install conan --user`
2. Run Conan doing anything:
```
$ conan --version
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.11 (/home/alexis/.local/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexis/.local/bin/conan", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25.11 (/home/alexis/.local/lib/python3.6/site-packages), Requirement.parse('urllib3<1.25,>=1.21.1'), {'requests'})
```

Reverting to `conan (1.34.0)` works.

**Comment by memsharded** [comment]
This seems more a bug in the python dependencies than in Conan itself, the above traceback doesn't touch Conan at all.
It is likely that modern Conan versions have upgraded some dependencies (typically due to vulnerabilities and similar things), and something in that Linux distro broke. 

Could you please print your installed dependencies versions? The output of the ``pip install`` or a ``pip freeze`` could help.

Also this issue can be produced by an outdated version of pip you are using to install Conan. Which ``pip`` version are you using? Please try upgrading it or using ``--use-feature=2020-resolver``, and let us know how it goes.
