### ISSUE TITLE
[bug] errors in conans\client\command.py after running `conan remove "*" -s -b -f`

### ISSUE THREAD

**Issue by llena1** [conan-io/conan#9541]
Hi, there's a rather big work project which libraries are set up with conan. Conan files have been taking a lot of space (110GB) and I followed advice from here to clean it up: https://stackoverflow.com/questions/50247671/repository-clean-up
After that `conan install` and `conan upload` commands result in similar errors.

### Environment Details
  * Operating System+version: Windows 10 Pro, 10.0.19043 Build 19043
  * Compiler+version: Visual Studio 16
  * Conan version: 1.36.0
  * Python version: 3.8.2

### Steps to reproduce
don't know how reproducible it is but here's the only thing I did:
`conan remove "*" -s -b -f`

### Logs
Upload command output:
`conan upload "*" --all --confirm -r artifactory
WARN: Skipping package '359e1f4d6c46da4930efac2fa5fc269ae5e6aff1', it doesn't belong to the current recipe revision
WARN: Skipping package '53842cd7b135925f0eab17bcbc4d63ea69fc5c26', it doesn't belong to the current recipe revision
WARN: Skipping package '8a1abd04fec603176897dbf6f8352239cbe2fe83', it doesn't belong to the current recipe revision
WARN: Skipping package 'd27fcb93bb54b26492eb70b6a366ece7ae96c316', it doesn't belong to the current recipe revision
WARN: Skipping package 'e3fe81c1ac4f7df0e5e317cdd8b3fb9546027ac6', it doesn't belong to the current recipe revision
WARN: Skipping package 'ff23458fdcfc6958846560aa100c418b1782364d', it doesn't belong to the current recipe revision
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\conans\client\command.py", line 2170, in run
    method(args[0][1:])
  File "c:\program files\python38\lib\site-packages\conans\client\command.py", line 1496, in upload
    info = self._conan.upload(pattern=reference, package=package_id,
  File "c:\program files\python38\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\conans\client\conan_api.py", line 984, in upload
    uploader.upload(pattern, remotes, upload_recorder, package, all_packages, confirm,
  File "c:\program files\python38\lib\site-packages\conans\client\cmd\uploader.py", line 455, in upload
    refs_by_remote = collecter.collect(package_id, reference_or_pattern, confirm, remotes,
  File "c:\program files\python38\lib\site-packages\conans\client\cmd\uploader.py", line 53, in collect
    refs_by_remote = self._collect_packages_to_upload(refs, confirm, remotes, all_packages,
  File "c:\program files\python38\lib\site-packages\conans\client\cmd\uploader.py", line 86, in _collect_packages_to_upload
    metadata = self._cache.package_layout(ref).load_metadata()
  File "c:\program files\python38\lib\site-packages\conans\paths\package_layouts\package_cache_layout.py", line 245, in load_metadata
    return PackageMetadata.loads(text)
  File "c:\program files\python38\lib\site-packages\conans\model\package_metadata.py", line 87, in loads
    data = json.loads(content)
  File "c:\program files\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Install:
`Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
cppstd=14
os=Windows
os_build=Windows
[options]
//project-related properties
[build_requires]
[env]`
`Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\conans\client\command.py", line 2170, in run
    method(args[0][1:])
  File "c:\program files\python38\lib\site-packages\conans\client\command.py", line 501, in install
    info = self._conan.install(path=args.path_or_reference,
  File "c:\program files\python38\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\conans\client\conan_api.py", line 598, in install
    deps_install(app=self.app,
  File "c:\program files\python38\lib\site-packages\conans\client\manager.py", line 57, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_manager.py", line 118, in load_graph
    deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_manager.py", line 263, in _resolve_graph
    deps_graph = self._load_graph(root_node, check_updates, update,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_manager.py", line 373, in _load_graph
    graph = builder.load_graph(root_node, check_updates, update, remotes, profile_host,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 66, in load_graph
    self._expand_node(root_node, dep_graph, Requirements(), None, None, check_updates,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 128, in _expand_node
    self._expand_require(require, node, graph, check_updates, update, remotes, profile_host,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 233, in _expand_require
    self._expand_node(new_node, graph, new_reqs, node.ref, new_options, check_updates,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 128, in _expand_node
    self._expand_require(require, node, graph, check_updates, update, remotes, profile_host,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 204, in _expand_require
    new_node = self._create_new_node(node, graph, require, check_updates, update,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 399, in _create_new_node
    result = self._resolve_recipe(current_node, dep_graph, requirement, check_updates, update,  File "c:\program files\python38\lib\site-packages\conans\client\graph\graph_builder.py", line 359, in _resolve_recipe
    result = self._proxy.get_recipe(requirement.ref, check_updates, update,
  File "c:\program files\python38\lib\site-packages\conans\client\graph\proxy.py", line 33, in get_recipe
    result = self._get_recipe(layout, ref, check_updates, update, remotes, recorder)
  File "c:\program files\python38\lib\site-packages\conans\client\graph\proxy.py", line 54, in _get_recipe
    metadata = layout.load_metadata()
  File "c:\program files\python38\lib\site-packages\conans\paths\package_layouts\package_cache_layout.py", line 245, in load_metadata
    return PackageMetadata.loads(text)
  File "c:\program files\python38\lib\site-packages\conans\model\package_metadata.py", line 87, in loads
    data = json.loads(content)
  File "c:\program files\python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by memsharded** [comment]
Hi @llena1 

It seems that your cache got corrupted at some point, could be a broken job or something similar. 
The problem is that the traces are not showing which one is the corrupted one. Some things that you can try:
- If using a server (recommended) that could re-install binaries from, then, you could just remove the cache folder completely (and using ``conan config install`` to manage configuration, which is recommended).
- If for some reason you really need to preserve your cache binaries, I would try to identify which package is the offending one. If you don't have too many packages, trying ``conan remove pkgname -s -b -f`` could help. If you have many packages, then I would setup a quick script to iterate them (as a result of ``conan search``), doing the ``conan remove <pkgname> -s -b -f`` until one fails.
- Go to the cache folder and remove manually that package, then re-build it.

I hope this helps, let me know how it goes, thanks!

**Comment by llena1** [comment]
Hi @memsharded,

I finally had time to try your suggestions. Removing commands have run without a failure, but quite a number of packages failed at upload. It's too many, so I'll be removing and reinstalling all of them as per the first suggestion.

Thank you for you help!
