### ISSUE TITLE
[bug] Conan is unable to extract .tar.bz2 on AIX

### ISSUE THREAD

**Issue by bemehiser** [conan-io/conan#9577]
On AIX, extracting a tar.bz2 file fails in Conan (see logs.)

```
$ conan install m4/1.4.18@ --build=m4
# ...
ERROR: m4/1.4.18: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version],
        ReadError: file could not be opened successfully
```

I attempted to download and extract the same file with `curl` and `tar`, and it extracts just fine.

```
$ curl -O https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.bz2
$ tar -xf m4-1.4.18.tar.bz2
$ ls m4-1.4.18
AUTHORS         ChangeLog       INSTALL         NEWS            TODO            ...
```

### Environment Details (include every applicable attribute)
  * Operating System+version: AIX 7.1
  * Compiler+version: GCC 10.2.0
  * Conan version: 1.39.0
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)

1. Setup Conan on AIX.

2. Attempt to build the m4 package.
```
conan install m4/1.4.18@ --build=m4
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan install m4/1.4.18@ --build=m4
Configuration:
[settings]
arch=ppc64
arch_build=ppc64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=AIX
os_build=AIX
[options]
[build_requires]
[env]
CC=gcc -maix64
CFLAGS=-maix64 -pthread
CPP=cpp -maix64
CXX=g++ -maix64
LDFLAGS=-pthread
OBJECT_MODE=64
m4/1.4.18: Forced build from source
Installing package: m4/1.4.18
Requirements
    m4/1.4.18 from 'conancenter' - Cache
Packages
    m4/1.4.18:f13702efcd7947235b0bb28d1be9fd785a995dbe - Build

Installing (downloading, building) binaries...
m4/1.4.18: WARN: Build folder is dirty, removing it: /home/jenkins/.conan/data/m4/1.4.18/_/_/build/f13702efcd7947235b0bb28d1be9fd785a995dbe
m4/1.4.18: WARN: Trying to remove corrupted source folder
m4/1.4.18: WARN: This can take a while for big packages
m4/1.4.18: Configuring sources in /home/jenkins/.conan/data/m4/1.4.18/_/_/source
Downloading m4-1.4.18.tar.bz2 completed [1481.41k]

ERROR: m4/1.4.18: Error in source() method, line 41
        tools.get(**self.conan_data["sources"][self.version],
        ReadError: file could not be opened successfully
```

**Comment by memsharded** [comment]
If that is reproducible only from a AIX, we would need some help to triage this. Anyone out there with AIX that could debug this issue? The code that extract it is very generic, maybe could be reproduced without Conan, just a python file:

```python
def untargz(filename, destination=".", pattern=None, strip_root=False):
    import tarfile
    with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:
        if not pattern and not strip_root:
            tarredgzippedFile.extractall(destination)
        else:
            members = tarredgzippedFile.getmembers()

            if strip_root:
                names = [n.replace("\\", "/") for n in tarredgzippedFile.getnames()]
                common_folder = os.path.commonprefix(names).split("/", 1)[0]
                if not common_folder and len(names) > 1:
                    raise ConanException("The tgz file contains more than 1 folder in the root")
                if len(names) == 1 and len(names[0].split("/", 1)) == 1:
                    raise ConanException("The tgz file contains a file in the root")
                # Remove the directory entry if present
                members = [m for m in members if m.name != common_folder]
                for member in members:
                    name = member.name.replace("\\", "/")
                    member.name = name.split("/", 1)[1]
                    member.path = member.name
            if pattern:
                members = list(filter(lambda m: fnmatch(m.name, pattern),
                                      tarredgzippedFile.getmembers()))
            tarredgzippedFile.extractall(destination, members=members)
```

**Comment by SSE4** [comment]
maybe it's just python interpreter compiled without bz2?
we had some similar reports in the past, e.g. https://github.com/conan-io/conan/issues/8503
could you possibly check this snippet in your python interpreter?
```
import tarfile
my_tar = tarfile.open('m4-1.4.18.tar.bz2')
my_tar.extractall('./m4-1.4.18')
my_tar.close()
```

**Comment by bemehiser** [comment]
@SSE4, I bet that's it. Our toolchain doesn't contain bz2, so python definitely isn't built with it.

When I the code snippet, I get this.
```
Traceback (most recent call last):
  File "/tmp/extract.py", line 2, in <module>
    my_tar = tarfile.open('m4-1.4.18.tar.bz2')
  File "/opt/atc-2.0/lib/python3.9/tarfile.py", line 1616, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

I'll close this for now, and re-open it if we still have issues after adding bz2.

Thanks for the help!
