### ISSUE TITLE
[bug] 'tuple' object has no attribute 'get_safe'

### ISSUE THREAD

**Issue by n-eq** [conan-io/conan#9586]
Hello, I am trying to cross-compile a package for Android (in this case Armv7) but the command fails with the following error.
`ERROR: 'tuple' object has no attribute 'get_safe'` (See full log trace below)

### Environment Details (include every applicable attribute)
* Operating System+version: MacOS Big Sur 11.4 (Darwin 20.5.0)
* Compiler+version: Clang (armv7a-linux-androideabi22-) 12.0.5
* Conan version: 1.36.0
* Python version: 3.9.6

### Steps to reproduce (Include if Applicable)

Recipe (only the interesting part): 

```
class FccFile(ConanFile):
    license = get_target_license()
    settings = "os", "compiler", "arch", "build_type"
    generators = "cmake"
    exports = "CMakeLists.txt", "*.cmake", "*.py"
    cross_build_settings = None
    requires = get_dependencies(cross_build_settings, "CMakeLists.txt")

    def __init__(self, output, runner, display_name="", user=None, channel=None):
        super().__init__(output, runner, display_name, user, channel)
        if tools.cross_building(self):
            cross_build_settings = tools.get_cross_building_settings(self)

    def package_info(self):
        osTmp = ''
        arch = ''

        if svfcc.os_is_linux():
            osTmp = 'lux'
            if self.settings.arch == "x86_64":
                arch = '64'
            self.cpp_info.libs = ['%s%s%s' % (self.name, osTmp, arch)]
        elif svfcc.os_is_windows():
            osTmp = 'w'
            arch = '32' if self.settings.arch == "x86" else '64'
            self.cpp_info.libs = ['%s%s%s' % (self.name, osTmp, arch)]
        else:
            self.cpp_info.frameworkdirs.append("%s/lib" % (self.package_folder))
            self.cpp_info.frameworks.append('ssv%sosx' % (self.name))

```

* Default profile
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release

[options]

[build_requires]

[env]
```

* Android Armv7 profile
```
include(default)
target_host=armv7a-linux-androideabi
android_ndk=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858
api_level=22

[settings]
arch=armv7
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=12
os=Android
os.api_level=$api_level

[build_requires]

[options]

[env]
PATH=[$android_ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin]
CHOST=$target_host
AR=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
AS=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-as
RANLIB=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib
CC=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi22-clang
CXX=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi22-clang++
LD=$target_host-ld
STRIP=/Users/n-eq/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-strip
CONAN_CMAKE_TOOLCHAIN_FILE=$android_ndk/build/cmake/android.toolchain.cmake
``` 

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan create . mypackage/android_armeabi-v7a -s build_type=Release -o shared=False -o log4c:shared=False -pr:h android_armeabi-v7a -pr:b default -tf None -j /Users/n-eq/Dev/mypackage/__liv/pkg_info/pkg_info_3.00.09_android_armeabi-v7a_Release_static.json --build missing
conan file settings get stfe:  ('os', 'compiler', 'build_type', 'arch', 'os_build', 'arch_build')
conanFile:  ('os', 'compiler', 'build_type', 'arch', 'os_build', 'arch_build')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 2170, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 372, in create
    info = self._conan.create(args.path, name, version, user, channel,
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 365, in create
    new_ref = cmd_export(self.app, conanfile_path, name, version, user, channel, keep_source,
  File "/usr/local/lib/python3.9/site-packages/conans/client/cmd/export.py", line 69, in cmd_export
    conanfile = loader.load_export(conanfile_path, name, version, user, channel)
  File "/usr/local/lib/python3.9/site-packages/conans/client/loader.py", line 160, in load_export
    conanfile = self.load_named(conanfile_path, name, version, user, channel,
  File "/usr/local/lib/python3.9/site-packages/conans/client/loader.py", line 129, in load_named
    conanfile, _ = self.load_basic_module(conanfile_path, lock_python_requires, user, channel)
  File "/usr/local/lib/python3.9/site-packages/conans/client/loader.py", line 88, in load_basic_module
    result = conanfile(self._output, self._runner, display, user, channel)
  File "/Users/n-eq/.svfcc/svfcc.py", line 1120, in __init__
    if tools.cross_building(self):
  File "/usr/local/lib/python3.9/site-packages/conans/client/tools/oss.py", line 477, in cross_building
    ret = get_cross_building_settings(conanfile, self_os, self_arch)
  File "/usr/local/lib/python3.9/site-packages/conans/client/tools/oss.py", line 508, in get_cross_building_settings
    os_host = conanfile.settings.get_safe("os")
AttributeError: 'tuple' object has no attribute 'get_safe'

ERROR: 'tuple' object has no attribute 'get_safe'

**Comment by n-eq** [comment]
Runnig again `conan create` `CONAN_LOGGING_LEVEL=debug` yiels this interesting line where it seems `settings=None`. How is this possible?
```
DEBUG :tracer.py      [156]: CONAN_API: create(test_build_folder=None,lockfile=None,lockfile_out=None,ignore_dirty=False,profile_build=ProfileData(profiles=['default'], settings=None, options=None, env=None)) [2021-09-11 19:19:24,068]
```

**Comment by memsharded** [comment]
Hi @n-eq 

It seems you are using some internal, private implementation of Conan, the ``__init__()`` method. As specified in the docs, this is not possible, can lead to undefined behavior, and is subject to break at any release. So this is not a bug.

In this case, you are trying to access some members with:
```python
if tools.cross_building(self):
            cross_build_settings = tools.get_cross_building_settings(self)
```
before they are correctly initialized.

You shouldn't do that, when you need the settings in the ``build()`` method typically, you should access them from that method. Please try moving that part to the correct location and let us know how it goes.

**Comment by n-eq** [comment]
Hey @memsharded!
Thanks for the insight. I am actually doing this as a way to check if we are building for the host machine or cross-building (e.g. for Android). I need this because the requirements are not completely the same, so I set them depending on the build configuration.

**Comment by n-eq** [comment]
> You shouldn't do that, when you need the settings in the `build()` method typically, you should access them from that method. Please try moving that part to the correct location and let us know how it goes.


I modified the build method to setup `requires`.

```
def copy_package_files(conanFile, include_dst="include", lib_dst="lib", bin_dst="bin", exe_dst="exe"):
    public_headers = [h for h in get_public_headers() if not '::' in h]

    if public_headers:
        for public_header in public_headers:
            if os.path.exists(public_header):
                if os.path.isdir(public_header):
                    conanFile.copy("*.h", src=public_header, dst=include_dst, keep_path=True)
                    conanFile.copy("*.hpp", src=public_header, dst=include_dst, keep_path=True)
                else:
                    conanFile.copy(public_header, dst=include_dst, keep_path=False)
    else:
        conanFile.copy("*.h", src="src", dst=include_dst)
        conanFile.copy("*.hpp", src="src", dst=include_dst)

    conanFile.copy("*.lib", src="lib", dst=lib_dst, keep_path=False)
    conanFile.copy("*.dll", src="bin", dst=bin_dst, keep_path=False)
    conanFile.copy("*.dylib*", src="lib", dst=lib_dst, keep_path=False)
    conanFile.copy("*.framework*", symlinks=True)
    conanFile.copy("*.so", src="lib", dst=lib_dst, keep_path=False)
    conanFile.copy("*.a", src="lib", dst=lib_dst, keep_path=False)
    conanFile.copy("*.pdb", src="bin", dst=bin_dst, keep_path=False)
    conanFile.copy("*.pdb", src="lib", dst=lib_dst, keep_path=False)
    conanFile.copy("*", src="bin", dst=bin_dst, keep_path=False, excludes=("*.dll", "*.ilk", "*.pdb"))

class FccFile(ConanFile):
# no more __init__ method
    def build(self):
        self.requires = get_dependencies(tools.get_cross_building_settings(self))
        cmake_build(self, CMake(self, set_cmake_flags=True), tools.cross_building(self))

	def package(self):
		copy_package_files(self)

```

Although it correctly compiles source files, it fails when calling `package`:

```
DEBUG :package.py     [73]: PACKAGE: Creating config files to /Users/n-eq/.conan/data/log4c/3.00.09/mypackage/android_armeabi-v7a/package/d6d2c699768969d10e64839398ba3af29895ba79 [2021-09-12 12:27:50,365]
log4c/3.00.09@mypackage/android_armeabi-v7a package(): Packaged 3 '.h' files: log4c-wrapper.h, category.h, log4c-api.h
log4c/3.00.09@mypackage/android_armeabi-v7a package(): Packaged 1 '.a' file: liblog4c.a
log4c/3.00.09@mypackage/android_armeabi-v7a: Package 'd6d2c699768969d10e64839398ba3af29895ba79' created
log4c/3.00.09@mypackage/android_armeabi-v7a: Created package revision d82b023ccd20effa6c83a5d7cd5c0931
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 2170, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conans/client/command.py", line 372, in create
    info = self._conan.create(args.path, name, version, user, channel,
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/conans/client/conan_api.py", line 385, in create
    create(self.app, ref, graph_info, remotes, update, build_modes,
  File "/usr/local/lib/python3.9/site-packages/conans/client/cmd/create.py", line 79, in create
    deps_install(app=app,
  File "/usr/local/lib/python3.9/site-packages/conans/client/manager.py", line 80, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", line 313, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", line 448, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", line 532, in _handle_node_cache
    self._call_package_info(conanfile, package_folder, ref=pref.ref)
  File "/usr/local/lib/python3.9/site-packages/conans/client/installer.py", line 615, in _call_package_info
    public_deps = [name for name, req in conanfile.requires.items() if not req.private
AttributeError: 'tuple' object has no attribute 'items'
```

**Comment by memsharded** [comment]
Yet another issue, with the location of the logic :)

Any conditional definition of ``requires`` needs to go to the ``requirements()`` method, something like:

```python
def requirements(self):
        for require in get_dependencies(tools.get_cross_building_settings(self)):
               self.requires(require)
```

The reason is that when the ``build()`` method executes, it has already computed the requirements, expanded the dependencies, and transitive dependencies, propagated information down to the current package via generators (like generating xxx-config.cmake files with CMakeDeps), and only then, it calls the ``build()`` method. If you try to change requirements there, it will fail. I'd recommend to have a look to the https://docs.conan.io/en/latest/reference/conanfile.html section to get some further insights of the different methods in recipes.

**Comment by n-eq** [comment]
I appreciate your explanation James. I ended out calling `get_dependencies`
as you suggest in the dedicated `requirements` method. However, I am now
faced with a *Loop detected in context host *issue although I am using
`pr:h` and `pr:b` arguments in my command line...

**Comment by memsharded** [comment]
Hi @n-eq 

Ok, that could be a different issue, and it would need analyzing the exact dependencies defined in that way. Even if using the ``profile:host``, it is totally possible that some package ends requiring itself directly or transitively.

I'd suggest closing this issue as solved, as it was not really a bug, and opening a new issue with the details of that "loop". Thanks!

**Comment by n-eq** [comment]
Hi @memsharded 
Opening a new issue, thanks again.
