### ISSUE TITLE
[bug] imports() issue with conan workspace install

### ISSUE THREAD

**Issue by FranzPoize** [conan-io/conan#9646]
### Environment Details (include every applicable attribute)
  * Operating System+version: 5.14.6-arch1-1
  * Compiler+version: clang 10.0.0
  * Conan version: 1.38.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
not sure because i'm not super fluent in conan
`conan workspace install` a project with an `imports()` method in one of your conanfile.py

### Logs (Executed commands with output) (Include/Attach if Applicable)
`File "/home/franz/.local/lib/python3.9/site-packages/conans/client/importer.py", line 76, in run_imports`

when using `conan workspace install` at this line imports_folder is None
when using `conan create` on the conanfile of the project which has the imports() method it has the proper value

Here is the full error:
```
grapkimbo/local: Calling generate()
grapkimbo/local: Generated conaninfo.txt
grapkimbo/local: Generated graphinfo
grapkimbo/local: Generated conanbuildinfo.txt
Traceback (most recent call last):
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/command.py", line 2213, in run
    method(args[0][1:])
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/command.py", line 1843, in workspace
    self._conan.workspace_install(args.path,
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 525, in workspace_install
    installer.install(deps_graph, remotes, build, update, graph_info.profile_host,
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/installer.py", line 316, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/installer.py", line 438, in _build
    self._handle_node_editable(node, profile_host, profile_build, graph_lock)
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/installer.py", line 519, in _handle_node_editable
    copied_files = run_imports(conanfile)
  File "/home/franz/.local/lib/python3.9/site-packages/conans/client/importer.py", line 76, in run_imports
    mkdir(conanfile.imports_folder)
  File "/home/franz/.local/lib/python3.9/site-packages/conans/util/files.py", line 287, in mkdir
    if os.path.exists(path):
  File "/usr/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
If I print `conanfile.imports_folder` it is None during `conan workspace install` and it has the proper value with `conan create`

**Comment by FranzPoize** [comment]
seems it's fixed in conan 1.40.0
