### ISSUE TITLE
Unhelpful error message (ERROR: 'NoneType' object is not iterable.) when working with faulty (gitlab) remote and range requirement

### ISSUE THREAD

**Issue by a-kryuk** [conan-io/conan#9751]
When I try to 'conan install' version-range-based requirements for a package from a GitLab remote package repository, I get an unhelpful Python message "ERROR: 'NoneType' object is not iterable." I believe it's triggered by some faulty implementation on the GitLab repository side, but it would be helpful if Conan provided a more specific indication of the error cause. 
My example conanfile.py:
```python
from conans import ConanFile

class BadConan(ConanFile):
  name = "badconan"
  version = "1.0.0"
  description = "Demonstrate problem"
  requires = [
    "pkgA/[>=1.0]@user/stream"
  ]
```
And here's the (edited) output:
```
$ conan --version
Conan version 1.40.3

$ export CONAN_LOGGING_LEVEL=10

$ conan install .
DEBUG :conan_api.py   [176]: INIT: Using config '/home/user/.conan/conan.conf' [2021-10-06 11:23:34,400]
DEBUG :tracer.py      [156]: CONAN_API: install(path=.,name=None,version=None,user=None,channel=None,settings=None,options=None,env=None,profile_names=None,conf=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None, conf=None),remote_name=None,verify=None,manifests=None,manifests_interactive=None,build=None,update=False,generators=None,no_imports=False,install_folder=None,lockfile=None,lockfile_out=None,require_overrides=None) [2021-10-06 11:23:34,402]
DEBUG :profile_loader.py[120]: PROFILE LOAD: /home/user/.conan/profiles/default [2021-10-06 11:23:34,403]
DEBUG :profile_loader.py[120]: PROFILE LOAD: /home/user/.conan/profiles/default [2021-10-06 11:23:34,440]
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

DEBUG :rest_client_common.py[160]: REST: ping: https://center.conan.io/v1/ping [2021-10-06 11:23:34,446]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions', 'matrix_params'] [2021-10-06 11:23:34,538]
DEBUG :rest_client_common.py[188]: REST: get: https://center.conan.io/v1/conans/search?q=pkgA%2F%2A%40user%2Fstream&ignorecase=False [2021-10-06 11:23:34,538]
DEBUG :rest_client_common.py[160]: REST: ping: https://gitlab.xxxx.com/api/v4/projects/48/packages/conan/v1/ping [2021-10-06 11:23:34,577]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: [] [2021-10-06 11:23:34,608]
DEBUG :rest_client_common.py[188]: REST: get: https://gitlab.xxxx.com/api/v4/projects/48/packages/conan/v1/conans/search?q=pkgA%2F%2A%40user%2Fstream&ignorecase=False [2021-10-06 11:23:34,608]
ERROR :remote_manager.py[294]: Traceback (most recent call last):
                                 File "/home/user/.local/lib/python3.8/site-packages/conans/client/remote_manager.py", line 283, in _call_remote
                                   return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
                                 File "/home/user/.local/lib/python3.8/site-packages/conans/client/rest/auth_manager.py", line 40, in call_rest_api_method
                                   ret = getattr(rest_client, method_name)(*args, **kwargs)
                                 File "/home/user/.local/lib/python3.8/site-packages/conans/client/rest/rest_client.py", line 138, in search
                                   return self._get_api().search(pattern, ignorecase)
                                 File "/home/user/.local/lib/python3.8/site-packages/conans/client/rest/rest_client_common.py", line 245, in search
                                   return [ConanFileReference.loads(reference) for reference in response]
                               TypeError: 'NoneType' object is not iterable
                                [2021-10-06 11:23:34,655]
ERROR: 'NoneType' object is not iterable. [Remote: myremote]
```

**Comment by memsharded** [comment]
While we could capture the returned value, and check for correctness, it seems a bit overkill (there are tons of other points where a bad server implementation could return something unexpected, and I would prefer not to be over-protective in code, if not super-necessary, like users typical failures. But a server implementation failure shouldn't be common issue). Have you filed an issue against the gitlab server? Feel free to link it here to track it too.

**Comment by a-kryuk** [comment]
I have not submitted an issue to GitLab for this particular case because they seem to have a few related problems already (e.g. [Conan version ranges not handled properly by GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/287819)). 
I understand that catching and reporting all the specific protocol errors would be a lot of work with a limited pay-off but it would be sufficient and helpful for troubleshooting to provide a fairly generic message like "Remote server returned unexpected results", if it can be done easily. Otherwise, it's not a biggy.

**Comment by memsharded** [comment]
Well, it never hurts (on the maintainer side), to have more evidence of what is failing and not. Better have many reports than none, I would certainly appreciate it. In the meantime, you might want to try ArtifactoryCE if you have some server there you could run it, it is completely free.


Lets label this as easy, will not be a priority, but if someone wants to contribute it, could be ok.

**Comment by adam248** [comment]
Doing a quick fix now.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12633
