### ISSUE TITLE
[bug] conan_build_info --v2 create Remote Issue

### ISSUE THREAD

**Issue by gpioloco** [conan-io/conan#9778]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Not used
  * Conan version: 1.40.1
  * Python version: 3.8.9

### Steps to reproduce (Include if Applicable)
1. Create a conan file with the following content:
```
from conans import ConanFile, tools


class PTestA(ConanFile):
    name = "PTestA"
    settings = "build_type"
    exports_sources = ["content.txt"]

    def package(self):
        self.copy("content.txt", src="", dst="inc")
```
2. Create an empty txt file named : "content.txt"
3. 
```
conan_build_info --v2 start BUILDNAME 1
```
4.
```
conan lock create conanfile.py --version 1.0.0 --lockfile-out lock
```
5.
```
conan create conanfile.py PTestA/1.0.0@ --lockfile lock --lockfile-out lock
```
6.
```
conan_build_info --v2 create buildinfo --lockfile lock
```

### Output
```
*********** Running: conan_build_info --v2 start gipibuild 1
*********** Running: conan lock create PTestA/conanfile.py --version 1.0.0 --lockfile-out PTestA/lock
Auto detecting your dev setup to initialize the default profile (W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\profiles\default)
Found Visual Studio 15
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=15
        build_type=Release
*** You can change them in W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


Requirements
Packages

Generated lockfile: W:\artifactory-test-scripts\PermissionsTest\PTestA\lock
*********** Running: conan create PTestA/conanfile.py PTestA/1.0.0@ --lockfile PTestA/lock --lockfile-out PTestA/lock
Using lockfile: 'W:\artifactory-test-scripts\PermissionsTest\PTestA\lock'
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute        
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute    
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
PTestA/1.0.0 exports_sources: Copied 1 '.txt' file: content.txt
PTestA/1.0.0: A new conanfile.py version was exported
PTestA/1.0.0: Folder: W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\data\PTestA\1.0.0\_\_\export
PTestA/1.0.0: Using the exported files summary hash as the recipe revision: 674f53139092efa8e9aa6e9cb69889d5 
PTestA/1.0.0: Exported revision: 674f53139092efa8e9aa6e9cb69889d5
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

PTestA/1.0.0: Forced build from source
Installing package: PTestA/1.0.0
Requirements
    PTestA/1.0.0 from local cache - Cache
Packages
    PTestA/1.0.0:4024617540c4f240a6a5e8911b0de9ef38a11a72 - Build

Installing (downloading, building) binaries...
PTestA/1.0.0: Configuring sources in W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\data\PTestA\1.0.0\_\_\source
PTestA/1.0.0: Copying sources to build folder
PTestA/1.0.0: Building your package in W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\data\PTestA\1.0.0\_\_\build\4024617540c4f240a6a5e8911b0de9ef38a11a72
PTestA/1.0.0: Generator txt created conanbuildinfo.txt
PTestA/1.0.0: Aggregating env generators
PTestA/1.0.0: Calling build()
PTestA/1.0.0: WARN: This conanfile has no build step
PTestA/1.0.0: Package '4024617540c4f240a6a5e8911b0de9ef38a11a72' built
PTestA/1.0.0: Build folder W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\data\PTestA\1.0.0\_\_\build\4024617540c4f240a6a5e8911b0de9ef38a11a72
PTestA/1.0.0: Generated conaninfo.txt
PTestA/1.0.0: Generated conanbuildinfo.txt
PTestA/1.0.0: Generating the package
PTestA/1.0.0: Package folder W:\artifactory-test-scripts\PermissionsTest\conanhome\.conan\data\PTestA\1.0.0\_\_\package\4024617540c4f240a6a5e8911b0de9ef38a11a72
PTestA/1.0.0: Calling package()
PTestA/1.0.0 package(): Packaged 1 '.txt' file: content.txt
PTestA/1.0.0: Package '4024617540c4f240a6a5e8911b0de9ef38a11a72' created
PTestA/1.0.0: Created package revision e6445ffbc832ce4d292b034974aaafe3
*********** Running: conan_build_info --v2 create buildinfo --lockfile PTestA/lock
ERROR: No remote 'None' defined in remotes
Traceback (most recent call last):
  File "test.py", line 145, in <module>
    ci_pipeline()
  File "test.py", line 133, in ci_pipeline
    TestPermissionReasonPromote()
  File "test.py", line 122, in TestPermissionReasonPromote
    run("conan_build_info --v2 create buildinfo --lockfile PTestA/lock")
  File "test.py", line 11, in run
    raise Exception("Failed command: %s" % cmd)
Exception: Failed command: conan_build_info --v2 create buildinfo --lockfile PTestA/lock
```

### Question
I do not really get what i am doing wrong i am trying to generate a buildinfo.json according to : https://docs.conan.io/en/1.19/reference/commands/misc/conan_build_info.html
But in the help page i do not find any information about remotes.

**Comment by czoido** [comment]
Hi @gpioloco,

> https://docs.conan.io/en/1.19/reference/commands/misc/conan_build_info.html

That link is outdated, please check: 
- https://docs.conan.io/en/latest/howtos/generic_ci_artifactory.html
- https://docs.conan.io/en/latest/reference/commands/misc/conan_build_info.html#conan-build-info-v2

It's important that you upload your packages to Artifactory before creating the BuildInfo, seems like you are not uploading them.
Also, seems that you are not adding the credentials to the `conan_build_info --v2 create` command?

Here there's a full example that should work: https://github.com/czoido/conan-build-info-example/blob/main/run_example.sh , maybe that's also useful for you.

Please tell me if this helps or you are still having issues.

**Comment by gpioloco** [comment]
Ah i see i tried to add the credentials but that would not work aswell because i did not upload the package, I see.
Thanks for your help.
